### ISSUE TITLE
PHPDOC align for all tags

### ISSUE THREAD

**Issue by rugk** [PHP-CS-Fixer/PHP-CS-Fixer#1362]
E.g.

``` php
<?php
/**
 * A description.
 *
 * @package package/subpackage
 * @author SomeGuy
 * @copyright Copyright (c) SomeGuy, SomeYear
 * @license SomeLicense
*/
```

should be aligned to 

``` php
<?php
/**
 * A description.
 *
 * @package   package/subpackage
 * @author    SomeGuy
 * @copyright Copyright (c) SomeGuy, SomeYear
 * @license   SomeLicense
*/
```

I think that's very similar to what _phpdoc_params_ currently does - it's just not (only) about @param.

**Comment by GrahamCampbell** [comment]
> all

We can't really do it for "all", but I think it would be a good idea to align anything that's a tag defined in https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/DocBlock/Tag.php#L26. That way we wouldn't be aligning custom annotations by mistake.

**Comment by GrahamCampbell** [comment]
We'd need to be really careful to get the annotation signatures right though, because each have different sets of arguments.

**Comment by rugk** [comment]
Yes, maybe also only the first align (as shown in my example) would be enough.
I mean in my example I only used tags with one argument.

The only other (important) tag I know of which would need a similar handling as ```@param``` is [@return](https://www.phpdoc.org/docs/latest/references/phpdoc/tags/return.html).

Of course all this things may be split into different fixers.

**Comment by GrahamCampbell** [comment]
> phpdoc_params

That fixer is renamed to phpdoc_align in 2.x though.

**Comment by GrahamCampbell** [comment]
> Of course all this things may be split into different fixers.

Meh, maybe the best thing to do would be to keep in one fixer and allow the tags to align to be configured in a simelar way to how the phpunit fixers work

**Comment by rugk** [comment]
> That fixer is renamed to phpdoc_align in 2.x though.

Ah okay, so then I would expect it to fix more than just ```@param``` (based of the name).

**Comment by GrahamCampbell** [comment]
> Ah okay, so then I would expect it to fix more than just @param (based of the name).

Yeh, the name sucks, but it was only changed on the 2.x line for BC reasons.
