### ISSUE TITLE
Extra brackets removal fixer proposal

### ISSUE THREAD

**Issue by GrahamCampbell** [PHP-CS-Fixer/PHP-CS-Fixer#1812]
For example:

``` php
$stuff = ($this->baz) ? $this->foo() : $this->bar();
```

We don't need the brackets around `$this->baz`.

**Comment by SpacePossum** [comment]
:+1:

**Comment by SpacePossum** [comment]
@keradus good pointers, but that kind of code.. oh no ^-^

**Comment by gharlan** [comment]
Extra cautions is also necessary for all assignment operators and for `and`, `or` and `xor`.

```php
($a = foo()) ? 1 : 2;

($a and $b) ? 1 : 2;
```

**Comment by interduo** [comment]
Example2 of doing useless bracketing:
`$stuff = ($this ? $something1 : $something2);`

**Comment by keradus** [comment]
Hey! I'm closing this as no commited effort to this by anyone. The idea is valid, yet it didn't get any movement around it code-wise for 8 years. I see no value in keeping it open due to that.
If any of you see a value in it and are ready to implement it, please raise a PR.
