### ISSUE TITLE
HeaderComment - not processing file with shebang 

### ISSUE THREAD

**Issue by glensc** [PHP-CS-Fixer/PHP-CS-Fixer#1871]
seems `header_comment` does not process file which has [shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) included

testcase: https://gist.github.com/glensc/3db778e86ff0de258581b0f1c26bfbf5

**Comment by glensc** [comment]
```
➔ php-cs-fixer.phar self-update
php-cs-fixer is already up to date.

➔ php-cs-fixer.phar --version
PHP CS Fixer version 1.11.2 by Fabien Potencier (41f7015)

➔ php-cs-fixer.phar fix -vvv
Loaded config from ".php_cs"
.F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) test2.php (header_comment)
Fixing time per file:
[0.060 s] test.php
[0.106 s] test2.php

Fixed all files in 0.168 seconds, 6.000 MB memory used
➔ git diff
diff --git a/test2.php b/test2.php
index 78a3aac..22ef5c3 100644
--- a/test2.php
+++ b/test2.php
@@ -1,3 +1,9 @@
 <?php
 
+/*
+ * For the full copyright and license information,
+ * please see the COPYING and AUTHORS files
+ * that were distributed with this source code.
+ */
+
 echo 123;
➔ 
```

**Comment by glensc** [comment]
also it seems to add `\n` between php tag and license block even `blankline_after_open_tag` is disabled

**Comment by keradus** [comment]
please provide php/hhvm version

ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Tokenizer/Tokens.php#L1381

**Comment by glensc** [comment]
```
➔ php --version
PHP 5.5.31 (cli) (built: Jan 31 2016 15:52:50) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by alcohol** [comment]
> also it seems to add \n between php tag and license block even blankline_after_open_tag is disabled

@glensc no that was already there. The header fixer adds a newline after the header comment. Check the source code of the fixer :-)

**Comment by SpacePossum** [comment]
```php
#!/usr/bin/php
<?php
echo 123;
```

the header fixer only runs on monolithic PHP files. An exception for files starting with a shebang could be made if we wan to. I'm :+1: , any other thoughts are welcome :)

(ps. this does not mean I start dev.ing it right away)

**Comment by SpacePossum** [comment]
Only HHVM has a special token for a `shebang`. This means that if we want to support this type of files (`shebang` followed by correct PHP code) we need to changes how we read, tokenize and write back the fixed result. IMHO it is not worth the trouble.

**Comment by Wirone** [comment]
Closing because now it's possible to analyse and fix PHP files with shebang.
