### ISSUE TITLE
Create a fixer fixing the return null vs void return statements

### ISSUE THREAD

**Issue by stof** [PHP-CS-Fixer/PHP-CS-Fixer#1916]
This fixer should handle 2 things (may be 2 different fixers though):
- converting `return;` to `return null;` when the function is not a void one (i.e. it has another return statement returning something explicitly. This may also read the phpdoc to detect more case but this is optional)
- converting `return null;` to `return;` in void-returning functions (detecting through the vod return typehint or through `@return void`. Detecting cases returning only null in the function would detect false positives when writing a null object).

such fixer could be in the Symfony ruleset as we changed our CS

**Comment by SpacePossum** [comment]
If we check the code and the PHPDoc of the function/method and these are in conflict than how should we proceed, fix the return value or the PHPDoc?

**Comment by stof** [comment]
@SpacePossum you mean if the phpdoc says ``@return void`` and the code contains return statements returning something else than null ? The method should be considered as a non-void-returning function, to keep the existing behavior of the code. Making the phpdoc win over the existing code would be risky.

**Comment by SpacePossum** [comment]
related discussion @ https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1638

**Comment by julienfalque** [comment]
IMO implementing a new fixer for this is not worth it: returning something in a void function or returning nothing in a non-void function is something that tools like PHPStan already report anyway.

**Comment by Wirone** [comment]
@julienfalque they report it, but they don't fix it 😉. 

In terms of conflicts between code, native return type and phpDoc I believe fixer should use only 2 latter to determine return type, with priorities:
- native return type
- phpDoc

If `void` is used, empty `return;` should be enforced, if nullable type is used then all empty returns should be converted to `return null;`. Fixer does not have full static analysis context and possible returned values can't be inferred from the code, so we can't find out if `null` is returned (not counting explicit `return null;`).

This fixer should be risky IMHO.
