### ISSUE TITLE
Feature Request: Copyright header configuration in header_comment

### ISSUE THREAD

**Issue by bshaffer** [PHP-CS-Fixer/PHP-CS-Fixer#2363]
Because copyright headers should be pinned to the year a file was created, `header_comment` quickly becomes impractical, as the copyright year can be different depending on the file. Excluding the copyright year is not an option for everyone. 

It would be great to have options like this:

```php
return PhpCsFixer\Config::create()
    ->setRules([
        'header_comment' => [
            'ignore_copyright' => true,
            'default_copyright' => 'Copyright Brent Shaffer ' . date('Y')
        ]
    ]);

// or...

return PhpCsFixer\Config::create()
    ->setRules([
        'header_comment' => [
            'copyright' => [
                'ignore' => true,
                'default' => 'Copyright Brent Shaffer ' . date('Y')
            ]
        ]
    ])
```

Thoughts?

**Comment by keradus** [comment]
if you want to keep a year in file header why not keep it up to date for all files?

**Comment by bshaffer** [comment]
@keradus because Copyright headers should reflect the year the file was added, not the current year.

**Comment by keradus** [comment]
why is that? created-current, as one didnt throw copyrights away
like 2015-2016

**Comment by bshaffer** [comment]
I feel like newer files should not have a previous copyright year.

**Comment by keradus** [comment]
To not copy-paste discussion let me hijack the thread and move forward discussion into https://github.com/GoogleCloudPlatform/php-docs-samples/pull/263#discussion_r90998582 ;)

**Comment by SpacePossum** [comment]
Maybe we could try a diff. approach. How about only replacing a header with the configured header if the current header is different more than a configurable Levenshtein distance?

**Comment by keradus** [comment]
:-1: for Levenshtein , if there is a typo in one file I want to have it fixed
:+1: for pattern matching

**Comment by keradus** [comment]
@Wirone , I'm still tricked with the default button text to be simply "Close issue"

<img width="592" alt="Screenshot 2023-09-08 at 21 03 09" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/2716794/af6ffc54-821a-4812-bc61-061345fcdf60">
