### ISSUE TITLE
Remove useless method comment

### ISSUE THREAD

**Issue by OskarStark** [PHP-CS-Fixer/PHP-CS-Fixer#2511]
It would be cool to have fixer like this:

## Before
```php
    /**
     * Constructor.
     *
     * @param CurrencyDataTransformer $currencyTransformer
     */
    public function __construct(CurrencyDataTransformer $currencyTransformer)
    {
        $this->currencyTransformer = $currencyTransformer;
    }
```

## After
```php
    /**
     * @param CurrencyDataTransformer $currencyTransformer
     */
    public function __construct(CurrencyDataTransformer $currencyTransformer)
    {
        $this->currencyTransformer = $currencyTransformer;
    }
```

because `Constructor.` is useless imo, or is this still possible?

Best regards and thank you,
Oskar

**Comment by SpacePossum** [comment]
I would say your sample PHPDoc is overcomplete as a whole ;) 

Anyway removing 'Constructor' (with or without trailing dot) as PHPDoc summary from constructors is fine by me :)
Removing `@return` annotations from constructors as well would be nice, but might be out-of-scope of the PR, although having a `NoUselessStuffInAPHPDocOfConstructorsFixer` could contain both ;)

**Comment by keradus** [comment]
not only constructor is a case.
```
/**
 * Class Foo.
 */
final class Foo
{
    /**
     * Constructor
     */
    public function __construct() {}

    /**
     * Destructor
     */
    public function __destruct() {}
}
```

**Comment by keradus** [comment]
@OskarStark , could you send a PR with proposal ?

**Comment by OskarStark** [comment]
Is there a fixer which could be used as an example to start working on a PR?

**Comment by SpacePossum** [comment]
I would go for;
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.0/src/Fixer/Phpdoc/PhpdocAddMissingParamAnnotationFixer.php

that fixer
- searches for PHPDocs
- check if the doc belong to a function (new one should be methods only)
- check some things about the function (new one needs to check the name of the method only (case insensitive))
- it checks and parses the PHPDoc (new needs to do that as well)
- fixes the PHPDoc if needed

so I think most parts that you need are in there, however there is also a lot of stuff in there you can ignore as it is unrelated to the what the new fixer needs.

**Comment by OskarStark** [comment]
> @OskarStark , could you send a PR with proposal ?

I checked the example, but to be honest, I currently don't have enough time to dive into it

**Comment by OskarStark** [comment]
Could be helpful ;-)

https://github.com/symfony/symfony/pull/24342

**Comment by keradus** [comment]
Sadly, I don't see how. Please provide more details.
Perhaps, you did that PR with using custom fixer you did already wrote and you want to share it with community ? :)

**Comment by OskarStark** [comment]
> Sadly, I don't see how. Please provide more details.

it seems to be needed by the community :)

> Perhaps, you did that PR with using custom fixer you did already wrote and you want to share it with community ? :)

No, this was just a sed replace and some manual adjustements

**Comment by keradus** [comment]
Manual work is not helping us in any way. About willingness to follow the rule by some community - we already accepted the idea of this rule and we are willing to have PR for it opened, especially by the community that need it. So... go ahead @OskarStark ! We will help by reviewing ;)

**Comment by iluuu1994** [comment]
This would be fantastic!

If even comments like this could be removed:

```php
// Do foo
$this->foo();
```

that would be amazing. I've seen other tools do this but I had no luck finding them again.

**Comment by wkania** [comment]
Just for reference, there is a similar fixer in the custom fixers. 
Examples of [NoUselessCommentFixer](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#nouselesscommentfixer) in the [tests](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/master/tests/Fixer/NoUselessCommentFixerTest.php).

**Comment by Wirone** [comment]
I'm going to close this since it's covered in @kubawerlos' Custom Fixers repository. Feel free to provide PR that would introduce this in the core, though 😉.
