### ISSUE TITLE
Fixer added dot at the end of line with a :

### ISSUE THREAD

**Issue by OskarStark** [PHP-CS-Fixer/PHP-CS-Fixer#2527]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/FriendsOfPHP/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

The PHP version you are using:
$ php -v - 7.0.14

PHP CS Fixer version you are using:
$ php-cs-fixer -V - 1.11.2

After a run, I got this diff:

```diff
- * API field for dividing livestream types in a boolean way:
+ * API field for dividing livestream types in a boolean way:.
```

Imo this `:.` should be avoided, what do you think?

**Comment by keradus** [comment]
Your docblock is invalid. You have In your docblock a description section, while valid docblock requires summary section before description if later exists

**Comment by GrahamCampbell** [comment]
Maybe we should actually change our fixer to either delete the colon and replace it with a full stop, or  to skip such cases, since the phpdoc is already invalid?

Perhaps could be suitable for configuration, since, this fixer is useful for people to catch and fix their already invalid phpdoc, like in this case?

**Comment by keradus** [comment]
why not. feel free to send PR ;)

**Comment by SpacePossum** [comment]
Why don't we skip PHPDoc's that PSR5 states are invalid, same like we skip invalid PHP code?

**Comment by lbassin** [comment]
I am working on a PR to ignore doc blocks if they don't match PSR-5 but i was wondering:
Can we consider that a summary longer than 2 lines is always invalid ? PSR-5 only RECOMMENDS us to keep summary smaller than 2 lines 

Also, I need your opinion on another case:
```
    /**
     * I don't know if this block is a summary:
     */
```
What should we do with this one ? IMO we should remove the colon

**Comment by SpacePossum** [comment]
>Can we consider that a summary longer than 2 lines is always invalid ? PSR-5 only RECOMMENDS us to keep summary smaller than 2 lines

for this rule, I would vote yes :) 

>What should we do with this one ? IMO we should remove the colon

if the summary is valid, as the sample is, but doesn't end with a sentence (full stop/period, exclamation mark, question mark), than it should add the dot. So in this case it leaves the removal of the `:` to the end user if wanted by the user.
It is an edge where we should throw a ton logic against IMHO as parsing languages is hard enough to get right (for example the rule only works for languages written from left to right to begin with...).

**Comment by GrahamCampbell** [comment]
I'd vote for not changing the behaviour, since it informs the user their doc is bad.

**Comment by SpacePossum** [comment]
The tool should either fix the code or not, it is not a sniffer that informs users. Therefore it should not touch docs that are bad and cannot be fixed to be good. Just like it does with bad PHP code it cannot fix, it should ignore it.

**Comment by GrahamCampbell** [comment]
I'd rather it deleted the colon and added a period, then.

**Comment by GrahamCampbell** [comment]
Than do nothing.

**Comment by dimaslanjaka** [comment]
> Why don't we skip PHPDoc's that PSR5 states are invalid, same like we skip invalid PHP code?

How to disable it on configuration phpcs.dist ?

**Comment by SpacePossum** [comment]
you can disable the rule by removing the rule from your config file or if you use a set containing it you can disable it by setting`"phpdoc_summary": false` in your config. If you have more questions about configuring the tool please check the documentation or ask your question here: https://gitter.im/PHP-CS-Fixer as github is not used for support question, thanks!

**Comment by dimaslanjaka** [comment]
> you can disable the rule by removing the rule from your config file or if you use a set containing it you can disable it by setting`"phpdoc_summary": false` in your config. If you have more questions about configuring the tool please check the documentation or ask your question here: https://gitter.im/PHP-CS-Fixer as github is not used for support question, thanks!

emm it will disabling beautify phpdoc.
i just need php-cs-fixer that only fix identation of phpdoc but **not adding dot on last line summaries**.
it required when phpdoc have **Example Codes**.
however, i made trick to prevent it.

```php
/**
 * This is wrong phpdoc, it'll adding dot on last summary and removing code example from it.
 * ```php
 * //this is example codes
 * ```. <--- this will added, and removing code example from typehinting of IDE
 * @params string $param example param
 */
```
This is title how to avoid dots on code example
```php
/** 
 * ```php
 * // this is code a long example
 * ```
 * Title goes here. <-- last dot generated php-cs-fixer
 * @param string $variableparam
 */
```

**Comment by dimaslanjaka** [comment]
This is php-cs-fixer phpdoc format identation which i need.
![image](https://user-images.githubusercontent.com/12471057/120914408-611d4880-c6c8-11eb-9bb9-068d6d5dcf75.png)

**Comment by dimaslanjaka** [comment]
Whenever without php-cs-fixer, will not beautify the phpdoc.
![image](https://user-images.githubusercontent.com/12471057/120914470-9f1a6c80-c6c8-11eb-9eab-4299277aabbf.png)

**Comment by SpacePossum** [comment]
@dimaslanjaka please ask your question here https://gitter.im/PHP-CS-Fixer , we will likely ask you to share your configuration and code sample as text, thanks :)

**Comment by keradus** [comment]
Hey! I'm closing this as no traffic around anymore. The idea could be valid, yet it didn't get any movement around.
If any of you see a value in it and are ready to implement it, please draft mini-RFC what you would like to achieve and how.
