### ISSUE TITLE
TernaryOperatorSpacesFixer - Add align option(s)

### ISSUE THREAD

**Issue by sebastianbergmann** [PHP-CS-Fixer/PHP-CS-Fixer#2559]
With this [`.php_cs`](https://github.com/sebastianbergmann/phpunit/blob/master/.php_cs) `php-cs-fixer` unaligns aligned ternary operator statements:

```diff
diff --git a/src/TextUI/TestRunner.php b/src/TextUI/TestRunner.php
index ca82375..39bfb06 100644
--- a/src/TextUI/TestRunner.php
+++ b/src/TextUI/TestRunner.php
@@ -729,8 +729,8 @@ protected function handleConfiguration(array &$arguments)
             );
         }
 
-        $arguments['debug']     = isset($arguments['debug'])     ? $arguments['debug']     : false;
-        $arguments['filter']    = isset($arguments['filter'])    ? $arguments['filter']    : false;
+        $arguments['debug']     = isset($arguments['debug']) ? $arguments['debug'] : false;
+        $arguments['filter']    = isset($arguments['filter']) ? $arguments['filter'] : false;
         $arguments['listeners'] = isset($arguments['listeners']) ? $arguments['listeners'] : [];
```

Is this a bug in one of the rules I am using? Am I missing something in my [`.php_cs`](https://github.com/sebastianbergmann/phpunit/blob/master/.php_cs) to achieve what I want?

Thanks!

**Comment by localheinz** [comment]
Related to https://github.com/sebastianbergmann/phpunit/pull/2516

**Comment by localheinz** [comment]
@sebastianbergmann 

As you can see in [`.php_cs`](https://github.com/sebastianbergmann/phpunit/blob/6052d68cae04df7f4baf5e823e7f214c40d60d1c/.php_cs#L64), the [`TernaryOperatorSpacesFixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Operator/TernaryOperatorSpacesFixer.php) is enabled, and this is the fixer sorting out spaces in ternary statements. 

If you don't want it, you should disable or remove it.

**Comment by localheinz** [comment]
Other than that, maybe someone wants to take a stab at turning it into a _configurable_ fixer?

**Comment by sebastianbergmann** [comment]
What then is the purpose of `ternary_operator_spaces` if it does not format the code as I have it right now? Does it simply ensure that there is a space around `?` and `:`?

**Comment by sebastianbergmann** [comment]
Probably unrelated to the original issue discussed here, but with the same configuration I also get this unintended change:
```diff
diff --git a/src/Util/Log/JUnit.php b/src/Util/Log/JUnit.php
index 7d86c63..924b75d 100644
--- a/src/Util/Log/JUnit.php
+++ b/src/Util/Log/JUnit.php
@@ -293,12 +293,12 @@ public function endTestSuite(TestSuite $suite)
         );
 
         if ($this->testSuiteLevel > 1) {
-            $this->testSuiteTests[$this->testSuiteLevel - 1]      += $this->testSuiteTests[$this->testSuiteLevel];
+            $this->testSuiteTests[$this->testSuiteLevel - 1] += $this->testSuiteTests[$this->testSuiteLevel];
             $this->testSuiteAssertions[$this->testSuiteLevel - 1] += $this->testSuiteAssertions[$this->testSuiteLevel];
-            $this->testSuiteErrors[$this->testSuiteLevel - 1]     += $this->testSuiteErrors[$this->testSuiteLevel];
-            $this->testSuiteFailures[$this->testSuiteLevel - 1]   += $this->testSuiteFailures[$this->testSuiteLevel];
-            $this->testSuiteSkipped[$this->testSuiteLevel - 1]    += $this->testSuiteSkipped[$this->testSuiteLevel];
-            $this->testSuiteTimes[$this->testSuiteLevel - 1]      += $this->testSuiteTimes[$this->testSuiteLevel];
+            $this->testSuiteErrors[$this->testSuiteLevel - 1] += $this->testSuiteErrors[$this->testSuiteLevel];
+            $this->testSuiteFailures[$this->testSuiteLevel - 1] += $this->testSuiteFailures[$this->testSuiteLevel];
+            $this->testSuiteSkipped[$this->testSuiteLevel - 1] += $this->testSuiteSkipped[$this->testSuiteLevel];
+            $this->testSuiteTimes[$this->testSuiteLevel - 1] += $this->testSuiteTimes[$this->testSuiteLevel];
```
Does the fixer aligning equal operators on consecutive lines not work for `+=` and friends?

**Comment by SpacePossum** [comment]
>[...] the purpose of `ternary_operator_spaces` [...] Does it simply ensure that there is a space around ? and :?

ATM yes, but I like @localheinz idea for configuration.
 
>Does the fixer aligning equal operators on consecutive lines not work for += and friends?

ATM no, only `=`. Maybe we could make the align logic based on configured binary operators, not sure how hard that would be though.

**Comment by sebastianbergmann** [comment]
Sounds great, @SpacePossum (and @localheinz).

**Comment by keradus** [comment]
In #2573 fixer has been reworked. Is there anything left here @sebastianbergmann still valid ?

**Comment by SpacePossum** [comment]
The first case will still happen because the `ternary operator` has no options to align like the bin. operators have.

**Comment by sudofox** [comment]
Would be nice to have this.

**Comment by Wirone** [comment]
@sebastianbergmann is it still valid expectation from your perspective? It's been 6 years, maybe you changed your coding standards in the meantime 😉.

**Comment by sebastianbergmann** [comment]
I can live with what we get right now with PHP-CS-Fixer and our current configuration. However, I would still like to see `+=` etc. on consecutive lines to be aligned.

**Comment by Wirone** [comment]
@sebastianbergmann thanks for the input. In terms of `+=` it's already possible to achieve what you need, you just need to configure `binary_operator_spaces` with `{"operators": {"+=": "align"}}`. Based on [this example](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/2559#issuecomment-282471875):

- Default value is `single_space`, so it's changed
  <img width="947" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/64b5b89f-e4e7-4414-8d07-543e3f0fddb2">

- There's no changes when using `align`:
  <img width="1039" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/5b38845a-6e54-4ee6-a8cc-f1c06313edb3">

So it can keep current formatting and also can fix to what you expect:

<img width="1044" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/2faecf06-7134-4c59-acc3-37e48e3de83c">

I'm going to close this since alignment in ternaries is not required and operators are handled as expected 🙂.

**Comment by sebastianbergmann** [comment]
Thank you, @Wirone!
