### ISSUE TITLE
Fixer for native classes casing

### ISSUE THREAD

**Issue by jtojnar** [PHP-CS-Fixer/PHP-CS-Fixer#2571]
Similarly to `NativeFunctionCasingFixer`, there should be a fixer for [native classes](https://secure.php.net/manual/en/reserved.classes.php) like `Exception`, `stdClass` or `Closure`.

**Comment by SpacePossum** [comment]
Thanks for the suggestion @jtojnar all :+1:  for it 
I just saw I labelled your request and dropped you a +1 but never a reaction ;)
Please let us know if we can help out getting this implemented :)

**Comment by Wirone** [comment]
Closing, as this was introduced in #6262 and works as expected:

<img width="897" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/247501a6-0cfd-48af-9071-2f6dde0d713d">
