### ISSUE TITLE
Improve class_definition documentation

### ISSUE THREAD

**Issue by Bilge** [PHP-CS-Fixer/PHP-CS-Fixer#2579]
RE #2578 

It is unclear to some users what the meaning is for the `singleItemSingleLine` and `multiLineExtendsEachSingleLine` options of the `class_definition` fixer. This issue proposes the following improvements:

* Better documentation. Let's expand the documentation with some prose to describe these options, in addition to the diff currently provided.
* Better names. It may be possible we can come up with more intuitive names for these options. Now would be an ideal opportunity to change the names since we have a secondary motivation to change them due to their non-conformance with the *snake_case* naming style found in most other fixer options.

cc @SpacePossum @julienfalque

**Comment by julienfalque** [comment]
This is what I understand:

* default behavior:
  * forces `extends`/`implements` to be on the same line than the declared element, but not necessarily the related items;
  * forces `implements` list to have one item per line if it contains several items *and* at least one new line before fixing;
  * removes extra whitespace around keywords in the declaration;
  * puts `{` on a new line;
* `singleLine` forces everything except `{` to be on the same line, including `extends`/`implements` items;
* `singleItemSingleLine` is like `singleLine` but leaves untouched the `extends` list if it contains several items;
* `multiLineExtendsEachSingleLine` is like `singleLine` but forces `extends` list to have one item per line if it contains several items *and* at least one new line before fixing;

Am I right?

**Comment by SpacePossum** [comment]
`singleItemSingleLine` is like `default` expect
* when an classy extends/implements one item it makes the declaration on one line

`multiLineExtendsEachSingleLine` is like `default` but also;
* forces extends list to have one item per line if it contains several items and at least one new line before fixing;

Im not good at this, nor in picking names for config item ;)

**Comment by julienfalque** [comment]
@SpacePossum I think we're saying the same things, just with different words 😅

Looks like the options are exclusive so what about replacing them with a single string option?

**Comment by Bilge** [comment]
Are we sure there's real-world use cases for all these different fixer modes?

**Comment by julienfalque** [comment]
@Bilge I think there isn't, but the discussion here is just about the options and their documentation, not changing the fixer's behavior itself.

**Comment by Bilge** [comment]
My concern was just whether or not spending time improving something is worth it, if just removing it is an equally viable alternative. However, I suppose since this iteration of the fixer has been released for at least six months it is bound to break someone's workflow if one of these features were to be removed. In that case you're right, let's just focus in improving them.

**Comment by SpacePossum** [comment]
I think all options are used, I can find F/OSS sample on github for it. For now lets focus on better docs., we can worry about naming and/or dropping config item later.

**Comment by Bilge** [comment]
>    when an classy extends/implements one item it makes the declaration on one line

Does *classy* have some special meaning or do you just mean a `class`?

Since PHP doesn't support multiple inheritance, isn't it redundant to state *when a class extends one item*? A class can only ever extend one other class, at most.

**Comment by Bilge** [comment]
Here is my proposed new documentation for each of the options:

* `single_line` &ndash; Unconditionally forces the entire definition onto a single line.
* `single_line_if_single_item` &ndash; Forces the entire definition onto a single line if both the *implements* and *extends* lists contain up to one item each.
* `split_extends` &ndash; Forces each extended item onto its own line (only applicable to interface definitions).

I'm pretty happy with the first two names. Other possibilities for the third might be: `separate_extends` or `multi_line_extends`.

**Comment by Bilge** [comment]
Having analysed these options it seems we're missing an option for `split_implements`. If we need the option `split_extends` why not have a matching option for the `implements` list?

**Comment by SpacePossum** [comment]
In PHP interfaces can extend multiple other interfaces, that is where the config item is for.

**Comment by Bilge** [comment]
@SpacePossum From what I have observed, the `implements` list is only split onto multiple lines (one item per line) if it was already spread across at least one additional line. This is in contrast to `multiLineExtendsEachSingleLine`, which forces each `extends` item onto a single line regardless of the input format. There appears to be no equivalent option for the `implements` list. Is this correct?

**Comment by SpacePossum** [comment]
```
<?php

interface A extends \PhpCsFixer\Fixer\FixerInterface, \PhpCsFixer\FixerDefinition\FixerDefinitionInterface
{
}
```

```
    ->setRules(array(
        'class_definition' => ['multiLineExtendsEachSingleLine' => true]
    ))
```

Fixer does not modify input, so i think "which forces each extends item onto a single line regardless of the input format." is not correct, if there is as case where it does it is a bug.

**Comment by Wirone** [comment]
@Bilge please let us know if this issue is still valid. `class_definition` fixer has changed seveeeeeral times over years, maybe right now it's user-friendly 🙂.
