### ISSUE TITLE
Docblocked static methods with return types.

### ISSUE THREAD

**Issue by rquadling** [PHP-CS-Fixer/PHP-CS-Fixer#2592]
Currently docblocked methods are: `@method returnType methodName($params) Description`.

This brings up an interesting issue when scope is introduced and there is no return type: `@method static methodName($params) Description`. Is this a static method or a non-static method that returns an instance of the called class?

Obviously, if a return type IS present, things are easy to parse: `@method static returnType methodName($params) Description`.

And an even more odd signature: `@method static static methodName($params) Description`, a perfect example of a fluid interface maybe?

But, in conjunction with appropriate code sniffing/styling support (we'll need to get those tools to support this also), and the fact that PHP now has proper support for return type hinting, a better pattern would be: `@method static methodName($params): returnType Description`.

Cross posted to : https://github.com/phpstan/phpstan/issues/190

**Comment by SpacePossum** [comment]
Hi!
Thanks for the description, interesting cases!
For my understanding, is there an issue with fixer ATM related to this cases? 
Most of our PHPDoc fixers are based upon the PSR5 proposal that was not updated for the return type.
So the return type hint might be an issue, but I'm not sure.
Typically we try to provide fixers/tooling to update code to a standard, we (try to) not make standards ;) that is why my interest for cases we do not support (i.e. break).

**Comment by rquadling** [comment]
Currently the fixer doesn't really do anything with the docblock as it is PSR5 compliant. But there is ambiguity due to static scope and void return type. Currently PSR5 doesn't have any mention of static scoped methods supported by `__callStatic()`, so that oversight, combined with the ambiguity, means static analysis tools are having to guess.

This was brought to light by https://github.com/beberlei/assert/pull/218. Currently I'm waiting on a release from PHPStan to not error when/if `static` keyword is present, but even then, I'd not considered the `static static` variation.

So. I suppose, being able to allow a dev to say what pattern they would like to support would be ideal.

I'll make a PR against PS5 to move the return type to the end of the method, matching PHP7's syntax. This removes all ambiguity (as far as I can tell) and hopefully doesn't conflict with anyone's usage where they've used a `:` as a separator in their method's description.

**Comment by rquadling** [comment]
I've proposed a change to PSR-5 (https://github.com/php-fig/fig-standards/pull/899). If you'd care to comment, correct, enhance, then that would be appreciated.

**Comment by Wirone** [comment]
Closing as changing the format of phpDoc (widely used common syntax) is out of the scope of this tool. I believe the only thing Fixer could do is updating phpDoc by adding return type inferred from the code, like:

```diff
- @method static methodName($params) Description
+ @method static void methodName($params) Description
```

but also I believe that if it's magic signature instead of actual method, it would be hard or even impossible to do it.
