### ISSUE TITLE
Rule braces too much concerned about blank lines (PSR2)

### ISSUE THREAD

**Issue by Isinlor** [PHP-CS-Fixer/PHP-CS-Fixer#2598]
Hello,

I'm using the latest version of code standard fixer (2.1.1) to make code compliant with PSR2. I have a problem with braces fixer. The fixer seems to be more concerned about my blank lines than about braces. I use blank lines to visually separate code. AFAIK PSR2 does not put any constraints on blank lines besides namespace and use declarations. Therefore I would suggest making this behavior configurable or move it to a separate fixer.

Example diff of my file:
```
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
             return;
-

@@ @@
         if ($skipChecksRequested && $this->isImpersonated($token)) {
-

@@ @@
         ));
-

@@ @@
         return true;
-

@@ @@
         $session->remove('redirectTo'); // prevent infinite loops and unexpected redirects
-

@@ @@
     }
-
 }
      ----------- end diff -----------
```

**Comment by SpacePossum** [comment]
Hi!

Can you provide the configuration file (if you use any) and the cli command, it would help to scope down the issue.

**Comment by Isinlor** [comment]
Thanks for quick reaction! ;)

Here is the command, no additional configuration:
`bin/php-cs-fixer fix ./file.php --rules=braces --diff --verbose`

**Comment by blexxed** [comment]
Yes, please fix this. I also have the same issue

**Comment by keradus** [comment]
@blexxed , this project is community driven and maintained.
We cannot fix/implement all requests at the same time. If you want to see this issue fixed sooner, any help would be appreciated ! :)
