### ISSUE TITLE
Line exceeds 120 characters; contains 168 characters

### ISSUE THREAD

**Issue by sakonachhoeurng** [PHP-CS-Fixer/PHP-CS-Fixer#2790]
I think I would like to have question for this.
Do this standard can apply for `phpcs` code checkstyle. because when I run on `Jenkins` it complains that `Line exceeds 120 characters; contains 168 characters` and I run php-cs-fixer cannot format my code that too long character.

I am using `PHPStorm 2017.1`, and I do not know php-cs-fixer have option to fix length of character.

**Comment by SpacePossum** [comment]
Currently we have no fixer to limit the line length. It was proposed before (https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/180 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1361). 
I would welcome such fixer, although it would be hard to implement (and sometimes impossible, for example if a class name is more than 120 chars. long it cannot be fixed).

**Comment by WyriHaximus** [comment]
Could we at the very least give an error without trying to fix it? Since fixing is impossible anyway.

**Comment by keradus** [comment]
no. this tool is a fixer.

**Comment by WyriHaximus** [comment]
Came to the conclusion going over how fixers work exactly. Will fix this another way

**Comment by artursvonda** [comment]
It should be possible with reasonable coverage. Prettier is doing it. I don't think we have to cover 100% of cases. And we can start slowly with easy ones (breaking down arguments for functions, breaking down arrays etc).

**Comment by TomasVotruba** [comment]
@artursvonda That sounds like something I'd use. I'm working on fixer that handles function arguments: https://github.com/Symplify/Symplify/pull/533

Are you able to do one for the arrays?

**Comment by evilebottnawi** [comment]
We develop https://github.com/prettier/plugin-php, any help welcome :+1:

**Comment by keradus** [comment]
wow, php tokenizer in js. js got more crazy now :D

**Comment by evilebottnawi** [comment]
@keradus you can help us :smile:

**Comment by keradus** [comment]
my first step would be to switch to ts actually ;)
anyway, i must admit I don't see a need for me to create/maintain 2 tools doing the same, just in different lang. not even thinking about having time for that.

**Comment by evilebottnawi** [comment]
@keradus we don't do the same :smile:

**Comment by keradus** [comment]
> Prettier is an opinionated code formatter.

I would say the very base idea is pretty much the same ;)
Anyway, while curious about it, I won't find time to contribute to it on regular basis...

**Comment by evilebottnawi** [comment]
@keradus difference - we respect line width and indent/tabs and don't do lint tasks and transformation, it is allow easy maintain and differentiate the responsibilities of each instrument. Anyway thanks for discussion and any help welcome :+1:

**Comment by keradus** [comment]
we also have a lot of reformatting, simply not that particular one ;)

**Comment by ktrzos** [comment]
Is there any plans on this feature? It's been a looong time since last talk about it :).

**Comment by kubawerlos** [comment]
@ktrzos if you have an idea how it could be implemented nicely do not hesitate to raise a PR ;)

**Comment by Wirone** [comment]
I am going to close this because I believe it's not possible to handle it within one fixer - it would end up with gigantic mess like `braces`, which was deprecated recently. We need multiple smaller fixers, for example for function signature, arrays etc. It's impossible to do with one fixer

**Comment by gordinskiy** [comment]
Wow, so much discussion and no result.
I fully understand why this hasn't been implemented yet, But it would be enough for me that CS-Fixer at least informs about these lines.

Just checking line length is much easier than trying to fix it. So i tried to implement such 'fixer' as a [custom rule](https://cs.symfony.com/doc/custom_rules.html) and for me it worked. 

I will stick with this solution instead of using other libraries for only that one check.

Maybe this will be useful to someone else, so I'll share my solution here.
[Line-Length-Checker](https://github.com/gordinskiy/Line-Length-Checker)

**Comment by gordinskiy** [comment]
> @gordinskiy the core purpose of PHP-CS-Fixer is... fixing. That's how it differs from PHPCodeSniffer - we don't have rules that only report stuff, we only have rules that can fix the code.
> 
> Thanks for sharing your custom rule, maybe people find it useful 👍.

And thanks for such flexible tool which allows to implement your own rules, including those that do not does not correspond to the purpose of the package itself 👍.

**Comment by ZhangSans** [comment]
Is there any way to configure the maximum number of characters per line of code? I think 120 characters is too few.

**Comment by Wirone** [comment]
@ZhangSans configure what 😉? Because we don't have rule for that.
