### ISSUE TITLE
Path-aware fixer sets

### ISSUE THREAD

**Issue by mlocati** [PHP-CS-Fixer/PHP-CS-Fixer#3126]
(ref. #3077)

What about implementing a way to specify fixer sets that depend on the path of the file currently being fixed?

For instance, we could have the following `.php_cs` configuration file:

```php
<?php
use PhpCsFixer\Config;
use PhpCsFixer\Finder;
use PhpCsFixer\PathAwareRules;

return Config::create()
    ->setRiskyAllowed(true)
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(__DIR__)
    )
    ->setRules([
        '@PSR2' => true,
        'psr4' => true,
    ])
    ->addPathAwareRules(
        PathAwareRules::create()
            ->setRelativeTo(__DIR__)
            ->setInheritRules(true)
            ->setRegularExpressions([
                '/^tests\//',
            ])
            ->setRules([
                'psr4' => false,
            ])
    )
    ->addPathAwareRules(
        PathAwareRules::create()
            ->setRelativeTo(__DIR__)
            ->setInheritRules(false)
            ->setRegularExpressions([
                '/^bin\//',
                '/^dev-bin\//',
            ])
            ->setRules([
                '@PSR1' => true,
            ])
   )
;
```

This file:
1. defines a default set of rules (`Config::setRules()`)
2. for paths relative to `__DIR__` (`PathAwareRules::setRelativeTo(__DIR__)`) that match `/^tests\//` (`PathAwareRules::setRegularExpressions()`) we use the default set of rules (`PathAwareRules::setInheritRules(true)`) but disabling the `psr4` fixer.
2. for paths relative to `__DIR__` (`PathAwareRules::setRelativeTo(__DIR__)`) that match `/^bin\//`or `/^dev-bin\//` (`PathAwareRules::setRegularExpressions()`) we use only (`PathAwareRules::setInheritRules(false)`) the `@PSR1` preset.

**Comment by SpacePossum** [comment]
Way back I build a prototype for something like:

```
<?php

$header = <<<'EOF'
This file is part of PHP CS Fixer.

(c) Fabien Potencier <fabien@symfony.com>
    Dariusz Rumiński <dariusz.ruminski@gmail.com>

This source file is subject to the MIT license that is bundled
with this source code in the file LICENSE.
EOF;

$rules = array(
	'@Symfony' => true,
	'@Symfony:risky' => true,
	'array_syntax' => array('syntax' => 'long'),
	'combine_consecutive_unsets' => true,
	// one should use PHPUnit methods to set up expected exception instead of annotations
	'general_phpdoc_annotation_remove' => array('annotations' => array('expectedException', 'expectedExceptionMessage', 'expectedExceptionMessageRegExp')),
	'header_comment' => array('header' => $header),
	'heredoc_to_nowdoc' => true,
	'no_extra_consecutive_blank_lines' => array('tokens' => array('break', 'continue', 'extra', 'return', 'throw', 'use', 'parenthesis_brace_block', 'square_brace_block', 'curly_brace_block')),
	'no_short_echo_tag' => true,
	'no_unreachable_default_argument_value' => true,
	'no_useless_else' => true,
	'no_useless_return' => true,
	'ordered_class_elements' => true,
	'ordered_imports' => true,
	'phpdoc_add_missing_param_annotation' => true,
	'phpdoc_order' => true,
	'semicolon_after_instruction' => true,
	'strict_comparison' => true,
	'strict_param' => true,
);


$config = [
    'src' =>	
	PhpCsFixer\Config::create()
	    ->setRiskyAllowed(true)
	    ->setRules($rules)
	    ->setFinder(
		PhpCsFixer\Finder::create()
		    ->in(__DIR__.'/src')
	    ),
    'test' =>	
	PhpCsFixer\Config::create()
	    ->setRiskyAllowed(true)
	    ->setRules(array(
		array_merge($rules, ['php_unit_strict' => true, # other PHPUnit fixers#])
	    ))
	    ->setFinder(
		PhpCsFixer\Finder::create()
		    ->exclude('tests/Fixtures')
		    ->in(__DIR__.'/tests')
	    )
];

return $config;
```

Never finished it, biggest issue was caching. I wonder, would a setup like that also works for your use-cases?

**Comment by mlocati** [comment]
> would a setup like that also works for your use-cases?

Nope: we have a rather complex system ([see here](https://github.com/mlocati/concrete5/blob/3dcd1124ab88ea42760a276a47f380b2c8cd4fe0/concrete/src/Support/CodingStyle.php#L467-L552) for the list of checks that we should use to determine the fixer list).

**Comment by keradus** [comment]
what if one provided same file with multiple different `PathAwareRule`  ?
like once `file.php` with concat=space, and 2nd time with concat=none ?

**Comment by mlocati** [comment]
I'd pick the first `PathAwareRules` that satisfies the criteria.
So, for instance, way we may have a *default* `PathAwareRules` for a folder, and a particular `PathAwareRules` for a specific file in that folder.

**Comment by mlocati** [comment]
For instance:
```php
$config
    ->addPathAwareRules(
        PathAwareRules::create()
            ->setRegularExpressions([
                '/^tests\/file.php$/',
            ])
            ->setRules($fileSpecificRules)
            ])
    )
    ->addPathAwareRules(
        PathAwareRules::create()
            ->setRegularExpressions([
                '/^tests\//',
            ])
            ->setRules($rulesForTheFolder)
            ])
    )
;
```

If somebody wants to include the `$rulesForTheFolder` in `$fileSpecificRules`, it's enough to write something like
```
$fileSpecificRules = ['fixerHandle' => false] + $rulesForTheFolder;
```

**Comment by keradus** [comment]
then it depends on order of injection to main config. for that I'm :-1:
one will set `/src -> fixer_a, / -> fixera,fixer_b` and wonder why `fixer_b` was not applied for `/src`

**Comment by mlocati** [comment]
> one will set `/src -> fixer_a, / -> fixera,fixer_b` and wonder why fixer_b was not applied for /src

Because he explicitly said `/src -> fixer_a`...

BTW, to solve this, we could add a flag to the `PathAwareRules` class, to say if the process should use only the rules defined by the `PathAwareRules` instance, or if all rules of all the applicable `PathAwareRules` should be applied.

Something like this (pseudocode):

```php
$finalRules = null;
foreach ($pathAwareRulesList as $par {
    /* @var PathAwareRules $par */
    if (false === $par->isForCurrentPath()) {
        continue;
    }
    $parRules = $par->getRules(); // This should take care of setInheritRules
     if (true === $par->getNameOfTheNewFlag()) {
        $finalRules = $parRules;
        break;
    }
    $finalRules = ($finalRules ?: []) + $parRules;
}
if (null === $finalRules) {
    $finalRules = $theDefaultRulesOfConfig;
}
```

**Comment by keradus** [comment]
then you will end up having conflicting rules for different paths which merge output is unpredictable

**Comment by mlocati** [comment]
I'm sorry I don't understand what you mean...

**Comment by KorvinSzanto** [comment]
@keradus That could just be solved with a descriptive exception thrown if a file path exists in two rule sets. No need to try to merge things.

**Comment by mlocati** [comment]
Well, I wouldn't do that: how could you say "use these fixers for all the files in this folder, but use these other fixers for this specific file in that folder"?

**Comment by keradus** [comment]
then it's different from what you said in 
> I'd pick the first PathAwareRules that satisfies the criteria.

**Comment by mlocati** [comment]
> then it's different from what you said in
>
>> I'd pick the first PathAwareRules that satisfies the criteria.

No. Consider this example:

```php
$config
    ->addPathAwareRules(
        PathAwareRules::create()
            ->setRegularExpressions([
                '/^tests\/file.php$/',
            ])
            ->setRules($fileSpecificRules)
    )
    ->addPathAwareRules(
        PathAwareRules::create()
            ->setRegularExpressions([
                '/^tests\//',
            ])
            ->setRules($rulesForTheFolder)
    )
;
```

As you can see, if the execution picks the first matching criteria, we'd use `$fileSpecificRules` for `tests/file.php`, and `$rulesForTheFolder` for all the other files in the `tests` folder.

**Comment by ktomk** [comment]
@SpacePossum: Your setup looks great to me, for the cache: just take one cache per set, I'm fine with that, too.

**Comment by KacerCZ** [comment]
@SpacePossum I like your prototype. Have you tried to complete its implementation<
Recently I found the need for exactly the same use case as in your example.
I check code and tests and can't enable "php_unit_test_class_requires_covers" rule because some of regular classes are named "Test".

**Comment by SpacePossum** [comment]
Hi @KacerCZ !

I haven't finished the prototype. We are still discussing how the new configuration could look like for v3.0 and forward, but it probably won't look (close) like my prototype. I still think it would be value to allow configuration of rules based on (exceptions) of files and directories. Therefore I hope to convince other for this need as well and figure out how to do implement it nicely (might be baselines or something, who knows!).

**Comment by mlocati** [comment]
I'm wondering if the new configuration approach @SpacePossum is referring to would support a rather complex situation.

For example, a typical concrete5 project has this structure (where `<HANDLE>` is not known in advance, and we may have 0...N of them):

| Path | Rule set |
|---|---|
| `/index.php` | Rule set A |
| `/concrete/dispatcher.php` | Rule set A |
| `/concrete/bin/concrete5` | Rule set A |
| `/concrete/attributes/<HANDLE>/controller.php` | Rule set B |
| `/application/attributes/<HANDLE>/controller.php` | Rule set B |
| `/packages/<HANDLE>/attributes/<HANDLE>/controller.php` | Rule set B |
| `/packages/<HANDLE>/controller.php` | Rule set B |
| `/concrete/authentication/<HANDLE>/controller.php` | Rule set B |
| `/application/authentication/<HANDLE>/controller.php` | Rule set B |
| `/packages/<HANDLE>/authentication/<HANDLE>/controller.php` | Rule set B |
| `/concrete/blocks/<HANDLE>/controller.php` | Rule set B |
| `/application/blocks/<HANDLE>/controller.php` | Rule set B |
| `/packages/<HANDLE>/blocks/<HANDLE>/controller.php` | Rule set B |
| `/concrete/geolocation/<HANDLE>/controller.php` | Rule set B |
| `/application/geolocation/<HANDLE>/controller.php` | Rule set B |
| `/packages/<HANDLE>/geolocation/<HANDLE>/controller.php` | Rule set B |
| `/concrete/themes/<HANDLE>/page_theme.php` | Rule set B |
| `/application/themes/<HANDLE>/page_theme.php` | Rule set B |
| `/packages/<HANDLE>/themes/<HANDLE>/page_theme.php` | Rule set B |
| `/concrete/controllers/**/*` | Rule set B |
| `/application/controllers/**/*` | Rule set B |
| `/packages/<HANDLE>/controllers/**/*` | Rule set B |
| `/concrete/jobs/**/*` | Rule set B |
| `/application/jobs/**/*` | Rule set B |
| `/packages/<HANDLE>/jobs/**/*` | Rule set B |
| `/concrete/bootstrap/**/*` | Rule set C |
| `/application/bootstrap/**/*` | Rule set C |
| `/concrete/config/**/*` | Rule set C |
| `/application/config/**/*` | Rule set C |
| `/packages/<HANDLE>/config/**/*` | Rule set C |
| `/concrete/routes/**/*` | Rule set C |
| `/application/routes/**/*` | Rule set C |
| `/packages/<HANDLE>/routes/**/*` | Rule set C |
| `/concrete/src/**/*` | Rule set C |
| `/application/src/**/*` | Rule set C |
| `/packages/<HANDLE>/src/**/*` | Rule set C |
| `/tests/**/*` | Rule set C |
| Anything else | Rule set D |

[At the moment](https://github.com/concrete5/concrete5/tree/8.5.4/concrete/src/Support/CodingStyle), we use some of the internal functions of php-cs-fixer to implement this approach:
- users provide one or more paths (to files or directories)
- we resolve all the paths to the full file list (if required)
- [we group the files/directories having the same rule set](https://github.com/concrete5/concrete5/blob/8.5.4/concrete/src/Support/CodingStyle/PhpFixer.php#L94)
- [we run php-cs-fixer](https://github.com/concrete5/concrete5/blob/8.5.4/concrete/src/Support/CodingStyle/PhpFixerRunner.php#L143) for every group of files/directories having the same ruleset

**Comment by mlocati** [comment]
About the [above comment of mine](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3126#issuecomment-724553262):
- the paths are relative to a predefined values (the web root)
- the rule sets A, B and C start from rule set D, but alter (add/edit/remove) some of its rules

**Comment by ktomk** [comment]
@Wirone: For me it _is_ status/stale, could you leave some comment and explain why this is different for you? Maybe I've overlooked something.

**Comment by Wirone** [comment]
Personally, as an ECS user, I would like to exclude rules for specific path and make some more specific conditions. This issue is valid, and `status/stale` is only automated reminder to verify issues/PRs. As I did a one full round of verification, I know issues and what was done in the meantime - this wasn't 😉.

**Comment by ktomk** [comment]
@Wirone: Thanks for the fast feedback, honestly I have problems to follow. What does ECS stand for in context of this issue? And so far one reason why this got stale for me is that there is no clear definition of done and ready, therefore it is hard to give it some traction. Maybe I've overlooked something.

**Comment by Wirone** [comment]
I just think it is fine feature of Easy Coding Standard that you can skip some fixers/sniffs for specific paths and I believe Fixer as a tool should have similar feature. I agree that scope is not clear, but it can be discussed when someone finally puts hands on this (maybe it'll be me, who knows).

**Comment by ktomk** [comment]
Could it be that you are referring to [easy-code-standard](https://github.com/easy-coding-standard/easy-coding-standard)?

And we wholeheartedly agree with humble yours that in general a fixer that is file-based could have exactly such a feature #3126 and given you referred to it, that is even regardless ecs(1) isn't php-cs-fixer(1).

And still, it is our true own believe that #3126 is status/stale. Which should go without saying that we can agree to disagree, there is no need for us to argue over the concrete status, but if I may ask, wouldn't you consider it beneficial to directly view that it is a stale feature request for PHP-CS-Fixer?

It should already be without writing this, naturally #3126 has to remain open regardless of its staleness.

**Comment by Wirone** [comment]
@ktomk just let me maintain the repo according to our workflow, ok 😉? If I leave `status/stale`, it will get closed in 90 days, which is undesired. Bot is just reminding us to decide on issues from time to time, as a backlog hygiene.

Yes, ECS mentioned by me is a tool you've linked.

**Comment by ktomk** [comment]
@Wirone Yes, sure, absolutely. We were interested in the rationale and the current heading direction of  #3126. 

And while doing so we missed this

> I will close it if no further activity occurs within the next 30 days.

Thanks for pointing it out! Despite the stale status (or not) in its own right was less of our interest.

Nevertheless, if you'd ask me for a practical hint related to the automated workflow: I'd suggest to not get naughty by the bot, and add a tag that marks an issue as verified, so that it won't get closed. Just a suggestion, we did this in the past and it helped a lot for peace of mind in backlog grooming.

And very happy to see all of your care-taking here, especially for the very fine reasons of portability and alignment with [ECS](https://github.com/easy-coding-standard/easy-coding-standard).

And thinking: If the bot auto-closes after 90 days, which are round about three months, would be interesting to hear about your current understanding of the time span of #3126. As commented earlier we were under the impression this one staled long ago which we're reading as that there's no traction any longer. Can't speak for the other contributors, but for us, we lost interest because of that. Are you willing to share some details apart from those you already thankfully shared?

> as an ECS user, I would like to exclude rules for specific path and make some more specific conditions also in Fixer. This issue is valid _([ref](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/3126#issuecomment-1703831264))_

Maybe things have shifted now and we'd reconsider.

**Comment by mlocati** [comment]
I think this is still valid

**Comment by nesl247** [comment]
Now that php-cs-fixer can auto import classes, we want this so we can disable that for symfony config files. It's more confusing there for us in our larger application.

**Comment by mikedfunk** [comment]
> If you're still interested in this, please let as know, we can consider re-opening it.

I am still interested in this

**Comment by c33s** [comment]
still relevant

**Comment by mlocati** [comment]
still relevant

**Comment by erickskrauch** [comment]
I'm still interested in this feature.

**Comment by mlocati** [comment]
Instead of the approach suggested here, what about #9107?

**Comment by keradus** [comment]
agree

**Comment by D3strukt0r** [comment]
I just realised I also really needed this feature. Disabling a rule entirely is dumb, and not checking a file at all is not better. Rector has also solved this neatly, I would say. see https://getrector.com/documentation/ignoring-rules-or-paths

```php
return RectorConfig::configure()
    ->withSkip([
        SimplifyIfReturnBoolRector::class => [
            __DIR__ . '/src/ComplicatedFile.php',
        ],
    ]);
```

way simpler for configuration than anything suggested. and then maybe add more complicate syntax with custom functions etc. etc. later

**Comment by mlocati** [comment]
> Rector has also solved this neatly, I would say. see https://getrector.com/documentation/ignoring-rules-or-paths

That's not what we need (see this dumb but simple [use case](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/9107#discussion_r2387356485) for example): we'd need to change the configuration of fixers for specific file patterns.

**Comment by D3strukt0r** [comment]
I totally agree, something more flexible is still better, but it's neither a better plan to postpone this ticket even longer just because one wants the perfect solution from the beginning. How long has this ticket been open? ~8 Years already, for such a basic feature.

Sorry, this wasn't meant as a rant. It's just harder to convince my company to start using this tool, while they want their stupid code-style edge cases to be handled in a good way, which won't work without this feature, even in its basic form.

I merely wanted to say a good starting point would be something like this:

(e.g. we don't want `declare(strict_types=1);` since we handle that with PhpStan, but keep it in Symfony's migrations folder, since it's already created with that)

Note: yes I know, I have to think different here, enable by default, and disable where I don't want to

```php
return new \PhpCsFixer\Config()
    ->setRules([
        'declare_strict_types' => true,
    ])
    ->setRulesSkipped([
        'declare_strict_types' => [
            __DIR__.'/src/*',
            '!'.__DIR__.'/src/myotherspecificfile.php',
            __DIR__.'/tests/*',
            // ...
        ],
    ])
;
```

Maybe just simple strings to begin with, then add support for gitignore style `array<string>`, which can then still be extended to something more sophisticated (sorry not sure if this is the right word, English is not my first language) with functions to handle the most complex/automated cases (i guess to enable/disable/configure differently).

```php
return new \PhpCsFixer\Config()
    ->setRules([
        'declare_strict_types' => true,
    ])
    ->setRulesSkipped([
        'declare_strict_types' => fn() => do_some_fancy_check(),
    ])
;
```

If you want to have different ways to apply rules, there doesn't only have to be one way, but AT LEAST one.

this comment was meant more as inspiration to get this going

**Comment by mlocati** [comment]
What's wrong with #9107? With that PR we can have something like this:

```php
<?php

declare(strict_types=1);

use PhpCsFixer\Config;
use PhpCsFixer\Finder;
use PhpCsFixer\Fixer\FixerInterface;
use PhpCsFixer\RuleCustomizationPolicyInterface;

$customizer = new class implements RuleCustomizationPolicyInterface
{
    public function customize(FixerInterface $fixer, SplFileInfo $file): ?FixerInterface
    {
        if ($fixer->getName() === 'declare_strict_types' && $file->getPathname() === __DIR__ . '/src/ComplicatedFile.php') {
            return null;
        }
        return $fixer;
    }
};

return (new Config())
    ->setRules([
        'declare_strict_types' => true,
    ])
    ->setFinder((new Finder())->in(__DIR__))
    ->setRuleCustomizationPolicy($customizer)
;
```

(We just have to wait for @keradus to [finish thinking](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/9107#discussion_r2387302651) 😉)
