### ISSUE TITLE
Git hook - Reading from standard input does not work.

### ISSUE THREAD

**Issue by stacyharper** [PHP-CS-Fixer/PHP-CS-Fixer#3165]
Hello everyone,
I'm facing a big problem. I'd like to create a good git hook to automaticaly fix my php files before commiting. My goal is to question me if a change has been done by php-cs-fixer

Here is my script:
```bash
#!/bin/bash -u

executable="$1"
rules="$2"
path="$3"

if [ -d "$path" -o -f "$path" ];
then
	if [ -f "$executable"  ];
	then
		needInteraction=0
		for file in $(git diff-index --cached --name-status HEAD -- | cut -c 3- | grep .php$);
		do
			git --no-pager show :"$file" | "$executable" fix --dry-run --quiet --rules="$rules" -
			if [ "$?" -eq "8" ]
			then
				needInteraction=1
				"$executable" fix --quiet --cache-file .git/.php_cs.cache --rules="$rules" "$file"
				echo "$file has been fixed by php-cs-fixer."
			fi
		done
		if [ "$needInteraction" -eq "1" ]
		then
			exec < /dev/tty
			read -p "Do you still want to commit ? [y/n]"
			if [[ ! "$REPLY" =~ ^[Yy]$ ]]
			then
				exit 1
			fi
		fi
	else
		echo "$executable not found"
		exit 1
	fi
fi
```

I want php-cs-fixer to test my staged files like they will be commited.

My problem is when I do this.
```bash
git --no-pager show :"$file" | "$executable" fix --dry-run --quiet --rules="$rules" -
```

The value of "$?" will always be "0", breaking all my logic...

When I try to execute this command outside of my script, replacing variables with true values, it seem thas php-cs-fixer does not read my file from standard input. It's the same thing if I try to cat a file then pipe the output to the php-cs-fixer with the "-" at the end...

And ofc, I tested my script with php files that contains multiple coding convention mistakes.

I think I probably do something badly, but the doc tell me that we can
```bash
$ cat foo.php | php php-cs-fixer fix --diff -
``` 

So where is my mistake ?

For information
```bash
php -v
PHP 7.1.10 (cli) (built: Sep 27 2017 17:33:37) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

```bash
lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

```bash
uname -a
Linux IDCI-FlyingSquirrel 4.13.7-1-ARCH #1 SMP PREEMPT Sat Oct 14 20:13:26 CEST 2017 x86_64 GNU/Linux
```

Thank a lot in advance !

**Comment by Eluminae** [comment]
Mhh, the $path variable is actually useless in the script, but this is definitly not the cause of my problem.

```bash
#!/bin/bash -u

executable="$1"
rules="$2"

if [ -f "$executable"  ];
then
	needInteraction=0
	for file in $(git diff-index --cached --name-status HEAD -- | cut -c 3- | grep .php$);
	do
		git --no-pager show :"$file" | "$executable" fix --dry-run --quiet --rules="$rules" -
		if [ "$?" -eq "8" ]
		then
			needInteraction=1
			"$executable" fix --quiet --cache-file .git/.php_cs.cache --rules="$rules" "$file"
			echo "$file has been fixed by php-cs-fixer."
		fi
	done
	if [ "$needInteraction" -eq "1" ]
	then
		exec < /dev/tty
		read -p "Do you still want to commit ? [y/n]"
		if [[ ! "$REPLY" =~ ^[Yy]$ ]]
		then
			exit 1
		fi
	fi
else
	echo "$executable not found"
	exit 1
fi
```

**Comment by Eluminae** [comment]
Here is my temporary solution

```bash
git --no-pager show :"$file" > "/tmp/php-cs-fixer-checked-file-cache.php"
"$executable" fix --dry-run --quiet --using-cache=no --rules="$rules" "/tmp/php-cs-fixer-checked-file-cache.php"
```

Yeah ugly... But it works !

**Comment by Eluminae** [comment]
Basicaly

```php
// test.php
<?php

class Test {
        private $foo;

    public function __consruct( ){
        $this->foo =  "bar";
    }
}
```

```bash
cat test.php |php-cs-fixer fix --diff -
Loaded config default.
```

```bash                                                                                                                                            
$ cat test.php |php-cs-fixer fix --quiet --dry-run -                                                                
$ echo $?
0
```

```bash
$ php-cs-fixer -v
PHP CS Fixer 2.7.0 Sandy Pool by Fabien Potencier and Dariusz Ruminski (e4e93a1)
```

**Comment by SpacePossum** [comment]
Thanks @Eluminae for sharing this :+1: 
Do you think we could use any of your experience on the integration samples we've in the project or maybe in the documentation somewhere?

**Comment by Eluminae** [comment]
@SpacePossum Yeah ofc ! I think it could be usefull for a lot. There is only this little problem which is breaking the script.

**Comment by keradus** [comment]
why not ask ppl to use `grumphp` (or anything else) for such kind of local-git-level integration ?

**Comment by Eluminae** [comment]
Mh I didn't know about grumphp but it's seems to be a very good tool ! I'll probably take a deeper look.
But my problem is not so about git hooks but the "read file from stdinput" feature which is just unworking at all on my machine.

**Comment by keradus** [comment]
there are few githook managers (written in any lang, not only PHP).
sorry, I was confused by title of this issue - "git hook" :D
let us investigate `stdin` issue for sure!

**Comment by Wirone** [comment]
Personally I can recommend [Captain Hook](https://github.com/captainhookphp/captainhook).
