### ISSUE TITLE
One-Time variables fixer

### ISSUE THREAD

**Issue by soullivaneuh** [PHP-CS-Fixer/PHP-CS-Fixer#3322]
The idea of this fixer is to removed useless one-time variable usages.

Basically, it will turn this:

```php
$context = [
    'customer' => $user,
    'domainNames' => $domainName,
];

$this->sendMessage($templateName, $context, [
    'to' => $user->getEmailCanonical(),
    'to_name' => $user->getFullname(),
    'locale' => $user->getLocale(),
]);
```

To this:

```php
$this->sendMessage($templateName, [
    'customer' => $user,
    'domainNames' => $domainName,
], [
    'to' => $user->getEmailCanonical(),
    'to_name' => $user->getFullname(),
    'locale' => $user->getLocale(),
]);
```

According to this: https://a-nickels-worth.blogspot.fr/2016/04/a-guide-to-naming-variables.html

> One-time variables (OTVs), also known as garbage variables, are those variables used passively for intermediate results passed between functions. They sometimes serve a valid purpose (see the next cookbook items), but are often left in thoughtlessly, and just clutter up the codebase. In the following code fragment, the coder has just made the reader's life more difficult:

On this article, some case when OTV seems to be useful are described. IMO, those cases just show a another code smell issue that should be fixed another way than OTV usages.

But this is debatable, so the fixer should not be on any standard preset.

**Comment by greg0ire** [comment]
It will also be risky, for instance in cases where the order of execution matters because the function that returns the variable has side effects.

**Comment by Soullivaneuh** [comment]
> It will also be risky, for instance in cases where the order of execution matters because the function that returns the variable has side effects.

Hmm... hard to see which case will be risky. Could you please provide a sample?

**Comment by SpacePossum** [comment]
For example in your sample, if `$context` was imported as a `global` you change the code meaning/executing. There are a lot of ways to do ugly stuff like that in PHP :|

**Comment by Soullivaneuh** [comment]
@SpacePossum Well, can't we find a way to detect is a variable is globally imported?

If not, the fixer may be indeed marked as risky, but it still worth it. Lot of (properly coded :trollface:) projects does not use global variables at all.

**Comment by greg0ire** [comment]
It is definitely risky, but indeed, might be worth it.

**Comment by Wirone** [comment]
With static analysis on significant level it's sometimes required to use OTV to enforce specific type in order to "fix" issues (especially for vendor code, that can't be modified in proper way). Such usages shouldn't be fixed by this fixer:

```php
/** @var Foo */
$foo = getFooButWithoutExplicitReturnTypeInSignature();

bar($foo); // function bar(Foo $foo)
```

Another case that should be taken into consideration is passing arguments by reference:

```php
function foo(&array $arr, /* other args may be here */) {
    $arr = ['result' => ['of' => ['some' => 'complex (or not) logic']]]; // This is NOT one-time variable

    bar($arr);
}
```

It is definitely risky 😉.

**Comment by Wirone** [comment]
FYI: there is [Rector rule](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#simplifyuselessvariablerector) for that.

**Comment by Wirone** [comment]
I believe this is slightly out of the scope of Fixer. Even though it's doable, it would be very risky and hard to achieve with tokenisation approach. The effort most probably is not worth it, especially considering that Rector already can do it. I am going to close this, as this is open for 7 years already and wasn't implemented, so there's very little chance it will change 🙂.
