### ISSUE TITLE
Decouple the getIndent(..) method

### ISSUE THREAD

**Issue by egircys** [PHP-CS-Fixer/PHP-CS-Fixer#3416]
Private logic for determining indentation like:

https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/b47030cb42be38dfcdb1d593b3dcf4ccfe72eb14/src/Fixer/Whitespace/MethodChainingIndentationFixer.php#L163

should be replaced with `WhitespacesAnalyzer::detectIndent()`.

**Comment by keradus** [comment]
Target: 2.2.x for maintainability reasons

**Comment by SpacePossum** [comment]
`NoBreakCommentFixer` now uses `WhitespacesAnalyzer::detectIndent` , however `MethodChainingIndentationFixer` still uses its own private methods to determine indentation.
