### ISSUE TITLE
multi line method calls get the wrong indentation

### ISSUE THREAD

**Issue by arosemena** [PHP-CS-Fixer/PHP-CS-Fixer#3469]
PHP 7.2.0
PHP CS Fixer 2.10.0

command is vscode format `shift+alt+f`

Config file
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('somedir')
    ->notPath('src/Symfony/Component/Translation/Tests/fixtures/resources.php')
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setIndent("  ")
    ->setFinder($finder)
;
```

 * before running PHP CS Fixer (no changes):
```php
<?php

  class Test
  {
    public function getModel()
    {
      $a = Model::where('something', true)
        ->skip(2)
        ->take(10)
        ->get();
    }
  }

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

  class Test
  {
    public function getModel()
    {
      $a = Model::where('something', true)
  ->skip(2)
  ->take(10)
  ->get();
    }
  }
```

 * with the changes you expected instead:
```php
<?php

  class Test
  {
    public function getModel()
    {
      $a = Model::where('something', true)
        ->skip(2)
        ->take(10)
        ->get();
    }
  }
```

It indents backwards, if ran again it unindents once more.
![a](https://user-images.githubusercontent.com/3158040/35366161-37cce758-0135-11e8-9909-664826ed46e4.gif)

**Comment by arosemena** [comment]
Adding 
```php
->setRules(['method_chaining_indentation' => true])
```
Seems to fix it

**Comment by ntzm** [comment]
The issue of it acting differently depending on how many times you run it is a bug. I know you solved your original issue but is it OK if you re-open it to track that bug? Thanks

**Comment by Wirone** [comment]
Closing as this issue refers to Fixer's version which is not maintained anymore. Feel free to reproduce it with latest version (`3.16.0`) and create new issue.

I tried to reproduce it, but Fixer did not change input snippet, so the result was valid after several runs.
