### ISSUE TITLE
phpdoc_annotation_without_dot incorrectly lowercases the first letter of referenced class name

### ISSUE THREAD

**Issue by Strate** [PHP-CS-Fixer/PHP-CS-Fixer#3491]
#### The PHP version you are using (`$ php -v`):
=> php 7.1.13

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.10.0 Bowling Bear

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer.phar fix -vvv filename.php

#### The configuration file you are using, if any:
```php
<?php

$config = PhpCsFixer\Config::create();
$config->setUsingCache(false);
$config->setRules([
    '@Symfony' => true,
    '@PSR2' => true,
    '@PSR1' => true,
    'psr0' => false,
    'class_definition' => [
        'singleItemSingleLine' => true,
        'multiLineExtendsEachSingleLine' => true,
    ],
    'array_syntax' => ['syntax' => 'short'],
    'phpdoc_align' => false,
    'phpdoc_to_comment' => false,
    'phpdoc_inline_tag' => false,
    'phpdoc_summary' => false,
    'phpdoc_no_empty_return' => false,
    'simplified_null_return' => false,
    'no_empty_phpdoc' => false,
    'phpdoc_no_alias_tag' => [
        'property-read' => 'property',
        'property-write' => 'property',
        'type' => 'var'
    ]
]);
$config->setFinder(
    PhpCsFixer\Finder::create()
            ->in([__DIR__.'/app', __DIR__.'/src'])
);

return $config;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
namespace some\namespace

class SomeClass
{
  /**
   * @var OtherClass
   * This is actually referenced some\namespace\OtherClass here.
   */
  private $variable;
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
namespace some\namespace

class SomeClass
{
  /**
   * @var otherClass
   * This is actually referenced some\namespace\OtherClass here
   */
  private $variable;
}
```

 * with the changes you expected instead:
```php
namespace some\namespace

class SomeClass
{
  /**
   * @var OtherClass
   * This is actually referenced some\namespace\OtherClass here
   */
  private $variable;
}
```

Why `phpdoc_annotation_without_dot` fixer even tries to deal with case of letters?

**Comment by SpacePossum** [comment]
Hi and thanks for the report.

There is a detail wrong in the provided sample, it should be:
```php
<?php

namespace some\A;

class SomeClass
{
    /**
     * This is actually referenced some\namespace\OtherClass here.
     * @var OtherClass.
     */
    private $variable;
}
```

without the dot after the `OtherClass` the fixer does not change the casing.

**Comment by Strate** [comment]
No, I have a dot after description, but fixer changes `@var OtherClass` to `@var otherClass`

**Comment by SpacePossum** [comment]
Well, if I correct your sample to:

```php
<?php
namespace a;

class SomeClass
{
    /**
     * This is actually referenced some\namespace\OtherClass here.
     * @var OtherClass
     */
    private $variable;
}
```

and use the config you provided, the result is:

```
<?php

namespace a;

class SomeClass
{
    /**
     * This is actually referenced some\namespace\OtherClass here.
     *
     * @var OtherClass
     */
    private $variable;
}
```

on both 2.2 and 2.10

**Comment by Strate** [comment]
Sorry for inconvinience, sample should be like this:

```php
namespace some\namespace

class SomeClass
{
  /**
   * @var OtherClass
   * This is actually referenced some\namespace\OtherClass here.
   */
  private $variable;
}
```

Description should be after type annotation. Just tested it with 2.10.0 phar.
I am also updated issue description.

**Comment by keradus** [comment]
we are following PHPDoc / PSR-5 proposal spec.
That means, PHPDoc is understand according to:
ABNF: `PHPDoc             = [summary] [description] [tags]`

that means, in your phpdoc, you need to move summary before tag.

**Comment by Strate** [comment]
@keradus I can agree with you about that note, but I can't agree that this is expected behaviour of fixer. As for now, fixer actually broke my code, because that annotations parsed and analyzed and compile time.

From my point of view, fixer should do only one thing, and that thing is about dot at the end of statement.

**Comment by keradus** [comment]
it's not about removing dot, it's about making statement (`Foo bar.`) non-statement (`foo bar`)
