### ISSUE TITLE
`PHPUnit70Migration` ruleset

### ISSUE THREAD

**Issue by BackEndTea** [PHP-CS-Fixer/PHP-CS-Fixer#3510]
One of the changes in phpunit 7.0 is that `@test` annotation is checked a bit more strict. This means that
```php
/**
 * Big @test, Only run if you have time
 */
```

Is no longer accepted as test annotation.

I propose a fixer that would change this into

```php
/**
 * @test
 * Big @test, Only run if you have time
 */
```

This should probably be a risky fixer, since it might change functions that you don't want to be tests into tests.
See: https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-7.0.md

**Comment by ntzm** [comment]
I guess this could be implemented as well:

> @scenario is no longer an alias for @test

**Comment by keradus** [comment]
@BackEndTea sounds like great idea, could you create a PR ?

**Comment by hkdobrev** [comment]
Another thing is that methods like `setUp`, `setUpBeforeClass`, `tearDown` and `tearDownAfterClass` must declare `void` as return type. There are some more signature changes listed here: https://phpunit.de/announcements/phpunit-7.html
