### ISSUE TITLE
Fixer for assignment operators

### ISSUE THREAD

**Issue by EvgenyOrekhov** [PHP-CS-Fixer/PHP-CS-Fixer#3515]
Similar to <https://eslint.org/docs/rules/operator-assignment>.

**Comment by ntzm** [comment]
This has also been discussed here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3235#issuecomment-349463668

I think this is a very good idea 👍

**Comment by keradus** [comment]
yep
@EvgenyOrekhov , go ahead and propose a PR ;)

**Comment by elfring** [comment]
Would you get any further software development ideas from [another information source](https://github.com/slevomat/coding-standard#slevomatcodingstandardoperatorsrequirecombinedassignmentoperator- "Slevomat Coding Standard")? :thinking:
