### ISSUE TITLE
PHPUnit arguments order fixer

### ISSUE THREAD

**Issue by Riimu** [PHP-CS-Fixer/PHP-CS-Fixer#3540]
It would be nice to have a fixer that could deal with a common woe I've encountered when reviewing PHPUnit tests in various projects. One particular problem that has stood out is that people not familiar with PHPUnit are not necessary aware of the argument order for assertions like `assertEquals`, `assertSame`, etc. In fact, in some other testing frameworks and/or languages, the order of arguments is not significant (or is exactly the opposite), which increases the confusion.

PHPUnit, however, clearly defines that the first argument is the expected value and the second argument is the actual value. (though, in practice it should not affect that actual result of assertions, only the formatting of the assertion errors).

I would propose a fixer that could deal with simple cases where the order of arguments seems obviously wrong. And by obvious, I mean when the actual value is a constant, but the expect value is not.

For example, it could fix the following assertion:

```php
$this->assertSame($foo, true);
```

into

```php
$this->assertSame(true, $foo);
```

At least for me, it does not seem to make sense that you would almost ever have a constant value like that as the actual value for the assertion. Additionally, the fixed version would then get picked up by `php_unit_construct` fixer and turned into `$this->assertTrue($foo)` (which currently does not happen due to incorrect order of arguments).

Not sure how feasible this would be to implement (especially as I'd imagine detecting a constant value with arrays is a bit more annoying), but would be a nice to have in any case.

If I had plenty of spare time, I would probably look into implementing this myself, but I'm not really interested delving that deeply into php-cs-fixer internals as of right now.

**Comment by ntzm** [comment]
I like the idea of this a lot 👍

**Comment by Wirone** [comment]
You can use [`PhpUnitAssertArgumentsOrderFixer`](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#phpunitassertargumentsorderfixer) from @kubawerlos' custom fixers. Maybe at some point it will be introduced in main repo, though 😉.
