### ISSUE TITLE
Normalize `null|Foo` vs `?Foo`

### ISSUE THREAD

**Issue by keradus** [PHP-CS-Fixer/PHP-CS-Fixer#3562]
ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3516

**Comment by SpacePossum** [comment]
why the downvote, could be a configurable fixer for one of the two styles?

**Comment by julienfalque** [comment]
Could be. My downvote is for a fixer that would change `Foo|null` to `?Foo`. I'm fine with a fixer doing the opposite change though I don't think it's worth it: I never saw such syntax in PHPDocs except here.

**Comment by ntzm** [comment]
I've never seen `?Foo`, only `null|foo`, would like to be proven wrong though

**Comment by keradus** [comment]
yes, would be nice if fixer could go both ways, so one could always unify his codebase.

there are not that much php 7.1+ codebase yet ;)

**Comment by GrahamCampbell** [comment]
This is implemented now, and can be closed.

**Comment by GrahamCampbell** [comment]
By the `nullable_type_declaration_for_default_null_value` fixer.

**Comment by julienfalque** [comment]
`nullable_type_declaration_for_default_null_value` is different: it updates the real type declaration, while this feature request is about PHPDoc syntax, i.e.:
```php
/** @param Foo|null $foo */
```
vs.
```php
/** @param ?null $foo */
```

**Comment by GrahamCampbell** [comment]
Oh, I see.

**Comment by julienfalque** [comment]
Since PHP now supports union types, I think such PHPDocs will disappear entirely and we won't need such rule anymore. Shall we close?

**Comment by keradus** [comment]
do we have a rule to move that PHPDoc to PHP type declaration?

**Comment by GrahamCampbell** [comment]
> Since PHP now supports union types, I think such PHPDocs will disappear entirely and we won't need such rule anymore. Shall we close?

I don't think so! We still can't express things like `?non-empty-list<non-empty-string>` in PHP types, but this is a valid specialism of `array|null` according to the type system specified by Psalm.

**Comment by pkly** [comment]
I'm working on an implementation of this feature and hopefully will provide a PR soon.

**Comment by paulbalandan** [comment]
This is for PHPDocs, not for type declarations. Should be reopened.
