### ISSUE TITLE
Use statements placement with ordered_imports

### ISSUE THREAD

**Issue by AntoineLemaire** [PHP-CS-Fixer/PHP-CS-Fixer#3586]
When I run PHP-CS-Fixer with `ordered_imports` rule, if I have rule badly located (not at the top of my file), they are not right ordered at the top. 

#### The PHP version you are using (`$ php -v`):
=> PHP 7.1.15

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.10.4

#### The command you use to run PHP CS Fixer:
=> /home/antoine/.composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer --verbose fix /var/www/myproject/src/AppBundle/Entity/MyEntity.php

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__.'/src')
;

return PhpCsFixer\Config::create()
    ->setUsingCache(false)
    ->setRules([
        '@Symfony'               => true,
        'array_syntax'           => ['syntax' => 'short'],
        'phpdoc_order'           => true,
        'ordered_imports'        => true,
        'phpdoc_to_comment'      => false,
        'binary_operator_spaces' => [
            'align_double_arrow' => true,
            'align_equals'       => true,
        ],
    ])
    ->setFinder($finder)
    ;

```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Locale;

class MyEntity
{
    /**
     * @var Ad
     */
    protected $ad;

    /**
     * @var Locale
     */
    protected $locale;
}

use AppBundle\Entity\Ad;

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Ad;

class MyEntity
{
    /**
     * @var Ad
     */
    protected $ad;

    /**
     * @var Locale
     */
    protected $locale;
}

use AppBundle\Entity\Locale;
```

 * with the changes you expected instead:
```php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Ad;
use AppBundle\Entity\Locale;

class MyEntity
{
    /**
     * @var Ad
     */
    protected $ad;

    /**
     * @var Locale
     */
    protected $locale;
}
```

**Comment by keradus** [comment]
Rule worked correctly - it reordered the imports to follow proper (here - alpha) order.

What you experienced is lack of rule to gather all imports in given namespace into one place.
I do agree it would be a nice feature to add. Would you dare and give it a try ? :D

**Comment by AntoineLemaire** [comment]
Damned, I was affraid of that. I never check how PHP-CS-Fixer is working, but I'll have a look if I can
Thanks for your answer

**Comment by keradus** [comment]
doing it as new fixer would simplify few things.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.10/doc/COOKBOOK-FIXERS.md could be a nice start;)

**Comment by AntoineLemaire** [comment]
I did a first try which could be ugly yet, but works

https://github.com/AntoineLemaire/PHP-CS-Fixer/commit/0c6c5d067c37fede50695c33d61c79de2d095b56

I had some problems when I tried to provide input and expected code together.  

```
Tokens collection built on expected code must not be marked as changed after fixing.
Tokens collection built on input code must be marked as changed after fixing.
```

So I forced with `$tokens->clearChanged();` and did not provide input code which make things works, but I would prefere if I can manage that. I think I need to check more documentations

**Comment by keradus** [comment]
the best way to get feedback and help is to open real PR. 
read-only compare on UI doesn't leave much place for comments
