### ISSUE TITLE
Can not format with ```['url' => $url] = $data;```

### ISSUE THREAD

**Issue by kmvan** [PHP-CS-Fixer/PHP-CS-Fixer#3635]
PHP7.2
CSFixer: 2.1.1

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
[                  'url' => $url                         ] = $data;
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
[                  'url' => $url                         ] = $data; //no change, shall be trim spaces.
```

 * with the changes you expected instead:
```php
['url' => $url] = $data;
```

I have look around API several times but not found option about that.

**Comment by keradus** [comment]
I don't believe we have option for that so far, we have `trim_array_spaces` for arrays, but not for list. I bet it's super simple to introduce new rule that would mimic it but for lists. Would you like to give it a try, @kmvan ?

**Comment by kmvan** [comment]
Yes, I will try. Thanks for reply.
