### ISSUE TITLE
PHP code does not align with html code

### ISSUE THREAD

**Issue by muuvmuuv** [PHP-CS-Fixer/PHP-CS-Fixer#3702]
I've a problem with aligning html within a php file. I use a Atom Editor plugin to automatically run php-cs-fixer.

PHP: 7.2.4
PHP-CS-Fixer: 2.11.1
PHP-CS-Fixer Conf: https://hastebin.com/ugimareluv.xml
ATOM: 1.25.1
Beautify: 0.32.2
Beautify Conf: https://hastebin.com/irokawonaq.scala

#### Sample of PHP code:
 * before running PHP CS Fixer (no changes):
```php
....

ob_start();
?>
  <div id="portfolio">
    <div class="container" hidden>
    ........
    </div>
    <div class="portfolio-grid row no-gutters">
      <div class="col-12 col-sm-6 col-md-4 col-xl-3 sizer" style="min-height:0;height:0;"></div>
      <?php
      $query_array = getQueryArray($params);
      $query_results = new \WP_Query($query_array);
      if($query_results->have_posts()):
        while($query_results->have_posts()): $query_results->the_post();

        $terms = wp_get_post_terms(get_the_ID(), 'portfolio-category' );
        $url = wp_get_attachment_url( get_post_thumbnail_id($post->ID) );

        $t = array();
        foreach($terms as $term) $t[] = $term->slug;
        ?>
....
```

 * unexpected changes applied when running PHP CS Fixer:
```php
....
  ob_start(); ?>
  <div id="portfolio">
    <div class="container" hidden>
    ........
    </div>
    <div class="portfolio-grid row no-gutters">
      <div class="col-12 col-sm-6 col-md-4 col-xl-3 sizer" style="min-height:0;height:0;"></div>
      <?php
    $query_array = getQueryArray($params);
  $query_results = new \WP_Query($query_array);
  if ($query_results->have_posts()):
    while ($query_results->have_posts()): $query_results->the_post();

  $terms = wp_get_post_terms(get_the_ID(), 'portfolio-category');
  $url = wp_get_attachment_url(get_post_thumbnail_id($post->ID));

  $t = array();
  foreach ($terms as $term) {
    $t[] = $term->slug;
  } ?>
....
```

 * with the changes you expected instead:
It should just normally align the php code with the html code.

**Comment by amitbisht511** [comment]
I am having the same problem in vscode

php 7.1.11
PHP-CS-Fixer: 2.11.1
vscode:-1.22.2

```PHP
<?php

return PhpCsFixer\Config::create()
    ->setRules(array(
        '@PSR2' => true,
        'array_syntax' => array('syntax' => 'short'),
        'array_indentation' => true,
        'combine_consecutive_unsets' => true,
        'method_separation' => true,
        'no_multiline_whitespace_before_semicolons' => true,
        'single_quote' => true,

        'binary_operator_spaces' => array(
            'align_double_arrow' => false,
            'align_equals' => false,
        ),
        // 'blank_line_after_opening_tag' => true,
        // 'blank_line_before_return' => true,
        'braces' => array(
            'allow_single_line_closure' => true,
        ),
        // 'cast_spaces' => true,
        // 'class_definition' => array('singleLine' => true),
        'concat_space' => array('spacing' => 'one'),
        'declare_equal_normalize' => true,
        'function_typehint_space' => true,
        'hash_to_slash_comment' => true,
        'include' => true,
        'lowercase_cast' => true,
        // 'native_function_casing' => true,
        // 'new_with_braces' => true,
        // 'no_blank_lines_after_class_opening' => true,
        // 'no_blank_lines_after_phpdoc' => true,
        // 'no_empty_comment' => true,
        // 'no_empty_phpdoc' => true,
        // 'no_empty_statement' => true,
        'no_extra_consecutive_blank_lines' => array(
            'curly_brace_block',
            'extra',
            'parenthesis_brace_block',
            'square_brace_block',
            'throw',
            'use',
        ),
        // 'no_leading_import_slash' => true,
        // 'no_leading_namespace_whitespace' => true,
        // 'no_mixed_echo_print' => array('use' => 'echo'),
        'no_multiline_whitespace_around_double_arrow' => true,
        // 'no_short_bool_cast' => true,
        // 'no_singleline_whitespace_before_semicolons' => true,
        'no_spaces_around_offset' => true,
        // 'no_trailing_comma_in_list_call' => true,
        // 'no_trailing_comma_in_singleline_array' => true,
        // 'no_unneeded_control_parentheses' => true,
        'no_unused_imports' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line' => true,
        // 'normalize_index_brace' => true,
        'object_operator_without_whitespace' => true,
        // 'php_unit_fqcn_annotation' => true,
        // 'phpdoc_align' => true,
        // 'phpdoc_annotation_without_dot' => true,
        // 'phpdoc_indent' => true,
        // 'phpdoc_inline_tag' => true,
        // 'phpdoc_no_access' => true,
        // 'phpdoc_no_alias_tag' => true,
        // 'phpdoc_no_empty_return' => true,
        // 'phpdoc_no_package' => true,
        // 'phpdoc_no_useless_inheritdoc' => true,
        // 'phpdoc_return_self_reference' => true,
        // 'phpdoc_scalar' => true,
        // 'phpdoc_separation' => true,
        // 'phpdoc_single_line_var_spacing' => true,
        // 'phpdoc_summary' => true,
        // 'phpdoc_to_comment' => true,
        // 'phpdoc_trim' => true,
        // 'phpdoc_types' => true,
        // 'phpdoc_var_without_name' => true,
        // 'pre_increment' => true,
        // 'return_type_declaration' => true,
        // 'self_accessor' => true,
        // 'short_scalar_cast' => true,
        'single_blank_line_before_namespace' => true,
        // 'single_class_element_per_statement' => true,
        // 'space_after_semicolon' => true,
        // 'standardize_not_equals' => true,
        'ternary_operator_spaces' => true,
        // 'trailing_comma_in_multiline_array' => true,
        'trim_array_spaces' => true,
        'unary_operator_spaces' => true,
        'whitespace_after_comma_in_array' => true,
    ))
    ->setIndent("  ")
    ->setLineEnding("\n")
;

**Comment by keradus** [comment]
PHP CS Fixer was never written with supporting mixed html/php file.
Some fixers are supporting one php part and one html part inside single file, but big mix of them, like in template files.
If we would like to support template files, we would need to not only detect and track concrete fixers, but also provide some big integration test (like we do for Sf ruleset) that it remains to work for most important rules.

Before that happen, I would not claim that we officially support html/php mixed-files. cc @FriendsOfPHP/php-cs-fixer 

-----------------------------------------------

currently, there are too many opened issues/PR to handle everything by core team. Do you want to help dealing with mixed files, @rattkin ?

**Comment by ntzm** [comment]
I think it's important to stress, maybe in the README or issue template, that mixed PHP and HTML files are not explicitly supported. It would be good to get a compiled list of every issue that relates to mixed PHP and HTML in case there's a common detail that can be fixed quite easily.

**Comment by amitbisht511** [comment]
Thats Ok i understand why its not support html with php

but instead i found my solution whenever i need to mix php with html i use [alternate syntax](https://secure.php.net/manual/en/control-structures.alternative-syntax.php)
and that is much cooler

By the way thank you everyone

**Comment by muuvmuuv** [comment]
Hey @amitbisht511 – nothing to this topic – how do u apply this phpcs config to vscode? Are you using a plugin, because I can not get mine running, only with .xml config...

**Comment by muuvmuuv** [comment]
@keradus maybe implement this functionality as a plugin in the future?

And do you have a example of plugins that can part php part html formating?

**Comment by keradus** [comment]
sorry @muuvmuuv , I'm not fully understand you here. what do you mean by a `plugin` here?
plugin for vscode?

**Comment by keradus** [comment]
>  It would be good to get a compiled list of every issue that relates to mixed PHP and HTML in case there's a common detail that can be fixed quite easily.

@ntzm , the thing is - do we want to have that support or not? there are already some rules that **requires** fixing file to be monolitic (explicitly no html content at all).
if, in future, we want to - first step IMO would be to create a PR with integration test, see how much it's failing, and then decide, is it small enough to simply fix it, or it's so big that we would add a note in readme

**Comment by muuvmuuv** [comment]
@keradus oh sry, I mean option. As I think this function will decrease performance, some users that use alternative syntax doesn't want to have this.

**Comment by keradus** [comment]
i don't believe that would be an `option` (like a configuration) for whole tool. it's every single rule that is affected by that would have to learn how to work properly with mixed content. some of them could be easy (fix indentation detection), some harder (move private methods after public methods, but I really doubt one would do that in template file...)

**Comment by muuvmuuv** [comment]
Hmm okay, I understand your point. Do you know any alternative fixer that supports mixed fixing? @keradus 

When do you think you will test that functionality to give us an insight into how hard it would be to implement this fully?

**Comment by kubawerlos** [comment]
I couldn't care less about files with mixed content - if one is mixing HTML with PHP he should not care about coding style - he has bigger problem and that is obviously having HTML mixed with PHP.

There is enough to do with monolitic files right now.

**Comment by muuvmuuv** [comment]
@kubawerlos and how do you think I should handle templating for CMS? I‘m working on a template for Joomla right now and there I have huge HTML/PHP mixed files. I can‘t get rid of them.

Here is an example of an index.php: https://hastebin.com/licopedatu.bash

**Comment by rattkin** [comment]
@kubawerlos Yes. OpenCart as well. It's not possible for us to replace a huge e-shop that took three years to build. Sure new stuff has elegant templating systems, but what about legacy (legacy = 3 years old)

**Comment by kubawerlos** [comment]
So, what's most important you have the will to improve :+1: 

When I approach legacy code I create 2 configurations - the "light" version and "strict" one with more rules - at the beginning all files under "light" check, and then, step by step move them under the "strict" when working with.

Or maybe instead of light/strict one for pure PHP files and one for mixed content.

**Comment by muuvmuuv** [comment]
@kubawerlos That is not possible, I can not rewrite a CMS… I think there is a big use for that feature. Many CMS like Wordpress or as I mentioned Joomla, are using PHP without a templating engine. That developers should be respected as well.

And as I can say about me, I‘m not a fan of the alternative style or implementing a templating engine in every project I create!

**Comment by keradus** [comment]
I decided to close this thread.
- thread is dead
- we do not aim to fix mixed file (PHP and HTML in single file)

**Comment by SagarKapasi099** [comment]
> * we do not aim to fix mixed file (PHP and HTML in single file)

For anyone who is still stuck, i am using this plugin with VS Code. Formats PHP Within HTML Properly.
```
Name: PHP Intelephense
Id: bmewburn.vscode-intelephense-client
Description: PHP code intelligence for Visual Studio Code
Version: 1.8.2
Publisher: Ben Mewburn
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client
```
![image](https://user-images.githubusercontent.com/26804608/179116991-427d74ac-0434-46c4-81db-ed8d2314e38c.png)

**Comment by pimvanderheijden-cpi** [comment]
Intelephense or IntelliSense?

**Comment by pimvanderheijden** [comment]
I started doing `"php-cs-fixer.formatHtml": false` in VSCode settings, combined with PHP Intelephense extension and Format HTML in PHP. It's the last extension that did the trick for me, not Intelephense. Now I've got a long list of extensions, not clear if compatible or recommended to combine them. 

![image](https://user-images.githubusercontent.com/112478297/196783352-424fa714-a914-45a4-bfdf-38fe0eba5daf.png)

**Comment by realjjaveweb** [comment]
@kubawerlos 
> if one is mixing HTML with PHP he should not care about coding style - he has bigger problem and that is obviously having HTML mixed with PHP

Your assumption in general is wrong, most of such files are actually simple PHP templates - which is how PHP even started.

There is a big performance difference between using PHP template directly over library that in the end does similar or the same. Also reduces any complexity if you do need to call something additional from PHP or add new template helpers.

That being said, big monolitic files mixing functionality and PHP/HTML templates are wrong ofc...

**Comment by Wirone** [comment]
@realjjaveweb Please have in mind that Fixer is focused on modern PHP, that does not mix code with HTML markup (see [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6788#issuecomment-1438688702)), that's why we closed all the issues related to HTML some time ago. There's no point in commenting issue closed 2 years ago 😉.

**Comment by realjjaveweb** [comment]
@Wirone 
> @realjjaveweb Please have in mind that Fixer is focused on modern PHP, that does not mix code with HTML markup (see [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6788#issuecomment-1438688702)), that's why we closed all the issues related to HTML some time ago. There's no point in commenting issue closed 2 years ago 😉.

I very strongly disagree, actually, I was hoping that maybe you've changed your mind after a few years and I was really hoping for this issue to be reopened, not closed.

The comment you've linked is inherently wrong with the argumentation - not all PHP&HTML mixed files are mixing logic with view - many of them are very simple view files, I have even seen project that leveraged `<?= $value ?>` in its PHP templates - and there was **no logic**, really a simple view.

Now I understand there is a good intention of discouraging mixing logic into view, however, removing it completely is using a sledge hammer on a fly - sure it will work, but it also destroys everything around that has nothing to do with it.
I would rather suggest enforcing the not-mixing policy (like forbidding class definitions when there's a mixed file) than removing the option to do simple efficient templating with PHP (we don't want to get back to "echo" times...).

Should I open a new issue then?

**Comment by Wirone** [comment]
> and I was really hoping for this issue to be reopened, not closed.

It was already closed [since May 13, 2021](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/3702#event-4743397292), I just only changed the resolution from "completed" to "not planned".

> Should I open a new issue then?

There's no point in opening new issue because decision has been made and we won't support non-monolithic PHP files. However, you still can use all the rules in such files, but we won't provide support if these rules don't work properly with mixed PHP/HTML.

**Comment by keradus** [comment]
> However, you still can use all the rules in such files (...)

this is temporary. PHP CS Fixer was never intended to support those files, but actual technical possibility to do it was an overlook from my side. With next major version, PHP CS Fixer will simply skip such files.

**Comment by realjjaveweb** [comment]
@keradus if that's the future aim, I would rather see it throw error and people would have to manually put those into ignore lists than sort of silently skipping them :-) I have a feeling that's what most would expect.

**Comment by Wirone** [comment]
Personally I believe it would be better to make it configurable:
- skip non-monolithic files (default)
- opt-in: allow non-monolithic files and continue like it was in v3 (without official support, users' responsibility)
- opt-in: exception on non-monolithic files (debatable, I am not sure if this is actually helpful)

Anyway, drop the support but allow people to use it like they use it now, because it somehow works for them, even if there are some issues. Removing this quasi-support completely can lead to users drop, which is not something we want. But it's only my opinion.

**Comment by RepinsPL** [comment]
Just made a solution:
https://github.com/RepinsPL/php-cs-fixer-html-indent
