### ISSUE TITLE
sprintf to interpolation fixer

### ISSUE THREAD

**Issue by ntzm** [PHP-CS-Fixer/PHP-CS-Fixer#3707]
As of PHP 7 string interpolation is more performant than `sprintf` calls: https://blog.blackfire.io/php-7-performance-improvements-encapsed-strings-optimization.html (thanks @keradus)

```diff
-echo sprintf('foo %s baz', $bar);
+echo "foo $bar baz";
```

```diff
-echo sprintf('foo %s baz', $this->bar());
+echo "foo {$this->bar()} baz";
```

Obviously it gets a bit more complicated when you have expressions in the sprintf, so it shouldn't be changed here:

```diff
echo sprintf('foo %s baz', 1 + 1);
```

**Comment by julienfalque** [comment]
Maybe variable detection (to know whether string interpolation can be applied) could be extracted from YodaStyleFixer.

**Comment by soullivaneuh** [comment]
We also may convert this:

```php
echo 'Hello '.$name.'!';
```

By this:

```php
echo "Hello {$name}!";

**Comment by Wirone** [comment]
Personally I think it's too complicated change with too little value. `sprintf()` supports different kinds of placeholders and to maintain the same output fixer should analyse the template (first argument), which seems like overkill. For example:

```
php > echo sprintf('%s', 1.23);
1.23
php > echo sprintf('%d', 1.23);
1
php > echo sprintf('%0.1f', 1.23);
1.2
```

Not to mention positional arguments (`%1$d`) where the same parameter can be printed several times. Such fixer would be too complicated or would have too little coverage if we decide to not support more complex cases. Not worth doing IMHO and this issue should be closed.

@keradus @kubawerlos what do you think?

**Comment by kubawerlos** [comment]
Sound complicated, also I'd prefer the fixer doing it the other way, so some may say the code is more readable then.
