### ISSUE TITLE
FR: Unnecessary type casting

### ISSUE THREAD

**Issue by kalessil** [PHP-CS-Fixer/PHP-CS-Fixer#3851]
Would love to have those cases covered:

```
... .= (string)...
... . (string)...
(float)1.0 /* or other implicit float value */
(int)1 /* or other implicit integer value */
```

**Comment by keradus** [comment]
while `(int)1` -> `1` is nice to have for every single time,
`"f" . (string)$object` may be there to explicitly do the conversion

:+1: for feature, but maybe a configurable one ?

**Comment by julienfalque** [comment]
I seldom see such obviously redundant type castings like `(int) 1`, `(float) 1.0`, ... Most involve variables and PHP CS Fixer isn't able to understand the code well enough to detect that. IMO this is a static analysis responsibility (PHPStan already reports those if I remember correctly).

**Comment by SpacePossum** [comment]
There can be other cases like `!true` , `!false`, but also `(true) isset()`, that can all be clear up (beside the language constructs removing casts from other PHP API methods might make sense as well like `(bool) in_array(...)` )

**Comment by Wirone** [comment]
I am going to close this because:
- it did not have any interest from the community
- Fixer does not have proper context to catch such things (I believe PHPStan/Psalm are better fit for this particular job)
- it's too wide (see comments above) and we don't have capacity to work on that
