### ISSUE TITLE
PHPUnit annotations for ignoring code coverage are reformatted incorrectly

### ISSUE THREAD

**Issue by sebastianbergmann** [PHP-CS-Fixer/PHP-CS-Fixer#3868]
#### The PHP version you are using (`$ php -v`):
```
$ php -v
PHP 7.2.7 (cli) (built: Jun 19 2018 14:40:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
```
$ php-cs-fixer -V
PHP CS Fixer 2.12.1 Long Journey by Fabien Potencier and Dariusz Ruminski (beef6cb)
```
## Original
```php
<?php
class C
{
    public function m()
    {
    // @codeCoverageIgnoreStart
    }
    // @codeCoverageIgnoreEnd

    public function n()
    {
    } // @codeCoverageIgnore
}
```
## Output
```
   1) C.php (class_attributes_separation, braces)
      ---------- begin diff ----------
--- Original
+++ New
@@ -3,11 +3,14 @@
 {
     public function m()
     {
-    // @codeCoverageIgnoreStart
+        // @codeCoverageIgnoreStart
     }
+
     // @codeCoverageIgnoreEnd
 
     public function n()
     {
-    } // @codeCoverageIgnore
+    }
+
+    // @codeCoverageIgnore
 }

      ----------- end diff -----------
```
## Result
```php
<?php
class C
{
    public function m()
    {
        // @codeCoverageIgnoreStart
    }

    // @codeCoverageIgnoreEnd

    public function n()
    {
    }

    // @codeCoverageIgnore
}
```
While the multi-line annotations `@codeCoverageIgnoreStart` and `@codeCoverageIgnoreEnd` are only reformatted so that they look "ugly" (IMO), the single-line annotation `@codeCoverageIgnore` is reformatted so that it no longer has the desired effect.

**Comment by keradus** [comment]
Hi @sebastianbergmann !
Body of code blocks, like here - methods, are indented accordingly to block + one nesting level.
And it;s exactly what happened here - it's not related to this particcular annotation, but to any code.

please consider having start/end annotation on same level (eg before/after `m` method or at start/end of it's body)

**Comment by sebastianbergmann** [comment]
I have them on the same level in the original. It's about ignoring the one line with the `}`, not the entire method.

**Comment by keradus** [comment]
That's why i said - content of block, here method body, was reformatted to match indentation of it.
you had them on same indent level, but in different blocks - so re-indenting changed them to match indent of block

**Comment by sebastianbergmann** [comment]
I get that. Is there any chance to add special treatment of these annotations to php-cs-fixer, at least for `// @codeCoverageIgnore`?

**Comment by keradus** [comment]
ping @localheinz @SpacePossum @julienfalque @ntzm @kubawerlos 
what do you think ?

**Comment by julienfalque** [comment]
Adding a blank line between the closing brace and the `// @codeCoverageIgnore` comment seems to be done by `class_attributes_separation` rule. I would say this a bug: the comment shouldn't move at all.

**Comment by ntzm** [comment]
If we are going to treat `@codeCoverageIgnore` differently to normal comments, it may be useful to find out if there are any other specific tags we should be ignoring too. I totally agree with @SpacePossum that there needs to be a unified style for ignores. I also agree with @julienfalque, it doesn't seem like `class_attributes_separation` should be moving comments as they are not a class attribute.

**Comment by julienfalque** [comment]
IMO there is no need for a special treatment here, any comment after a closing brace should not be moved.

**Comment by SpacePossum** [comment]
The comment doesn't belong to the method so it gets separated from it, which is what the rule is designed to do. If you don't want to make an exception for these types of comments than I would advice disabling the rule.

**Comment by kubawerlos** [comment]
I would consider extending fixer `class_attributes_separation` with option like `separate_comments` (default to `false`).

**Comment by SpacePossum** [comment]
that would bring back something like this;
```php
    public function testCreate()
    {
    } //a
    /**
     */
    public function testIfAllRulesInSetsExists($setName, $ruleName, $ruleConfig)
    {
    } /**
     **/
    public function testThatThereIsNoDeprecatedFixerInRuleSet($setName, $ruleName)
    {
    }
```

I really don't get it, if you don't want to separate elements (which is totally fine), why run with the rule?

Adding a vague exception to that single rule is not going to solve the issue with moving this special type of comment, some other rule will break it soon enough. If we want to deal with this comment, awesome lets model it so all rules can detect it and leave it alone.

**Comment by julienfalque** [comment]
Maybe the fixer should add the blank line only before a DocComment instead of all kinds of comment? A `// single line comment` is more likely to be related to the closing brace before it, while a DocComment is more likely to be related to the next element.

**Comment by SpacePossum** [comment]
There is no way I'm going back into the `comment moving` discussion for this rule over something that is not related;
if you don't want to not move some special comment than lets get that in, but please don't make this something bigger.

**Comment by keradus** [comment]
@sebastianbergmann , you have opened Pandora's box...

**Comment by Wirone** [comment]
I'm going to close this because issue mentions Fixer version which is not maintained anymore. Feel free to reproduce it on latest version (if problem still exists) and create new issue.
