### ISSUE TITLE
Support phpDoc in `fully_qualified_strict_types`

### ISSUE THREAD

**Issue by CMalvika** [PHP-CS-Fixer/PHP-CS-Fixer#3958]
First of all i know it's not a bug or really an issue, but i would like to have it as a feature request. 
Reason for that, is currently using this fixer, leaves code base in inconsistent state. 

If i use fully_qualified_strict_types to transforms imported FQCN parameters and return types in function arguments to short version, i would also expect that if it can also transforms for the types that are mentioned within Phpdoc.

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.1.16
#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.10.0

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
/** @param \This\Is\Param\Namespace\User $x **/
public function beforePhpCsFixer(\This\Is\Param\Namespace\User $x, string $y): void
{
    // function body
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
/** @param \This\Is\Param\Namespace\User $x **/
public function beforePhpCsFixer(User $x, string $y): void
{
    // function body
}
```

 * with the changes you expected instead:
```php
/** @param User $x **/
public function beforePhpCsFixer(User $x, string $y): void
{
    // function body
}
```

Thank you!

**Comment by ntzm** [comment]
👍 for this feature. Btw, you have `\This\Is\Param\Namespace\Use` instead of `\This\Is\Param\Namespace\User` 😉

**Comment by CMalvika** [comment]
Updated it!

**Comment by dmvdbrugge** [comment]
Just as a thought: should it be an option (but enabled by default)? I know people who prefer docs to always be FQCN even while code might use short version.

**Comment by ntzm** [comment]
Definitely should be an option, the default behaviour of a fixer shouldn't be changed in minor releases.

**Comment by dmvdbrugge** [comment]
> Definitely should be an option

> shouldn't be changed in minor

That thus depends on which version you target 😉 but I agree.
However, (in the case this feature gets built) enabling by default for next major, 👍 or 👎?

**Comment by CMalvika** [comment]
Thank you @ntzm and @dmvdbrugge for supporting my request.

**Comment by Jadro007** [comment]
Hello guys,
I opened PR that should address this thread as it add support for PHPDoc for the fully_qualified_strict_types fixer. Feel free to check it and add some comments, so there is a chance that it gets merged. 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5620

**Comment by CMalvika** [comment]
Thanks @Jadro007 after 2.5 years, i even forgot about this report :)
