### ISSUE TITLE
NoExtraBlankLinesFixer and curly braces

### ISSUE THREAD

**Issue by kubawerlos** [PHP-CS-Fixer/PHP-CS-Fixer#3975]
#### The PHP version you are using (`$ php -v`):
=> 7.2.8

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> master

#### The configuration file you are using, if any:
```php
'no_extra_blank_lines' => ['tokens' => ['curly_brace_block',]]
```

 * before running PHP CS Fixer (no changes):
```php
class FooClass
{use FooTest;

    public function fooFunction() {}
}

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
class FooClass
{use FooTest;
    public function fooFunction() {}
}

```

 * with the changes you expected instead:
no changes (?)

It is a but with the fixer, right? If not, `ClassAttributesSeparationFixer` will have priority conflict with it which will be hard to solve (`-20` and `55` priorities to swap).

**Comment by SpacePossum** [comment]
both fixers are correct, so sadly yeah this is a priority issue that will be hard to solve :|

**Comment by kubawerlos** [comment]
`ClassAttributesSeparationFixer` is now nicely handling all the separation, the issue is no more.

**Comment by Wirone** [comment]
FYI:

<img width="970" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/84db721a-83a2-469b-af6b-9438f6480370">
