### ISSUE TITLE
Indention broken

### ISSUE THREAD

**Issue by muuvmuuv** [PHP-CS-Fixer/PHP-CS-Fixer#3984]
When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> PHP 7.2.8 (cli) (built: Jul 19 2018 12:15:24) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.12.2 Long Journey by Fabien Potencier and Dariusz Ruminski (dcc87d5)

#### The command you use to run PHP CS Fixer:
=> I'm using a plugin for VSCode but the same occurs when `php-cs-fixer fix <FILE> --config=<CONFIG>`

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
  ->setRiskyAllowed(true)
  ->setIndent('  ')
  ->setRules([
    '@Symfony' => true,
    'align_multiline_comment' => ['comment_type' => 'all_multiline'],
    'array_indentation' => true,
    'array_syntax' => ['syntax' => 'short'],
    'backtick_to_shell_exec' => true,
    'braces' => true,
    'combine_consecutive_issets' => true,
    'combine_consecutive_unsets' => true,
    'comment_to_phpdoc' => true,
    'compact_nullable_typehint' => true,
    'doctrine_annotation_array_assignment' => ['operator' => ':'],
    'doctrine_annotation_braces' => ['syntax' => 'with_braces'],
    'doctrine_annotation_indentation' => true,
    'doctrine_annotation_spaces' => true,
    'ereg_to_preg' => true,
    'error_suppression' => true,
    'explicit_indirect_variable' => true,
    'fully_qualified_strict_types' => true,
    'function_to_constant' => true,
    'increment_style' => ['style' => 'post'],
    'indentation_type' => true,
    'linebreak_after_opening_tag' => true,
    'list_syntax' => ['syntax' => 'short'],
    'logical_operators' => true,
    'method_chaining_indentation' => true,
    'multiline_comment_opening_closing' => true,
    'multiline_whitespace_before_semicolons' => true,
    'no_null_property_initialization' => true,
    'no_php4_constructor' => true,
    'no_short_echo_tag' => true,
    'no_useless_else' => true,
    'no_useless_return' => true,
    'phpdoc_add_missing_param_annotation' => true,
    'phpdoc_trim_consecutive_blank_line_separation' => true,
    'phpdoc_types_order' => true,
    'self_accessor' => true,
    'simplified_null_return' => true,
  ])
  ->setFinder(PhpCsFixer\Finder::create()
  ->exclude('vendor')
  ->in(__DIR__)
  );
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

unset(
  $this->_scripts['/plugins/system/mediabox_ck/assets/mediaboxck.min.js'], $this->_scripts['/media/jui/js/jquery-migrate.min.js'],
$this->_scripts['/media/jui/js/jquery-noconflict.js']);

  $app = JFactory::getApplication();
$document = JFactory::getDocument();
$user = JFactory::getUser();
```

 * with the changes you expected instead:
```php
<?php

unset(
   $this->_scripts['/plugins/system/mediabox_ck/assets/mediaboxck.min.js'], 
   $this->_scripts['/media/jui/js/jquery-migrate.min.js'],
   $this->_scripts['/media/jui/js/jquery-noconflict.js']
);

$app      = JFactory::getApplication();
$document = JFactory::getDocument();
$user     = JFactory::getUser();
```

**Comment by dmvdbrugge** [comment]
Your title says "array indentation", however I see no new arrays being created.

The alignment of the equals is `binary_operator_spaces` (which is enabled in `@Symfony`, just not with the config you want so you'll have to respecify it).

I don't know what you'd want with the unset, but personally what I'd expect would be more like

```
unset(
    $this->_scripts['/plugins/system/mediabox_ck/assets/mediaboxck.min.js'],
    $this->_scripts['/media/jui/js/jquery-migrate.min.js'],
    $this->_scripts['/media/jui/js/jquery-noconflict.js']
);
```

However I'm not entirely sure what config would fix that. I thought `method_argument_space` or perhaps `braces` would do it but they're already enabled.

**Comment by muuvmuuv** [comment]
@dmvdbrugge oops sorry forgot to change this. Updated it. I mean generally indention for that example. I have symphony enabled as you can see but it does nothing and it is not fixing those things above...

**Comment by SpacePossum** [comment]
Hi @dmvdbrugge 

The Symfony CodeStyle will unalign your statements. Given your example and expected fixing I would recommend adding the folowing to your config;

```
->setRules([
[...]
 '@Symfony' => true,
[...]
        'binary_operator_spaces' => [
            'operators' => [
                '=' => 'align_single_space_minimal',
            ]
        ],
```

this will align the last 3 lines.

For the indenting within the `unset`, we've `method_argument_space`  which seems to do just that for `methods` and `functions` but not for language constructs it seems, maybe that one can be added as an option.

**Comment by keradus** [comment]
question - if you would put that piece of code in any kind of braces - `{` (eg wrap code in function, condition), would `$app` be aligned?

**Comment by muuvmuuv** [comment]
@keradus yes. That works. Anyway, shouldn't that work without wrapping too?

**Comment by keradus** [comment]
that's what I expected, cool.

So, aligning of `=` works with config, cool.

Missing part is `braces` rule does not fix unwrapped code. It's simplification we assumed in this fixer, we are open to start doing those changes as well - but that require someone to get his hands dirty on it. Do you want to give it a try ?

**Comment by keradus** [comment]
Fixer responsible for this is https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.12/src/Fixer/Basic/BracesFixer.php

I would suggest to start by adding next unit test for it (vide `BracesFixerTest` file) and then trying to figure out which part of BracesFixer is responsible for adjusting indentation. look for things like `'{'` and `'}'` to find respective code pieces.

**Comment by SpacePossum** [comment]
`$app` is properly unindented by `braces` as well.

This leaves, for this issue, the `unset` arguments not be placed on one per line.
The `method_argument_space` does this for function calls (not just methods, so the name is a bit off), but since `unset` is a language construct it does not get fixed.
Maybe we can an option to the fixer to fix constructs as well (`unset`, `isset`, etc)

**Comment by Wirone** [comment]
I'm going to close this one since the context of the issue has changed. @muuvmuuv feel free to open feature request with what @SpacePossum said [here](#issuecomment-1229128990) if you still need it 🙂.
