### ISSUE TITLE
New rule to configure a code example in the description of a PHPDoc

### ISSUE THREAD

**Issue by maidmaid** [PHP-CS-Fixer/PHP-CS-Fixer#3985]
It exists different ways to write a code example in the description of a PHPDoc.

- 4 spaces of indentation:

```php
 /**
  * This is the summary for a DocBlock.
  *
  *     $a = [];
  */
```

- `<code>` or `<pre>` tag:

```php
 /**
  * This is the summary for a DocBlock.
  *
  * <code>
  * $a = [];
  * </code>
  */
```

- markdown syntax:

```php
 /**
  * This is the summary for a DocBlock.
  *
  * ```
  * $a = [];
  * ```
  */
```
It could be interesting to have a new rule configuring which way is allowed. See https://github.com/symfony/symfony/pull/28301 for a real use case.

**Comment by keradus** [comment]
Hi @maidmaid !
This feature request looks interesting, yet I must say that it won't end up as my prio.
Maybe, you want to help and implement it? it would be great!

**Comment by maidmaid** [comment]
Hi @keradus, thanks for your comment ! I can't guarantee to have the time to do it. Let's keep this issue opened and if I (or someone else) find the time to do it, it'd perfect !

**Comment by maidmaid** [comment]
Another feature could be to detect the _wrong_ code example (PHP code without indentation, tag or markdown syntax), which breaks the PHPDoc render.

```
 /**
  * This is the summary for a DocBlock.
  *
  * $a = [];
  */
```

**Comment by keradus** [comment]
:-1: for that
you can't say for 100% that given part is code or not, and then even if you would, you can't say it shall be treated as code sample

**Comment by Wirone** [comment]
I am going to close this one because there was literally 0 interest in this for past 5 years. It has minimal value IMHO and in modern PHP phpDoc is rather not used much.
