### ISSUE TITLE
doctrine_annotation_spaces.after_array_assignments_colon rule doesn't add a space if key is a constant

### ISSUE THREAD

**Issue by flaksp** [PHP-CS-Fixer/PHP-CS-Fixer#3994]
The difference between two last examples is space after `:` symbol.

#### The PHP version you are using (`$ php -v`):
PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul  4 2018 16:55:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.7-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
PHP CS Fixer 2.13.0 Yogi's BBQ by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
```console
vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --show-progress=dots --allow-risky=yes
```
#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setRules([
        'doctrine_annotation_array_assignment' => [
            'operator' => ':',
        ],
        'doctrine_annotation_braces' => [
            'syntax' => 'with_braces'
        ],
        'doctrine_annotation_indentation' => [
            'indent_mixed_lines' => true,
        ],
        'doctrine_annotation_spaces' => [
            'after_argument_assignments' => false,
            'after_array_assignments_colon' => true,
            'after_array_assignments_equals' => false,
            'around_commas' => true,
            'around_parentheses' => true,
            'before_argument_assignments' => false,
            'before_array_assignments_colon' => false,
            'before_array_assignments_equals' => false,
        ],
    ])
    ->setFinder($finder)
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace App\Entity;

use App\Enum\Foo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorMap({
 *     Foo::A=EntityA::class,
 *     Foo::B=EntityB::class,
 *     Foo::C=EntityC::class,
 * })
 */
abstract class MyEntity
{
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

namespace App\Entity;

use App\Enum\Foo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorMap({
 *     Foo::A:EntityA::class,
 *     Foo::B:EntityB::class,
 *     Foo::C:EntityC::class,
 * })
 */
abstract class MyEntity
{
}
```

 * with the changes you expected instead:
```php
<?php

namespace App\Entity;

use App\Enum\Foo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorMap({
 *     Foo::A: EntityA::class,
 *     Foo::B: EntityB::class,
 *     Foo::C: EntityC::class,
 * })
 */
abstract class MyEntity
{
}
```

**Comment by julienfalque** [comment]
This is because `Foo::A:EntityA::class` is parsed as a single token of type `T_IDENTIFIER`. Maybe this issue should be forwarded to [`doctrine/annotations`](https://github.com/doctrine/annotations/)?

**Comment by Wirone** [comment]
Reproduced on `3.16`, but it's weird since Fixer applies `doctrine_annotation_array_assignment, doctrine_annotation_braces` when using `@DoctrineAnnotation`, and when I use each of those 2 fixers separately, there is no such change (from `=` to `:`) 🤷.

**Comment by Wirone** [comment]
I am going to close this, as this wasn't picked up for 6 years, and there's close-to-zero chance that anyone will do it at this point, especially when annotations are not actively supported anymore and PHP8 attributes are the way to go.
