### ISSUE TITLE
Show filename in -vvv output

### ISSUE THREAD

**Issue by flack** [PHP-CS-Fixer/PHP-CS-Fixer#3997]
Currently when `php-cs-fixer` is running recursively on an entire file tree, you only get a `.` output for each file it's processing. For debugging purposes, for example when the program gets stuck (see #3996 e.g) it would be helpful if it would show the filename at least when `-vvv` is provided. Because otherwise, it's really hard to find out where exactly it gets stuck

**Comment by keradus** [comment]
probably, `--show-progress=testdox` (default is `dots`) would be better to serve this purpose

(see `vendor/bin/phpunit --testdox` for example)

**Comment by flack** [comment]
works for me. As long as I can see what it is currently working on, the problem is solved :-)

**Comment by Wirone** [comment]
FYI: Initial refactor of progress output handling is in #6848, when it gets merged I will rebase #6842 which brings new progress output formats (with file names).
