### ISSUE TITLE
Warning: Octal escape sequence overflow \542 is greater than \377

### ISSUE THREAD

**Issue by petk** [PHP-CS-Fixer/PHP-CS-Fixer#4018]
#### The PHP version you are using (`$ php -v`):
=> PHP 7.2 latest

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=>  2.13.0 

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix foo.php

#### The configuration file you are using, if any:
no configuration file

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

var_dump("\542");
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

var_dump("\542");
```

 * with the changes you expected instead:
```php
<?php

var_dump("\542");
```

Hello, when token_get_all() encounters the octal sequence greater than `\377` it emits a warning.

See: https://wiki.php.net/rfc/octal.overload-checking

For example, above PHP file emits this warning when running php-cs-fixer on such file:

Warning: Octal escape sequence overflow \542 is greater than \377
Thanks...

**Comment by Wirone** [comment]
I'm going to close this one, because it seems out of the scope of Fixer. There isn't even any specified suggestion what should happen. Feel free to reopen issue, but please verify it with latest Fixer release and provide information about what would you expect from the tool.

**Comment by keradus** [comment]
yep, looks PHP itself
```
ker@d ~ λ php -l x.php 
PHP Warning:  Octal escape sequence overflow \542 is greater than \377 in x.php on line 3

Warning: Octal escape sequence overflow \542 is greater than \377 in x.php on line 3
```
