### ISSUE TITLE
BlankLineAfterStatementFixer

### ISSUE THREAD

**Issue by dennisdahlc** [PHP-CS-Fixer/PHP-CS-Fixer#4053]
Would it be possible to create a fixer which could take the same arguments as the BlankLineBeforeStatementFixer ensuring a blank line after the end of the control structure ?

A obvious exception should be that it should not require a blank line if the next meaningful token is not a '}'

**Comment by SpacePossum** [comment]
Hi and thanks for the suggestion,

Worth  try I would say, maybe these rules can be merge into it:
- `blank_line_after_namespace`
- `blank_line_after_opening_tag`
- (not sure about `single_blank_line_at_eof`)

**Comment by localheinz** [comment]
@dennisdahlc 

Ha, also see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4065#issuecomment-432166113!

Would be great to have such a fixer!

**Comment by Rolige** [comment]
I think that at the beginning it would be easier and easier to create it in a separate rule.

**Comment by Vashkatsi** [comment]
Any news?

**Comment by Wirone** [comment]
I believe we need proper [RFC](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/categories/rfc) for this, but for now I'm going to keep this issue to not lose track of it.
