### ISSUE TITLE
Suggestion for "header_comment"

### ISSUE THREAD

**Issue by Rolige** [PHP-CS-Fixer/PHP-CS-Fixer#4072]
As title say, this is not an issue, is just a suggestion for this option `header_comment`, with which we can add, replace or remove header comments, but, how about of "change"?, actually there is no way to keep the original header comment changing only the blank line in the top or bottom, or I'm missing out on some other option?

**Comment by SpacePossum** [comment]
Hi @Rolige and thanks for your suggestion.

What you describe about not being able to change the spacing around existing headers sounds like a bug to me. Can you give a minimal sample of what you would like to change and the expected result?

**Comment by Rolige** [comment]
Hi @SpacePossum, is not a bug, it's just a combination that can not be achieved, or at least I could not. Let me give you an example...

**Original code:**
```php
<?php
/**
 * My header text
 *
 * @author Me
 */

$x = 1;

class MyClass
{
    /**
     * My method
     * @param string $var [My variable]
     */
    public function __construct($var)
    {
        return $var;
    }
}

```
**Command applied:**
`php-cs-fixer fix /path/my-file.php --rules=-@PSR2,@Symfony`

**Result:**
```php
<?php
/**
 * My header text.
 *
 * @author Me
 */
$x = 1;

class MyClass
{
    /**
     * My method.
     *
     * @param string $var [My variable]
     */
    public function __construct($var)
    {
        return $var;
    }
}
```
So, how I can keep my original header message with the blank line (or add custom blank lines) between this and the next code?, resulting something like this...
```php
<?php
/**
 * My header text.
 *
 * @author Me
 */

$x = 1;

class MyClass
{
    /**
     * My method.
     *
     * @param string $var [My variable]
     */
    public function __construct($var)
    {
        return $var;
    }
}
```

**Comment by Rolige** [comment]
@SpacePossum That’s exactly the point, of course I could achieve it by using my custom message in the `header_comment`, but I'm creating my custom config file for a general use, not for a single project, as most developers do (I think).

**Comment by SpacePossum** [comment]
ah right, so you want a rule to fix the spacing around a header only and not the header itself?

**Comment by Rolige** [comment]
Exactly!

**Comment by Wirone** [comment]
Closing, as it seems to work correctly in `3.16`:

<img width="1055" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/47209f67-7053-4ff4-b8c9-093ba34e7b41">
