### ISSUE TITLE
[PHPUnit] Add migration for 7.5 assertEqualsWithDelta

### ISSUE THREAD

**Issue by Slamdunk** [PHP-CS-Fixer/PHP-CS-Fixer#4145]
References: https://github.com/sebastianbergmann/phpunit/blob/7.5.0/ChangeLog-7.5.md

> Implemented https://github.com/sebastianbergmann/phpunit/issues/3340: Added assertEqualsCanonicalizing(), assertEqualsIgnoringCase(), assertEqualsWithDelta(), assertNotEqualsCanonicalizing(), assertNotEqualsIgnoringCase(), and assertNotEqualsWithDelta() as alternatives to using assertEquals() and assertNotEquals() with the $delta, $canonicalize, or $ignoreCase parameters
> 
> The optional parameters $delta, $maxDepth, $canonicalize, and $ignoreCase of assertEquals() and assertNotEquals() are now deprecated. There is no behavioral change in this version of PHPUnit. Using these parameters will trigger a deprecation warning in PHPUnit 8 and in PHPUnit 9 these parameters will be removed.

**Comment by TomasVotruba** [comment]
AST implementation in Rector for inspiration: https://github.com/rectorphp/rector/pull/825/commits/334c9893da4473ea38c742d5b2f9fb99cd6d5e19#diff-de1172102c1d09f6d2910b0571e5f546

Test cases included. I hope I got them right :smile:
