### ISSUE TITLE
Automate changes from `with($this->equalTo('something'))` to `with('something')`

### ISSUE THREAD

**Issue by gmponos** [PHP-CS-Fixer/PHP-CS-Fixer#4164]
It would be nice if PHP-CS-fixer could automate and apply a change like this:

From 

 `$mockObject->with($this->equalTo('something'))` 

to 

`$mockObject->with('something')`

This should only happen if the class extends a `TestCase` of PHPUnit and only if the `equalTo` does not use any extra parameter and it is inside a `with` function

Related to https://github.com/symfony/symfony/pull/29685

**Comment by gmponos** [comment]
FYI I would really like to know if these kind of changes can be automated with php-cs-fixer and then maybe I could try and create a PR.. although there is a learning curve for me since I never used php-cs-fixer..

**Comment by keradus** [comment]
in general - yes, they can. we already do some changes like that for phpunit

**Comment by Wirone** [comment]
I am going to close this issue. It's been almost 5 years without implementation, there's [Rector rule for that](https://github.com/rectorphp/rector-phpunit/blob/e6dd6a009924699ecb60caf0837f423cc13f8511/docs/rector_rules_overview.md#usespecificwithmethodrector), there wasn't any interest in this, and most probably no one from core team will work on it.

Linked PR was closed without merging and even if Symfony would like to see this in Fixer, [they can live without it too](https://github.com/symfony/symfony/pull/29685#issuecomment-451152375) ("little practical benefits").
