### ISSUE TITLE
header_comment isn't applied if file has open/close PHP tags

### ISSUE THREAD

**Issue by cdukes** [PHP-CS-Fixer/PHP-CS-Fixer#4255]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
7.2.13

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
2.14.0

#### The command you use to run PHP CS Fixer:
php-cs-fixer fix --config=config/php_cs.php .

#### The configuration file you are using, if any:
```php
$finder = PhpCsFixer\Finder::create()
	->in(__DIR__);

return PhpCsFixer\Config::create()
	->setRules(
		array(
			'header_comment' => array(
				'header' => 'COMMENT',
			),
		)
	)
	->setFinder($finder);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

function test() {

	?>
	<p>HTML Text</p>
	<?php

}
```

 * with unexpected changes applied when running PHP CS Fixer:
(No header comment changes occur in any file with a ?>...<?php block, although other rules are applied to those files)

 * with the changes you expected instead:
```php
<?php

/*
 * COMMENT
 */

function test() {

	?>
	<p>HTML Text</p>
	<?php

}
```

**Comment by kubawerlos** [comment]
This is intended behaviour, the fixer only [works](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.14.0/src/Fixer/Comment/HeaderCommentFixer.php#L110) with monolithic PHP files.

**Comment by cdukes** [comment]
Thanks for the quick reply. Yes, let's make this a feature request for a config toggle

**Comment by keradus** [comment]
:-1: from my side. this gonna be mess, both if you look at outcome of the "fixing", and the maintenance - header vs declare-strict is already problematic, let's not make it worse by supporting non-monolithic files now

**Comment by cdukes** [comment]
For what it's worth, I just cloned the repo, removed the indicated line, and ran this on ~100 non-monolithic files. Every single one updated without issues, but it would still be nice to have this as an option for future uses. =)
