### ISSUE TITLE
Support for `FullyQualifiedStrictTypesFixer` in classes' `extends` part

### ISSUE THREAD

**Issue by drupol** [PHP-CS-Fixer/PHP-CS-Fixer#4309]
When using the directive `fully_qualified_strict_types`, the `class extends` should be shortened when it's possible.

#### The PHP version you are using (`$ php -v`):
=> 7.2.15

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.14.1

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace Foo\Bar;

class SomeClass extends \Foo\Bar\Izumi
{
}
```

 * with the changes you expected instead:
```php
<?php

namespace Foo\Bar;

class SomeClass extends Izumi
{
}
```

**Comment by Wirone** [comment]
@drupol please don't close this issue because it's still relevant - we don't have support for FQCNs in `extends`. If you don't want notifications, just unsubscribe from the issue (or change to "status only") 🙂.

**Comment by drupol** [comment]
Fair enough! Reopening the issue.
