### ISSUE TITLE
Implements a ClassAnalyzer

### ISSUE THREAD

**Issue by drupol** [PHP-CS-Fixer/PHP-CS-Fixer#4361]
This issue is from this comment from @keradus : https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4310#discussion_r271581322

Just like the FunctionsAnalyzer, CommentsAnalyzer and NamespacesAnalyzer, the class ClassAnalyzer will work with classes.

This has been created during the `#EUFOSSA Hackathon`.

**Comment by Wirone** [comment]
Closing as #4362 was closed by @drupol. Sorry to see your work being not merged.
