### ISSUE TITLE
[Feature Request]: check for fclose / closedir / pclose ...

### ISSUE THREAD

**Issue by voku** [PHP-CS-Fixer/PHP-CS-Fixer#4454]
If a developer isn't using a php "close" functions in the code, then the code run anyway ... but if the same function is used for many files, then there will be a fatal errro "Too many open files". So I think best practice is not to use this functions, but if you need to use it then then "open" function and the "close" function should be in the same function call.

So maybe we can write a check for this behavior? Or maybe there is already some kind of check?

before:

```php
functinon foo($dir))
{
    $handle = opendir($dir);
    
    // do stuff

	return $result;
}
```

after:

```php
functinon foo()
{
    $handle = opendir($dir);
    
    // do stuff

	closedir($handle);

	return $result;
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for proposing this idea,

Although I like it, I do feel it is on the border of code style fixing and SCA based fixing ;)
Lets see what others think as well.

**Comment by drupol** [comment]
I like it as well, but I have the feeling that it's out of the PHP CS Fixer scope.

I guess it should be done in static analysis tools.

**Comment by keradus** [comment]
Slightly agree. I see possibility to have the Fixer implemented, but also not much ppl eager to implement it since 2019 😅  Maybe too edge case to leave it only for SCA detection indeed. If anyone is interested to implement it, feel free to raise a PR!
