### ISSUE TITLE
List params closure not add space

### ISSUE THREAD

**Issue by PhanAnh1001** [PHP-CS-Fixer/PHP-CS-Fixer#4475]
#### The PHP version you are using (`$ php -v`):
7.2.19

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
2.15.1

#### The command you use to run PHP CS Fixer:
/usr/local/bin/php-cs-fixer fix /home/anhtp/app/3ple-point-api/app/Services/Eloquent --rules=@PhpCsFixer

#### The configuration file you are using, if any:
```php
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
DB::transaction(function () use ($point_attribute,$user) {
   ...
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
DB::transaction(function () use ($point_attribute,$user) {
   ...
}
```

 * with the changes you expected instead:
```php
DB::transaction(function () use ($point_attribute, $user) {
   ...
}
```

**Comment by SpacePossum** [comment]
Hi @PhanAnh1001 ,

Thanks fro reporting, this is indeed currently missing, would be nice to have!

**Comment by Wirone** [comment]
Closing, as this works properly with `method_argument_space` fixer (tested on `3.16-DEV` = current master).

<img width="900" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/a2282f16-def3-440e-a5b1-01df98057cc7">
