### ISSUE TITLE
Space after opening comment marker fixer

### ISSUE THREAD

**Issue by Bilge** [PHP-CS-Fixer/PHP-CS-Fixer#4480]
Is there a fixer for ensuring a space appears after the opening comment marker, as in the following example?

```diff
-//foo
+// foo
```

**Comment by SpacePossum** [comment]
Hi,
Currently we don't but I would to have it as well (same for `#foo` version and `/*foo*/`)

**Comment by weshooper** [comment]
@kubawerlos would https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v1.15.0#commentsurroundedbyspacesfixer handle this situation also do you think?

**Comment by kubawerlos** [comment]
[Yes](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/v1.15.0/tests/Fixer/CommentSurroundedBySpacesFixerTest.php#L67).

**Comment by Wirone** [comment]
There is [`single_line_comment_spacing`](https://cs.symfony.com/doc/rules/comment/single_line_comment_spacing.html), with improvements needed (#7228).
