### ISSUE TITLE
phpdoc_no_* fixers should be replaced by configurable fixer

### ISSUE THREAD

**Issue by Bilge** [PHP-CS-Fixer/PHP-CS-Fixer#4503]
The fixers, *phpdoc_no_package* and *phpdoc_no_access* could be deprecated in favour of a fixer that removes phpDoc tags according to a configurable list. In this way it would be easy to enforce omission of arbitrary annotations, such as `@author` and `@copyright` instead of relying on predefined fixers to suffice.

**Comment by SpacePossum** [comment]
yes please :)

**Comment by Pazns** [comment]
afaik, this is the purpose of `general_phpdoc_annotation_remove` rule.

**Comment by SpacePossum** [comment]
Yeah both fixers are proxied to the generic, I'm in favor of deprecating the rules and remove these on 3.0

**Comment by Wirone** [comment]
I am going to close this one because it's possible to remove any phpDoc annotations using `general_phpdoc_annotation_remove` (thanks @Pazns for pointing it out), and deprecating proxy fixers is a separate story (to be decided internally).
