### ISSUE TITLE
Array keys alphabetically sorting/ordering

### ISSUE THREAD

**Issue by flaksp** [PHP-CS-Fixer/PHP-CS-Fixer#4552]
I want to suggest to add rule that will allow enforcing sorting array keys alphabetically.

## If keys are simple strings or ints

Before:

```php
$arr = [
    'c' => 'foo',
    'a' => 'foo',
    'b' => 'foo',
];
```

After:

```php
$arr = [
    'a' => 'foo',
    'b' => 'foo',
    'c' => 'foo',
];
```

## If keys are NOT simple strings or ints

If there are any keys that contain PHP expression, user may choose how to sort them: move expressions to the start of array or to the end. Order of keys with expressions should not be changed cuz we (probably?) can't be sure how to sort them against each other.

Example. Before:

```php

$arr = [
    foo() . ' baz' => 'foo',
    'a' => 'foo',
    bar() => 'foo',
];
```

After (if keys with expressions should be moved to the top):

```php

$arr = [
    foo() . ' baz' => 'foo',
    bar() => 'foo',
    'a' => 'foo',
];
```

After (if keys with expressions should be moved to the end):

```php

$arr = [
    'a' => 'foo',
    foo() . ' baz' => 'foo',
    bar() => 'foo',
];
```

## It's risky rule

This rule should be marked as risky because it may change method call orders if they present in array value expressions (of course this scenario may exist only in bad architecture, but we should not close eyes on this fact). Example of that case:

```php
$arr = [
    'c' => thisFunctionDesignedToBeCalledFirst(),
    'a' => thisFunctionDesignedToBeCalledSecond(),
    'b' => 'foo ' . thisFunctionDesignedToBeCalledThird(),
];
```

**Comment by localheinz** [comment]
Love it!

**Comment by localheinz** [comment]
@neluzhin 

I think, though, that this will be a lot easier with [`rector/rector`](https://github.com/rectorphp/rector).
