### ISSUE TITLE
The `blank_line_before_statement` rule does not work with single-line comments

### ISSUE THREAD

**Issue by andrzejkupczyk** [PHP-CS-Fixer/PHP-CS-Fixer#4578]
Dunno if this is an expected behaviour (?) :man_shrugging: 

#### The PHP version you are using (`$ php -v`):
\>=7.1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
2.15.1 Europe Round

#### The command you use to run PHP CS Fixer:
`fix --rules='{"blank_line_before_statement":{"statements":["return","foreach"]}}'`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
function foo()
{
    $foo = ['bar', 'baz'];
    // a single-line comment
    foreach ($foo as $whatever) {}
    // other comment
    return $foo;
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
function foo()
{
    $foo = ['bar', 'baz'];
    // a single-line comment
    foreach ($foo as $whatever) {}
    // other comment
    return $foo;
}
```

 * with the changes you expected instead:
```php
function foo()
{
    $foo = ['bar', 'baz'];

    // a single-line comment
    foreach ($foo as $whatever) {}

    // other comment
    return $foo;
}
```

**Comment by SpacePossum** [comment]
Hi and thanks for reporting!

The reported behavior is expected. Currently you cannot configure that rule to make sure there is a empty line above a comment (nor comment block or PHPDoc). 

Would be a nice addition : )
(we just have to be careful it doesn't conflict with what other rules already do)

**Comment by andrzejkupczyk** [comment]
I thought so, thank you for a quick response :+1:

**Comment by Wirone** [comment]
FYI: reproduced on v3.16.1, so it's still to pick up to work on.

**Comment by Wirone** [comment]
It works as expected on `3.23.1-DEV (dc9d9584)`.

<img width="1124" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/921f2ecb-a680-4fc5-adea-15a2cfdd9693">
