### ISSUE TITLE
"binary_operator_spaces" and "whitespace_after_comma_in_array" rules are extremely slow

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#4656]
#### The PHP version you are using (`$ php -v`):
=> 7.3

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16.0

All rules of the CS fixer completes within 10 - 20 seconds (tested all `@PSR1`, `@PSR2` and `@Symfony` one by one), except:
```
    'whitespace_after_comma_in_array' => true,
    'binary_operator_spaces' => true,
```
the `whitespace_after_comma_in_array` rule completed in ~17 minutes, the `binary_operator_spaces` takes currently forever (more than 4 hours, actually never completed).
on very large arrays formatted like this:
```
array(1=>2, 3=>4,...)
```
notice the missing spaces. If the file is preprocessed by regular expression, i.e. "=>" converted to " => " (with one space on each side), then the rules completes also very fast.

Test file:
```
https://github.com/tecnickcom/TCPDF/blob/6.3.2/fonts/cid0ct.php
```

**Comment by mvorisek** [comment]
Is here any core developer of the CS Fixer that knows the fixer internals and how to fix this effectively? Large arrays with bad syntax are very common if some maps like this are generated by code.

**Comment by SpacePossum** [comment]
Hi and thanks for reporting!

I know a bit or two about the `binary_operator_spaces` fixer and it has some serious issues, however refactoring it will be hard as well.

However, one of the biggest issues is not just with that fixer but the Tokens collection. Inserting into a large Tokens collection triggers a lot of array coping with all the memory and speed issues that comes with that.

That is why the speed of the fixer is OK as long as it doesn't touches the tokens.

There are details here https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3996 as well and a proposed fix that might be of interest for you https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4250

**Comment by mvorisek** [comment]
Hi @SpacePossum , thank you for your message!

I meant if there can be done an easy fix especially for large arrays, i.e. traverse 1 array level at once, fix the elements and then replace it with the results. Does it makes some sense?

**Comment by SpacePossum** [comment]
It is worth checking if there is such a fix doable!

However there are some things to keep in mind like usage of multi line comments and spacing, heredoc, nowdoc, anonymous classes, lamdas, etc. within the array. All the fun stuff :)

**Comment by mvorisek** [comment]
Here are stats after running only the `whitespace_after_comma_in_array` rule on https://github.com/tecnickcom/TCPDF/tree/6.3.5 fonts folder (php files with size 100 - 1500 KB):
```
Fixed all files in 48181.029 seconds, 522.000 MB memory used
```

**Comment by mvorisek** [comment]
> However, one of the biggest issues is not just with that fixer but the Tokens collection. Inserting into a large Tokens collection triggers a lot of array coping with all the memory and speed issues that comes with that.

can we use tree or array linked structure? If not, is there anything againt creating 1, 2 empty tokens after each real one, so we can use the empty one for quick insertion?

**Comment by mvorisek** [comment]
duplicate of #5279 and probably improved by #4250
