### ISSUE TITLE
Add a fixer that set fully-qualified class names in phpdoc?

### ISSUE THREAD

**Issue by mlocati** [PHP-CS-Fixer/PHP-CS-Fixer#4696]
What about adding a fixer that replaces all the class names in phpdocs (`@param`, `@throws`, `@return`, `@see`, others?) with their fully-qualified name?

For example, consider this code:

```php
<?php
namespace Namespace1;
use Namespace2\ClassName;
use Namespace3\ClassName as ClassNameAlias;
/**
 * @return ClassNameAlias
 */
function foo() {
}
```

Humans reading it needs to look at the `use` statements to see what actually `ClassNameAlias` is.

Consider this other example:

```php
<?php
namespace Namespace1;
use Namespace2\ClassName;
/**
 * @return ClassName
 */
function foo() {
}
```

The `use` statement is used only for the phpdoc, and IMHO it pretty useless (just my opinion of course).

So, what about adding a fixer that replaces all the class references with their fully-qualified names?

The two examples above would be "fixed" to:

```php
<?php
namespace Namespace1;
use Namespace2\ClassName;
use Namespace3\ClassName as ClassNameAlias;
/**
 * @return \Namespace3\ClassName
 */
function foo() {
}
```

```php
<?php
namespace Namespace1;
use Namespace2\ClassName;
/**
 * @return \Namespace2\ClassName
 */
function foo() {
}
```

**Comment by kubawerlos** [comment]
> Humans reading it needs to look at the `use` statements

How is it different from reading a class in code? That argument applies there as well.

**Comment by mlocati** [comment]
Yep, but to only know the input and the output of a method, you don't have to read all the code, just its phpdoc

**Comment by julienfalque** [comment]
You also have to read the parameters and return type declarations where @kubawerlos' comment still applies.

**Comment by svenluijten** [comment]
I also needed/wanted this, and found [this third-party fixer](https://github.com/adamwojs/php-cs-fixer-phpdoc-force-fqcn) that does exactly what you ask. Doesn't need to be in core IMO.

**Comment by mlocati** [comment]
> You also have to read the parameters and return type declarations where @kubawerlos' comment still applies.

Well, I always add all `@param` and `@return` phpdocs, I don't have to read the function declaration

**Comment by Wirone** [comment]
I am going to close this, because I believe it does not fit general trend in PHP, which is getting more and more strictly-typed in recent years. I would rather [remove superfluous phpDocs](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#phpdocnosuperfluousparamfixer) than to add all the annotations with FQCN every time. Additionally, as @svenluijten pointed out, there's userland fixer for that so there's no point in including it to the core.
