### ISSUE TITLE
Show currently running rule & file path in debug mode (`-vvv`)

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#4727]
This is a feature request to show currently running ruleset and elapsed time after the ruleset finished. It should be enabled only when verbose output is enabled.

Usecase: to quickly identify issues like #4656

**Comment by mvorisek** [comment]
Should be easy to emit a verbose log at https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.7/src/Runner/Runner.php#L190

PS: I do not know the internal guidelines for logging, thus I will not submit a PR, but it is easy to print the filename/rule/time here. Official support still highly welcomed.

**Comment by Wirone** [comment]
@mvorisek what do you mean by "currently running ruleset"? Progress output is based on files, do you want to display currently applied rules for each file? It will be probably easier after #6848 gets merged.
