### ISSUE TITLE
about exit('...') / die('...') and echo '...'; exit;

### ISSUE THREAD

**Issue by bluedasher13** [PHP-CS-Fixer/PHP-CS-Fixer#4806]
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> `7.3.8`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> `3.0.0-DEV`

#### The command you use to run PHP CS Fixer:
=> `php-cs-fixer fix`

#### The configuration file you are using, if any:
```php
<?php
return PhpCsFixer\Config::create()
    ->setRules([
        'no_alias_language_construct_call' => true
    ]);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

die('message1');

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

exit('message1');

```

 * with the changes you expected instead:
```php
<?php

echo 'message1';
exit;

```

Thanks for the contribution. Last time, I submitted a issue (#4717), I found there's a new option called `no_alias_language_construct_call` now.

But maybe the description of the previous issue is not detailed enough. In fact, I hope it could replace `exit('message');` with `echo 'message'; exit;`, not just replace `die()` with `exit()`.

Because `exit()` and `die()` are not real functions, I think it would be clearly in the form of `echo '...'; exit;`.

**Comment by SpacePossum** [comment]
I think we could add this to `no_unneeded_control_parentheses`, that one removes other not needed `()` as well.

**Comment by Wirone** [comment]
I am going to close this one because:

- 0 interest for 3 years+ since this issue was created (self-like does not count 😉)
- I don't see any value in proposed change: instead of 1 statement there would be 2, so initial intent is split for no reason
