### ISSUE TITLE
[Improvement] Display linting error if occurs

### ISSUE THREAD

**Issue by Yivan** [PHP-CS-Fixer/PHP-CS-Fixer#4819]
Hello,

When a linting error occurs after fix, maybe verbose mode could send back the linting error to help developer to fix it.

Actually we just know there was an error (even with --dry-run --verbose --diff), and are left as it.
Printing the error linting send by php at the output will greatly help I think.

Use case: i got into this with a file having this code and take me a long time to understand from where it was coming (stripping bloc of code by block of code and running manually the fixer):
```
<?=$this->areablock(
        'test',
        [
            'allowed' => [
                'test-header',
                'demo-guided-search',
            ],
            'globalParams' => [
                'forceEditInView' => true
            ]
        ]
);?>
```
The lint fail if with `@PhpCsFixer` + `'no_alternative_syntax' => false`.

This is a suggestion, but I think it could really help!

Best regards.

**Comment by Wirone** [comment]
FYI: reproducer example does not work - it's properly analysed:

<img width="1124" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/debe7cc3-4ff4-4d1b-93c8-aa9943c1bdd5">

However, it's easy to reproduce the intention of this feature request, you just need to make any syntax error in the analysed file, and you can display error information with `-vvv` flag (`--verbose` is not enough):

<img width="1049" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/222e06cb-776c-4fe1-9025-e29ba117dfeb">

It is not user-friendly that there are 2 different flags for verbosity, but at least it's documented in the `php-cs-fixer fix --help`:

> The --verbose option will show the applied rules. When using the `txt` format it will also display progress notifications.
> 
>  NOTE: if there is an error like "errors reported during linting after fixing", you can use this to be even more verbose for debugging purpose
>  
>  * `-v`: verbose
>  * `-vv`: very verbose
>  * `-vvv`: debug
