### ISSUE TITLE
idea: phpdoc_to_property_type

### ISSUE THREAD

**Issue by AJenbo** [PHP-CS-Fixer/PHP-CS-Fixer#4876]
It would be nice if there was a rule for turning @var annotations in to property types as supported in php7.4.

https://wiki.php.net/rfc/typed_properties_v2

Just like phpdoc_to_param_type and phpdoc_to_return_type allows the user to turn @param and @return in to actual type hinting

--
Thanks for a grate tool

**Comment by julienfalque** [comment]
Already proposed in #4592.

**Comment by Wirone** [comment]
[Introduced](https://cs.symfony.com/doc/rules/function_notation/phpdoc_to_param_type.html) in #4592.
