### ISSUE TITLE
Unable to multiline_whitespace_before_semicolons with both strategies

### ISSUE THREAD

**Issue by ossinkine** [PHP-CS-Fixer/PHP-CS-Fixer#4896]
`multiline_whitespace_before_semicolons` is a great fixer, but it's unclear how to use it with both strategies.
I want to forbid multi-line whitespace before the closing semicolon except chained calls.
I get this result if I run a fixer with the `no_multi_line` strategy, and then run it again with the `new_line_for_chained_calls` strategy, but this cannot be done in one pass.

Are there any technical limitations to do this, or have I just not figured out how to do this?

#### The PHP version you are using (`$ php -v`):
```
PHP 7.4.3 (cli) (built: Feb 20 2020 21:53:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
    with Xdebug v2.9.2, Copyright (c) 2002-2020, by Derick Rethans
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
```
PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:
```
vendor/bin/php-cs-fixer fix -vv --using-cache=no
```

#### The configuration file you are using, if any:
```php
$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude('var')
;

return PhpCsFixer\Config::create()
    ->setRules([
        'multiline_whitespace_before_semicolons' => ['strategy' => 'new_line_for_chained_calls'],
    ])
    ->setFinder($finder)
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
$this
    ->foo()
    ->bar();
$this->baz()
;
```

 * with unexpected changes applied when running PHP CS Fixer:
with `new_line_for_chained_calls` strategy:
```php
$this
    ->foo()
    ->bar()
;
$this->baz()
;
```
with `no_multi_line` strategy:
```php
$this
    ->foo()
    ->bar();
$this->baz();
```

 * with the changes you expected instead:
```php
$this
    ->foo()
    ->bar()
;
$this->baz();
```

**Comment by SpacePossum** [comment]
Hi and thanks for reporting!

Based on the description of the rule I consider the following not being fixed by the rule using `new_line_for_chained_calls` a bug

```php
$this->baz()
;
```

Since this is not a chained call I expect it to be fixed to a single line. In other words, I would expect `new_line_for_chained_calls` to act the same as `no_multi_line` _except_ for chained calls.
Would like to hear opinions from others on it though.
