### ISSUE TITLE
no_blank_lines_before_namespace behaviour with declare() statements above

### ISSUE THREAD

**Issue by DocFX** [PHP-CS-Fixer/PHP-CS-Fixer#4897]
Not sure about this one. Not sure either about which one to trust or not.
`no_blank_lines_before_namespace` is supposed to remove blank lines to stick namespace declaration to the opening tag basically. BUT there's one more statement that can exist before: the declare statement (strict_types, notably).

What are we expecting when this happens? I would expect the rule to stick declare up, then leave a blank line around namespace declaration OR stick the namespace up. Maybe there should be an option like `leave_line_before_if_not_first_line` or such. Am I wrong?

#### The PHP version you are using (`$ php -v`):
=> PHP 7.3.10 (cli) (built: Sep 24 2019 11:58:16) ( NTS MSVC15 (Visual C++ 2017) x64 )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer-v2.phar fix --show-progress dots --verbose --config=./devops-sources/.php_cs.dist

#### The configuration file you are using, if any:
=> any, at least containing `no_blank_lines_before_namespace`  and `declare_strict_types`  true rules

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

declare(strict_types = 1);

namespace App\Entity;
```

```php
<?php

namespace App\Entity;
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

declare(strict_types = 1);
namespace App\Entity;
```

```php
<?php
namespace App\Entity;
```

 * with the changes you expected instead:
```php
<?php

declare(strict_types = 1);

namespace App\Entity;
```

```php
<?php
namespace App\Entity;
```

**Comment by kubawerlos** [comment]
> `no_blank_lines_before_namespace` is supposed to remove blank lines to stick namespace declaration to the opening tag basically

Really? The description only claims:
> There should be no blank lines before a namespace declaration.

> BUT there's one more statement that can exist before: the declare statement

That's not the only one, another namespace can too.

**Comment by SpacePossum** [comment]
Not sure if I see an issue here. If you want;

```php
<?php

declare(strict_types = 1);

namespace App\Entity;
```

I think you should use the `SingleBlankLineBeforeNamespaceFixer` with the `DeclareStrictTypesFixer`. If you want the no line before it like;

```php
<?php
namespace App\Entity;
```

you can use `NoBlankLinesBeforeNamespace`.

However you cannot configure two different styles, one for when there is a declare strict and one for when there is not. To me it makes sense, you can have only style.

**Comment by Wirone** [comment]
Closing, as this is [expected behavior](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/4897#issuecomment-630685667).

As a side note: I think we could deprecate [`no_blank_lines_before_namespace`](https://cs.symfony.com/doc/rules/namespace_notation/no_blank_lines_before_namespace.html) and [`single_blank_line_before_namespace`](https://cs.symfony.com/doc/rules/namespace_notation/single_blank_line_before_namespace.html), and introduce `blank_line_before_namespace` with configurable strategies. This way discoverability would be better.
