### ISSUE TITLE
nonstandard/phpunit annotation spaces are not normalized/fixed

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#4993]
nonstandard/phpunit annotation is not fully fixed:
```
class ValidationTests extends TestCase
{
    /**
     * @expectedException        \TypeError
     */
    public function testValidate5()
    {
        // ...
    }
}
```

I think it should be normalized to:
```
class ValidationTests extends TestCase
{
    /**
     * @expectedException \TypeError
     */
    public function testValidate5()
    {
        // ...
    }
}
```

ie. no multple spaces after `@expectedException`

config file: https://github.com/atk4/data/blob/90ab68ac063b8fc2c72dcd66115f1bd3f70a3a92/.php_cs.dist

**Comment by Wirone** [comment]
It's possible to align non-standard annotations, but you must configure `tags` option:

<img width="987" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/43af285f-2cf2-4ce0-be90-002feb6662c8">
