### ISSUE TITLE
Indentation does not detect right indentation level

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#5001]
The following code:
```
$json = preg_replace_callback('~long'
    . 'regex~s', function ($matches) {
    return $matches[0];
}, $json);
```
is fixed to:
```
$json = preg_replace_callback('~long'
    . 'regex~s', function ($matches) {
        return $matches[0];
    }, $json);
```
but no action should be takes (and actually the badly fixed should be fixed back to original)

config file: https://github.com/atk4/data/blob/90ab68ac063b8fc2c72dcd66115f1bd3f70a3a92/.php_cs.dist

please verify and fix

**Comment by mvorisek** [comment]
@SpacePossum wdyt?

**Comment by Wirone** [comment]
I believe it should be rather like:

```php
$json = preg_replace_callback(
    '~long' . 'regex~s',
    function ($matches) {
        return $matches[0];
    },
    $json
);
```

or 

```php
$regex = '~long' . 'regex~s';
$json = preg_replace_callback($regex, fn ($matches) => $matches[0], $json);
```

But considering your current formatting, from `function` perspective indentation is correct after the fix (1 level of indentation in the function's body).

There's nothing to fix here from the tool perspective.
