### ISSUE TITLE
Support typed properties in `fully_qualified_strict_types`

### ISSUE THREAD

**Issue by Slamdunk** [PHP-CS-Fixer/PHP-CS-Fixer#5004]
Currently `fully_qualified_strict_types` can handle multiple scenarios, but does not cover class' properties. We need this fixer to make changes like this:

```diff
 use Foo\Bar;
 
 class SomeClass
 {
-    private \Foo\Bar $baz;
+    private Bar $baz;
 }
```

**Comment by julienfalque** [comment]
Note: I added the "feature request" label but IMO this should be considered an enhancement and target lowest maintained branch.
