### ISSUE TITLE
[RFC] Move Mac and Windows builds to GitHub actions

### ISSUE THREAD

**Issue by GrahamCampbell** [PHP-CS-Fixer/PHP-CS-Fixer#5091]
There seems to be silently of trouble with mac and windows builds at the moment. I'd suggest we move those builds to GitHub actions. We could possible move some of the linux builds too, but that's not urgent.

**Comment by Wirone** [comment]
I'm going to close this because currently all the jobs are run in Github Actions. This issue was created around [v2.15.8](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v2.15.8), where Travis, CircleCI and Appveyor were used, which is not the case anymore.
