### ISSUE TITLE
Is there no rule which fixes wrong namespaces?

### ISSUE THREAD

**Issue by c33s** [PHP-CS-Fixer/PHP-CS-Fixer#5125]
## Support question

`composer.json` autoload section:
```
...
    "autoload": {
        "psr-4": {
            "C33s\\Doctrine\\": "src/Doctrine"
        }
    },
...
```

class `src/Doctrine/Types/AbstractValueObjectJsonType.php` :
```php
namespace App\Doctrine\Types;

use C33s\Doctrine\Types\Interfaces\ArrayInterface;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\ConversionException;
use Doctrine\DBAL\Types\JsonType;
use Exception;

abstract class AbstractValueObjectJsonType extends JsonType
...
```

the namespace is wrong, according to `composer.json` and the path it should be `C33s\Doctrine\Types` but the rule `@Symfony` and `psr4` doesn't fix it. is there no rule which can fix wrong namespaces?

also tried phpstan and php-codesniffer. for codesniffer if found https://github.com/suin/phpcs-psr4-sniff but it's not compativle with php7.4

**Comment by SpacePossum** [comment]
ping @kubawerlos as I've not enough insight on the PSR4 fixer to say anything of value about this.

**Comment by kubawerlos** [comment]
The `psr0` fixer has a `dir` option, you can set it to `src/Doctrine`.

To find the wrong namespaces I find PHPStan doing great job, ii is reading from autoload from `composer.json` and throwing an error when a class cannot be found.
