### ISSUE TITLE
Spaces after opening and before closing echo tags

### ISSUE THREAD

**Issue by VBelozyorov** [PHP-CS-Fixer/PHP-CS-Fixer#5283]
## Rule request

I'm interested in rule which would set exactly one whitespace after opening and before closing echo tags.

I've tried to search `space` [there](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/doc/rules/index.rst) maybe just overlooked it.

### Code snippet that shows how the rule would fix PHP code

  ```
-  <span><?=$someValue?></span>
+  <span><?= $someValue ?></span>
  ```

**Comment by SpacePossum** [comment]
Hi,

For the after part, it will be in 2.17: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/language_construct/single_space_after_construct.rst

**Comment by VBelozyorov** [comment]
Looks like #5272 is what I want and even more

**Comment by VBelozyorov** [comment]
Oops, #5272 is not merged yet, I will gladly close this again when that happens :)

**Comment by Wirone** [comment]
I am going to close this, you can find reasoning [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/5272#issuecomment-1094138247).
