### ISSUE TITLE
PhpdocAlignFixer breaks with psalm-param or phpstan-param

### ISSUE THREAD

**Issue by Seldaek** [PHP-CS-Fixer/PHP-CS-Fixer#5290]
For example, when running against:

```
    /**
     * @param         string       $source        source package name
     * @param         string       $sourceVersion source package version (pretty version ideally)
     * @param         string       $description   link description (e.g. requires, replaces, ..)
     * @phpstan-param Link::TYPE_* $description
     * @param         array        $links         array of package name => constraint mappings
     * @return Link[]
     */
    public function parseLinks($source, $sourceVersion, $description, $links)
    {
    }
```

The output is:

```
    /**
     * @param string $source        source package name
     * @param string $sourceVersion source package version (pretty version ideally)
     * @param string $description   link description (e.g. requires, replaces, ..)
     * @phpstan-param Link::TYPE_* $description
     * @param  array  $links array of package name => constraint mappings
     * @return Link[]
     */
    public function parseLinks($source, $sourceVersion, $description, $links)
```

So we see that things are aligned above and below the phpstan-param, but it kinda broke alignment. This makes sense as per the [configuration of phpdoc_align](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/doc/rules/phpdoc/phpdoc_align.rst#tags) which only lists other tags, but I do wonder why the list of tags is restricted. Why can't I add any tag name in there and have it align? Or alternatively, could php-cs-fixer support these phpstan/psalm-param tags and others out of the box?

**Comment by VincentLanglet** [comment]
Hi @Seldaek, can you try https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6564 ?

**Comment by Seldaek** [comment]
Sorry probably won't be able to for a while, but patch seems reasonable to me.
