### ISSUE TITLE
Ignore errors of classes inherited external classes/interfaces uses another style

### ISSUE THREAD

**Issue by WinterSilence** [PHP-CS-Fixer/PHP-CS-Fixer#5291]
For example: 
some native PHP classes/interfaces use `underscore_style` for methods/properties.
For fix errors in projects uses another code styles developers use something like this:
~~~php
// @codingStandardsIgnoreStart
public function stream_open($path, $mode, $options, &$opened_path)
{
// @codingStandardsIgnoreEnd
~~~
I'm think it's ugly solution.

**Vote to**:
add option/flag `ignore_inheritance_errors` to ignore errors caused by inheritance from external code:

1. parent not in finder files (`setFinder()`)
2. parent from PHP or extensions

**Comment by Wirone** [comment]
Hi @WinterSilence, thanks for the report. Unfortunately I am going to close it since Fixer works in closed, single-file scope and does not have any information about inheritance tree. It's simply impossible to achieve with current approach.
