### ISSUE TITLE
NoOptionalArgumentsWithDefaultValueFixer

### ISSUE THREAD

**Issue by MatTheCat** [PHP-CS-Fixer/PHP-CS-Fixer#5315]
## Feature request

A new ~`OptionalArgumentsFixer`~ `NoOptionalArgumentsWithDefaultValueFixer` could remove arguments when their value is the default:

```diff
- <?php chunk_split('This should be changed', 76);
+ <?php chunk_split('This should be changed');
```

A `name_arguments` option could be enabled on PHP ≥ 8:

```diff
- <?php chunk_split('This may be changed', 76, "\n");
+ <?php chunk_split('This may be changed', end: "\n");
```

I think implementing this would require reflection and work for built-in functions and methods only. Would that be okay?

**Comment by SpacePossum** [comment]
Hi great idea!

Maybe start with the build in functions? We already have code to find the names of these, than we have code to find calls to such a function, if found you can use reflection indeed to figure out if the default matches the given value (and store the reflection values for the rest of the run for performance reasons).

**Comment by MatTheCat** [comment]
> great idea!

Yay :smile: 

> We already have code to find the names of [built-in functions]

Are you referring to `NativeFunctionInvocationFixer::getAllInternalFunctionsNormalized`? I guess some refactoring would be needed if I were to use it.

> we have code to find calls to such a function

Is that `AbstractFunctionReferenceFixer::find`? Wouldn’t it be more performant to find calls from the tokens instead?

**Comment by SpacePossum** [comment]
>NativeFunctionInvocationFixer::getAllInternalFunctionsNormalized

indeed :)  we should extract that method into some provider and use that in the current NativeFunctionInvocationFixer and your new fixer, I think to a method on `PhpCsFixer\Tokenizer\Analyzer\FunctionsAnalyzer` would work

>Is that AbstractFunctionReferenceFixer::find?

I would do it it the other way around.
Something like

```php
// in your new fixer class

    protected function applyFix(\SplFileInfo $file, Tokens $tokens)
    {
        $functionsAnalyzer = new FunctionsAnalyzer();
        $normalizedFunctionNames = $functionsAnalyzer->getAllInternalFunctionsNormalized();
        $normalizedFunctionReflectionInfo = [];
        
        $argumentsAnalyzer = new ArgumentsAnalyzer();

        for ($index = $tokens->count(); $index > 0; --$index) {
            if (!$functionsAnalyzer->isGlobalFunctionCall($tokens, $index)) {
                continue;
            }

            $functionName = $tokens[$index]->getContent();
            
            // check if known global function
            $tokenContent = strtolower($functionName);

            if (!isset($normalizedFunctionNames[$tokenContent])) {
                continue;
            }

            $openParenthesis = $tokens->getNextMeaningfulToken($index);
            $closeParenthesis = $tokens->findBlockEnd(Tokens::BLOCK_TYPE_PARENTHESIS_BRACE, $openParenthesis);
            
            $arguments = $argumentsAnalyzer->getArguments($tokens, $openParenthesis, $closeParenthesis);
            
            if (\count($arguments) < 1) {
                continue; // no arguments so nothing to fix 
            }
            
            // get reflection info
            if (!isset($normalizedFunctionReflectionInfo[$functionName])) {
                $normalizedFunctionReflectionInfo[$functionName] = // TODO reflection magic
            }
            
            // TODO check arguments against reflection value and fix if needed            
    }

```

**Comment by MatTheCat** [comment]
Damn I just realized you cannot get the default value of an internal function’s parameter before PHP 8. Would this fixer still makes sense if it’s only available for PHP ≥ 8?

**Comment by SpacePossum** [comment]
For me it does, maybe even more people will start updating to PHP8 because of it : )

**Comment by Wirone** [comment]
The idea is great, but I'm afraid it's not possible to properly implement it using current Fixer's internal system - it does not have full static analysis context even within single file, not to mention metadata outside of the analysed file. It would require inferring a lot of information in order to determine such superfluous arguments (determining called method, imported class, then whole inheritance tree because method could be defined deeper in parent class etc.).

I'll leave it open as long-term idea, but I think it won't happen anytime soon 😔.
