### ISSUE TITLE
psr_autoloading: possible to exclude certain files/directories?

### ISSUE THREAD

**Issue by mfn** [PHP-CS-Fixer/PHP-CS-Fixer#5365]
## Support question

I've files which don't adhere to PSR autoloading: they're magically managed by the frameworks (think: Laravel migrations or CakePHP2 config files etc.) and when upgrade to 2.17.x (from 2.16.*) I started seeing changes in files not adhering to the PSR-4 correctly (expected, but see below).

Gitter reference: https://gitter.im/PHP-CS-Fixer/Lobby?at=5fd786b79700c07b17ed73e8 / @kubawerlos 

I made a repo with some repro steps => https://github.com/mfn/php-cs-fixer-psr-autoloading

```php
<?php

$finder = PhpCsFixer\Finder::create()->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setFinder($finder)
    ->setRiskyAllowed(true)
    ->setRules([
        'psr4' => true,
    ]);
```
```
$ ls -ld Test1/* Test2/*
-rw-r--r--  1 neo  staff  40 Dec 16 07:46 Test1/File.php
-rw-r--r--  1 neo  staff  44 Dec 16 07:46 Test2/___file.php
$ cat Test1/File.php
<?php

namespace Test1;

class File {
}
$ cat Test2/___file.php
<?php

class NamedCompletelyDifferently {
}
```

I was using `'psr4' => true` for the longest time but after upgrading to 2.17.* I saw the following effect in change, where none was before:
```
Files that were not fixed due to errors reported during linting after fixing:
   1) /Users/neo/tmp/php-cs-fixer-psr-autoloading/Test2/___file.php


        [PhpCsFixer\Linter\LintingException]
        Parse error: syntax error, unexpected '-', expecting identifier (T_STRING) on line 3.


      Applied fixers: psr4
      ---------- begin diff ----------
--- Original
+++ New
@@ -1,4 +1,4 @@
 <?php

-class NamedCompletelyDifferently {
+class -autoloading_Test2____file {
 }

      ----------- end diff -----------
```

### Note
My initial intention was not to report the totally invalid class name being generated in this example `-autoloading_Test2____file` 😅 I assume this is a side-effect of this non-composer barebones test case 🤔

The actual report is regarding the file name being (rightfully according to the rule) being changed.

I noticed it has been renamed to `psr_autoloading` recently https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.17/doc/rules/basic/psr_autoloading.rst

It now has `'dir'` option:

> Configuration
> dir
> 
> If provided, the directory where the project code is placed.
> 
> Allowed types: null, string
> 
> Default value: null

But I'm unsure to what it relates. I tried to treat it like being an explicit list of directories being allowed to apply the fixer, yet when I changed the config to
```php
    ->setRules([
        'psr_autoloading' => [
            'dir' => 'Test1/',
        ]
    ]);
```
it was still modifying the files in `Test2/` so not sure.

### Question
Is it possible to have `psr4` / `psr_autoloading` being enabled in php-cs-fixer >= 2.17.0 but exclude certain directories?

Or what could a solution be to use the whole php-cs-fixer config (assuming there are tons of more rules) and not apply to a certain tree? Multiple configs and invocations of running the fixer?

Thank you!

**Comment by SpacePossum** [comment]
Hi and thanks for reporting with such great detail!

On your question:
>Is it possible to have psr4 / psr_autoloading being enabled in php-cs-fixer >= 2.17.0 but exclude certain directories?

This is currently not possible, there have been/are some talks about having some rules + configuration for some files/dirs, but no conclusion/solution seems available in the near future.

On your other questions about the PSR autoloading rule behavior kubawerlos might have more details. More in general I would advise removing the rule from you configuration given the setup/nature of your project. Instead I would write a phpunit test that validates the naming of the classes combined with the file and directory names as you expect these to be. It will allow for exception cases, odd ducks, etc. all while you still have the autoreview behavior in your CI.

**Comment by mfn** [comment]
> More in general I would advise removing the rule from you configuration given the setup/nature of your project.

This is in fact what I had to do anyway.

Personally, I'm fine if the project wants to close this issue; maybe the idea of the `psr_autoloading` rule simply does not work with projects using possible mixed variants (CakePHP2 is EOL anyway).

Thanks!

**Comment by mfn** [comment]
FTR, also "for my own record", just had the same issue on https://github.com/rebing/graphql-laravel/runs/1841503211?check_suite_focus=true#step:7:15
