### ISSUE TITLE
Enforce proper multiline in `array_indentation`

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#5393]
## Bug report

version: 2.17.2

### Code snippet that reproduces the problem

```php
$a = [Form\Control\Dropdown::class,
    'caption' => 'Multiple selection',
];
```

must be fixed to:
```php
$a = [
    Form\Control\Dropdown::class,
    'caption' => 'Multiple selection',
];
```

**Comment by julienfalque** [comment]
This is not a bug: `array_indentation` only fixes indentation in arrays, it does not add/remove newline characters, as this should be the responsibility of another rule that does not exist yet.

**Comment by julienfalque** [comment]
@YLivay As far as I know nobody is working on this currently.

**Comment by julienfalque** [comment]
This is also covered by #6675, let's close here.
