### ISSUE TITLE
PhpCsFixer\Fixer\Phpdoc\PhpdocVarWithoutNameFixer removes only the first variable name

### ISSUE THREAD

**Issue by patrickkusebauch** [PHP-CS-Fixer/PHP-CS-Fixer#5402]
## Bug report
PHP version: 7.4
PHP CS Fixer 2.17.3 Desert Beast by Fabien Potencier and Dariusz Ruminski

Run via `https://github.com/symplify/easy-coding-standard`

Console output:
``` bash
13) FeedbackModalControl.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -16,7 +16,7 @@
 {

     /**
-     * @var array<callable(string $feedback, FileUpload $screenshot): void>
+     * @var array<callable(string, FileUpload $screenshot): void>
      */
     public array $onSuccess = [];
    ----------- end diff -----------


Applied checkers:

 * PhpCsFixer\Fixer\Phpdoc\PhpdocVarWithoutNameFixer
```

Relevant source code:
```php
final class FeedbackModalControl extends Control
{

    /**
     * @var array<callable(string $feedback, FileUpload $screenshot): void>
     */
    public array $onSuccess = [];

}
```

Expected behavior:
Remove both variables.

**Comment by julienfalque** [comment]
Actually I don't think it should remove anything at all: the type is an array of callables and the variables are the arguments of the signature those callables must match.

**Comment by patrickkusebauch** [comment]
@juliendufresne 
The resulting (fixed) code I expected is this:
```php
final class FeedbackModalControl extends Control
{

    /**
     * @var array<callable(string, FileUpload): void>
     */
    public array $onSuccess = [];

}
```

This is absolutely fine by me. It hints at the number and type of arguments for the callable and is supported by both `phpstan` and `psalm`. It is true that having the variable name might help in aiding the developer to know what is the meaning of the parameter, however, removing only some but not all cannot be IMHO correct behavior.

**Comment by julienfalque** [comment]
Ah you're right, the variable names are not needed here. Though I think removing them should be a new rule then. The first one is likely removed because `phpdoc_var_without_name` does not understand this syntax correctly.

**Comment by patrickkusebauch** [comment]
@julienfalque Yes, I think this is the case, hence the bug report. I hope we can agree that this syntax is not too outlandish. I do not know any better of encoding the same semantics - an array of event subscribers.

**Comment by keradus** [comment]
can you raise a fix proposal, @patrickkusebauch ?

**Comment by patrickkusebauch** [comment]
@keradus I would argue for removing all variable names. I am not up to creating a PR if that is what you are asking.

**Comment by Wirone** [comment]
FYI: reproduced on v3.16.1, so it's still relevant.
