### ISSUE TITLE
[BracesFixer] constructor property promotion: allow braces on same line

### ISSUE THREAD

**Issue by gharlan** [PHP-CS-Fixer/PHP-CS-Fixer#5475]
## Feature request

I want to write constructors like this:

```php
class Foo
{
    public construct(
        private int $bar;
    ) {}
}
```

But the BracesFixer moves the closing `}` to the next line:

```php
class Foo
{
    public construct(
        private int $bar;
    ) {
    }
}
```

**Comment by adpeyre** [comment]
That would be great. The syntax forced by BracesFixer is really ugly when body constructor is empty. :)

**Comment by julienfalque** [comment]
We already have `allow_single_line_anonymous_class_with_empty_body` which is similar and maybe there are more situations where that could make sense, e.g. empty `catch` block. Shall we aim for a more generic option?

**Comment by benjy** [comment]
`allow_single_line_anonymous_class_with_empty_body` was what I first tried when facing this issue before I noticed the word anonymous.
I think making a generic version of this would make sense.

**Comment by robfrawley** [comment]
Is anyone actively working on this? I'm looking for a relatively simple PR to work on as my first contribution to this project, and this functionality seems straightforward (as well as being desirable per my own "styling preferences").

**Comment by trollfalgar** [comment]
Any news on this?

**Comment by faizanakram99** [comment]
There was an attempt to do this in #5757 but OP deleted branch, feel free to pick it up again :D

**Comment by raveren** [comment]
It's a long purple link road to get to the answer, but this was implemented and if you want to use it, add the rule `'single_line_empty_body'` to your config, example:

```php
// as close to PER as possible 
return (new PhpCsFixer\Config())->setRules([
    '@PSR12'                 => true,
    'function_declaration'   => ['closure_function_spacing' => 'none', 'closure_fn_spacing' => 'none'],
    'no_break_comment'       => false,
    'single_line_empty_body' => true, // this!
])
    ->setFinder($finder)
```
