### ISSUE TITLE
`simplified_if_return` fixer introduces double negation

### ISSUE THREAD

**Issue by weshooper** [PHP-CS-Fixer/PHP-CS-Fixer#5573]
Snippet:

```php
        if (! isset($this->element->{'variations'})) {
            return false;
        }

        return true;
```

Actual output:

```diff
-        if (! isset($this->element->{'variations'})) {
-            return false;
-        }
-
-        return true;
+        return ! (! isset($this->element->{'variations'}));
```

Expected output:

```diff
-        if (! isset($this->element->{'variations'})) {
-            return false;
-        }
-
-        return true;
+        return isset($this->element->{'variations'});
```

- Command: `php-cs-fixer fix --config=.php_cs.dist --dry-run --diff --verbose --stop-on-violation`
- Version: PHP CS Fixer 2.18.4-DEV Remote Void
- Runtime: PHP 7.4.14

**Comment by SpacePossum** [comment]
Thanks for reporting!

We could have a useless `(` remove rule and one for the "useless" `!!` in other rule at some time in the future, than using priorities this could be fixed. Would be a bunch of work so don't expect it any time soon : )

**Comment by julienfalque** [comment]
I didn't see integration tests in #6409 regarding this issue. @SpacePossum are we sure this is fixed?

**Comment by SpacePossum** [comment]
I think there are still unresolved casing indeed, maybe lets reopen

**Comment by nwehrhan** [comment]
Ran into this today

**Comment by Wirone** [comment]
FYI: reproduced on v3.16.1:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/600668/230324338-ec286ac1-65a9-44c9-b9e8-772e085d4a86.png">

**Comment by keradus** [comment]
I'm not sure if I would apply this change, due to underlying type casting to bool
```foo
-!(!$foo)
+$foo
```

we may convert it to `!!$foo`, but probably task for `no_unneeded_control_parentheses` fixer



With that, I will close the issue - core team will not focus on this optimization.
If *you* are eager to bring the PR solving this, please go ahead!

**Comment by keradus** [comment]
I mark as completed, because most significant part was accomplished here
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/5573#event-6963746974
