### ISSUE TITLE
Normalize nullable union types

### ISSUE THREAD

**Issue by derrabus** [PHP-CS-Fixer/PHP-CS-Fixer#5651]
## Feature request

With PHP 8, there are two ways to specify a nullable type declaration:

* Nullable type (PHP 7.1): `function myFunction(): ?SomeType`
* Union with `null`: `function myFunction(): SomeType | null`

Both notations are equivalent. However, I'd like to enforce a consistent code-style on my code-base and only allow one of the notations. I'd love to have a fixer where I can configure to which of the two styles all nullable types should be normalized to.

Of course, this fixer should ignore union types with three or more atomic types, like `int | float | null`. Here, the union notation is the only valid notation.

## Related issues

* #3562 proposes the same fixer for PHPDoc blocks
* #5548 introduced a fixer that adds/removes a nullable type for parameters with `null` as default value, but the union style cannot be configured here.

**Comment by julienfalque** [comment]
We could also adapt [phpdoc_types_order](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/phpdoc/phpdoc_types_order.rst) for native type declarations.
