### ISSUE TITLE
`no_spaces_after_function_name` conflict with `single_space_after_construct`

### ISSUE THREAD

**Issue by KacerCZ** [PHP-CS-Fixer/PHP-CS-Fixer#5712]
## Bug report

Using PHP CS Fixer 3.0.0 run on PHP 8.0.5 with following config:
```php
<?php

$finder = \PhpCsFixer\Finder::create()
        ->in( __DIR__ )
        ->path( '/^*.php/' );

$rules = [
        'no_spaces_after_function_name' => TRUE,
        'single_space_after_construct' => [ 'constructs' => [ 'echo' ] ],
];

$config = new \PhpCsFixer\Config();
$config->setRules( $rules )
        ->setRiskyAllowed( TRUE )
        ->setIndent( "\t" )
        ->setFinder( $finder );

return $config;
```

or using `--rules='{"no_spaces_after_function_name": true, "single_space_after_construct": {"constructs": ["echo"]}}'` CLI param.

### Code snippet that reproduces the problem

Save content to file `echo_bug.php`:
```php
<?php

echo ( $flag ? 'yes' : 'no' ) . "\n";
```

Run `vendor/bin/php-cs-fixer fix -v --dry-run --diff echo_bug.php`.

Following fix is suggested:
```
   1) echo_bug.php (no_spaces_after_function_name)
      ---------- begin diff ----------
--- /tmp/fixer-bug/echo_bug.php
+++ /tmp/fixer-bug/echo_bug.php
@@ -1,4 +1,4 @@
 <?php
 
-echo ( $flag ? 'yes' : 'no' ) . "\n";
+echo( $flag ? 'yes' : 'no' ) . "\n";
 ```

Expected result is that no change is suggested.

**Comment by Wirone** [comment]
Reproduced on `3.16`:

<img width="1370" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/6a4be209-3415-4969-82fd-473f2b232987">

**Comment by keradus** [comment]
The original snippet
```
<?php

echo ( $flag ? 'yes' : 'no' ) . "\n";
```

is no longer modified after #7430 was merged and released.
kudos @kubawerlos
