### ISSUE TITLE
PHP API

### ISSUE THREAD

**Issue by joachim-n** [PHP-CS-Fixer/PHP-CS-Fixer#5728]
## Feature request

It would be useful to have a way to run the fixer from PHP code, passing in the code to be fixed as a string.

My use case is https://github.com/drupal-code-builder/drupal-code-builder, a code generator for Drupal. I'm looking at using https://github.com/nikic/PHP-Parser to analyse existing code and add to it, but the output doesn't conform to Drupal's code formatting standards.

The documentation for PHP-Parser (https://github.com/nikic/PHP-Parser/blob/master/doc/component/Pretty_printing.markdown) suggests using PHP-CS-Fixer to get the right format, and there is a PHP-CS-Fixer configuration for Drupal (https://github.com/drupol/phpcsfixer-configs-drupal).

However, looking at PHP-CS-Fixer I can only see how to run it as a command line tool on files. I'd like to be able to access it from PHP code instead.

**Comment by kubawerlos** [comment]
The CLI `fix` command is using a runner: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/src/Console/Command/FixCommand.php#L318 - you can simply use it as well.

Or with Symfony Process component you can run command from code: https://github.com/kubawerlos/php-cs-fixer-config/blob/v2.0.0/src/Builder/build.php#L19

**Comment by shalvah** [comment]
> I'm looking at using https://github.com/nikic/PHP-Parser to analyse existing code and add to it, but the output doesn't conform to Drupal's code formatting standards.

Coincidentally, I have the same use case too (on a Laravel project though)😅. Was surprised to find there isn't a defined PHP API. Giving the runner a shot, but the code is really tightly coupled and hard to figure out.

**Comment by joachim-n** [comment]
That was my impression of the Runner too. It has a LOT of constructor parameters, and I agree that it doesn't look like figuring out how to provide them all is going to be simple. That makes it look internal to me.

I'd also be concerned about it not being covered by semver BC if it's not defined as an API.

**Comment by keradus** [comment]
you basically want to generate the code (potentially to be written down later to a single file) on your side and then format it with given ruleset via PHP code, is that right?

**Comment by joachim-n** [comment]
In my use case, yes. My steps would ideally be:

1. My system uses PHP-Parser to generate PHP code, as a string $php_code.
2. I pass $php_code to PHP-CS-Fixer's API, specifying a ruleset, and get back $php_code_formatted
3. My system shows $php_code_formatted to the user for confirmation and then can write it to a file MyClass.php

**Comment by shalvah** [comment]
Personally, I'm writing to a file and then using PHP CS Fixer to clean it up. I have up on using the runner and I'm trying calling a process now.

Interestingly, this has been requested before: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5059

Seems like a no-brainer. I know it might not be an obvious priority to the maintainers, but it's not a strange use case. I'd think it'd even make things like testing easier.

**Comment by joachim-n** [comment]
> The CLI fix command is using a runner: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/src/Console/Command/FixCommand.php#L318 - you can simply use it as well.

I've had a bit of a look around, and I'm not sure how that's going to work.

As said above, the Runner class is complicated to construct. But even assuming that's done, and I do `        $changed = $runner->fix();`, the Runner class has strong assumptions about how it's getting its files.

Runner::fix() expects $this->finder to be a an iterable of \SplFileInfo objects, and does this with them:

```

        $old = FileReader::createSingleton()->read($file->getRealPath());


        $changed = $runner->fix();

**Comment by joachim-n** [comment]
I came up with an idea for a hack to fool PHP-CS-Fixer into thinking it's dealing with a file when it's not -- register a stream wrapper with a class, and pass a filename on that protocol. The registered  class could then return the string.

However, it doesn't work because there is a call to SplFileInfo::getRealPath().

Gory details here: https://stackoverflow.com/questions/67847684/splfileinfogetrealpath-when-using-a-streamwrapper

**Comment by keradus** [comment]
your best way could be to simply raise a PR to PHP CS Fixer that exposes new API for such feature.

the only interesting point to align would be the interface - eg so the "single bullet file fixer" could be reused by the complex Runner

**Comment by joachim-n** [comment]
@keradus before I start working on a PR for this, do you have any preferences or ideas on what I name things, such at the API class?

**Comment by keradus** [comment]
I'm open for ideas, especially as some of them should not be written from scratch but decoupled from our existing Runner, I think.

Maybe draft the RFC before writing the code?

**Comment by joachim-n** [comment]
Ok, so rough thoughts so far:

FixerInterface is part of the public API, since there are docs that explain how to create custom fixer classes. And FixerInterface::supports() and FixerInterface::fix() both take a \SplFileInfo that describes the file to fix. So we can't decouple fixers from files without a new major version -- and in fact, we wouldn't want to do that anyway, as there are fixers that specifically need to know about the source file they operate on, such as PsrAutoloadingFixer.

However, there's already `class StdinFileInfo extends \SplFileInfo` which is STDIN pretending to be a file. So we could create a similar StringFileInfo class.

For the API, we add a class \PhpCsFixer\Processor. This would get most of the code from PhpCsFixer\Runner\Runner::fixFile() moved over to it, and fixFile() would call Processor::fix() instead.

However, we want Processor to have a simple API. By the time the code gets to Runner, instead of a config object, we have a ton of constructor parameters.

What I'd like for Processor instead is something like:

```
$phpcsProcessor = new Processor();
// Optional steps to override default config:
$config = new Config();
$config->setIndent();
// etc
$phpcsProcessor->setConfig($config);

$fixedPhpString = $phpcsProcessor->fix($givenPhpString);
```

In order to do that, I think we need to change Runner to take a Config object instead of its many constructor params.

My very vague idea of how to do that is that we change ConfigurationResolver so that instead of being a separate class from Config, it also inherits ConfigInterface and acts as a wrapper. Or we keep ConfigurationResolver as the class that does the work of figuring out command line options, and add a CommandConfig class which wraps the initial Config class.

That's as far as I've got -- comments and suggestions welcome!

**Comment by keradus** [comment]
thanks for the kick-off!
would you mind to raise this RFC as structured MD file in PR (draft), so we can give review/discuss in threads?

**Comment by onet4** [comment]
Is there an actual working example code for this? Very simple one would be appreciated.

**Comment by joachim-n** [comment]
Not yet, as I wanted to get feedback on the approach before embarking on what is going to be a fairly fiddly refactor.

I'll try to find time to write my plan up as an RFC soon!

**Comment by onet4** [comment]
@joachim-n 
> I came up with an idea for a hack to fool PHP-CS-Fixer into thinking it's dealing with a file when it's not -- register a stream wrapper with a class, and pass a filename on that protocol. The registered class could then return the string.

Have you tried the `php://filter/write` meta wrapper with a custom filter to capture the output?

**Comment by onet4** [comment]
Ok, I could successfully achieve this without modifying the core.

```php
include( dirname( __DIR__ ) . '/vendor/autoload.php' );

include __DIR__ . '/VariableStream.php';
include __DIR__ . '/VirtualFileInfo.php';
include __DIR__ . '/VariableCodeProcessor.php';

$code = <<<PHPCODE
<?php
\$a = 'Hello world!';
\$b = array('zzz' => 'yy'          );
class A {
public function test() { echo 'foo'; }
}    
PHPCODE;

$codeFixer = new VariableCodeProcessor( __DIR__ . '/.php-cs-fixer.dist.php' );
var_dump( $codeFixer->getFromPath( __DIR__ . '/sample.php' ) );
var_dump( $codeFixer->get( $code ) );
```
This produces 
```
string(442) "<?php

declare(strict_types=1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * Comments.
 */
class A
{
    public function test(): void
    {
        $a = ['foo' => 'bar'];
        echo 'text!!!!!!!!!!!!!!!!';
    }
}
"
string(416) "<?php

declare(strict_types=1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

$a = 'Hello world!';
$b = ['zzz' => 'yy'];
class A
{
    public function test(): void
    {
        echo 'foo';
    }
}
"
```

https://gist.github.com/onet4/a8eacc42ed38e9f8a1a1b291d53dab98

**Comment by joachim-n** [comment]
Thanks!! I've got the gist working, but I needed a few tweaks:

1. Needed this because otherwise it crashed saying the stream file is not writable:

```
--- a/PhpCsFixer/VariableStream.php
+++ b/PhpCsFixer/VariableStream.php
@@ -86,7 +86,7 @@ class VariableStream {
         return [
             'dev'     => 0,
             'ino'     => 0,
-            'mode'    => 0100755,  // 0100000 + 0755 so that is_writable() yields true
+            'mode'    => 0100777,  // 0100000 + 0777 so that is_writable() yields true
```

I've put my copies of the classes from the gist in a namespace, so the quoted class name doesn't work and needs this:

```
--- a/PhpCsFixer/VariableCodeProcessor.php
+++ b/PhpCsFixer/VariableCodeProcessor.php
@@ -22,7 +22,7 @@ class VariableCodeProcessor {
         if ( $existed ) {
             stream_wrapper_unregister( $this->protocol );
         }
-        stream_wrapper_register( $this->protocol, 'VariableStream' );
+        stream_wrapper_register( $this->protocol, VariableStream::class );
```

PHP 7:

```
--- a/PhpCsFixer/VariableCodeProcessor.php
+++ b/PhpCsFixer/VariableCodeProcessor.php
@@ -16,7 +16,7 @@ class VariableCodeProcessor {
     /**
      * @param string|Config|null $config A path to configuration file or a config object
      */
-    public function __construct( string|Config $config=null) {
+    public function __construct($config=null) {
         $this->config = $config;
         $existed = in_array( $this->protocol, stream_get_wrappers() );
         if ( $existed ) {
```

**Comment by joachim-n** [comment]
This would still be a useful feature to have.

**Comment by Wirone** [comment]
I am not sure about this request. How would you want to achieve it, with some static factory that would prepare whole app so you could pass PHP code as an argument? I believe that would be some kind of precedent, because I don't know any tool that offers PHP API like this - PHPUnit, PHPStan, PHP CodeSniffer, Rector, and many other does not offer entrypoints other than CLI. Moreover, some of them (and Fixer too) encourage their users to use PHAR (or shim) version, that just can't provide PHP API.

Personally I would close this, as I think that there's already API, the CLI one. Everything can be built on top of that (as already [pointed out](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/5728#issuecomment-846156432)) - you can generate some code to temporary file, run Fixer in separate process using existing libs, then proceed with the modified content. There's no need to provide additional way of executing Fixer IMHO.

**Comment by joachim-n** [comment]
> some static factory that would prepare whole app so you could pass PHP code as an argument

That sounds like a wrapper that pretends to be the CLI?

I'd do it the other way round - refactor the current code so there is a command handler which then calls the API.

Surely doing that would be really beneficial for running unit tests as well?

**Comment by Wirone** [comment]
@joachim-n it could be beneficial, but it's a lot of work for really little (IMHO) gain. I believe that the amount of users that would utilise this API is really marginal. Also, as I think of it, it would require significant amount of code on the users' side - reading config or preparing rule set, initialising runner/something with it... why would you want to do it instead of running the CLI command with process wrapper?

It's all doable, but we have limited capacity and focusing on such features does not seem like something worthy to do and to maintain later. And by "worthy" I mostly mean balance between required work and potential usage 🙂.
