### ISSUE TITLE
Rule to catch characters before <?php

### ISSUE THREAD

**Issue by arrilot** [PHP-CS-Fixer/PHP-CS-Fixer#5767]
## Rule request

A new rule that detects characters before <?php in the beginning of the file and reports/deletes them

### Code snippet that shows how the rule would fix PHP code

Before
```php
  <?php
class Foo { ...
```
  
After
```php
<?php

class Foo { ...
```

This kind of errors are important because they are hard to detect and can cause some strange errors with Content-Type headers e.g.
[php-cs](https://github.com/squizlabs/PHP_CodeSniffer/issues/2038) project has some sniffers like that but I can't find anything similar for php-cs-fixer

**Comment by keradus** [comment]
Do we see value in this Fixer?
how common case it is?

**Comment by Wirone** [comment]
This somehow overlaps with sunsetting the support for mixed content (see [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6788#issuecomment-1438688702)). It would be great to cover basic scenario (only whitespace before opening tag) though.
