### ISSUE TITLE
[FinalClassFixer] Support attributes for Doctrine entity detection

### ISSUE THREAD

**Issue by gharlan** [PHP-CS-Fixer/PHP-CS-Fixer#5782]
The rule description of `FinalClassFixer` is:

> All classes must be final, except abstract ones and Doctrine entities.

But Doctrine entities are only detected by `@ORM\Entity` annotation, not by php8 attribute `#[ORM\Entity]`.

**Comment by darthf1** [comment]
Is it true that entities are also not detected if you use [PHP mapping](https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/php-mapping.html)?
