### ISSUE TITLE
Remove `|null` from union types when null is the default

### ISSUE THREAD

**Issue by nicolas-grekas** [PHP-CS-Fixer/PHP-CS-Fixer#5785]
I don't remember: do we have a rule to turn an argument like `?foo $bar = null` into `foo $bat = null`, don't we?
We might need one if not :)

And with union types, this rule should also turn `foo|bar|null $bar = null` into `foo|bar $bar = null`.

:pray:

**Comment by keradus** [comment]
can you share the reasoning behind such rule, @nicolas-grekas ?
frankly speaking, I would rather to the opposite, if argument is optional, I would add `?`/`null` to the typehint, if missing

**Comment by nicolas-grekas** [comment]
With union types, signatures are already very long. That CS style makes them a bit shorter without any downside.
Also, that's two possible styles. A CS fixer tool is supposed to normalize, and there are two ways here.

**Comment by julienfalque** [comment]
> do we have a rule to turn an argument like `?foo $bar = null` into `foo = null`

Did you mean
```diff
-?foo $bar = null
+foo $bar = null
```
?

**Comment by nicolas-grekas** [comment]
@julienfalque yes, updtaed

**Comment by kubawerlos** [comment]
[nullable_type_declaration_for_default_null_value](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/doc/rules/function_notation/nullable_type_declaration_for_default_null_value.rst)

**Comment by julienfalque** [comment]
Ah yes, I forgot this rule has an option to make the reverse change. Closing then, thanks @kubawerlos :)

**Comment by julienfalque** [comment]
Mmmh actually the rule does not cover the `|null` part in union types. Maybe we could simply update it.

**Comment by Wirone** [comment]
@nicolas-grekas it took 2 years, but finally it's done 😁. Thank you @HypeMC for this great improvement.
