### ISSUE TITLE
Sort Includes

### ISSUE THREAD

**Issue by TimothyJCowen** [PHP-CS-Fixer/PHP-CS-Fixer#5796]
## Feature request

There is the `ordered_imports` rule which sorts `use` statements. It would be nice to have a similar `ordered_includes` rule to sort `include`/`require` statements.

**Comment by SpacePossum** [comment]
Maybe do `require_once` and `include_once` as well. This will be `risky` fixing though.

**Comment by Wirone** [comment]
I'm going to close this request, because ordering  of includes/requires may impact the runtime and it's not something that should be done with a tool. Imports are totally different thing, their order does not affect the runtime.
