### ISSUE TITLE
feature request: change param/return types from array to iterable

### ISSUE THREAD

**Issue by keradus** [PHP-CS-Fixer/PHP-CS-Fixer#5841]

**Comment by julienfalque** [comment]
What would be the benefit of always replacing `array` with `iterable`?

**Comment by julienfalque** [comment]
I understand that, but IMO use cases are quite specific. I would not enforce such rule globally.

Currently, the only common cases where I prefer `iterable` over `array` are:
* PHPUnit data providers return type;
* class properties (and related methods) that are mapped to `*toMany` associations in Doctrine but you don't want to use Doctrine types (i.e. `Collection`). It's not perfect though, a better replacement would be something like `list<T>|(Traversable<T>&Countable&ArrayAccess<int, T>)`. Using `array<T>` or `list<T>` on such properties would be wrong anyway.

**Comment by keradus** [comment]
having the proper generics in PHP would be great, but out of scope for my idea.

for me, it's basically like relying on smallest, most generic unit, rather than concrete implementation. eg in DI - you put dependency via interface and not concrete implementation. that's how I approach `iterable`, as interface for possible implementations like `array`, `generator` etc

**Comment by julienfalque** [comment]
That's how I see it too, but `iterable` misses a lot of the "API" of `array`: you can't use access indexes or any function that expects `array`, such as `count()`, `array_filter()`, ... It's comparable to using type `InterfaceA` where you know you want `InterfaceA&InterfaceB&InterfaceC`. You can get an array back using `iterator_to_array()` but in most cases it would be easier to directly have an array.

**Comment by keradus** [comment]
agree to disagree then ;)
in my case, if I need to really have access with indexes, i use SplFixedArray (which works for me if I don't want to have mutable variables anyway)

**Comment by Wirone** [comment]
I am on @julienfalque's side here. There's no point in changing `array` to `iterable` just for the sake of doing that. We recently introduced `php_unit_data_provider_return_type` which makes sense for PHPUnit's data providers, because all you want to do with data returned from them is iterating. For regular array usage it will only cause reducing the available API. Personally I would close this 🙂.
