### ISSUE TITLE
`phpdoc_annotation_without_dot` should have option to leave description capitalized

### ISSUE THREAD

**Issue by devbanana** [PHP-CS-Fixer/PHP-CS-Fixer#5873]
## Feature request

Currently using the `phpdoc_annotation_without_dot` rule, the description of the annotation is made lowercase along with the final period being removed.

However, see this [question about Symfony's coding standards](https://github.com/symfony/symfony/issues/24164#issuecomment-388196094), namely that it was clarified that the description of a param, return, etc, should be capitalized.

This was clarified about 3 years ago but it is still default in php-cs-fixer to lowercase the description when using this rule, which is included in the Symfony ruleset.

I propose adding a configuration option, something like `lowercase`, which can be set to false to keep the description within its given case.

I'm opening a pull request which should implement this as well.

---

FYI: [state of the issue as of September 2023](#issuecomment-1735937042).

**Comment by SpacePossum** [comment]
Hi and thanks for sharing your idea,

Maybe it makes sense to split the rule. Having a `phpdoc_annotation_without_dot` and a `phpdoc_annotation_casing_start`, so both annotation with and without dots will be fixed in the expected casing.

**Comment by devbanana** [comment]
Thanks @SpacePossum . I can certainly try to do the work of splitting it out into a separate rule, though I'm not sure I'm familiar enough with the internals. I'll make an attempt at it though and update my PR if that seems to be a better approach.

**Comment by SpacePossum** [comment]
Hi! Thanks for all the work! you might wanna wait a bit to see what others think, maybe they don't like my idea so....

**Comment by keradus** [comment]
Argument A:
Use statement. Or not. Whatever you prefer. Using uppercased sentence without final dot is not grammatically correct. The tool doing standardization should not promote such setup, imho. :-1: for the feature request.

Argument B:
The Sf feedback was from 2018. I wouldn't blindly take it as still valid.
Sf is using `phpdoc_annotation_without_dot` rule and fully following it.
One of Sf golden rule for standards is "follow what you see around". PHP CS Fixer is automating that. Don't follow a 3 years old claim that is not reflected in codebase or style configuration.

**Comment by devbanana** [comment]
@keradus I think they are using uppercase a lot more than they are using lowercase.

I did a quick test. In my Symfony 5.3 application I checked for both cases in the vendor/symfony directory. Here's what I found:

``` shell
$ grep -r -E '\* @param [^$]+\$[^[:space:]]+\s+[[:lower:]]' vendor/symfony | wc -l
      61
$ grep -r -E '\* @param [^$]+\$[^[:space:]]+\s+[[:upper:]]' vendor/symfony | wc -l
    2075
$ 
```

So 2,075 instances of uppercase against 61 instances of lowercase, in the whole framework code and related dependencies. I think that shows a clear trend, at least enough that php-cs-fixer should at least offer it as an option.

**Comment by devbanana** [comment]
Also here's a pretty clear example from their [coding standards](https://symfony.com/doc/current/contributing/code/standards.html#symfony-coding-standards-in-detail):

``` php
    /**
     * Transforms the input given as first argument.
     *
     * @param bool|string $dummy   Some argument description
     * @param array       $options An options collection to be used within the transformation
     *
     * @return string|null The transformed input
     *
     * @throws \RuntimeException When an invalid option is provided
     */
    private function transformText($dummy, array $options = [])
    {
        // …
    }
```

This is full of capitalized descriptions in param, return, and throws.

**Comment by keradus** [comment]
if there is no full stop already, the fixer does not do any changes already:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/src/Fixer/Phpdoc/PhpdocAnnotationWithoutDotFixer.php#L110

**Comment by devbanana** [comment]
@keradus Yes I noticed that. But it seems that if Symfony uses a particular standard throughout their code, it should at least be made an option. Currently if code has trailing fullstops, the only options are to keep them, or to have lowercase descriptions, which as I've shown above goes against the Symfony standard as both practiced in their code and demonstrated in their documentation.

To add a lowercase option, defaulting to true as I have it in my PR, doesn't break backwards compatibility but still allows for the option of maintaining case as it is.

**Comment by keradus** [comment]
would love to get more recent Sf opinion on it

**Comment by Wirone** [comment]
@nicolas-grekas what's the current approach in Symfony? Is [this](https://github.com/symfony/symfony/issues/24164#issuecomment-388196094) still valid?

**Comment by nicolas-grekas** [comment]
We do as described in the issue

**Comment by Wirone** [comment]
To summarise current state of the issue: Symfony [still uses](https://github.com/symfony/symfony/issues/24164#issuecomment-388196094) "uppercase first letter but no final dot" approach but fixer currently can't enforce such standardisation, so Symfony's codebase takes advantage of current "side effect", which [is](#issuecomment-899338975) "if there is no full stop already, the fixer does not do any changes". I believe it would be better if fixer could ensure that all phpDoc descriptions follow the same standard, hence we need config option for that. This option should:

- keep current behaviour as default
- be configured properly in `@Symfony` ruleset, so it follows their policy

@devbanana are you still interested in implementing this?
