### ISSUE TITLE
Switch to match fixer

### ISSUE THREAD

**Issue by Bilge** [PHP-CS-Fixer/PHP-CS-Fixer#5894]
It seems to me that certain uses of `switch` can be transformed automatically into `match`, whilst others cannot. Specifically, the following `case`, `return`, `case`, `return` pattern of switch statement could be converted automatically.

```php
static function (?string $rank): ?string {
    switch ($rank) {
        case $rank <= 250:
            return 'gold';

        case $rank <= 500:
            return 'silver';

        case $rank <= 1000:
            return 'bronze';
    }

    return null;
}
```

Can be converted to the following match function.

```php
static function (?string $rank): ?string {
    return match (true) {
        $rank <= 250 => 'gold',
        $rank <= 500 => 'silver',
        $rank <= 1000 => 'bronze',
        default => null,
    };
},
```

If the switch statement uses `break` instead of `return`, it can also be converted provided it either does _no assignment_ in each branch, or it does _the same assignment_ in each branch.

```php
switch ($this->lexer->lookahead['type']) {
    case Lexer::T_SELECT:
        $statement = $this->SelectStatement();
        break;
 
    case Lexer::T_UPDATE:
        $statement = $this->UpdateStatement();
        break;
 
    case Lexer::T_DELETE:
        $statement = $this->DeleteStatement();
        break;
 
    default:
        $this->syntaxError('SELECT, UPDATE or DELETE');
        break;
}
```
 
Can be converted to the following match function.

```php
$statement = match ($this->lexer->lookahead['type']) {
    Lexer::T_SELECT => $this->SelectStatement(),
    Lexer::T_UPDATE => $this->UpdateStatement(),
    Lexer::T_DELETE => $this->DeleteStatement(),
    default => $this->syntaxError('SELECT, UPDATE or DELETE'),
};
```

If a switch statement executes multiple statements per case, it cannot be converted.

**Comment by keradus** [comment]
feel free to raise a PR proposal

**Comment by Bilge** [comment]
It seems to me that certain uses of `switch` can be transformed automatically into `match`, whilst others cannot. Specifically, the following form of `switch` could be converted automatically.

For example, the following switch function...

```php
static function (?string $rank): ?string {
    switch ($rank) {
        case $rank <= 250:
            return 'gold';

        case $rank <= 500:
            return 'silver';

        case $rank <= 1000:
            return 'bronze';
    }

    return null;
}
```

Can be converted to the following match function.

```php
static function (?string $rank): ?string {
    return match ($rank) {
        $rank <= 250 => 'gold',
        $rank <= 500 => 'silver',
        $rank <= 1000 => 'bronze',
        default => null,
    };
},
```

For this to be valid, the `switch` must generally have the form: `case`, `return`, `case`, `return`. If it uses `break` instead of `return`, it cannot be converted. If it executes multiple statements, it cannot be converted.

**Comment by donatj** [comment]
Has there been any work towards this? I was pondering if I _could_ write a fixer and thought I'd check the tickets first and sure enough…
