### ISSUE TITLE
PSR-12 closing parentheese and opening curly brace inconsistent behavior

### ISSUE THREAD

**Issue by NekaKawaii** [PHP-CS-Fixer/PHP-CS-Fixer#5898]
## Bug report

PHP-CS-Fixer version: 3.0.2
PHP version: 7.4.22
CLI command (no config file exists): vendor/bin/php-cs-fixer fix cs-test.php --rules=@PSR12 --using-cache=no -vvv

### Code snippet that reproduces the problem
  ```php
<?php

function test(string $firstArgument, string $secondArgument, string $thirdArgument, string $fourthArgument,
    string $fifthArgument)
{
    return '';
}

  ```

Expected
  ```php
<?php

function test(
    string $firstArgument,
    string $secondArgument,
    string $thirdArgument,
    string $fourthArgument,
    string $fifthArgument
) {
    return '';
}
  ```

Actual
  ```php
<?php

function test(
    string $firstArgument,
    string $secondArgument,
    string $thirdArgument,
    string $fourthArgument,
    string $fifthArgument
)
{
    return '';
}
  ```

Due to PRS-12 ruleset
> When the argument list is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.

> When you have a return type declaration present, there MUST be one space after the colon followed by the type declaration. The colon and declaration MUST be on the same line as the argument list closing parenthesis with no spaces between the two characters.

#### Inconsistency
Running fixer second time fixes the same file again to the right state according to PRS-12

Code from first cs-fix run
  ```php
<?php

function test(
    string $firstArgument,
    string $secondArgument,
    string $thirdArgument,
    string $fourthArgument,
    string $fifthArgument
)
{
    return '';
}
  ```

After second run of cs-fixer
  ```php
<?php

function test(
    string $firstArgument,
    string $secondArgument,
    string $thirdArgument,
    string $fourthArgument,
    string $fifthArgument
) {
    return '';
}
  ```

No changes were done between first and second run

**Comment by keradus** [comment]
Hey!
Thanks for your report.

We identified that `braces` fixer is too complex and has too many responsibilities. With that, we decided to **deprecate** it [ref #4885].

That also means that we will not be extending, changing the behaviour or fixing anything around `braces` fixer. Please, use [replacement rules](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/braces.rst#this-rule-is-deprecated-and-will-be-removed-on-next-major-version) instead.

If you see the issue that you reported to be present in one of the replacement rules, please report a new github issue.

Big thanks!
