### ISSUE TITLE
Detect useless doc comments even when they contain whitespace

### ISSUE THREAD

**Issue by dktapps** [PHP-CS-Fixer/PHP-CS-Fixer#5903]
## Feature request
Right now, code such as

```

	/**
	 * @return TaskHandler | null
	 */
	final public function getHandler() : ?TaskHandler{
		return $this->taskHandler;
	}
```
is overlooked by the following config:
```
		'no_superfluous_phpdoc_tags' => [
			'allow_mixed' => true,
		],
```

The fixer should be more tolerant of these kinds of whitespaces. (I don't see them often in the wild, but PhpStorm understand doc comments like this are useless, so it's unfortunate that php-cs-fixer doesn't.)

**Comment by keradus** [comment]
I think it's not that much about `no_superfluous_phpdoc_tags`, but more about fixing the phpdoc in first case.
Right now, `| null` is , according to PHPDoc, a `description`

you basically would like to have a correction of PHPDoc like following:
```diff
 	/**
-	 * @return TaskHandler | null
+	 * @return TaskHandler | null
 	 */
```

(and then ensure it runs before `no_superfluous_phpdoc_tags`

**Comment by dktapps** [comment]
Yeah, I guess that works.

**Comment by keradus** [comment]
would you like to propose a PR with that new rule, @dktapps ?

**Comment by dktapps** [comment]
I'll see if I can find some time tomorrow. Thanks for the suggestion.

**Comment by mvorisek** [comment]
@dktapps please retest, `TaskHandler | null` (with spaces) should be parsed correctly at least after https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7010

**Comment by Wirone** [comment]
I am going to close this one, because it now works as expected (or even better):

<img width="899" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/68a5eee6-06be-43ef-8041-e9c16ee62d68">
