### ISSUE TITLE
Conflict between method_argument_space:ensure_fully_multiline and braces rules

### ISSUE THREAD

**Issue by mortenscheel** [PHP-CS-Fixer/PHP-CS-Fixer#5990]
## Bug report

Using rules:
```php
[
    'method_argument_space' => [
        'on_multiline' => 'ensure_fully_multiline',
    ],
    'braces' => true,
]
```

The `ensure_fully_multiline` fixer places the opening brace on a new line even though the `braces` rule wants it on the same line.
And `braces` can't fix it, because the problem is created _after_ braces has run.
Running the `fix` command again doesn't fix it (unless cache is disabled) because the file gets skipped.

### Code snippet that reproduces the problem

Example:
```php
public function myMethod($foo, 
    $bar)
{
    // ...
}
```

Expected:
```php
public function myMethod(
    $foo,
    $bar
) {
    // ...
}
```

Actual:
```php
public function myMethod(
    $foo,
    $bar
)
{
    // ...
}
```

**Comment by SpacePossum** [comment]
Thanks for reporting! 
The `braces` rule is in the middle of a big refactor, so lets see if this can be fixed in that as well or if we can fix it after the refactor :+1:

**Comment by keradus** [comment]
Hey!
Thanks for your report.

We identified that `braces` fixer is too complex and has too many responsibilities. With that, we decided to **deprecate** it [ref #4885].

That also means that we will not be extending, changing the behaviour or fixing anything around `braces` fixer. Please, use [replacement rules](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/braces.rst#this-rule-is-deprecated-and-will-be-removed-on-next-major-version) instead.

If you see the issue that you reported to be present in one of the replacement rules, please report a new github issue.

Big thanks!
