### ISSUE TITLE
Phar only package / shim

### ISSUE THREAD

**Issue by gjuric** [PHP-CS-Fixer/PHP-CS-Fixer#5998]
## Feature request

It would be nice to have a phar only composer package, the same way phpstan/phpstan is installed (previously phpstan/phpstan-shim) or psalm (via psalm/phar). That would skip the need to have a separate composer file in `tools/php-cs-fixer` as advised in the installation instructions.

**Comment by SpacePossum** [comment]
Hi and thanks for proposing this,

Is this different than the current `phar` release we do? 

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.1.0/doc/installation.rst#locally
```
Download the php-cs-fixer.phar file and store it somewhere on your computer.
```

**Comment by gjuric** [comment]
Yes, it's different because version (and installation) of phar is then managed by composer. As far as I can tell it is just a separate repository with the phar file published.

For example, phpstan's development is made in https://github.com/phpstan/phpstan-src but installation is made from https://github.com/phpstan/phpstan where only the phar is published. Same things with psalm, development is made in https://github.com/vimeo/psalm but there is separate phar only repo: https://github.com/psalm/phar

**Comment by gjuric** [comment]
I've created a [repository](https://github.com/gjuric/PHP-CS-Fixer-phar) to show what I mean. You can test it out by running `composer require --dev gjuric/php-cs-fixer-phar `

**Comment by keradus** [comment]
To be honest it's on my TODO list, sth like `php-cs-fixer/shim`, but not top prio

**Comment by keradus** [comment]
I'm not sure if we should make *main* composer repo to be the shim (=phar) , as some folks are downloading the tool for custom fixers purpose.

we also have a mess of `friendsofphp` namespaces not fully focusing on PHP CS Fixer, and moving main repo to `php-cs-fixer` org would be a mess (ppl are still installing `fabbot/php-cs-fixer` we abandoned years ago)

**Comment by gjuric** [comment]
I understand, on the other hand having a new org would be a chance to clear up the stale issues and PRs :) 

If you need any help with it please let me know.

**Comment by keradus** [comment]
take a look at generator branch of our website: https://github.com/php-cs-fixer/php-cs-fixer.github.io
CI (now, Travis, maybe GitHub Actions one day) runs daily and checks for new releases in main repo - if any, it's updating the main branch.

i can imagine sth similar for shim - generator branch triggers job daily and create new shim tags for any new (and >=3.0) tags of main repo. would you be willing to propose such automation? if so, I can create a dummy repo in our namespace, where you can raise the PR proposal ;)

**Comment by gjuric** [comment]
OK, I will take a look at how to create a Github Action that runs daily, runs self-update on the phar and if the updated phar is newer tags a commit. 

I can play with it in my own brunch until I make it work, once I am done you can create a dummy repo.

**Comment by spideyfusion** [comment]
@gjuric Have you made any progress on this? I would be willing to lend a hand if needed.

Having a `shim` release variant would be super convenient for including the tool into existing projects without requiring developers to alter their scripts and directory structure.

We have been using [irstea/php-cs-fixer-shim](https://packagist.org/packages/irstea/php-cs-fixer-shim) up until now, but sadly, it doesn't appear to be maintained anymore.

**Comment by gjuric** [comment]
If you have the time to take a go at it go ahead, I am in the process of moving offices so my time is limited at the moment.

**Comment by keradus** [comment]
@gjuric , would you like to continue on this topic ?

**Comment by keradus** [comment]
hey folks, would you like to try out https://github.com/PHP-CS-Fixer/shim and share your experience with it?

**Comment by trsteel88** [comment]
Looks good. Thanks @keradus

**Comment by gjuric** [comment]
I've been using it for a while and it works great, there is only one small issue.

It would be nice if the file was called `php-cs-fixer.phar` instead of `php-cs-fixer` so PhpStorm parses the context of the phar file and does not complain when working on `.php-cs-fixer.dist.php` that `PhpCsFixer\Finder` or `PhpCsFixer\Config` does not exist. Also auto-complete for those classes would then work as well.

If you want to keep the `vendor/bin/php-cs-fixer` file maybe you could do the same thins as phpstan does, see [here](https://github.com/phpstan/phpstan/blob/bf4d335fbbba4dbb98dac4bd82fcf0fa03907e7d/composer.json#L12-L13) and [here](https://github.com/phpstan/phpstan/blob/bf4d335fbbba4dbb98dac4bd82fcf0fa03907e7d/phpstan).

**Comment by gjuric** [comment]
I've been running the shim release for almost a year now and it works great, so I will close this issue and open a new one regarding my last comment.
