### ISSUE TITLE
`phpdoc_annotation_without_dot` makes exception name lower case in `@throws` annotation

### ISSUE THREAD

**Issue by CodeCasterNL** [PHP-CS-Fixer/PHP-CS-Fixer#6094]
* PHP version: 8.0.12
* PHP CS Fixer version: 3.2.1 Mountains

### Code snippet that reproduces the problem

```php
<?php

class Foo {
    /**
     * @throws Exception When foo
     * @throws Exception When foo.
     * @throws Exception .
     */
    public function __construct()
    {
    }
}
```

* Run `php-cs-fixer fix CsFixerExceptionFixer.php --rules=phpdoc_annotation_without_dot`.

### Ouput

```php
<?php

class Foo {
    /**
     * @throws Exception When foo
     * @throws Exception when foo
     * @throws exception
     */
    public function __construct()
    {
    }
}
```

I would not expect the third `Exception` to be renamed to `exception`.

**Comment by GrahamCampbell** [comment]
You need to tell us the fixer you were using, otherwise nobody can investigate here.

**Comment by GrahamCampbell** [comment]
(as per the issue template. you didn't provide "   * the configuration (file) you used")

**Comment by CodeCasterNL** [comment]
@GrahamCampbell sorry, thought we were running the default config - we're using @Symfony, the culprit is `phpdoc_annotation_without_dot`, issue updated.

**Comment by Wirone** [comment]
Reproduced on `3.16`:

<img width="897" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/0257128e-2fd9-4f2c-a23d-64dd174dceab">
