### ISSUE TITLE
Removal of try-catch blocks which only throw

### ISSUE THREAD

**Issue by boesing** [PHP-CS-Fixer/PHP-CS-Fixer#6158]
## Feature request

I'd like to create a fixer which removes useless try-catch.
I am working on a project with massive of this "style" and I want to get rid and prevent such code in the future.

```php
try {
    $this->doSomething();
} catch (Throwable $throwable) {
    throw $throwable;
}
```

Is that something which is of interest for this project? Happy to get feedback here.

**Comment by keradus** [comment]
do you know the origin idea behind this code?
I'm wondering, is it sth related to the single project you faced, or maybe more common across different projects.

**Comment by julienfalque** [comment]
I would say static analysis tools would be more suitable for this.

**Comment by boesing** [comment]
> do you know the original idea behind this code? I'm wondering, is it sth related to the single project you faced, or maybe more common across different projects.

Nope, don't know about the original idea behind this. But there is plenty of code like mentioned in the initial thread but also stuff like:

```php
try {
    doSomething();
} catch (RuntimeException $exception) {
    throw $exception;
} catch (InvalidArgumentException $exception) {
    throw $exception;
}
```

So to me, this is just useless boilerplate code which can safely be removed.



> I would say static analysis tools would be more suitable for this.

Sure, static analyzers could handle this as well but since only psalm is able to alter code, I'd say its better off in a codestyle fixer.
However, I will build this either way. But if there is no need for that rule in here, I will just add it to our internal coding standard. Just wanted to get some feedback first.

**Comment by Wirone** [comment]
I believe that initial idea behind these `try` blocks was about changing stacktrace of such exception.

We'll try to recover #6393, too bad it wasn't picked up by maintainers on time and was closed (understandably) after few months 😞.
