### ISSUE TITLE
Is it possible to apply the rules from the `.editorconfig` file?

### ISSUE THREAD

**Issue by ralphjsmit** [PHP-CS-Fixer/PHP-CS-Fixer#6162]
Hey there, I'm just getting started with PHP CS Fixer and I really like the way it is setup and how nicely it can be integrated with GitHub Actions.

The past few weeks I've been tweaking my PHPStorm Code Style settings, which I can export and include as a `.editorconfig` in the root of all my projects.

Because I already configured this `.editorconfig` file, is it possible to let PHP CS Fixer automatically apply that file and take its settings from there?

Thank you!

**Comment by SpacePossum** [comment]
Hi @ralphjsmit 

Great to hear you setup the tool and are using it :) Currently we have no logic to make use of a `.editorconfig` file. We could investigate what parts we could use of such file (indenting comes to mind) and how the integration would look like.

**Comment by ralphjsmit** [comment]
Okay, I understand, thanks!

Do you perhaps know of any resource you could point me to that displays all the available rules, perhaps with some examples? It's a bit hard to understand all the available rules and what they do if you're just getting started with it.

**Comment by julienfalque** [comment]
[List of available rules](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/index.rst).

**Comment by keradus** [comment]
for start, i would suggest to not analyse each rule independently, but use well-prepared rulesets like PSR or Symfony

**Comment by Wirone** [comment]
EditorConfig has IDE support, and I believe that in general support for `.editorconfig` is out of the scope of Fixer. However, it has basic standardisation features (indentation, trailing spaces, new line at the end etc.), and most or even all of these can be ensured with Fixer too, using proper config.
