### ISSUE TITLE
Support for `throw` in `fully_qualified_strict_types`

### ISSUE THREAD

**Issue by gnutix** [PHP-CS-Fixer/PHP-CS-Fixer#6169]
Given a file `test.php` : 

```php
<?php

throw new \Exception('ohoh');
```

When I execute PHP-CS-Fixer with the following command : 

```shell
php-cs-fixer fix test.php --rules=fully_qualified_strict_types
```

the file `test.php` is untouched. I would expect `test.php` to be changed to : 

```
<?php

throw new Exception('ohoh');
```

---

Original content:

## Support question

Hello there,

I'm migrating a legacy codebase to new standards, and I was surprised when activating GlobalNamespaceImportFixer to find out that all files where there are no namespace defined were left untouched.

Why does this Fixer ignores them ([backed by tests](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/97b49c8bb0f747a932d9019a9df3238ece618c85/tests/Fixer/Import/GlobalNamespaceImportFixerTest.php#L70)) ? Are such files risky to alter ? Should it be an option on the Fixer ?

Thanks for your insights.
gnutix

**Comment by SpacePossum** [comment]
Hi and thanks for using this tool and stopping by with this question.

Basically it comes down to this; https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4776#issuecomment-581487486
So if you do something like:

```php
<?php

use Exception;

$a = new \Exception();

```

PHP raises the warning:
```bash
$ php test.php 
PHP Warning:  The use statement with non-compound name 'Exception' has no effect in /home/possum/work/PHP-CS-Fixer/test.php on line 3
```

Please let me know if this answers your question :)

**Comment by gnutix** [comment]
Hey :) so what I understand is that adding the use statement for a class in the global namespace in a file without a namespace triggers a warning.

But my point was that the fixer could still remove the leading backslash from every references to classes in the global namespace is such files. So that `\Exception` becomes `Exception` ?

**Comment by SpacePossum** [comment]
Hmm ok, can you maybe fill out the bug report template for the case? it will make it more easy to see what is going on :)

**Comment by gnutix** [comment]
## Bug report

Given a file `test.php` : 

```php
<?php

throw new \Exception('ohoh');
```

When I execute PHP-CS-Fixer with the following command : 

```shell
php-cs-fixer fix test.php --rules=global_namespace_import
```

The output is : 

```
Loaded config default.

Fixed all files in 0.002 seconds, 12.000 MB memory used
```

The file content is untouched. I expect it to be : 

```
<?php

throw new Exception('ohoh');
```

* PHP CS Fixer 3.4.0 Si!
* PHP 8.0.7 (cli) (built: Jun  4 2021 21:26:29) ( NTS ), Zend Engine v4.0.7

**Comment by Wirone** [comment]
Confirmed on 3.14.5 - if current file does not define namespace (so it's global), the FQCNs from global namespace are not imported. When there's custom namespace, fixer adds the import:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/600668/224186990-103c8dcb-0ff3-491e-803b-01f4a0603555.png">

I believe it could be added as an opt-in provided with new option, but if we consider it as a bug it could be also changed within `import_classes`.

**Comment by mvorisek** [comment]
`fully_qualified_strict_types` should simply fix all places where a type/class name can be present, ie. even in `Xxx::class` for example.

**Comment by Wirone** [comment]
I believe that at this point this issue duplicates #5594 which was narrowed to class instantiation, which is also the case for `throw new ...`. I am going to close this one, and will add example in #5594.
