### ISSUE TITLE
False positive for PhpdocTypesFixer when referencing constants that are also reserved keywords

### ISSUE THREAD

**Issue by gnutix** [PHP-CS-Fixer/PHP-CS-Fixer#6193]
## Bug report

PhpdocTypesFixer will change valid PHPDoc types if they reference constants that are also reserved keywords.

### Code snippet that reproduces the problem

```php
class SomeClass
{
    public const BOOLEAN = 0;
    public const NULL = 1;
    public const STRING = 2;
    // ...

    /**
     * @param self::BOOLEAN|self::NULL $someValue
     */
    public function someMethod(int $someValue): void
    {
        // ...
    }
}
```

### Current behavior

```diff
-     * @param self::BOOLEAN|self::NULL $someValue
+     * @param self::boolean|self::null $someValue
```

### Expected

No changes.

**Comment by SpacePossum** [comment]
Hi,

The issue here is more that in `@param self::BOOLEAN|self::NULL $someValue` the "type" is `self::BOOLEAN|self::NULL` , which isn't a `type` but two references to consts/int _values_.
I'm not sure that reference in a PHPDoc to consts to define the type is (wdiely) supported?

Maybe the doc should be:

```php
/**
 * @param int $someValue values can be self::BOOLEAN|self::NULL
 */
```

 or something like that?

**Comment by gnutix** [comment]
"widely supported", I don't know. I do know that PHPStan supports it, and it's an awesome feature to rely on when typing your code. :shrug:

**Comment by Wirone** [comment]
Closing as this now works as expected:

<img width="889" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/29b17962-0061-4a6a-bf97-91381070d4b8">

Most probably it was fixed with some of @mvorisek's contributions related to parsing types in phpDoc 🙂.
