### ISSUE TITLE
method_argument_space(?) issue in with HTML indentation

### ISSUE THREAD

**Issue by larsgw** [PHP-CS-Fixer/PHP-CS-Fixer#6234]
## Bug report

```
$ php ../php-cs-fixer-v3.phar -V
PHP CS Fixer 3.4.0 Si! by Fabien Potencier and Dariusz Ruminski (47177af)
```

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('tmp')
    ->exclude('vendor')
    ->in(__DIR__ . '/app/cake');

$config = new PhpCsFixer\Config();

return $config
    ->setFinder($finder);

```

Command:

    php ../php-cs-fixer-v3.phar fix --config .php-cs-fixer.dist.php

### Code snippet that reproduces the problem

```php
<?php
?>

<div>
    <div>
        <?= $this->Html->link(
            'Test',
            ['controller' => 'Foo', 'action' => 'index', $test->id]
        ) ?>
    </div>
</div>
```

gets changed to

```php
<?php
?>

<div>
    <div>
        <?= $this->Html->link(
    'Test',
    ['controller' => 'Foo', 'action' => 'index', $test->id]
) ?>
    </div>
</div>
```

This still kind of makes sense maybe, since the PHP part is indented correctly if you ignore the indentation of the HTML and the `<?= ?>`. However, I have also encountered cases where the whole part is indented another ~4 levels, so that does not make sense either way (not sure how to reproduce that part though).

**Comment by keradus** [comment]
Thanks for the report!
PHP CS Fixer should not mess up with the template file at all, we need to take a look here

**Comment by larsgw** [comment]
How does it identify templates, by syntax? Or by file extension/location?

**Comment by keradus** [comment]
we aim to check if file is monolithic or not

you may see some improvements around this topic here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6233/files , maybe add your case to it

**Comment by larsgw** [comment]
The unit test seems to work as expected when I insert the example in `PhpCsFixer\Tests\Tokenizer\TokensTest::testMonolithicPhpDetection`.

**Comment by keradus** [comment]
Hey. thanks for your report!

I understand this is not best outcome for you, but core team will not put effort to fix this issue - I will also close it now [but feel free to continue discussion with anyone interested]

The HTML support will be revoked in code as it was never supposed to be officially supported. If you mix PHP with any other language, we consider it as bad practice and encourage to separate your logic from your view, and if you need code-support in view like for templating, we suggest to use one of templating engines.

If you want to still rely on Fixer for HTML-mixed files, till it's officially dropped, and you want to have bug you noticed fixed, I do encourage you to run PR with the fix. It will be recognised and merged with same flow as any other ticket - the only difference is that the fix need to come from interested ppl [and not from the core team]

You may take a look at search feature looking for HTML keyword to get extra context.

Big thanks for understanding!

**Comment by larsgw** [comment]
No problem, thank you.
