### ISSUE TITLE
Rule to enforce implementing `\Stringable` explicitly on `__toString()` implementations

### ISSUE THREAD

**Issue by chalasr** [PHP-CS-Fixer/PHP-CS-Fixer#6235]
## Feature request

Hi there. 

Not sure if there is something already done on that topic, but at least Symfony would need a rule to enforce implementing the PHP8+ `\Stringable` interface for classes that implement `__toString()` (and thus already implement the interface implicitly). Ref: https://github.com/symfony/symfony/pull/45008.

Would it make sense? If it does, I won't be able to send a PR right now myself so anyone please feel free to do it.

**Comment by stof** [comment]
I don't think this can be implemented in php-cs-fixer, as this would require checking the class hierarchy for classes that extend another class or implement another interface (which might extend from Stringable), which is not something php-cs-fixer can do.

**Comment by ro0NL** [comment]
psalm maybe? :sweat_smile:  It could warn us at least on consistency issues :thinking:

**Comment by keradus** [comment]
```php
class Foo implements \Stringable {
    public function __toString() { return "FOO-stringified"; }
}

class Bar extends Foo {}
```

@stof , would you indeed want to have `\Stringable` for both, `Foo` and `Bar`?
If `Bar` relies on `__toString()` implementation of it's parent, it can as well rely on `implements \Stringable` of it's parent.

Then, if we talking about adding `implements \Stringable` only for `Foo`, then it's definitely possible for Fixer to handle such case.

**Comment by kubawerlos** [comment]
Can you check if https://github.com/kubawerlos/php-cs-fixer-custom-fixers/tree/v3.6.1#StringableInterfaceFixer is working as expected currently?

**Comment by derrabus** [comment]
> would you indeed want to have `\Stringable` for both, `Foo` and `Bar`? If `Bar` relies on `__toString()` implementation of it's parent, it can as well rely on `implements \Stringable` of it's parent.

In your example, I would not add `Stringable` to `Bar` because it is inherited from `Foo`.

Apart from that, I'd like to propose that abstract `__toString()` functions are replaced by announcing the interface:

**Before**
```PHP
interface Foo
{
    abstract public function __toString(): string
}

abstract class Bar
{
    abstract public function __toString(): string
}
```

**After**
```PHP
interface Foo extends \Stringable
{
}

abstract class Bar implements \Stringable
{
}
```

**Comment by Littleman778** [comment]
Reopen it


Skinwalker778
