### ISSUE TITLE
Create directory containing cache file when it does not exist

### ISSUE THREAD

**Issue by localheinz** [PHP-CS-Fixer/PHP-CS-Fixer#6249]
## Feature request

What do you think about creating the directory containing the cache file when it does not exist?

Many other tools do that, for example, `phpunit/phpunit`.

I'll be happy to submit a pull request!

**Comment by SpacePossum** [comment]
Hi!
Definitely understand where this idea goes from :)
however, would like to point towards https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4827 , main concern is making the directory on typo and such, maybe @keradus has an idea as well,

**Comment by keradus** [comment]
TBH i wouldn't mind to create the folder, but I'm also ok with just having good message that it is a folder that is missing (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5161/files#diff-aa06d5d6cc326a13ed49230d45f80626c32578e377e4e61584b155be12b28ec9R86)

**Comment by SpacePossum** [comment]
:+1: thanks for input
I'm +1 for creating the directory if it is not empty, like `''`, `null`, `/` etc. to prevent we make it in some root directory as it is the most common typo/misconfigure
