### ISSUE TITLE
Add support of Codeception ordering (_before, _after, etc.)

### ISSUE THREAD

**Issue by bloomsamyk** [PHP-CS-Fixer/PHP-CS-Fixer#6252]
## Feature request

Add support of Codeception - PHP Testing framework.

Unlike the phpunit, instead of "setUp" and "tearDown" the "_before" and "_after" method are used here. 
 [Codeception documentation](https://codeception.com/docs/reference/Module.html#algolia:p:nth-of-type(28))

So this feature should add "codeception" special type in OrderedClassElementsFixer for correct sorting these methods 
'_before',
'_beforeStep',
'_beforeSuite',
'_after',
'_afterStep',
'_afterSuite'

**Comment by keradus** [comment]
is there any recommendation how they should be ordered by default?

**Comment by igorrebega** [comment]
I guess we can follow an order from the documentation:

https://codeception.com/docs/reference/Module.html#algolia:p:nth-of-type(31)

So before tests:
'_before',
'_beforeStep',
'_beforeSuite',

After tests:
'_after',
'_afterStep',
'_afterSuite'

**Comment by SpacePossum** [comment]
I think this is PR'ed here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6360

**Comment by bloomsamyk** [comment]
Thank you!
