### ISSUE TITLE
Regression on `fully_qualified_strict_types` from v3.5 -> v3.6

### ISSUE THREAD

**Issue by jtreminio** [PHP-CS-Fixer/PHP-CS-Fixer#6285]
## Bug report

`fully_qualified_strict_types` no longer removes the FQDN from method parameters as of v3.6.

_composer.json_

```json
{
    "require-dev": {
        "friendsofphp/php-cs-fixer": "3.6"
    },
    "autoload": {
        "psr-4": { "FQST\\" : "src/" }
    }
}

```

_src/Api/Bar.php_

```php
<?php

namespace FQST\Api;

use FQST\Model;

class Bar
{
    public function qwe(\FQST\Model\Foo $foo)
    {
        // ...
    }
}

```

_src/Model/Foo.php_

```php
<?php

namespace FQST\Model;

class Foo
{
}

```

_.php-cs-fixer.php_

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__);

$config = new PhpCsFixer\Config();
return $config->setRules([
    'fully_qualified_strict_types' => true,
])
    ->setFinder($finder)
    ->setRiskyAllowed(true);

```

```shell
./vendor/bin/php-cs-fixer fix --verbose
PHP CS Fixer 3.6.0 Roe Deer by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.27
Loaded config default from "/app/.php-cs-fixer.php".
..                                                                                                                                                      2 / 2 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error

Fixed all files in 0.066 seconds, 6.000 MB memory used

```

I expected `public function qwe(\FQST\Model\Foo $foo)` to be changed to `public function qwe(Model\Foo $foo)`.

This is the behavior seen on v3.5:

```shell
./vendor/bin/php-cs-fixer fix --verbose
PHP CS Fixer 3.5.0 The Creation by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.27
Loaded config default from "/app/.php-cs-fixer.php".
F.                                                                                                                                                      2 / 2 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) src/Api/Bar.php (fully_qualified_strict_types)

Fixed all files in 0.077 seconds, 6.000 MB memory used

```

results in _src/Api/Bar.php_

```php
<?php

namespace FQST\Api;

use FQST\Model;

class Bar
{
    public function qwe(Model\Foo $foo)
    {
        // ...
    }
}

```

**Comment by Wirone** [comment]
I'm going to close this one in favor of #5199 which describes the need for this behavior with less cognitive load 😉.

BTW. This behavior was changed in #6197 (in v3.6.0) with [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6197/files#r778784733) and I am not completely sure if it was a bug that should have been fixed or unfortunate breaking change 🤷‍♂️. @SpacePossum can you explain why it was changed (if you remember after year and a half 😅)?

**Comment by SpacePossum** [comment]
note that the example in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/5199 is very different than this issue and the one linked to my comment, as 5199 shows imports in the _root_ namespace (which is also a far more of rare case)

**Comment by Wirone** [comment]
@SpacePossum do you think this issue should be reopened then? Or maybe we just can add info to the 5199 to handle both scenarios (root and custom namespace)?

**Comment by SpacePossum** [comment]
I think the fix that has been done is correct, so if this is to be reopened than we need a better example of what is wrong. 
5199 can be done by its own I think.
