### ISSUE TITLE
no_unused_imports false negative on classname in different capitalization at end of docblock

### ISSUE THREAD

**Issue by PrinsFrank** [PHP-CS-Fixer/PHP-CS-Fixer#6308]
## Bug report

When an import is unused, but the classname accors anywhere in a docblock - even in lower case - the unused import is not reported.

### Code snippet that reproduces the problem

```php
<?php

use Foo\Bar; // Should be reported as unused import but isn't

/**
 * Say something here about bar.
 */
class Boop {

}
```

**Comment by Wirone** [comment]
Closing as there is #2814 describing the need to handle comments (phpDoc) better.
