### ISSUE TITLE
Applying `allow_single_line_closure` to a single line code

### ISSUE THREAD

**Issue by onet4** [PHP-CS-Fixer/PHP-CS-Fixer#6313]
## Support question

Hello, 

I'd like to make the following code 

```php
class Test { const FOO = 'bar'; }
```

to 

```php
class Test { 
    const FOO = 'bar'; 
}
```

I tried the following configuration.

```php
$config = new PhpCsFixer\Config();
$config->setRules([
        '@PSR2' => true,
        'braces' => [
            'allow_single_line_closure' => true,
        ],
    ]);
```

But the result  is

```php
class Test
{
    const FOO = 'bar';
}
```

It is possible?

**Comment by SpacePossum** [comment]
Hi!

Currently this style is not supported:
```php
class Test { 
    const FOO = 'bar'; 
}
```
The tool can fix to PSR standard, like:
```php
class Test
{
    const FOO = 'bar';
}
```
it is not likely the first style will be supported as it is not part of a widely used CS or standard.

**Comment by onet4** [comment]
I see. It would be nice to see this to be supported. 

> as it is not part of a widely used CS or standard.

Please see [this](https://www.drupal.org/docs/develop/standards/coding-standards#controlstruct) and [this](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#brace-style) as popular open source CMSs employ it.

**Comment by Wirone** [comment]
@onet4 `'allow_single_line_closure' => true` is intended for totally different thing than you describe. You can achieve opening brace in the same line as class name by using `'position_after_functions_and_oop_constructs' => 'same',` for `braces` fixer.
