### ISSUE TITLE
OpenAPI annotation and unused import

### ISSUE THREAD

**Issue by 111ypuk** [PHP-CS-Fixer/PHP-CS-Fixer#6354]
## Bug report
When using Openapi annotaion, unused import not erased.

### Code snippet that reproduces the problem

  ```php
  <?php
namespace App\Model\CustomerAttraction\Controller;

use App\Model\Customer\Entity\Customer; //unused import
use OpenApi\Annotations as OA;

class CustomerProductAttractionController
{

    /**
     * @OA\Post(
     *     path="/api/v1/customer-product-attraction/",
     *     operationId="v1-customer-product-attraction",
     *     tags={"product-attraction"},
     *     @OA\Response(
     *         response=200,
     *         @OA\JsonContent(
     *             allOf={
     *                 @OA\Schema(ref="#/components/schemas/response_success"),
     *             }
     *         )
     *     ),
     * )     
     */
 public function __invoke() {
}
}
```

_use App\Model\Customer\Entity\Customer_ - not erased

But If remove 
```

     *     path="/api/v1/customer-product-attraction/",
     *     operationId="v1-customer-product-attraction",
```
import erased.

**Comment by SpacePossum** [comment]
Hi and thanks opening this issue,

It is the same as this one, although I know that one was raised later
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6428#issuecomment-1156344843

see also the reasoning of Julien here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6363
also same as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6308 ,
I recommend closing some of the issue and keep only one open

**Comment by Wirone** [comment]
@111ypuk it's by design, `no_unused_imports` fixer currently has very simple implementation that is case-insensitive. I am going to close this one in favor of #2814, feel free to subscribe there.
