### ISSUE TITLE
`class_attributes_separation`: ability to insert empty line between groups of elements of the same kind

### ISSUE THREAD

**Issue by annuh** [PHP-CS-Fixer/PHP-CS-Fixer#6368]
## Feature request

It looks like the `class_attributes_separation` does not support inserting empty line between groups of elements with different  kind. 

PHP CS Fixer version:
```
❯ php php-cs-fixer -V

PHP CS Fixer 3.8.0 (cbad111) BerSzcz against war! by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.4
```

Command used: 
```
php php-cs-fixer fix src
```

Configuration (simplified):
```php
return $config->setRules([
    'class_attributes_separation' => [
        'elements' => [
            'const' => 'only_if_meta',
            'method' => 'one',
            'property' => 'only_if_meta',
            'trait_import' => 'none',
            'case' => 'none',
]
    ],
]);
```
as a CLI option: `--rules='{"class_attributes_separation":{"elements":{"const":"only_if_meta","method":"one","property":"only_if_meta","trait_import":"none","case":"none"}}}' `

### Code snippet that reproduces the problem

Before fix:
```php
<?php

class Foo
{
    use Bar;

    const SOME_CONST_1 = 'constant';

    const SOME_CONST_2 = 'constant';
}
```

After fix:
```php
<?php

class Foo
{
    use Bar;
    const SOME_CONST_1 = 'constant';
    const SOME_CONST_2 = 'constant';
}
```

Expected result:
```php
<?php

class Foo
{
    use Bar;

    const SOME_CONST_1 = 'constant';
    const SOME_CONST_2 = 'constant';
}
```

I would expect an empty line after the trait imports. Using option `one` for `const` elements would put empty line between constants too, but I would like to add it only before first one.

**Comment by SpacePossum** [comment]
Hi and thanks for reporting.

Sadly, same with https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6251 it seems near impossible to fix this as the priorities have become to complex here.

**Comment by SlyDave** [comment]
I don't suppose anyone has any update on this?

**Comment by Wirone** [comment]
@SlyDave `single_line_after_imports` handles only top-level imports of symbols, it does not cover importing traits ([there are even tests cases showing this](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/tests/Fixer/Import/SingleLineAfterImportsFixerTest.php#L344-L351)). It does not have anything in common with `class_attributes_separation` and its `trait_import` element.

What you want, if I understand correctly, is another strategy for putting empty line, like `only_if_first_of_a_kind` (or something like that). I believe this was already pointed out somewhere, but I can't find it now. For now, let's keep this, but I'm going to improve title and description.

**Comment by Wirone** [comment]
Sorry @SlyDave, I should mention @annuh 😅. Anyway, `use` (for trait inside class) is not different than `const` in terms of separation, the problem is that `class_attributes_separation` does not have option to leave empty line only for first element of a kind. There's either `one`, which adds empty line above each element of a kind, or `only_if_meta`, which adds new line if there's a comment/attribute above the element (otherwise empty line is removed). So basically with current options you can achieve the code provided as an example (empty line between each element of a class) or the one provided as "after fix" example (everything condensed, no empty lines).

There should be a strategy to add new line only for first element of a kind. At least that's how I see it 🙂.

**Comment by paulbalandan** [comment]
Use `const => none`

**Comment by Wirone** [comment]
@paulbalandan with this config it would not end up like in the "expected result" (all empty lines would be removed removed).

**Comment by paulbalandan** [comment]
The `none` option value removes the empty lines in between same elements (like consts) but enforces a single in between different elements (consts and trait_import).

**Comment by annuh** [comment]
@Wirone thanks for reminder!

I checked our configs, and it seemed we were already using `none`! (we are using ECS to apply PHP-CS-Fixer rules)
```
    $ecsConfig->ruleWithConfiguration(ClassAttributesSeparationFixer::class, [
        'elements' => [
            'const' => 'none',
            'method' => 'one',
            'property' => 'none',
            'trait_import' => 'none',
        ],
    ]);
```

My apologies for not updating this issue! 😳
