### ISSUE TITLE
Leading white space is not removed

### ISSUE THREAD

**Issue by dennisr40** [PHP-CS-Fixer/PHP-CS-Fixer#6418]
Leading white space is not removed. In my .php file  the leading white space is irregular. Some lines have 2 leading spaces, other lines have 4 spaces. Can this be done?

![WHITEPSPACE3](https://user-images.githubusercontent.com/105660260/174441099-57497704-4e60-4f40-89c1-58c860019381.png)

**Comment by dennisr40** [comment]
![WHITESPACE3X](https://user-images.githubusercontent.com/105660260/175955555-effaca9a-8f9f-4424-8986-de4b18b42c3f.png)

As you can see, there is one space too much in the first three lines.

**Comment by keradus** [comment]
could you consider steps needed to reproduce?
like version of the tool, config file, CLI execution arguments?

**Comment by dennisr40** [comment]
I used: php-cs-fixer fix ./
without config file.
verion 3.8.0

**Comment by dennisr40** [comment]
the result:
![whitespace4](https://user-images.githubusercontent.com/105660260/176930603-88010deb-67b5-4d20-bcb5-730d22725e29.png)

**Comment by julienfalque** [comment]
This seems to be caused by `blank_line_before_statement`. Can you try changing the config of the rule (to not add blank lines before `require_once` statements) or disabling it?

**Comment by Wirone** [comment]
Closing this, as it's clearly configuration issue and there's no response for almost a year.
