### ISSUE TITLE
Enforce dollar signs in PHPDoc `@property` lines

### ISSUE THREAD

**Issue by BrekiTomasson** [PHP-CS-Fixer/PHP-CS-Fixer#6449]
## Feature request

As it stands, both of these syntaxes are *technically* correct when writing docblocks in PHP:

```php
/**
 * @property       string $myProperty
 * @property-read  string $myReadOnlyProperty
 * @property-write string $myWriteOnlyProperty
 */

/**
 * @property       string myProperty
 * @property-read  string myReadOnlyProperty
 * @property-write string myWriteOnlyProperty
 */
```

There should be a PHP-CS-Fixer rule that enforces one format over the other. Terribly sorry if there is one already, but I've searched through the documentation and can't seem to find one that matches this request.

**Comment by jrmajor** [comment]
> both of these syntaxes are technically correct when writing docblocks in PHP

They are invalid both in [Psalm](https://psalm.dev/r/8a03a40911) and [PHPStan](https://phpstan.org/r/3f6ae3c0-dc8e-437f-b4d5-a8c82fbb053d). What are the tools/specifications that do support this syntax?

**Comment by SpacePossum** [comment]
Maybe we only need a way to enforce the `$` ?

**Comment by BrekiTomasson** [comment]
Yeah, that's probably the best call. I did some digging and it turns out that it's my IDE that doesn't strictly enforce the `$` sign in the docblock, not the standards themselves.
