### ISSUE TITLE
Comment moved to the next line

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#6492]
## Bug report

issue for https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6470#issuecomment-1186240933

### Code snippet that reproduces the problem

https://raw.githubusercontent.com/atk4/data/57aab906cc88e28ebea2b44be8293e57fc778021/src/Schema/TestCase.php

issue still present in the latest release and on master/https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/b23c1c7beddcb219f6f5ef0428f1c34940060e44

Steps to reproduce:
```
git clone git clone atk4/data
cd data
replace the `src/Schema/TestCase.php` file with https://raw.githubusercontent.com/atk4/data/57aab906cc88e28ebea2b44be8293e57fc778021/src/Schema/TestCase.php
composer update
(optionally replace vendor/friendsofphp/php-cs-fixer with the latest git@github.com:FriendsOfPHP/PHP-CS-Fixer.git)
php vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run --diff
```

Tested with PHP 7.4 (on Windows) and 8.0 (on linux).

**Comment by julienfalque** [comment]
This is an issue in `class_attributes_separation`. This can be reproduced with this snippet:
```php
<?php
class Foo { // foo
    public function bar()
    {
    }
}
```
and this config:
```php
[
    'elements' => [
        'method' => 'one',
    ],
]
```

**Comment by SpacePossum** [comment]
Not sure if the minimal sample provided by Julien is fixed incorrectly, I think `class_attributes_separation` is working ok there.

This
```php
<?php
$a ??= new class { // @phpstan-ignore-line
    function foo() {}
};
```
also gets fixed, of which I think might be improved.
Not sure what the logic should be however, maybe no fixer should ever move an `@phpstan-ignore-line` to another line.

**Comment by julienfalque** [comment]
I think we cannot reliably assume a comment is "tied" to the next element unless it's a DocBlock. Always ignoring regular comments seems like a more sensible choice to me. This is kind of related to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6490#issuecomment-1186473223=.

**Comment by SpacePossum** [comment]
I think 6490 and this are different cases that might require different solutions.
