### ISSUE TITLE
Rule `no_extra_blank_lines` with `tokens: ['throw']` removes blank line after `? : throw`

### ISSUE THREAD

**Issue by CodeCasterNL** [PHP-CS-Fixer/PHP-CS-Fixer#6499]
## Bug report
When running `vendor/bin/php-cs-fixer fix . -vvv --rules='{"no_extra_blank_lines": {"tokens": ["throw"] }}'` on v3.9.4 Grand Awaiting (and prior versions), it removes the blank line between two code blocks (line 12), when the first one ends with an inline `throw`, and reports:

>    1) Foo.php (no_extra_blank_lines)

### Code snippet that reproduces the problem
```php
<?php

class Foo
{
    private readonly string $bar;
    private readonly string $baz;

    public function __construct()
    {
        $bar = getenv('bar');
        $this->bar = is_string($bar) ? $bar : throw new InvalidArgumentException('bar not set');

        $baz = getenv('baz'); // blank line above is removed
        $this->baz = is_string($baz) ? $baz : throw new InvalidArgumentException('bar not set');

        $this->nope = 'oof' ?? throw new InvalidArgumentException('nope not set');

        if (true){ // blank line above remains
            throw new Exception();
        }
    }
}
```

The blank line above `$baz = getenv('baz');`, or rather, after `? : throw` (conditional expression) should not be removed, I think? The rule leaves the line after `?? throw` (null-coalescing operator) alone.

Inline throw (or rather, throw expressions) are [allowed since PHP 8.0](https://www.php.net/manual/en/language.exceptions.php).

**Comment by SpacePossum** [comment]
>and why won't running the rule standalone remove that line while running with [at]Symfony it will, and will report that it applied that rule?

From the docs of the rule:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.9.4/doc/rules/whitespace/no_extra_blank_lines.rst

```
Configuration
tokens

List of tokens to fix.

Default value: ['extra']
```

```
Rule sets

The rule is part of the following rule sets:

@Symfony

    Using the [@Symfony](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/ruleSets/Symfony.rst) rule set will enable the no_extra_blank_lines rule with the config below:

    ['tokens' => ['attribute', 'case', 'continue', 'curly_brace_block', 'default', 'extra', 'parenthesis_brace_block', 'square_brace_block', 'switch', 'throw', 'use']]
```

The SF set configures the rule different from the default.

----

If the SF community does not want this change to be made by the fixer the SF ruleset can be updated per PR.

**Comment by CodeCasterNL** [comment]
@SpacePossum thanks, updated the issue, the culprit seems to be the `throw` token parameter.

**Comment by CodeCasterNL** [comment]
This code is too greedy:

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/c87361818e90bfc7395e2b887498782cd3b25179/src/Fixer/Whitespace/NoExtraBlankLinesFixer.php#L392

The colon (`:`) is there to fix extraneous newlines after `switch - case - throw`, but it also triggers on the conditional (ternary) operator.

More elaborate test case:

```php
<?php
$foo = $b ? $b : throw new \Exception();

switch ($a) {
    case 0:
        throw new \Exception();
    
    case 1:
        $a = $b ? $b : throw new \Exception();

        return $b ?? throw new \Exception();
        
}
```

Should only remove lines 7 and 12 (after `case 0 ... throw` and `case 1 ... return ... throw` respectively), but also removes line 3 and 10.

**Comment by SpacePossum** [comment]
Since we tokenize the colon for `T_CASE` and `ternary` (and even more cases like `goto`-colon) to the exact same type/value it is a real pain to deal with these in the fixers.
I wouldn't be surprised if your sample doesn't stop by `switch` , things like `enum` case's are likely effected as well.

**Comment by CodeCasterNL** [comment]
> Since we tokenize the colon for `T_CASE` and `ternary` (and even more cases like `goto`-colon) to the exact same type/value it is a real pain to deal with these in the fixers. 

Could you perhaps extend the type constants and the parser/transformers?

* T_COLON: 10029
* T_COLON_SWITCH_CASE: 26413
* T_COLON_ENUM_CASE: 59181
* T_COLON_TYPE: ...
* T_COLON_TERNARY: ...
* ...

And then either do a bitwise comparison if you want to check for colon characters (`if (T_COLON === $token & T_COLON)`) or add `Token->isColon()` which checks against an array of known token types?

I do believe that's not a small fix.

**Comment by SpacePossum** [comment]
yeah it is very much doable, but we are stuck with these until the next major release because of BC concerns as 3rd party fixers may rely on the current way/result of the tokenizing.
So we just have to work with what we got for now :|
