### ISSUE TITLE
`braces` suggests wrong indent on multiline property declaration

### ISSUE THREAD

**Issue by emmanuelballery** [PHP-CS-Fixer/PHP-CS-Fixer#6509]
Hi 👋🏻

In 3.9.4 `braces` is suggesting for this property declaration (without `single_class_element_per_statement`):

```php
class Invoice
{
    public float
        $late = .0,
        $paid = .0,
        $other = .0;
}
```

To look like this:

```php
class Invoice
{
    public float
        $late = .0,
    $paid = .0,
    $other = .0;
}
```

We have big POPO (10 to 20 properties with the same configuration); it felt cleaner to write them like this.

Report example:

![image](https://user-images.githubusercontent.com/1687685/180376553-d2fded96-1a18-447a-96ad-7ca4ae2592e2.png)

Should this be considered a bug?

Thanks!

**Comment by jrmajor** [comment]
Failing test case: https://github.com/jrmajor/PHP-CS-Fixer/commit/89bc6feaaa96a3d2ca412003f1cf122f0569494c.

**Comment by Wirone** [comment]
Hey!

Thanks for your report.

We identified that `braces` fixer is too complex and has too many responsibilities. With that, [we decided to deprecate it](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/4885).

That also means that we will not be extending, changing the behaviour or fixing anything around braces fixer. Please, use [replacement rules](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/braces.rst#this-rule-is-deprecated-and-will-be-removed-on-next-major-version) instead.

If you see the issue that you reported to be present in one of the replacement rules, please report a new issue.

Big thanks!

**Comment by julienfalque** [comment]
The bug was reported for `braces` but it actually relies on `statement_indentation` internally, were the bug has been fixed, so it should be fixed for `braces` as well.
