### ISSUE TITLE
Braces rule: Incorrect indent in HTML/PHP mix

### ISSUE THREAD

**Issue by SvenRtbg** [PHP-CS-Fixer/PHP-CS-Fixer#6521]
## Bug report

Adding another test case for incorrect indentation, adding to #6513 and #6470.

PHP CS Fixer 3.9.5 Grand Awaiting by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.30

Command:
php-cs-fixer fix -vvv --rules=braces testcase.php

### Code snippet that reproduces the problem

Expecting no changes to the following file:

```php
<ul>
    <li><a href="foo">foo</a>
        <?php if (!isset($_COOKIE['foo'])) : ?>
            (no foo)
        <?php else : ?>
            (foo)
        <?php endif; ?>
    </li>
</ul>

<h3>Headline</h3>
<?php
if (isset($_GET['include']) || isset($_GET['exclude'])) {
    echo '<small>filtered</small>';
}

?>
<small>Fineprint</small>

<h3>Headline</h3>
<dl>
    <?php
    $headers = ['Sorry' => 'The header_list function cannot be used on this server.'];
    if (function_exists("headers_list")) {
        $headers = headers_list();
    }

    foreach ($headers as $key => $value) {
        echo "<dt>" . htmlspecialchars($key) . "</dt>";
        echo "<dd>" . htmlspecialchars($value) . "</dd>";
    }
    ?>
</dl>
```

The file gets indentations added in the closing PHP tag before "Fineprint" and inside the `<dl>` code part, indenting the first line "Headers: Sorry" by two levels, everything else by one.

If you remove the first `<ul>` block containing an `if` statement in alternative syntax, the indentation below is actually REMOVING one level, leaving the "Headers: Sorry" line in the correct level - I assume by accident.

**Comment by driehle** [comment]
This could be related to #6481. With 3.9.5 I am experiencing the issue with PHPCsFixer continously applying indent especially in files with mixed PHP/HTML code (.phtml view scripts).

**Comment by Alesseon** [comment]
This could be also related to: #6550

**Comment by driehle** [comment]
For me, space is incorrectly added (over and over again, with each run), while for #6550 it seems like space is incorrectly removed. However, @SvenRtbg mentions above that was able to produce both behaviours - adding and removing of space.

The 3.9.x series seems totally broken in regard to HTML/PHP mix files. I am currently staying with `~3.8.0` in my composer.

**Comment by ItsReddi** [comment]
Feels the same bug as in https://github.com/symplify/symplify/issues/4344

**Comment by scsmash3r** [comment]
> For me, space is incorrectly added (over and over again, with each run), while for #6550 it seems like space is incorrectly removed. However, @SvenRtbg mentions above that was able to produce both behaviours - adding and removing of space.
> 
> The 3.9.x series seems totally broken in regard to HTML/PHP mix files. I am currently staying with `~3.8.0` in my composer.

Having same problem, so rolled back to 3.8.* release, because that one is not messing up with mixed code.

**Comment by keradus** [comment]
Hey. thanks for your report!

I understand this is not best outcome for you, but core team will not put effort to fix this issue - I will also close it now [but feel free to continue discussion with anyone interested]

The HTML support will be revoked in code as it was never supposed to be officially supported. If you mix PHP with any other language, we consider it as bad practice and encourage to separate your logic from your view, and if you need code-support in view like for templating, we suggest to use one of templating engines.

If you want to still rely on Fixer for HTML-mixed files, till it's officially dropped, and you want to have bug you noticed fixed, I do encourage you to run PR with the fix. It will be recognised and merged with same flow as any other ticket - the only difference is that the fix need to come from interested ppl [and not from the core team]

You may take a look at search feature looking for HTML keyword to get extra context.

Big thanks for understanding!

----

also, `braces` rule is now deprecated
