### ISSUE TITLE
Use unpacking to replace the `array_merge` function

### ISSUE THREAD

**Issue by kayw-geek** [PHP-CS-Fixer/PHP-CS-Fixer#6532]
## Feature request

I want to add a rule that use unpacking to replace the `array_merge` function, I want to seek advice, and I will try to realize it if I can.

Example:

```PHP
$arr1 = ['a'=>1];
$arr2 = ['b'=>2];

[...$arr1,...$arr2];
 // [ 'a' => 1, 'b' => 2]
array_merge($arr1,$arr2);
 // [ 'a' => 1, 'b' => 2]
```

**Comment by keradus** [comment]
@kayw-geek , would you like to propose a PR for this idea?

**Comment by kayw-geek** [comment]
> @kayw-geek , would you like to propose a PR for this idea?
Sure, I will try to complete it

**Comment by fancyweb** [comment]
This feature was never implemented, wasn't it?

**Comment by Wirone** [comment]
It looks like it was proposed and closed without implementation, that's why I've changed issue's resolution.
