### ISSUE TITLE
Support for attributes in `method_argument_space`

### ISSUE THREAD

**Issue by Aerendir** [PHP-CS-Fixer/PHP-CS-Fixer#6546]
What I'd like to achieve:

```diff
class MyClass
{
    public function __construct(
        string $id,
-       #[ORM\Column(type: Types::STRING, nullable: true)] #[Groups(['get_my_class'])] private ?string $name = null,
+
+       #[ORM\Column(type: Types::STRING, nullable: true)]
+       #[Groups(['get_my_class'])]
+       private ?string $name = null,
    ) {}
```

Is it possible with current rules?

**Comment by julienfalque** [comment]
There are no rules for doing that at the moment.

**Comment by Aerendir** [comment]
Hi @julienfalque , thank you for your reply :)

Can you think at some rules that may be adapted to do this? I need some inspiration for configurations, primarily.

**Comment by julienfalque** [comment]
No I think this is quite new :)

**Comment by lochmueller** [comment]
Note. There are some devs that ar also used Multiline Attributes in one, that ar currently bad formatted:
```php
        #[
            Assert\NotBlank,
            Assert\Email,
            ORM\Column(type: 'string', length: 255),
        ]
```

Current result:
```php
        #[
            Assert\NotBlank,
        Assert\Email,
        ORM\Column(type: 'string', length: 255),
        ]
```

**Comment by JarJak** [comment]
I'd assume `'method_argument_space' => ['on_multiline' => 'ensure_fully_multiline'],` would fix it, but it didn't...
