### ISSUE TITLE
PSR12 mixing with html

### ISSUE THREAD

**Issue by vitvavra** [PHP-CS-Fixer/PHP-CS-Fixer#6550]
## Bug report

version:  3.9.5
PHP runtime: 7.4.30
Command used to run:
 `php-cs-fixer fix --rules=@PSR12 -vvv test.php`

Expected output: 
  ```php
<?php
//something
?>
<div>
    <h3>hello</h3>
    <?php
    if (true) {
        echo '';
    } else {
        throw new Exception();
    }
    $table = true;
    if (true) {
        echo '';
    }
    ?>
</div>

  ```
Actual output:
```php
<?php
//something
?>
<div>
    <h3>hello</h3>
    <?php
    if (true) {
        echo '';
    } else {
        throw new Exception();
    }
    $table = true;
if (true) {
    echo '';
}
?>
</div>


```

**Comment by keradus** [comment]
Hey. thanks for your report!

I understand this is not best outcome for you, but core team will not put effort to fix this issue - I will also close it now [but feel free to continue discussion with anyone interested]

The HTML support will be revoked in code as it was never supposed to be officially supported. If you mix PHP with any other language, we consider it as bad practice and encourage to separate your logic from your view, and if you need code-support in view like for templating, we suggest to use one of templating engines.

If you want to still rely on Fixer for HTML-mixed files, till it's officially dropped, and you want to have bug you noticed fixed, I do encourage you to run PR with the fix. It will be recognised and merged with same flow as any other ticket - the only difference is that the fix need to come from interested ppl [and not from the core team]

You may take a look at search feature looking for HTML keyword to get extra context.

Big thanks for understanding!
