### ISSUE TITLE
Complex/conditional phpdoc is not parsed/indented correctly

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#6568]
### Code snippet that reproduces the problem

file: https://github.com/atk4/ui/blob/f92de2734264a328918e61b28f5822c88eecf60b/src/View.php#L971
config: https://github.com/atk4/ui/blob/f92de2734264a328918e61b28f5822c88eecf60b/.php-cs-fixer.dist.php
PHP CS Fixer version: latest/3.10.0

the following fix https://github.com/atk4/ui/commit/d592b86c0b8b79d4b3534f96cd8454dde382dba2 was needed to satisfy PHP CS Fixer, but the indentation is corrupted

It seems the complex phpstan phpdoc conditional type is not parsed by PHP CS Fixer correctly.

**Comment by VincentLanglet** [comment]
The regex used is defined here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/DocBlock/TypeExpression.php#L32

This might be improve to support conditional type if we find a regex, maybe something like
```
ContionalType = ($variable is RegexType ? ContionalType : ConditionalType)
```

I think it could be a great improvement and I assume it will be BC. But will require unit tests.

**Comment by mvorisek** [comment]
another example: https://github.com/atk4/ui/commit/dbd32fb9fa7b5f7ade7236b01851252048f8f6d8

the grammar of conditional type is defined here: https://github.com/phpstan/phpdoc-parser/blob/1e355a35e2a8ddfd1910ae674ee99d562847b4b5/doc/grammars/type.abnf#L20

**Comment by VincentLanglet** [comment]
> the grammar of conditional type is defined here: https://github.com/phpstan/phpdoc-parser/blob/1e355a35e2a8ddfd1910ae674ee99d562847b4b5/doc/grammars/type.abnf#L20

But you can have nested conditional.

**Comment by mvorisek** [comment]
Yes, `Atomic` token there takes care of that...

**Comment by mvorisek** [comment]
```
    /**
     * @param string|array<int, string|array{string, 'asc'|'desc'}>|array<string, 'asc'|'desc'> $field
     * @param 'asc'|'desc' $direction
     *
     * @return $this
     */
    public function setOrder($field, string $direction = 'asc')
    {
```

this phpdoc is also not fixed - I would expect the `$field` and `$direction` variables in `@param` phpdoc lines aligned vertically

**Comment by mvorisek** [comment]
what about using https://github.com/phpstan/phpdoc-parser for parsing the phpdoc?

**Comment by kubawerlos** [comment]
@mvorisek https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6619
