### ISSUE TITLE
Braces rule: Comments in switch are indented wrong

### ISSUE THREAD

**Issue by SvenRtbg** [PHP-CS-Fixer/PHP-CS-Fixer#6572]
## Bug report

   * PHP CS Fixer version and PHP runtime: php-cs-fixer -V

    PHP CS Fixer 3.10.0 Oliva by Fabien Potencier and Dariusz Ruminski.
    PHP runtime: 7.4.30

   * the command used to run PHP CS Fixer (run with `-vvv`)

    vendor/bin/php-cs-fixer fix --dry-run --rules=braces -vvv --diff switch_comments.php

### Code snippet that reproduces the problem

  ```php
<?php

$var = "foo";

switch ($var) {
    // do more
    case "more":
        $do = "more";
        break;
    // do less
    default:
        $do = "less";
        break;
}
  ```

expected no change at all, but getting

  ```bash
PHP CS Fixer 3.10.0 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.30
Loaded config default.
F                                                                                                                                                                                                       1 / 1 (100%)
Legend: .-no changes, F-fixed, S-skipped (cached or empty file), I-invalid file syntax (file ignored), E-error
   1) switch_comments.php (braces)
      ---------- begin diff ----------
--- /sources/tools-github/php-cs-fixer-issue/switch_comments.php
+++ /sources/tools-github/php-cs-fixer-issue/switch_comments.php
@@ -7,7 +7,7 @@
     case "more":
         $do = "more";
         break;
-    // do less
+        // do less
     default:
         $do = "less";
         break;

      ----------- end diff -----------

```
The comment belongs to the level of "case/default", because it is written after the "break".

**Comment by SvenRtbg** [comment]
Worked with 3.8.0. Broken with 3.10.0, 3.9.5. Haven't checked any previous 3.9.x versions.

**Comment by julienfalque** [comment]
See #6490.

**Comment by keradus** [comment]
Hey!
Thanks for your report.

We identified that `braces` fixer is too complex and has too many responsibilities. With that, we decided to **deprecate** it [ref #4885].

That also means that we will not be extending, changing the behaviour or fixing anything around `braces` fixer. Please, use [replacement rules](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/braces.rst#this-rule-is-deprecated-and-will-be-removed-on-next-major-version) instead.

If you see the issue that you reported to be present in one of the replacement rules, please report a new github issue.

Big thanks!
