### ISSUE TITLE
Missing a FQCN to Import (use) conversion

### ISSUE THREAD

**Issue by ksiatka** [PHP-CS-Fixer/PHP-CS-Fixer#6582]
## Rule request

Either I'm poorly looking for it, or a fairly (IMO) important rule is missing.

The FQCN is not replaced by the Import (use keyword), unless this import had been already added.

#### How it is (already after `php-cs-fixer fix`):

  ```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TestController extends AbstractController
{
    public function index(): \Symfony\Component\HttpFoundation\Response
    {
        return new \Symfony\Component\HttpFoundation\Response();
    }
}
  ```

#### What would I expect:

```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

class TestController extends AbstractController
{
    public function index(): Response
    {
        return new Response();
    }
}
```

Only when I manually add `use Symfony\Component\HttpFoundation\Response;` and then run cs-fixer, it will do the necessary conversion in the class body.

**Comment by VincentLanglet** [comment]
Is there any other rules that already add a new `use` line ?
I would say it would be kinda tricky to implement.

Also, you could have issue with
```
<?php

namespace App\Controller;

use CustomNamespace\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TestController extends AbstractController
{
  public function index(): \Symfony\Component\HttpFoundation\Response
  {
      return new \Symfony\Component\HttpFoundation\Response();
  }
}
```
If the linter add Response without any question, it will crash the code.

You should look at https://github.com/rectorphp/rector which is already doing this.

**Comment by ksiatka** [comment]
I don't know if there is any other method for adding a `use` line. I just started with cs-fixer.

Rector, on the other hand, adds the FQCN (eg when the return type declaration is missing) and its purpose is not to add a `use` line. According to https://symfonycasts.com/screencast/symfony6-upgrade/rector-fixup, php-cs-fixer solves this problem by default, but (not in my case ;) and) not on the above tested example. Maybe I'm doing something wrong, maybe the issue is somehow the Sf44 version, or rather php 7.2.

**Comment by arderyp** [comment]
im seeing this too and was also expecting a new use statement and removed FQCN references in the code

**Comment by Wirone** [comment]
@ksiatka there is [`fully_qualified_strict_types`](https://cs.symfony.com/doc/rules/import/fully_qualified_strict_types.html) fixer, but:

- it fixes only FQCNs that are used within code, but are already imported (does not add `use`, only converts types to short version if there is existing import)
- it does not support class' properties (see #5004) and probably more other cases

Probably we need to make some enhancements to existing fixer, so it can fix more scenarios.

**Comment by ksiatka** [comment]
@Wirone Yes, you are right. I've already come to that.

For me the solution became PhpStorm -> `Code Cleanup`. It is important to disable the configuration "PHP | Code style | Fully qualified name usage | Ignore global namespace" so as not to import e.g. `\DateTime`.

**Comment by ruudk** [comment]
@ksiatka Thanks. If someone can't find the setting, for me it's under Intentions:
![Screenshot 2023-07-27 at 11 50 16@2x](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/104180/eeadb553-20a9-47c4-9666-a2a24eff4fe2)

**Comment by chescos** [comment]
There is no way to get this working with CS Fixer currently, right?
