### ISSUE TITLE
php-cs-fixer formatting does not work

### ISSUE THREAD

**Issue by nwbkhan** [PHP-CS-Fixer/PHP-CS-Fixer#6596]
## Support question

I have installed `php-cs-fixer` but running following command would just replace the spaces, its not doing and indentation on its own. I have following requirements to achieve - 
- Have `If statement conditions appear on new line` like `ES6` formatting does.
- Format `array and variable assignments with indent` and `give spaces` before and after equal signs.

I thought this would be already defined as defaults somewhere. I checked with `Nvim` not working, tried by `command` not working, checked with `VS code` not working still. Is there something i need to do for to get it working?

Versions - 
```
$ php-cs-fixer -V
PHP CS Fixer 3.10.0 (76d7da6) Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.9
```

```
$ cat abcd.php
<?php

$foo=['bar' => [ "bax"
     => true,
]];


if(
    1 == 1
    &&
    2 == 2 && 1 == 1 && 2 == 2 && 1 == 1 && 2 == 2
) {
    print 1;
}
```
after php-cs-fixer (It does noting)
```
$ php-cs-fixer fix abcd.php
Loaded config default.
Using cache file ".php-cs-fixer.cache".
   1) abcd.php

Fixed all files in 0.004 seconds, 12.000 MB memory used

$ cat abcd.php
<?php

$foo=['bar' => [ "bax"
     => true,
]];


if (
    1 == 1
    &&
    2 == 2 && 1 == 1 && 2 == 2 && 1 == 1 && 2 == 2
) {
    print 1;
}
```

BTW, I am running this MacOS M1.

**Comment by keradus** [comment]
I think we all failed to understand the request.
can you show a diff of  what changes you are expecting, for those of us who are not familiar with ES6 etc?

**Comment by Wirone** [comment]
Closing because of lack of answer. @nwbkhan feel free to ask again, but please:
- provide your config file and expected output
- use [Discussions](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions) instead.
