### ISSUE TITLE
3.11.0 separates all tags, but phpstan/psalm tags should be not separated but placed & ordered after "native" tags instead

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#6602]
## Feature request

Since the latest changes in `master` all phpdoc are separated. (this was not the case in v3.10.x)

It seems correct but `@phpstan-xxx` and `@psalm-xxx` phpdoc tags are special. They are used to narrow the "native" `@xxx` phpdoc tags and they should NOT be separated by an empty line.

This is a feature request for a fixed, that will move phpstan/psalm tags after the "native" tags in a defined order.

3.11.0 PHP CS Fixer breaking change example:
```
    2) data/src/Persistence/Sql/Expression.php (phpdoc_separation)
      ---------- begin diff ----------
--- /__w/data/data/src/Persistence/Sql/Expression.php
+++ /__w/data/data/src/Persistence/Sql/Expression.php
@@ -544,6 +544,7 @@
      * @param DbalConnection|Connection $connection
      *
      * @return DbalResult|int<0, max>
+     *
      * @phpstan-return ($fromExecuteStatement is true ? int<0, max> : DbalResult)
      */
     protected function _execute(?object $connection, bool $fromExecuteStatement)
```

full file: https://github.com/atk4/data/blob/ca0251dcff10dae02beab190b42526761aa5f705/src/Persistence/Sql/Expression.php#L547

----

From this feature request I would expect the following method phpdoc:

```
    /**
     * @psalm-param DbalConnection|Connection $connection
     * @phpstan-return ($fromExecuteStatement is true ? int<0, max> : DbalResult)
     *
     * @param DbalConnection|Connection $connection
     * @param bool                      $fromExecuteStatement
     *
     * @return DbalResult|int<0, max>
     */
    protected function _execute(?object $connection, $fromExecuteStatement)
    {
```

fixed to:

```
    /**
     * @param DbalConnection|Connection       $connection
     * @psalm-param DbalConnection|Connection $connection
     * @param bool                            $fromExecuteStatement
     *
     * @return DbalResult|int<0, max>
     * @phpstan-return ($fromExecuteStatement is true ? int<0, max> : DbalResult)
     */
    protected function _execute(?object $connection, $fromExecuteStatement)
    {
```

**Comment by mvorisek** [comment]
Another (unexpected) fix since v3.11.0 on property phpdoc:

```
    2) ui/src/Form/Control.php (phpdoc_separation)
      ---------- begin diff ----------
--- /__w/ui/ui/src/Form/Control.php
+++ /__w/ui/ui/src/Form/Control.php
@@ -24,6 +24,7 @@
 
     /**
      * @var EntityFieldPair|null
+     *
      * @phpstan-var EntityFieldPair<Model, Field>|null
      */
     public $entityField;
```

**Comment by VincentLanglet** [comment]
Hi, @mvorisek.

I disagree with the request change.
I personally always add extra line between phpstan-tags and default tags.

IMHO, everybody has a different point of view on the situation and I think php-cs-fixer choose the right strategy.
Every different tags are separated without any exceptions, this is a general rule.

Then, if you want something different, there is configuration
you can use the `groups` configuration.

**Comment by SpacePossum** [comment]
This is a support question about `phpdoc_separation` rule. If you run the tool as described in the issue template you can see in the output that this rule makes this change. From there you can lookup the doc of this rule and update your configuration as you like. In this case:  https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.11.0/doc/rules/phpdoc/phpdoc_separation.rst

I think this question can be closed as it was answered.

**Comment by mvorisek** [comment]
Yes, `phpdoc_separation` package.

This is a feature request to add something like `grouped_prefixes` = `['', 'psalm-', 'phpstan-']` which will honor the existing grouping, but group & order the prefixed tags together with the native tags.

**Comment by VincentLanglet** [comment]
You can just copy the existing groups and add psalm-param, phpstan-param, etc

less options is better

**Comment by mvorisek** [comment]
related PR https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6614

**Comment by Wirone** [comment]
I am going to close this since it's already available to achieve with explicit custom config using existing options.
