### ISSUE TITLE
[PHP8.2] Support for `readonly` classes

### ISSUE THREAD

**Issue by Wirone** [PHP-CS-Fixer/PHP-CS-Fixer#6604]
The goal of this task is to provide support for [`readonly` classes](https://php.watch/versions/8.2/readonly-classes). New class-level keyword must not break any fixers and should be supported only for PHP 8.2+

**Comment by kubawerlos** [comment]
Would be nice to have indeed, can you propose a PR for it, please?

**Comment by SpacePossum** [comment]
we should update the tokenizer to make a custom `CT::CLASS_READONLY` token for this and than make PR's to update the rules that need it

**Comment by SpacePossum** [comment]
Just to double check, but `anonymous` classes cannot be `readonly` right? (not sure why TBH, didn't find anything on the subject)

**Comment by jaikdean** [comment]
> Just to double check, but `anonymous` classes cannot be `readonly` right? (not sure why TBH, didn't find anything on the subject)

Correct, anonymous classes cannot be `readonly`.

**Comment by BenMorel** [comment]
2 points:

- indeed, anonymous classes cannot be `readonly`: https://3v4l.org/s536m
- interestingly, a `readonly` class can have redundant `readonly` properties: https://3v4l.org/4KTVg

-> It would be nice to provider a fixer to remove `readonly` from properties of `readonly` classes.

**Comment by SpacePossum** [comment]
it is all here https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6624 , if anyone is interested in finishing it

**Comment by Wirone** [comment]
@alfredbez could you verify #6745 against your reproducer and check if it works properly?

**Comment by alfredbez** [comment]
This bug is solved with the change from the PR: [CI output](https://github.com/alfredbez/php-cs-fixer-8.2/actions/runs/3877107108/jobs/6611731723) 🎉 

([commit](https://github.com/alfredbez/php-cs-fixer-8.2/commit/d7ca395fb93be54dfd1aa816d1bb3bd1527f59c3))
