### ISSUE TITLE
[PHP8.2] Support for `null`, `false` and `true` standalone types

### ISSUE THREAD

**Issue by Wirone** [PHP-CS-Fixer/PHP-CS-Fixer#6605]
The goal of this task is to provide support for new standalone types:
- [`null`, `false`](https://php.watch/versions/8.2/null-false-types)
- [`true`](https://php.watch/versions/8.2/true-type)

Code that uses these types in arguments, properties or return types must not break any fixers. All tests related to these types must `@require` PHP 8.2

**TODO**

- [x] Add [more fixtures](#issuecomment-1241946842) and fix them (done in #6623)

**Comment by kubawerlos** [comment]
What kind of support do you have in mind?

With https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6558 showing there is no regression it seems they are already supported when used.

**Comment by Wirone** [comment]
@kubawerlos All issues created for 8.2 by me are some kind of backlog (checklist). @keradus asked me if I could prepare it, like #4702 was done before. But as I said, we decided to try milestones with issues. 

I don't see how #6558 verified regression since I don't see usages of those new types in the PR's diff. Shouldn't they be actually used somewhere to verify if Fixer does not fail on it? 🤔

**Comment by SpacePossum** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6427 contains the changes needed I think

**Comment by Wirone** [comment]
@SpacePossum @keradus I am not sure if #6427 (and [my appendix](https://github.com/SpacePossum/PHP-CS-Fixer/pull/1)) covers new standalone types fully: they can be used also in class properties but `NativeFunctionTypeDeclarationCasingFixer` does not handle it. I don't see any test related to casing which would cover class' properties 🤔 

PS. Also, does `NativeFunctionTypeDeclarationCasingFixerTest` works on actual PHP 8.2 runtime? Or should there be some integration test too?

**Comment by SpacePossum** [comment]
> I don't see any test related to casing which would cover class' properties 

Can you update this issue with an example?
6427 doesn't aim to bring all support for this change in PHP8.2, it might be better to have multiple smaller PRs in some cases.

>Does NativeFunctionTypeDeclarationCasingFixerTest works on actual PHP 8.2 runtime?

6427 brings test for PHP8.2, so this can be discussed there if you want, like to know if stuff is missing :)

**Comment by Wirone** [comment]
@SpacePossum my comment was sent before I started work on #6621 and I see that casing in the promoted property ([here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6621/files#diff-a689797fee8dd59c4fe97b1523a45e3538ac9add3a1981200286aa4a3875161aR114) and [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6621/files#diff-a689797fee8dd59c4fe97b1523a45e3538ac9add3a1981200286aa4a3875161aR133)) is fixed - not sure which fixer covers it but it looks like it's handled. So it looks like #6427 brings remaining support. I'll add more fixtures later (non-promoted properties, function params etc).

And yeah, sometimes I may ask dumb questions because I'm entering this codebase for the first time, sometimes I answer myself later like about the runtime 😅

**Comment by SpacePossum** [comment]
haven't seen a dumb question yet so no worries, I'm just trying to figure out a todo-list for 8.2 :D thanks for all the help!

**Comment by Wirone** [comment]
After #6621 gets merged, we need to create another MR that would add and fix such fixtures:

```diff
Index: tests/Fixtures/Integration/misc/PHP8_2.test
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tests/Fixtures/Integration/misc/PHP8_2.test b/tests/Fixtures/Integration/misc/PHP8_2.test
--- a/tests/Fixtures/Integration/misc/PHP8_2.test	(revision 6c6655389b3b2d6d5f0ebaab6248daf10b76e1d7)
+++ b/tests/Fixtures/Integration/misc/PHP8_2.test	(date 1662728038955)
@@ -28,6 +28,16 @@
     ) {
     }
 
+    public function falsy(): false
+    {
+        return $this->falsy;
+    }
+
+    public function nully(): null
+    {
+        return $this->nully;
+    }
+
     public function setAB(false $a, null $b): void
     {
         $this->a = $a;
@@ -35,6 +45,10 @@
     }
 }
 
+function falsyNull(null $n, false $f): null|false
+{
+}
+
 array_filter([], fn (null $n) => null === $n);
 array_filter([], fn (false $n) => false === $n);
 
@@ -48,12 +62,22 @@
     ) {
     }
 
+    public function havingABud(): true
+    {
+        return $this->havingABud;
+    }
+
     public function setA(true $a): void
     {
         $this->a = $a;
     }
 }
 
+function truish(true $true): true
+{
+    return $true;
+}
+
 array_filter([], fn (true $n) => true === $n);
 
 // https://wiki.php.net/rfc/constants_in_traits
@@ -84,6 +108,16 @@
     ) {
     }
 
+    public function falsy(): FALSE
+    {
+        return $this -> falsy;
+    }
+
+    public function nully(): NULL
+    {
+        return $this -> nully;
+    }
+
     public function setAB(FALSE $a, NULL $b): void
     {
         $this->a = $a;
@@ -91,6 +125,10 @@
     }
 }
 
+function   falsyNull   (NULL   $n,   FALSE   $f):   NULL|FALSE
+{
+}
+
 array_filter([], fn     (NULL     $n)     =>     NULL     ===     $n);
 array_filter([], fn     (FALSE     $n)     =>     FALSE     ===     $n);
 
@@ -103,12 +141,22 @@
     ) {
     }
 
+    public function havingABud(): TRUE
+    {
+        return $this -> havingABud;
+    }
+
     public function setA(TRUE $a): void
     {
         $this->a = $a;
     }
 }
 
+function truish  (TRUE   $true):   TRUE
+{
+    return   $true;
+}
+
 array_filter([], fn     (TRUE     $n)     =>     TRUE     ===     $n);
 
 // https://wiki.php.net/rfc/constants_in_traits

```

Those fixture were failing, so they were removed in order to be able to merge integration test's base.

**Comment by magikid** [comment]
Is this done now that #6623 has been merged in?

**Comment by keradus** [comment]
can you take a look, @Wirone ?

**Comment by Wirone** [comment]
Mentioned PR clearly states:

> not necessarily provides full support

and I'm completely sure 😉 Probably it's ready for those new types, or pretty close to it. Unfortunately I did not have time lately to coordinate those works..

**Comment by Wirone** [comment]
I'm going to close this one. PHP 8.2 support was officially added in v3.15 so if anything doesn't work as expected, we will handle it in new issues.
