### ISSUE TITLE
[PHP8.2] Support for constants in traits

### ISSUE THREAD

**Issue by Wirone** [PHP-CS-Fixer/PHP-CS-Fixer#6610]
The goal of this task is to provide support for [constants in traits](https://wiki.php.net/rfc/constants_in_traits).

Code that uses consts in traits must not break any fixers. All tests related to such usage must `@require` PHP 8.2

**Comment by SpacePossum** [comment]
draft PR is here https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6607

**Comment by pietaj** [comment]
Is this issue still relevant? The mentioned PR https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6607 has been merged on Oct 11

**Comment by Wirone** [comment]
@pietaj you're right, PR was created few hours before the issue so it wasn't linked with `Closes`, so issue wasn't closed automatically. I'll close it now, thanks!
