### ISSUE TITLE
Scalar array key should be fixed to the evaluated type

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#6617]
## Feature request

https://3v4l.org/32UWR

if a string type key `$k` is `$k === (string) (int) $k`, then the key is evaluated/stored as an integer

if a key type is float, then the key is evaluated/stored as an integer

From this feature request rule, I would expect the following fix:
```diff
-var_export(['1' => '1', 2.1 => '2.1']);
+var_export([1 => '1', 2 => '2.1']);
```

**Comment by mvorisek** [comment]
I propose a `array_key` rule.

I can also remove the keys if not needed, examples:
```diff
-[0 => 'foo', 1 => 'bar']
+['foo', 'bar']
```
```diff
-[1 => 'foo', 2 => 'bar']
+[1 => 'foo', 'bar']
```

**Comment by julienfalque** [comment]
IMO that would be two separate rules but I'd be interested in having them :+1:

**Comment by VincentLanglet** [comment]
> ```diff
> -var_export(['1' => '1', 2.1 => '2.1']);
> +var_export([1 => '1', 2 => '2.1']);
> ```

This might be interesting, but I would only touch the string keys.
Passing a boolean or a float as array_key should be a come smell and I would avoid to fix it automatically to let tools like phpstan report this as an error, because maybe the right fix won't be juste a cast.

> ```diff
> -[0 => 'foo', 1 => 'bar']
> +['foo', 'bar']
> ```
> 
> ```diff
> -[1 => 'foo', 2 => 'bar']
> +[1 => 'foo', 'bar']
> ```

I would only touch the list (first example).

Mixing value with and without keys shouldn't be recommended. It's confusing and promote errors, like
```
> [1 => 'foo', 'bar', 2 => 'baz']
```

**Comment by mvorisek** [comment]
Fixing `['1' => 1]` to `[1 => 1]` seems like a very well reasoned feature request and the stale bot should never kick in again.

**Comment by Wirone** [comment]
Personally I don't see much value in this. Using float as a key is deprecated (triggers "Deprecated: Implicit conversion from float ... to int loses precision") and will cause error in the future. Using numeric key as a string maybe is not elegant, but works interchangeably with integers (`$a = ['2' => 'arr']` and then `$a[2]` gives you `arr`). I don't see a point in investing time in this, but I'll keep it for now - let's see if someone picks it up 🙂.

**Comment by mvorisek** [comment]
Let's start simple.

```
$v = [
    0 => [
        0 => 'foo',
        1 => [],
        2 => [],
    ],
];
```

This is for example a format produced by `var_export()`.

should be definitely fixed to:

```
$v = [
    [
        'foo',
        [],
        [],
    ],
];
```

**Comment by mvorisek** [comment]
not stale

**Comment by mvorisek** [comment]
Please keep this issue open, the impl. is actually quite easy.

**Comment by Wirone** [comment]
@mvorisek The [initial proposal](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6617#issue-1360530808) was addressed [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6617#issuecomment-1684482603) and I don't think we should work on this. However, [this one](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6617#issuecomment-1788988427) is OK for me, but IMHO it requires new issue with clear DoD (this issue should have been created as a "Feature idea" discussion).
