### ISSUE TITLE
how to auto import, explicit import class that in same namespace / directory?

### ISSUE THREAD

**Issue by erlangparasu** [PHP-CS-Fixer/PHP-CS-Fixer#6625]
## Support question

how to auto import, explicit import class that in same namespace / directory?
thanks

**Comment by erlangparasu** [comment]
For example, files directory look like this:
```
- app/
    - Book.php
    - KlassA.php
```

Before format:
```php
namespace App;

// <-- no use stmt here

class KlassA {
    public function createFirstBook()
    {
        $book = new Book();
    }
}
```

Expectation after format:
```php
namespace App;

use App\Book; // <-- please make phpcsfixer add this line

class KlassA {
    public function createFirstBook()
    {
        $book = new Book();
    }
}
```

**Comment by Wirone** [comment]
I believe there's no need for such import. QA tools or IDEs would rather report such unnecessary imports, like PHPStorm does:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/600668/224177424-d5010237-35bc-4ca2-b65e-7eca5581ea04.png">

I'm going to close this one, @erlangparasu if you still need to discuss it, please use [Discussions](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions) instead.
