### ISSUE TITLE
Curly Braces Position Fixer bug

### ISSUE THREAD

**Issue by kayw-geek** [PHP-CS-Fixer/PHP-CS-Fixer#6641]
The bug recurrent in the following:

```php
<?php
    class Foo
    {
    public function test()
    { 
    }
    }
```
it will be fixed before v3.10.0, but it doesn't fix now.

#4884 
I think it may have something to do with this change.

**Comment by kayw-geek** [comment]
@julienfalque

**Comment by julienfalque** [comment]
I tried running `braces` rule on your code sample on latest `master` and on `v3.0.0` and I didn't notice any difference. In both cases, the code was fixed to:
```php
<?php
    class Foo
    {
        public function test()
        {
        }
    }
```
Are you sure there was a change with `v3.10.0`?

Note that removing the extra indentation level was never supported by `braces` and since we are about to deprecate the rule, it is unlikely to change. However, the new `statement_indentation` rule does support that so you can switch to it to get your code fixed to:
```php
<?php
class Foo
{
    public function test()
    {
    }
}
```

**Comment by kayw-geek** [comment]
> I tried running `braces` rule on your code sample on latest `master` and on `v3.0.0` and I didn't notice any difference. In both cases, the code was fixed to:
> 
> ```
> <?php
>     class Foo
>     {
>         public function test()
>         {
>         }
>     }
> ```
> 
> Are you sure there was a change with `v3.10.0`?
> 
> Note that removing the extra indentation level was never supported by `braces` and since we are about to deprecate the rule, it is unlikely to change. However, the new `statement_indentation` rule does support that so you can switch to it to get your code fixed to:
> 
> ```
> <?php
> class Foo
> {
>     public function test()
>     {
>     }
> }
> ```



```php
// before
                class Foo {

                public function foo() {

                    if (true)
                    {

                        echo "foo";

                    }

                }

                }

// after fix

                class Foo
                {

                public function foo()
                {

                    if (true) {

                        echo "foo";

                    }

                }

                }'

```

**Comment by kayw-geek** [comment]
> I tried running `braces` rule on your code sample on latest `master` and on `v3.0.0` and I didn't notice any difference. In both cases, the code was fixed to:
> 
> ```
> <?php
>     class Foo
>     {
>         public function test()
>         {
>         }
>     }
> ```
> 
> Are you sure there was a change with `v3.10.0`?
> 
> Note that removing the extra indentation level was never supported by `braces` and since we are about to deprecate the rule, it is unlikely to change. However, the new `statement_indentation` rule does support that so you can switch to it to get your code fixed to:
> 
> ```
> <?php
> class Foo
> {
>     public function test()
>     {
>     }
> }
> ```

Oh, sorry, I got the use case wrong. please looking latest cases.

**Comment by kayw-geek** [comment]
@julienfalque

**Comment by Wirone** [comment]
Hey!

Thanks for your report.

We identified that `braces` fixer is too complex and has too many responsibilities. With that, [we decided to deprecate it](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/4885).

That also means that we will not be extending, changing the behaviour or fixing anything around braces fixer. Please, use [replacement rules](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/braces.rst#this-rule-is-deprecated-and-will-be-removed-on-next-major-version) instead.

If you see the issue that you reported to be present in one of the replacement rules, please report a new issue.

Big thanks!
