### ISSUE TITLE
Rules `braces, method_argument_space` keeps being re-applied

### ISSUE THREAD

**Issue by mathieuimbert** [PHP-CS-Fixer/PHP-CS-Fixer#6650]
## Bug report

- Version affected: from v3.9.0
- Tested int v3.8.0 and it does not happen

I found a file (it's a legacy view file) where php-cs-fixer will keep adding spaces to method (`Ui::fieldRenderer`) parameters every time it runs.

Here's the command:

```
vendor/bin/php-cs-fixer fix edit.php -vvv --diff
PHP CS Fixer 3.11.0 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.30
Loaded config default.
Using cache file ".php-cs-fixer.cache".
F                                                                                                                                                                                   1 / 1 (100%)
Legend: .-no changes, F-fixed, S-skipped (cached or empty file), I-invalid file syntax (file ignored), E-error
   1) edit.php (braces, method_argument_space)
      ---------- begin diff ----------
--- /srv/drive/www/ttc/protected/edit.php
+++ /srv/drive/www/ttc/protected/edit.php
@@ -5,7 +5,7 @@
 ) ?>
     <div>
         <?= Ui::fieldRenderer([
-                'type' => "list",
-            ]) ?>
+                    'type' => "list",
+                ]) ?>
     </div>
 </div>

      ----------- end diff -----------
```

### Code snippet that reproduces the problem

```
<div>
    <?= $helper->getDropDown(
    "item[$i][idbillitem]",
    $item->idbillitem
) ?>
    <div>
        <?= Ui::fieldRenderer([
            'type' => "list",
        ]) ?>
    </div>
</div>
```

Note that if I modify the first line format, then the bug doesn't occur. For instance:

```
<div>
<?= $helper->getDropDown(
    "item[$i][idbillitem]",
    $item->idbillitem
) ?>
```

or

```
<div>
    <?= $helper->getDropDown("item[$i][idbillitem]", $item->idbillitem) ?>
```

It's quite low priority for us since there is a workaround and it only seems to happen in legacy template files, but others might have the same issue.

**Comment by driehle** [comment]
I can confirm this. Seems to happen mostly in mixed HTML/PHP files. There are numerous issues already:

- #6470
- #6513
- #6521
- #6550

This has all started with the 3.9.0 release and since then everything is broken. :-\

**Comment by scsmash3r** [comment]
Confirming the same issue with mixed content.

**Comment by yeroon** [comment]
Same issue here with PHP 8.0 and php-cs-fixer v3.9.1 and higher. A minimal php file to reproduce looks like this (A php file, with an open tag and a space on a blank line):

```
<?php
 
```

**Comment by driehle** [comment]
@keradus @vitvavra @julienfalque @mathieuimbert 

Sorry to bother you, but could I bring your attention to this issue? It seems like there are three open tickets (#6470, #6521, #6550) all refereing to the same bug introduced in 3.9.0, which still occurs in the latest 3.14.2.

**Comment by keradus** [comment]
sure thing. it took a long indeed, but here we go

**Comment by keradus** [comment]
Hey!
Thanks for your report.

We identified that `braces` fixer is too complex and has too many responsibilities. With that, we decided to **deprecate** it [ref #4885].

That also means that we will not be extending, changing the behaviour or fixing anything around `braces` fixer. Please, use [replacement rules](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/braces.rst#this-rule-is-deprecated-and-will-be-removed-on-next-major-version) instead.

If you see the issue that you reported to be present in one of the replacement rules, please report a new github issue.

Big thanks!
