### ISSUE TITLE
`no_spaces_after_function_name` treats `list` intrinsic as function

### ISSUE THREAD

**Issue by Strongleong** [PHP-CS-Fixer/PHP-CS-Fixer#6654]
Company that I work in wants space between `list` intrinsic and `(` symbol. But when I apply fixer to my code it removes the spaces, and I must re-add them by hands.

Also it would be nice to have rule like `list_space` and `array_space` where I can specify if I need space and where I need it.

Minimal PhpCsFixer config:

```php
<?php

$finder = PhpCsFixer\Finder::create()->in(__DIR__);
My compan

return (new PhpCsFixer\Config())
    ->setRules([
        'no_spaces_after_function_name' => true,
    ])
    ->setFinder($finder);
```

Code
  ```php
  <?php

  $array = array('a' => 'b');
  list ($a) = $array;
  ```

After aplying fixer: 
 - Expected: nothing changes
 - Result:
  ```php
  <?php

  $array = array('a' => 'b');
  list($a) = $array;
  ```

P.S. Sorry for bad English 😅

**Comment by kubawerlos** [comment]
It works as [expected](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.16.0/tests/Fixer/FunctionNotation/NoSpacesAfterFunctionNameFixerTest.php#L60-L77).
