### ISSUE TITLE
Exception when directory does not exist

### ISSUE THREAD

**Issue by RuckieOfficial** [PHP-CS-Fixer/PHP-CS-Fixer#6676]
The issue is that if watching multiple directories via the Finder class.
If one does not exist, the Finder will throw an exception and the fixer will die.

Is there a possibility of adding an option to "skip if directory does not exist" so it doesn't kill the fixer if one of the directories does not exist? 

```
$finder = Finder::create()
    ->in([
        __DIR__ . '/web/app/mu-plugins/ys-*',
        __DIR__ . '/web/app/plugins/ys-*'
    ])
    ->name('*.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);
```

![exception](https://user-images.githubusercontent.com/43410493/199715242-4772afa2-5a66-4948-a105-254ef17350db.png)

**Comment by kubawerlos** [comment]
This is something to be handled by the user. You can loop through the directories, check if they exist and add the to finder, and then add the finder to the config.
