### ISSUE TITLE
fully_qualified_strict_types should be considered risky or updated

### ISSUE THREAD

**Issue by mjedlick2** [PHP-CS-Fixer/PHP-CS-Fixer#6678]
## Bug report
fully_qualified_strict_types rule replaces namespace even if the resulting class name is overriden by the `use` command. Result could be a PHP error.

### Code snippet that reproduces the problem
```
namespace A\B;

require "ABClazz.php";
require "AClazz.php";

use A\Clazz;

class Service
{
    public function __construct(
        private \A\B\Clazz $clz
    ) {
    }
}

new Service(new \A\B\Clazz());
```
ABClazz.php:
```
namespace A\B;
class Clazz {}
```

AClazz.php:
```
namespace A;
class Clazz {}
```

Result after php-cs-fixer:
```diff
    public function __construct(
-        private \A\B\Clazz $clz
+        private Clazz $clz
    ) {
```
Namespace in Service constructor is removed so Clazz from A\Clazz is used instead of A\B\Clazz. It leads to PHP error when making new instance of Service. I guess it should be considered there is a namespace conflict and replacement should be avoided. Or this directive should be considered risky if it can lead to error.

**Comment by kubawerlos** [comment]
Of course, this is a bug, marking fixer risky because it breaks code is nonsense.
