### ISSUE TITLE
PHPMD error `MissingImport  Missing class import via use statement`

### ISSUE THREAD

**Issue by talhaamir4130** [PHP-CS-Fixer/PHP-CS-Fixer#6683]
## Bug report

Version:
```
PHP CS Fixer 3.13.0 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.33
```

Config:
```
<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude('var')
;

return (new PhpCsFixer\Config())
    ->setRules([
        '@Symfony' => true,
    ])
    ->setFinder($finder)
;

```

### Code snippet that reproduces the problem
```
<?php

namespace App\Service;

class SomeClass
{
    public function randomFunction(string ?$variable): self
    {
        if (is_null($variable)) {
            throw new \RuntimeException('Variable can not be null');
        }

        return $this;
    }
```

Here phpmd is throwing error `MissingImport  Missing class import via use statement` which `\RuntimeException`.

**Comment by julienfalque** [comment]
Did you mean to report this on [PHPMD's repository](https://github.com/phpmd/phpmd)?

**Comment by talhaamir4130** [comment]
The latest version of phpcs-fixer creates this error.

**Comment by julienfalque** [comment]
What do you mean? What command do you run to get this error?

**Comment by matiascaniete** [comment]
I had the same problem after updating php-cs-fixer. @talhaamir4130 you can fix this "error" by adding the rule **global_namespace_import** in the config file:

```php
// ...
->setRules([
        '@Symfony' => true,
        'concat_space' => ['spacing' => 'one'],
        'global_namespace_import' => true,
    ])
// ...
```

Source:
https://mlocati.github.io/php-cs-fixer-configurator/#version:3.13|fixer:global_namespace_import
