### ISSUE TITLE
README > Installation : "--parent" argument of mkdir does not exist on macOS

### ISSUE THREAD

**Issue by MTindev** [PHP-CS-Fixer/PHP-CS-Fixer#6684]
## Bug report

Hello,

In the README file, in the section _Documentation > Installation_, it is expected that the given commands make it easy to perform the installation.

However, in macOS, the `--parent` argument does not exist for the `mkdir` command. Only the `-p` argument exists.

### Code snippet that reproduces the problem

```sh
$ mkdir --parents tools/php-cs-fixer

# returns :
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory_name ...
```

### What is expected ?

To facilitate the process on all platforms (and avoid an error on macOS), I suggest :

```
mkdir -p tools/php-cs-fixer
```

**Comment by julienfalque** [comment]
👍

Do you mind creating a PR with this change?

**Comment by MTindev** [comment]
Hi @julienfalque,

I'm OK and dit it it pull request : #6689 
Hopefully it will meet your expectations.
