### ISSUE TITLE
Output for dry-run containing an error message and line/col number

### ISSUE THREAD

**Issue by danrot** [PHP-CS-Fixer/PHP-CS-Fixer#6686]
## Feature request

I would like to execute a command like `php-cs-fixer fix --dry-run --format=json` and receive a message explaining the coding style violation including the line and column number in which it appeared. That would allow me to use it as a linter in neovim.

Is that something that is already possible and I am still missing something, or is that something that would have to be implemented?

**Comment by d8vjork** [comment]
Check #3990

**Comment by Wirone** [comment]
Hi @danrot it's not possible to provide such information, please read [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7171#issuecomment-1645441674) related to same concept but for Gitlab. I'm going to close this, but feel free to let us know if anything should be done here.
