### ISSUE TITLE
`declare_strict_types`: skip files that don't contain any function call

### ISSUE THREAD

**Issue by julienfalque** [PHP-CS-Fixer/PHP-CS-Fixer#6688]
As [suggested by @heiglandreas](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/2062#issuecomment-1313235270), `declare(strict_types=1)` is only relevant for files that contain at least one function call. We could add an option to skip files that don't contain any. Maybe we can even remove the statement in such case.

**Comment by keradus** [comment]
Myself, 👎🏻 .
IMHO, we should aim for unification and standardization - having a declaration always, even if not technically needed, is no-brainer, rather than having it conditionally, always juggling with which file "header" to use.

**Comment by kubawerlos** [comment]
Agree with @keradus - if we would like to go with strategy "only when it is relevant" then in the file like this:
```php
<?php
class Foo
{
    private const MAP = [
        'letter' => 'abc',
        'number' => 123,
    ];

    public function addData(int $i, string $c) : array
    {
        $x = self::MAP;
        $x['letter'] += $i;
        $x['number'] .= $c;

        return $x;
    }
}
```
we don't have strict typing enabled.

**Comment by julienfalque** [comment]
Fair enough, closing then. Thanks for your feedback :)
