### ISSUE TITLE
Blank line after `declare(strict_types=1);`

### ISSUE THREAD

**Issue by Jamesking56** [PHP-CS-Fixer/PHP-CS-Fixer#6692]
## Feature request

Ability to enforce a blank line after `declare(strict_types=1);` line.

From:

```php
<?php

declare(strict_types=1);
use Some\Class;
```

To:

```php
<?php

declare(strict_types=1);

use Some\Class;
```

**Comment by Wirone** [comment]
@Jamesking56 there's [single_blank_line_before_namespace](https://cs.symfony.com/doc/rules/namespace_notation/single_blank_line_before_namespace.html#rule-single-blank-line-before-namespace) that would do exactly the same, but from the other side 😉.
