### ISSUE TITLE
ordered_imports should be considered risky

### ISSUE THREAD

**Issue by Neo-Oli** [PHP-CS-Fixer/PHP-CS-Fixer#6697]
## Bug report

`ordered_imports` can actually break your code, if it is particularly bad code:

### Code snippet that reproduces the problem

```php
<?php
use B;
$foo=new class_from_B();
use A; 
```
This will be turned into the following, which is now broken.

```php
<?php
use A;
$foo=new class_from_B();
use B; 
```

I think this is related to https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/3586

**Comment by keradus** [comment]
> if it is particularly bad code

oh my... I enjoy this comment!

IMHO we should consider to fix only first group (imports before any logic) and not mark as risky, wdyt?

**Comment by Neo-Oli** [comment]
@keradus That would work too, of course. I just thought that maybe it is really hard, considering how long https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/3586 (whose suggestion would also fix my issue) has been open. If it can be easily fixed, this would be preferable, but if it isn't easy or no one has the time or will to do it, it should be marked risky in the interim.

**Comment by keradus** [comment]
I think its a fair point.

Are you open to create a PR when we either do the fix or mark it as risky (with description "why" and mentioned what will be solution to un-risk it) ?

**Comment by Neo-Oli** [comment]
> Are you open to create a PR when we either do the fix or mark it as risky (with description "why" and mentioned what will be solution to un-risk it) ?

@keradus Sorry, I don't really know what you mean here. If you mean, that I should create a PR to fix it I have to sadly decline. This is not really my wheelhouse. I'm just a user, at least for this one ;) .

**Comment by keradus** [comment]
yeah, that's the part I was suggesting. no worry, we will see what we can do, but taking 3586 as example, this issue looks to not be the biggest need by community :(

if anyone eager to take over, please go ahead!
