### ISSUE TITLE
Indentation fix is broken in 3.13

### ISSUE THREAD

**Issue by emulgeator** [PHP-CS-Fixer/PHP-CS-Fixer#6699]
## Bug report

PHP CS Fixer 3.13.0 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.0.22

### Code snippet that reproduces the problem

Run a simple PSR12 fix on the following file

  ```php
<?php

declare(strict_types=1);

class Test
{
    public function test()
    {
        return '';
    }

public function test2()
{
    return '';
}

    public function test3()
    {
        return '';
    }

        public function test4()
        {
            return '';
        }
}

  ```

The indentation of the methods should be fixed, but when the first method is aligned properly php-cs-fixer wont fix the others anymore.

**Comment by Wirone** [comment]
It was fixed in #6978 (Fixer v3.18+).
