### ISSUE TITLE
PER ruleset is misnamed

### ISSUE THREAD

**Issue by Crell** [PHP-CS-Fixer/PHP-CS-Fixer#6700]
It's unfortunately a common confusion, but calling the latest ruleset "PER" is confusing and misleading.  PER stands for "PHP Evolving Recommendation".  And, there will be several of them.  What this ruleset follows is the Coding Style PER, which we've been commonly abbreviating "PER-CS".  It would be like referring to the older guidelines as "PSR", which (although people did it) is equally wrong.

It would be helpful if this project would use the proper name to minimize confusion in the future.  (Possibly with PER as an deprecated alias for it to avoid a BC break.)

**Comment by keradus** [comment]
Hey, big thanks for pointing this out, @Crell !

As you already have a clear idea how it should look, what would you say about dropping a PR to fix the concern?

**Comment by Crell** [comment]
Well, I'm not sure all the places that would be impacted.  Is it just renaming the one ruleset file (and maybe adding another)?

**Comment by keradus** [comment]
Indeed, I think we can mimic existing one ( https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/RuleSet/Sets/PERSet.php ) and have the existing one simply including the one with a proper name.

Also, right now, I don't think we have a good way of marking the ruleset as deprecated other than adding annotation.

**Comment by jrmajor** [comment]
FYI this was discussed in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6545#discussion_r942502314.

**Comment by Crell** [comment]
I suppose another interesting question is if it should include a version number.  Since PER-CS 1.0 is basically PSR-12, but 1.1 (coming soon, I swear) will include a lot more stuff, and there will be a 1.2 at some point as well.  Do we want those separately listed so people can adopt new versions manually, or automatically?

Perhaps go all-in on aliasing.  `PERCS1.0`, `PERCS1.1`, and `PERCS` is an alias to whichever is latest.  That lets people "tag" to a specific release or get auto-updates whenever there's a new release.  Sound reasonable?

**Comment by SpacePossum** [comment]
Wanted to ask and it might very well be because my English isn't the greatest, but IIUC PER CS2 states there must not be a empty line @ EOF, contrary to what PSR2 (/12) states?

PSR2
https://www.php-fig.org/psr/psr-2/#22-files
>All PHP files MUST end with a single blank line.

PER CS 2.0
https://www.php-fig.org/per/coding-style/#22-files
>All PHP files MUST end with a non-blank line, terminated with a single LF.

should the set be updated in this project to reflect this (.i.e. remove the rule `single_blank_line_at_eof` and create/update a new one to remove empty line @ EOF when applicable)?

Also, on https://www.php-fig.org/psr/ PSR2 is listed as deprecated, will PSR1 and PSR12 be deprecated soon as well now PER CS2 is released?

**Comment by jrmajor** [comment]
@SpacePossum My understanding is that it's the same: LF creates a new line, so a “non-blank line terminated with LF” is the same as a non-blank line with a blank line after it.

**Comment by Crell** [comment]
PSR1 is still valid.  PSR-12 should be marked deprecated though, you're right.

The wording change, I think, happened in PSR-12, but I don't recall exactly.  But yes, it's not really a change as much as clarification as to what "blank line" means.  It means a single LF character, aka `\n`.

**Comment by SpacePossum** [comment]
Thank you both for explaining it to me, very clear :+1:  : )
