### ISSUE TITLE
php-cs-fixer 3.13.0 does not run with php 8.2

### ISSUE THREAD

**Issue by chenrui333** [PHP-CS-Fixer/PHP-CS-Fixer#6704]
## Bug report

I can see the support message showing only supporting up to 8.1.x
```
  ==> /opt/homebrew/Cellar/php-cs-fixer/3.13.0/bin/php-cs-fixer fix test.php
  PHP needs to be a minimum version of PHP 7.4.0 and maximum version of PHP 8.1.*.
  Current PHP version: 8.2.0.
  To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
  If you use PHP version higher than supported, you may experience code modified in a wrong way.
  Please report such cases at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer .
```

Just log an issue to raise it up. Thanks!

relates to Homebrew/homebrew-core#117647

**Comment by keradus** [comment]
As you see, PHP CS Fixer is not ready to run on 8.2.
Please be aware that PHP CS Fixer is not a random cli package that executes on a vast amounts of envs, but that needs to understand the code syntax, and each PHP x.y version bringing new syntax.
You may follow the guidance of using `PHP_CS_FIXER_IGNORE_ENV` to run Fixer anyway - if so, please raise the issues you found on 8.2

Same time, we are already aware of some of them - please do not hesitate to help solving those!
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues?q=is%3Aissue+is%3Aopen+8.2+label%3Atopic%2FPHP8.2

For the time being, I close this thread as we are aware that 8.2 is not supported and there are dedicated tickets to respective parts of it.

**Comment by chenrui333** [comment]
Yeah, I am aware of that bucket of issues. I was mostly raising this ticket for some quick discussion. Thanks @keradus!

**Comment by 8ctopus** [comment]
For those like me looking how to run PHP CS Fixer using the `PHP_CS_FIXER_IGNORE_ENV ` flag, here's the answer:

PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix app

**Comment by Fuck4ik** [comment]
For those like me looking how to run PHP CS Fixer using `IDE quality tool`:
`bin/phpstorm-csfixer.php`
```
#!/usr/bin/env php
<?php

putenv('PHP_CS_FIXER_IGNORE_ENV=1');
include __DIR__ . '/../vendor/bin/php-cs-fixer';
```
