### ISSUE TITLE
no_superfluous_phpdoc_tags gets confused by trailing comma after variable name

### ISSUE THREAD

**Issue by jack-worman** [PHP-CS-Fixer/PHP-CS-Fixer#6708]
## Bug report

`no_superfluous_phpdoc_tags` is removes `@param` if it has a trailing comma after the variable name. I assume the problem is that it considers the comma part of the name and cannot find it in the method signature.

Versions:
```
PHP CS Fixer 3.13.0 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.13
```

Config:
```php
return (new PhpCsFixer\Config())
    ->setFinder($finder)
    ->setRiskyAllowed(true)
    // https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/index.rst
    ->setRules([
        'no_superfluous_phpdoc_tags' => ['allow_mixed' => true],
        'no_empty_phpdoc' => true,
        'phpdoc_trim' => true,
    ]);
```

### Code snippet that reproduces the problem

```php
    /**
     * @param non-empty-string $fullyQualifiedClassName, e.g. '\Psalm\Internal\Analyzer\NamespaceAnalyzer'
     */
    public static function getNameSpaceRoot(string $fullyQualifiedClassName): void
    {
    }
```

**Comment by kubawerlos** [comment]
@jack-worman how come the comma after the name is correct? If so, what about dots, semicolons, and other characters?

Why do you have such a construct anyway? It is not allowed according to https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md
