### ISSUE TITLE
[ErrorException] Undefined index: type

### ISSUE THREAD

**Issue by genius4339** [PHP-CS-Fixer/PHP-CS-Fixer#6709]
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/0ad2f84130e8fec8655682532e6d39553054831c/src/Doctrine/Annotation/Tokens.php#L72

 [ErrorException] Undefined index: type 
please fix it

**Comment by kubawerlos** [comment]
Hello @genius4339 and welcome to the open source community where everyone is welcome to create a pull request with changes, e.g. with a bufix for an issue.

Would you like to give it a try and raise a fixing PR? We would be glad to review and merge it!

**Comment by genius4339** [comment]
> Hello @genius4339 and welcome to the open source community where everyone is welcome to create a pull request with changes, e.g. with a bufix for an issue.
> 
> Would you like to give it a try and raise a fixing PR? We would be glad to review and merge it!

https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6710/commits/5694dd6e413df61c2d612a504dc998c4542fd5e3

**Comment by genius4339** [comment]
> Hello @genius4339 and welcome to the open source community where everyone is welcome to create a pull request with changes, e.g. with a bufix for an issue.
> 
> Would you like to give it a try and raise a fixing PR? We would be glad to review and merge it!

this is my pr , please review it. Thank You.
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6710/commits/5694dd6e413df61c2d612a504dc998c4542fd5e3

**Comment by julienfalque** [comment]
This looks like #6706. Did you try upgrading `doctrine/annotations`?

**Comment by genius4339** [comment]
> This looks like #6706. Did you try upgrading `doctrine/annotations`?



> This looks like #6706. Did you try upgrading `doctrine/annotations`?

thank you! when i upgrade doctrine/annotations, the exception is resovled~
