### ISSUE TITLE
Add `.phar` to the filename in the shim release

### ISSUE THREAD

**Issue by gjuric** [PHP-CS-Fixer/PHP-CS-Fixer#6711]
## Feature request

It would be nice if the [shim](https://github.com/PHP-CS-Fixer/shim) file was called `php-cs-fixer.phar` instead of `php-cs-fixer` so PhpStorm parses the context of the phar file and does not complain when working on `.php-cs-fixer.dist.php` that `PhpCsFixer\Finder` or `PhpCsFixer\Config` does not exist. Also auto-complete for those classes would then work as well.

If you want to keep the `vendor/bin/php-cs-fixer` file maybe you could do the same thins as phpstan does, see [here](https://github.com/phpstan/phpstan/blob/bf4d335fbbba4dbb98dac4bd82fcf0fa03907e7d/composer.json#L12-L13) and [here](https://github.com/phpstan/phpstan/blob/bf4d335fbbba4dbb98dac4bd82fcf0fa03907e7d/phpstan).

**Comment by keradus** [comment]
@gjuric , idea sounds ok for me! would you mind to open a PR @ https://github.com/PHP-CS-Fixer/shim ?

**Comment by gjuric** [comment]
Done: https://github.com/PHP-CS-Fixer/shim/pull/2

**Comment by localheinz** [comment]
Thank you, @gjuric and @keradus!
