### ISSUE TITLE
[wrapper-only] Fatal error in v3.13.1 but not in v3.13.0

### ISSUE THREAD

**Issue by bilogic** [PHP-CS-Fixer/PHP-CS-Fixer#6715]
## Bug report

```
Loaded config Laravel from "d:/.php-cs-fixer.php".
PHP Fatal error:  Uncaught TypeError: PhpCsFixer\Console\Report\FixReport\ReportSummary::__construct(): Argument #4 ($memory) must be of type int, bool given, called in D:\Users\User\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\Command\FixCommand.php on line 318 and defined in E:\projectx\www\stage\example\example-project\vendor\friendsofphp\php-cs-fixer\src\Console\Report\FixReport\ReportSummary.php:46
Stack trace:
#0 D:\Users\User\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\Command\FixCommand.php(318): PhpCsFixer\Console\Report\FixReport\ReportSummary->__construct()
#1 D:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php(291): PhpCsFixer\Console\Command\FixCommand->execute()
#2 D:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Application.php(998): Symfony\Component\Console\Command\Command->run()
#3 D:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#4 D:\Users\User\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\src\Console\Application.php(94): Symfony\Component\Console\Application->doRun()
#5 D:\Users\User\AppData\Roaming\Composer\vendor\symfony\console\Application.php(171): PhpCsFixer\Console\Application->doRun()
#6 D:\Users\User\AppData\Roaming\Composer\vendor\friendsofphp\php-cs-fixer\php-cs-fixer(115): Symfony\Component\Console\Application->run()
#7 {main}
  thrown in E:\projectx\www\stage\example\example-project\vendor\friendsofphp\php-cs-fixer\src\Console\Report\FixReport\ReportSummary.php on line 46
```
I get the above fatal error on v3.13.1, but not v3.13.0, but I'm in the middle of something, hope the above is helpful enough, otherwise will update this as I get more information. 

### Code snippet that reproduces the problem

On first glance, it doesn't look like snippet related to me.

Thank you.

**Comment by keradus** [comment]
Hey, do you see this issue related to #6718 , or sth different?

Can you share CLI command that you run and the config file of yours? [you can skip the enabled rules, but would be beneficial to see the rest].
Or publish that "example-project" as mini github repo

**Comment by keradus** [comment]
@bilogic , it looks like you are using an unofficial wrapper around PHP CS Fixer that is playing with the internal logic of PHP CS Fixer and for that is receptive for such issues.

When using wrapper, please report to wrapper creators first.

Here, it looks like they patched this issue for now
https://github.com/laravel/pint/pull/133/files#r1060209503

**Comment by bilogic** [comment]
@keradus I'm not using Pint. I'm using PHP CS Fixer as-is, this is my config. If there is a new release, I can test if this issue is still happening.

```
use Jubeki\LaravelCodeStyle\Config;
use PhpCsFixer\Finder;

$base_path = dirname($path);

$files[] = '/vendor/autoload.php';
$files[] = '/bootstrap/app.php';

foreach ($files as $file) {
    $required = $base_path.$file;
    if (file_exists($required)) {
        require $required;
        break;
    }
}

return (new Config())
    ->setFinder(Finder::create())
    ->setRules([
        '@Laravel' => true,
        'braces' => true,
        'array_indentation' => true,
        'single_line_comment_style' => false,
    ]);
```

**Comment by keradus** [comment]
@bilogic , I tried to reproduce your problem but failed.
I installed v3.13.1 and used exactly your config, guessed the command you run and... it works.
You can find my attempt here: https://github.com/keradus/PHP-CS-Fixer-repro-cases/tree/6715
Please raise a PR there that would cause `composer repro` command to reproduce issue you are reporting.

<img width="1019" alt="Screenshot 2023-01-03 at 11 55 31" src="https://user-images.githubusercontent.com/2716794/210343886-a2923df8-ed3b-40c9-b44e-3f755a297f5c.png">

**Comment by keradus** [comment]
only the shortcut for the command, I'm trying to guess what command you are running
https://github.com/keradus/PHP-CS-Fixer-repro-cases/blob/6715/composer.json#L14

feel free to adjust the command to one you are using

**Comment by bilogic** [comment]
```
Loaded config Laravel from "/home/dv1/code-server/projects/example/current/.php-cs-fixer.php".
PHP Fatal error:  Uncaught TypeError: PhpCsFixer\Console\Report\FixReport\ReportSummary::__construct(): Argument #4 ($addAppliedFixers) must be of type bool, int given, called in phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/src/Console/Command/FixCommand.php on line 322 and defined in /home/dv1/code-server/projects/example/example-project/vendor/friendsofphp/php-cs-fixer/src/Console/Report/FixReport/ReportSummary.php:44
Stack trace:
#0 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/src/Console/Command/FixCommand.php(322): PhpCsFixer\Console\Report\FixReport\ReportSummary->__construct()
#1 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/vendor/symfony/console/Command/Command.php(298): PhpCsFixer\Console\Command\FixCommand->execute()
#2 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#3 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#4 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/src/Console/Application.php(94): Symfony\Component\Console\Application->doRun()
#5 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/vendor/symfony/console/Application.php(171): PhpCsFixer\Console\Application->doRun()
#6 /home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar(102): Symfony\Component\Console\Application->run()
#7 {main}
  thrown in /home/dv1/code-server/projects/example/example-project/vendor/friendsofphp/php-cs-fixer/src/Console/Report/FixReport/ReportSummary.php on line 44
```
Some additional logs as I'm trying to figure out what is wrong.

**Comment by bilogic** [comment]
@keradus this is the command that VSCode is running
```
[
  "/home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar",
  "fix",
  "--using-cache=no",
  "--format=json",
  "--config=/home/dv1/code-server/projects/example/current/.php-cs-fixer.php",
  "--path-mode=override",
  "/tmp/pcf-tmp0.8820509050331113/User.php"
]
```

**Comment by bilogic** [comment]
@keradus 

I think this the clearest way I can show there are no wrappers, same exception happening in 3.13.2

```BASH
# Bash command for php-cs-fixer 3.13.1

./php-cs-fixer.phar \
  fix \
  --using-cache=no \
  --format=json \
  --config=/home/dv1/code-server/projects/vxcharts/current/.php-cs-fixer.php \
  --path-mode=override \
  /home/dv1/code-server/projects/vxcharts/current/.php-cs-fixer.php
```


```PHP
// .php-cs-fixer.php
use Jubeki\LaravelCodeStyle\Config;
use PhpCsFixer\Finder;

$base_path = dirname($path);

$files[] = '/vendor/autoload.php';
$files[] = '/bootstrap/app.php';

foreach ($files as $file) {
    $required = $base_path.$file;
    if (file_exists($required)) {
        require $required;
        break;
    }
}

return (new Config())
    ->setFinder(Finder::create())
    ->setRules([
        '@Laravel' => true,
        'braces' => true,
        'array_indentation' => true,
        'single_line_comment_style' => false,
    ]);
```



```BASH
dv1@linuxdev:~/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal$ ./php-cs-fixer.phar
PHP CS Fixer 3.13.1 (78d2251) Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.13

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display help for the given command. When no command is given display help for the list command
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  describe     Describe rule / ruleset.
  fix          Fixes a directory or a file.
  help         Display help for a command
  list         List commands
  list-files   List all files being fixed by the given config.
  list-sets    List all available RuleSets.
  self-update  [selfupdate] Update php-cs-fixer.phar to the latest stable version.
```

```
# Output of php-cs-fixer 3.13.1

dv1@linuxdev:~/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal$ ./php-cs-fixer.phar fix --using-cache=no --format=json --config=/home/dv1/code-server/projects/vxcharts/current/.php-cs-fixer.php --path-mode=override /home/dv1/code-server/projects/vxcharts/current/.php-cs-fixer.php
Loaded config Laravel from "/home/dv1/code-server/projects/vxcharts/current/.php-cs-fixer.php".
PHP Fatal error:  Uncaught TypeError: PhpCsFixer\Console\Report\FixReport\ReportSummary::__construct(): Argument #4 ($addAppliedFixers) must be of type bool, int given, called in phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/src/Console/Command/FixCommand.php on line 323 and defined in /home/dv1/code-server/projects/vxcharts/vxcharts-project/vendor/friendsofphp/php-cs-fixer/src/Console/Report/FixReport/ReportSummary.php:44
Stack trace:
#0 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/src/Console/Command/FixCommand.php(323): PhpCsFixer\Console\Report\FixReport\ReportSummary->__construct()
#1 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/vendor/symfony/console/Command/Command.php(298): PhpCsFixer\Console\Command\FixCommand->execute()
#2 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#3 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#4 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/src/Console/Application.php(94): Symfony\Component\Console\Application->doRun()
#5 phar:///home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar/vendor/symfony/console/Application.php(171): PhpCsFixer\Console\Application->doRun()
#6 /home/dv1/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal/php-cs-fixer.phar(102): Symfony\Component\Console\Application->run()
#7 {main}
  thrown in /home/dv1/code-server/projects/vxcharts/vxcharts-project/vendor/friendsofphp/php-cs-fixer/src/Console/Report/FixReport/ReportSummary.php on line 44
dv1@linuxdev:~/code-server/user/extensions/junstyle.php-cs-fixer-0.3.8-universal$ 
```

**Comment by bilogic** [comment]
@keradus eventually, I switched to laravel/pint, which also relies on PHP-CS-Fixer. Thank you.

**Comment by keradus** [comment]
if issue is in Fixer, using wrapper will not solve the problem - could be wrapper is simply not yet using the version that introduced the problem.

could you create a PR against this branch, or create your own repo showing reproduction? https://github.com/keradus/PHP-CS-Fixer-repro-cases/tree/6715

by copy-pasting your command/lines, I see no issue raised.

**Comment by bilogic** [comment]
Hmm, do you consider jubeki as a wrapper? I had a very quick glance into his repository, too many files, decided not to read.

End of day, I just need my code to be styled, I did not go for pint because I was concerned it would introduced small changes everywhere. But when jubeki + Fixer crashed, I was left with the lesser evil of going with pint.

If jubeki is considered a wrapper, then I think it's most likely the culprit (Pint did not give me any crashes).

I will try to give you a conclusive answer if I can find some time. Thank you for the help.

**Comment by bilogic** [comment]
@keradus I cloned your repro repo, it ran without a hitch. Then I reinstalled 3.13.1 in my VSCode, no issues again this time.
I updated everything to 3.13.2 and no issues as well.

As of now, it has mysteriously gone away. I will put in more effort to trace it if it comes back via Pint. Thank you.

**Comment by bilogic** [comment]
@keradus ok, I have new insights:

> e:\temp\PHP-CS-Fixer-repro-cases>vendor\bin\php-cs-fixer fix --using-cache=no --format=json --config=e:/projectx/www/stage/bcr/bcr-project/.php-cs-fixer.php --path-mode=override e:\projectx\www\stage\bcr\bcr-project\.php-cs-fixer.php
> Loaded config Laravel from "e:/projectx/www/stage/bcr/bcr-project/.php-cs-fixer.php".
> PHP Fatal error:  Uncaught TypeError: PhpCsFixer\Console\Report\FixReport\ReportSummary::__construct(): Argument #4 ($addAppliedFixers) must be of type bool, int given, called in E:\temp\PHP-CS-Fixer-repro-cases\vendor\friendsofphp\php-cs-fixer\src\Console\Command\FixCommand.php on line 323 and defined in E:\projectx\www\stage\bcr\bcr-project\vendor\friendsofphp\php-cs-fixer\src\Console\Report\FixReport\ReportSummary.php:44
> Stack trace:
> #0 E:\temp\PHP-CS-Fixer-repro-cases\vendor\friendsofphp\php-cs-fixer\src\Console\Command\FixCommand.php(323): PhpCsFixer\Console\Report\FixReport\ReportSummary->__construct()
> #1 E:\temp\PHP-CS-Fixer-repro-cases\vendor\symfony\console\Command\Command.php(312): PhpCsFixer\Console\Command\FixCommand->execute()
> #2 E:\temp\PHP-CS-Fixer-repro-cases\vendor\symfony\console\Application.php(1022): Symfony\Component\Console\Command\Command->run()
> #3 E:\temp\PHP-CS-Fixer-repro-cases\vendor\symfony\console\Application.php(314): Symfony\Component\Console\Application->doRunCommand()
> #4 E:\temp\PHP-CS-Fixer-repro-cases\vendor\friendsofphp\php-cs-fixer\src\Console\Application.php(94): Symfony\Component\Console\Application->doRun()
> #5 E:\temp\PHP-CS-Fixer-repro-cases\vendor\symfony\console\Application.php(168): PhpCsFixer\Console\Application->doRun()
> #6 E:\temp\PHP-CS-Fixer-repro-cases\vendor\friendsofphp\php-cs-fixer\php-cs-fixer(102): Symfony\Component\Console\Application->run()
> #7 {main}
>   thrown in E:\projectx\www\stage\bcr\bcr-project\vendor\friendsofphp\php-cs-fixer\src\Console\Report\FixReport\ReportSummary.php on line 44
> 
> e:\temp\PHP-CS-Fixer-repro-cases>vendor\bin\php-cs-fixer fix --using-cache=no --format=json --config=e:/projectx/www/stage/bcr/.php-cs-fixer.php --path-mode=override e:\projectx\www\stage\bcr\.php-cs-fixer.php
> Loaded config Laravel from "e:/projectx/www/stage/bcr/.php-cs-fixer.php".
> {"files":[],"time":{"total":0.02},"memory":12}
> e:\temp\PHP-CS-Fixer-repro-cases>

```BASH
// exception
vendor\bin\php-cs-fixer fix --using-cache=no --format=json --config=e:/projectx/www/stage/bcr/bcr-project/.php-cs-fixer.php --path-mode=override e:\projectx\www\stage\bcr\bcr-project\.php-cs-fixer.php

// OK
vendor\bin\php-cs-fixer fix --using-cache=no --format=json --config=e:/projectx/www/stage/bcr/.php-cs-fixer.php --path-mode=override e:\projectx\www\stage\bcr\.php-cs-fixer.php
```

The difference being only the path. in `bcr-project`. Initial I thought it was due to `bcr-project` having a `vendor` folder, but that was not the case.

**Comment by keradus** [comment]
can you share as standalone repo or PR to my PHP-CS-Fixer-repro-cases repo? otherwise, if this issue will be limited only to your localhost, i don't think we will be able to fix it, especially when your commands are referring to paths outside of `cwd` and only you have insights whats in those files/folders

**Comment by bilogic** [comment]
@keradus yes, please bear with me, I'm working towards that and using this issue as a storage space for my findings. I'm quite tight on time and can only dig into this when the issue surfaces + my vendor repo contains info I can't share freely. In any case, I don't think vendor is the cause, as I removed it but the exception still surfaced.
