### ISSUE TITLE
Let `phpdoc_line_span` also handle inline `/** @var */` declarations

### ISSUE THREAD

**Issue by ruudk** [PHP-CS-Fixer/PHP-CS-Fixer#6726]
## Feature request

I configured `phpdoc_line_span` with:
```php
[
    'const' => 'multi',
    'method' => 'multi',
    'property' => 'multi',
]
```

It would be great if it could also handle inline phpdoc declarations like:
```php
/** @var Form $form */
$form = $this->createForm();
```

**Comment by devnix** [comment]
It's also transforming
```php
/** @var self<C> */
return new self();
```
into
```php
/* @var self<C> */
return new self();
```
and using php-cs-fixer with phpstan is quickly becoming cumbersome for these things!

**Comment by ruudk** [comment]
Still relevant.

**Comment by ruudk** [comment]
Still relevant.
