### ISSUE TITLE
Inconsistent PHP constraint version ^8.0 with PHP 8.2 error requirement message

### ISSUE THREAD

**Issue by Maxooo** [PHP-CS-Fixer/PHP-CS-Fixer#6728]
## Bug report

Making an upgrade from PHP 8.1 to PHP 8.2 leads to the following PHP CS Fixer error.

```
PHP needs to be a minimum version of PHP 7.4.0 and maximum version of PHP 8.1.*.
Current PHP version: 8.2.0.
To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
If you use PHP version higher than supported, you may experience code modified in a wrong way.
Please report such cases at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer .
```

As explained in the error, it's possible to ignore this requirement with the `PHP_CS_FIXER_IGNORE_ENV` environment variable but I don't think that this is something needed or recommendable. In fact PHP CS Fixer is marked compatible with PHP 8.2 with the following composer requirement `"php": "^7.4 || ^8.0",`.

If it's truely the case (I think it is), the test located in the `php-cs-fixer` file and which trigger the requirement message has to be updated :

https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/78d2251dd86b49c609a0fd37c20dcf0a00aea5a7/php-cs-fixer#L31-L32

The following test would be more appropriated : 
```php
if (\PHP_VERSION_ID < 70400 || \PHP_VERSION_ID >= 80300) {
        fwrite(STDERR, "PHP needs to be a minimum version of PHP 7.4.0 and maximum version of PHP 8.2.*.\n");
        // ...
}
```

Here are some information about the current configuration.

* PHP CS Fixer version : 3.13.1 
* PHP runtime: PHP 8.2.0 (cli) (built: Dec  8 2022 20:02:39) (NTS)
* Command used to run PHP CS Fixer : `/usr/local/bin/php -d memory_limit=-1 vendor/bin/php-cs-fixer fix --vvv`
* All custom CS rules have been deactivated. 

### Code snippet that reproduces the problem

To reproduce the behavior, please execute a CS fix with a PHP 8.2 CLI binary.

 `/usr/local/bin/php -d memory_limit=-1 vendor/bin/php-cs-fixer fix --vvv`

Then you will face the error message.

Thank you for the time and the efforts put into this fabulous project.

**Comment by keradus** [comment]
- PHP 8.2 is not yet supported, if you are eager to help, please start here: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues?q=is%3Aissue+is%3Aopen+8.2+label%3Atopic%2FPHP8.2

- your suggestion wouldn't really help - same concern as you have now, would reappear when 8.3 will get released

- there were endless discussion if PHP CS Fixer should PREVENT any installation of composer dependencies at all (due to php < 8.2 constraint in composer file), or allow to install all dependencies, but do not run on runtime. While neither of those is perfect, we decided for later. ref https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/5326

**Comment by Maxooo** [comment]
Thank you for your fast answer and the information provided. It's cristal clear, and the fact that PHP 8.2 is not supported yet explain everything : I'm sorry for this useless issue so.
Nevertheless, I think that it could be great to provide this information somewhere. By reading other discussions, I know that PHP CS Fixer only support active PHP versions. And since the composer requirements has been relaxed for PHP 8 (choice that I understand and approve) we can't rely on it to understand which version is supported. A new documentation (kind of `requirements.rst` file) explaining this strategy and listing the supported version would be great.

What do you think ?

Thank you again for your answer and your precious time.

**Comment by keradus** [comment]
No worry ;)

More docs won't hurt. If you are eager to add it, please raise a PR.
Not sure myself if it should be a separate file, or part of the installation instructions.

Please ensure it's covered with auto-tests - so when we check the checks on runtime, the tests are failing if docs were not updated. (you may check https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/tree/master/tests/AutoReview idea)
