### ISSUE TITLE
Extra empty line with phpdoc_separation

### ISSUE THREAD

**Issue by jderusse** [PHP-CS-Fixer/PHP-CS-Fixer#6733]
## Bug report

when a multiline parameter contains an `@`, the `phpdoc_separation` rule adds an extra blank line

### Code snippet that reproduces the problem

given the following code

```php
class X {
    /**
     * @param array{
     *   Foo?: string,
     *   Bar?: string,
     *   @baz?: string,
     * } $input
     */
    public function __construct(array $input = [])
    {

    }
}
```

the rule, generated
```diff
 class X {
     /**
      * @param array{
      *   Foo?: string,
      *   Bar?: string,
+     *
      *   @baz?: string,
      * } $input
      */
     public function __construct(array $input = [])
     {
 
     }
 }
```

**Comment by keradus** [comment]
interesting case!
can you share what `@` stands for, for `baz` ?

**Comment by jderusse** [comment]
> interesting case! can you share what `@` stands for, for `baz` ?

`@` is just the first char of the array's key, it is used like this`new X(['@baz' => true])`.

For a real world example it is used by AWS PHP SDK like this (https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multiregion-client.html)
```
$objects = $s3Client->listObjects([
    'Bucket' => $bucketName,
    '@region' => 'eu-west-1',
]);
```

**Comment by keradus** [comment]
got you!
would you like to propose a PR with a bugfix?

**Comment by thsmrtone1** [comment]
Also happens for annotations containing other nested annotations. For example:

(before)

```php
/**
 * @OpenApi\Property(type="array", items=@OpenApi\Schema(type="object", allOf={
 *     @OpenAPI\Schema(type="object", properties={
 *         @OpenApi\Property(
 *             property="id",
 *             type="string"
 *         )
 *     })
 * }))
 */
public function example(
) {
    // ...
}
```


(after)

```php
/**
 * @OpenApi\Property(type="array", items=@OpenApi\Schema(type="object", allOf={
 *
 *     @OpenAPI\Schema(type="object", properties={
 *
 *         @OpenApi\Property(
 *             property="id",
 *             type="string"
 *         )
 *     })
 * }))
 */
#[Route('/test', methods: 'GET')]
public function test(
) {
}
```


Definitely makes these look real awkward.

**Comment by partulaj** [comment]
Hello,

After struggling with this issue I finally found the solution in this MR #6668 

It seem that now we should either set the `skip_unlisted_annotations` options of `phpdoc_separation` to `true` or either defined custom groups using regex like `ORM\*`

**Comment by Wirone** [comment]
Thanks @partulaj for the feedback 🙂. I've tested it with a snippets from the bug report and it actually fixes the problem.

<img width="1064" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/816153da-7d79-4d4f-aff1-e2a22b32b2c1">

<img width="1066" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/586ecd65-d0bf-48ce-af7f-d233fee7f22c">

But I'm not sure if we can think of it as an actual bug fix or just a workaround 🤔. `phpdoc_separation` should only sort top-level annotations, without touching inner content? @jderusse @thsmrtone1 is this workaround helpful for now?

**Comment by thsmrtone1** [comment]
@partulaj @Wirone Yes, this is precisely what we are currently doing as a workaround with the "skip_unlisted_annotations" option. But I would definitely consider this a workaround, and not a solution. 

Perhaps it wont matter much to us when everything is converted to attributes, but for now, we will live with it.
