### ISSUE TITLE
Call to undefined method Fiber::create()

### ISSUE THREAD

**Issue by davidvigoda2022** [PHP-CS-Fixer/PHP-CS-Fixer#6742]
Why are the new features of PHP v8.1 mentioned in the official documentation not compiled in the core of PHP v8.1, and how can I enable Fiber in PHP v8.1 on Debian 11

**Comment by kubawerlos** [comment]
Just because. You have to do what is needed to enable them.

**Comment by davidvigoda2022** [comment]
thank you for your feedback, i found my mistake to use fiber
can you please help me to use fiber on a loop like pcntl_fork to process data in parallel, 
Here is the code for converting to fiber, Thanks.

	$names = array('A','B','C','D','E');
	$childs = array();

	for ($i=0; $i < count($names) ; $i++) {

		$pid = pcntl_fork();
		if($pid == -1)
			die('Could not fork \n');

		if ($pid) {
			//echo 'parent \n';
			$childs[] = $pid;
		} else {
			// Sleep $i+1 (s). The child process can get this parameters($i).
			get_data_function($names[$i]);
			sleep(1);						
	
			// The child process needed to end the loop.
			exit();
		}		
			
		
	}
	while(count($childs) > 0) {
		foreach($childs as $key => $pid) {
			$res = pcntl_waitpid($pid, $status, WNOHANG);
			
			// If the process has already exited
			if($res == -1 || $res > 0)
				unset($childs[$key]);
		}
		
		sleep(1);
	}

**Comment by keradus** [comment]
This is very general question for help about how to write code in PHP, using given features of language itself. This is not related to PHP CS Fixer and we suggest to raise this question on PHP support groups, like https://stackoverflow.com/questions/tagged/php
