### ISSUE TITLE
blank_line_before_statement: prevent adding line before enum case

### ISSUE THREAD

**Issue by bendavies** [PHP-CS-Fixer/PHP-CS-Fixer#6747]
## Feature request
Given:
```php
enum Foo
{
    case One;
    case Two;
}
```

`blank_line_before_statement`, with `case` configured will transform to:

```php
enum Foo
{
    case One;
    
    case Two;
}
```

This is undesirable formatting.

An option could be introduced to somehow exclude these specific enum`cases`.

**Comment by smottt** [comment]
Yes, please.
