### ISSUE TITLE
[PHP 8.2] Doesn't supported

### ISSUE THREAD

**Issue by RamsDark** [PHP-CS-Fixer/PHP-CS-Fixer#6749]
## Bug report

Does't supported with PHP 8.2

### Description

Updated cs-fixer to the latest version & doesn't work o PHP 8.2, despite that the semver is satisfied by "^7.1 || ^8.0"

### Runtime version

3.13.2

### Used command

Any command leads to this bug. See screenshot

![image](https://user-images.githubusercontent.com/47033638/212665637-360f0ae5-0126-4a3d-a685-bd37be6076f5.png)

**Comment by attalbialami** [comment]
+1 I am facing the same problem 😞

**Comment by patrickcurl** [comment]
Same issue, on arch linux, today apparently the default php package upgraded to 8.2.

**Comment by kubawerlos** [comment]
What exactly is the issue you're facing that the solution isn't on the 3rd row of the picture with the CLI output?

**Comment by keradus** [comment]
Folks, highly encouraging to use the search feature.
TL;DR - 8,2 is not currently supported as it takes huge effort to support each new PHP syntax. If you need it, consider to support the project [eg with code contribution].
ref https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6714#issuecomment-1359166470
