### ISSUE TITLE
Linting fails with mixed opening tags

### ISSUE THREAD

**Issue by CasEbb** [PHP-CS-Fixer/PHP-CS-Fixer#6751]
### Description

When `short_open_tag = "0"`, PHP-CS-Fixer fails during the linting phase when code blocks are opened with full tags and closed with short tags (or vice versa).

### Runtime version

PHP CS Fixer 3.13.2 (3952f08) Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.14

### Used command

```
$ php-cs-fixer fix -vvv --rules=full_opening_tag example.php
```

### Code snippet that reproduces the problem

```php
<?php if (1) { ?><? } ?>
```

**Comment by kubawerlos** [comment]
> PHP-CS-Fixer fails during the linting phase

Because the file does not contain valid PHP code which is expected:
```bash
$ cat example.php
<?php if (1) { ?><? } ?>

$ php -d short_open_tag=On -l example.php
No syntax errors detected in example.php

$ php -d short_open_tag=Off -l example.php
PHP Parse error:  Unclosed '{' on line 1 in example.php on line 2
Errors parsing example.php
```
