### ISSUE TITLE
When using group_import and no_unused_imports CS fixer does not delete unused imports in grouped statements

### ISSUE THREAD

**Issue by isabellenoe** [PHP-CS-Fixer/PHP-CS-Fixer#6754]
### Description

When using the configuration options group_import and no_unused_imports together, ununsed imports in the grouped statements aren't removed.

### Runtime version

PHP runtime: 8.1.8
PHP CS Fixer 3.13.0

### Used command

`vendor/bin/php-cs-fixer fix --ansi -vvv`

### Configuration file

```php
return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        '@PhpCsFixer:risky' => true,
        'array_syntax' => ['syntax' => 'short'],
        'yoda_style' => false,
        'single_import_per_statement' => false,
        'concat_space' => ['spacing' => 'one'],
        'declare_strict_types' => true,
        'no_unused_imports' => true,
        'group_import' => true,
    ])
    ->setFinder($finder)
;
```

### Code snippet that reproduces the problem

```php
<?php

declare(strict_types=1);

namespace App\SampleDomain;

use App\Common\{Date, UnusedClass};
use App\AnotherDomain\NotGroupedUnusedClass;

class SampleClass
{
    public function date(): Date
    {
        return new Date();
    }
}
``` 
`Unused Class` is not removed by csfixer. `NotGroupedUnusedClass` is removed, because it is not grouped.

**Comment by devsquad-eduardo-barijan** [comment]
Same behavior here, even using `Laravel Pint`. So for the example provided the expected use line would be: 
`use App\Common\Date;`

Note that it removes the grouping in this case because it would be only one class.

**Comment by kubawerlos** [comment]
> Same behavior here, even using `Laravel Pint`.

What do you mean by "even using `Laravel Pint`"? Isn't this simply a wrapper for PHP CS Fixer for lazy people?

Can you raise a PR with a bugfix for this behavior?

**Comment by isabellenoe** [comment]
I wrote a test case for this behaviour:

**Comment by hosmelq** [comment]
I have the same problem. I enabled `group_import` and `no_unused_imports`, but unused imports inside groups are not removed.

<img width="810" alt="CleanShot 2023-04-08 at 12 57 11@2x" src="https://user-images.githubusercontent.com/1166143/230738325-d619de63-9e71-4145-a9e1-e144648c4070.png">

**Comment by Wirone** [comment]
Closing as a duplicate of #6431.
