### ISSUE TITLE
Force Numeric Literal Separator

### ISSUE THREAD

**Issue by muuvmuuv** [PHP-CS-Fixer/PHP-CS-Fixer#6755]
## Rule request

I think this would be useful if an int is typed that it will be forced to be separated with that underscore.

### Code snippet that shows how the rule would fix PHP code

```php
<?php

$var1 = 412561242;

/* Would become */

$var2 = 412_561_242;
```

**Comment by keradus** [comment]
I think it's very valid idea indeed.
would you like to give it a try and propose one? you can also look at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/cookbook_fixers.rst to get head start

**Comment by muuvmuuv** [comment]
I will give it a try, lets see how far I come ^^

**Comment by ziemkowski** [comment]
While searching for this exact feature, I found an implementation in another repo. I'm not sure if it would help for inspiration or is problematic because of licensing, but [here is one implementation](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/main/src/Fixer/NumericLiteralSeparatorFixer.php) (documented [here](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#numericliteralseparatorfixer)).

**Comment by muuvmuuv** [comment]
I have an idea that is way simpler than that. I will continue on it on Monday. But anyway good to know somebody worked on it already, thanks!

**Comment by muuvmuuv** [comment]
@ziemkowski the one you shared seem to do the reversed thing; removing all `_` separator. I want it to be added.

While working on it today I noticed a few things that are difficult to handle: floats. I thought it would be simple by just using `number_format($token, $deciamsl, ",", "_")` but it does not convert decimal points correctly as I expected; `1.243_2` would become `1.2432`.

For binary and hex I expect the parts to always have 4 chars (while 8 is valid):

- '0b0101010001101000' => '0b0101_0100_0110_1000'
- '0B01010100_01101000' => '0B0101_0100_0110_1000'
- '0b110001000' => '0b1_1000_1000'

I use some of the tests from the impl here: https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/main/tests/Fixer/NumericLiteralSeparatorFixerTest.php#L86

Guess I can publish a draft pr soon...

**Comment by muuvmuuv** [comment]
A thought about performance: I do a lot of `strtolower` for checking for hex and bin, but I guess converting it earlier and force it, would anger people, if I change their uppercase preference in binary and hex strings. Wdyt?

**Comment by kubawerlos** [comment]
> one you shared seem to do the reversed thing; removing all `_` separator. I want it to be added.

@muuvmuuv if you look closer at the [docs](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#NumericLiteralSeparatorFixer) you will see that it is not a problem to configure the fixer to add `_` separator.

**Comment by muuvmuuv** [comment]
So, first impl is done, please let me know what you think. Tests are all running. Just had difficult with Octals. And currently no options are provided for simplicity and development.
