### ISSUE TITLE
`braces.position_after_functions_and_oop_constructs: next` doesn't work with multiline method declaration

### ISSUE THREAD

**Issue by speller** [PHP-CS-Fixer/PHP-CS-Fixer#6770]
## Bug report

The `braces.position_after_functions_and_oop_constructs: next` option doesn't work with multiline methods declaration.

### Runtime version

php-cs-fixer: 3.14.3

### Configuration file

```
<?php

/**
 * PHP Coding Standards fixer configuration
 */

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude('public')
    ->exclude('bin')
    ->exclude('config')
    ->exclude('scripts')
    ->exclude('templates')
    ->exclude('vendor')
    ->exclude('var');

$config = new PhpCsFixer\Config();
$config->setFinder($finder)
    ->setRiskyAllowed(true)
    ->registerCustomFixers([
        new \AdamWojs\PhpCsFixerPhpdocForceFQCN\Fixer\Phpdoc\ForceFQCNFixer()
    ])
    ->setRules([
        '@PSR12' => true,
        '@PHP82Migration' => true,
        'array_syntax' => ['syntax' => 'short'],
        'concat_space' => ['spacing' => 'one'],
        'braces' => [
            'position_after_functions_and_oop_constructs' => 'next',
            'position_after_control_structures' => 'same',
            'allow_single_line_closure' => true,
            'allow_single_line_anonymous_class_with_empty_body' => true,
        ],
        'include' => true,
        'no_empty_statement' => true,
        'no_extra_blank_lines' => true,
        'no_leading_namespace_whitespace' => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'multiline_whitespace_before_semicolons' => [
            'strategy' => 'new_line_for_chained_calls',
        ],
        'no_singleline_whitespace_before_semicolons' => true,
        'no_trailing_comma_in_singleline' => true,
        'no_unused_imports' => true,
        'object_operator_without_whitespace' => true,
        'ordered_imports' => true,
        'standardize_not_equals' => true,
        'ternary_operator_spaces' => true,
        'declare_strict_types' => true,
        'no_unneeded_import_alias' => true,
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'AdamWojs/phpdoc_force_fqcn_fixer' => true,
    ]);
return $config;
```

### Code snippet that reproduces the problem

```php
<?php
class Foo {
    public function a(Bool $a): Bool
    {
        return true;
    }

    public function b(
        string $a,
        string $b,
        string $c
    ): Bool {
        return true;
    }
}

```

The opening curly brace of method `b` should be located on the next line according to the  `braces.position_after_functions_and_oop_constructs: next`  configuration. It is placed on the same line instead. The expected formatting is the following:

```php
    public function b(
        string $a,
        string $b,
        string $c
    ): Bool 
    {
        return true;
    }
```

**Comment by keradus** [comment]
Hey!
Thanks for your report.

We identified that `braces` fixer is too complex and has too many responsibilities. With that, we decided to **deprecate** it [ref #4885].

That also means that we will not be extending, changing the behaviour or fixing anything around `braces` fixer. Please, use replacement rules instead [ref https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/braces.rst#this-rule-is-deprecated-and-will-be-removed-on-next-major-version ].

If you see the issue that you reported to be present in one of the replacement rules, please report a new github issue.

Big thanks!

**Comment by kczx3** [comment]
> Hey! Thanks for your report.
> 
> We identified that `braces` fixer is too complex and has too many responsibilities. With that, we decided to **deprecate** it [ref #4885].
> 
> That also means that we will not be extending, changing the behaviour or fixing anything around `braces` fixer. Please, use [replacement rules](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/braces.rst#this-rule-is-deprecated-and-will-be-removed-on-next-major-version) instead.
> 
> If you see the issue that you reported to be present in one of the replacement rules, please report a new github issue.
> 
> Big thanks!

Is there a good place for consumers to track these deprecations and what replaces what?  I have enjoyed using the documentation of this repository but this was something that I randomly noticed while looking into why `control_structure_continuation_position.position` wasn't being flagged in my code but its because the `braces` rule was overriding it or something.

**Comment by kczx3** [comment]
You know...  I now see the Warning header in the Braces documentation file.  Honestly, that didn't stick out to me at all and I've looked at that file numerous times over the last few days.  Any way to make it stand out a bit more?

**Comment by Wirone** [comment]
Deprecations are displayed on the rules list and inside each rule's docs. IIRC it's also pointed out in the CLI output that you use deprecated rule. There's always room for improvement 🙂.

**Comment by kczx3** [comment]
I noticed in a separate repo that there was a deprecation output in their console but I'm not seeing that in mine for some reason.  It may also be helpful in the Warning within braces.rst to specifically say to include `'braces' => false` in the configuration.  Without that, I still see the braces rule come back as something that needs fixing when doing a dry run.

```shell
$ ./vendor/bin/php-cs-fixer fix --dry-run --verbose --using-cache=no views/transition_of_care/main.php
PHP CS Fixer 3.13.2 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.23
Loaded config default from "/home/<username>/public_html/<project>/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
F                                                                                                                                         1 / 1 (100%)
Legend: .-no changes, F-fixed, S-skipped (cached or empty file), I-invalid file syntax (file ignored), E-error
   1) views/transition_of_care/main.php (indentation_type, elseif, braces, method_argument_space, no_spaces_inside_parenthesis, constant_case, no_closing_tag, control_structure_continuation_position, single_blank_line_at_eof)

Found 1 of 1 files that can be fixed in 0.166 seconds, 16.000 MB memory used
```

Notice that braces is mentioned above but no deprecation warning.  I just started using this so its possible I am missing something.

**Comment by Wirone** [comment]
@kczx3 you're using Fixer 3.13.2, while documentation represents latest version which is 3.30 as of now 🙂. Braces fixer was deprecated in [3.16](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.16.0).

**Comment by kczx3** [comment]
Interesting...  I'm certainly not a whiz when it comes to composer but I've deleted the vendor directory and cleared the composer cache.  Reinstalling still grabs ^3.13.2 for some reason.

**Comment by Wirone** [comment]
Try `composer why-not friendsofphp/php-cs-fixer 3.14` 🙂

**Comment by kczx3** [comment]
Oh jeez, ok this is confusing.  So I have PHPSpreadsheet installed which requires maennchen/zipstream-php and that requires symfony/polyfill-mbstring (^1.0).  I'm guessing that when I last updated PHPSpreadsheet, the most recent version of symfony/polyfill-mbstring was 1.26 as that is what I have in my composer.lock.

It appears that running the suggested composer command and including the `--update-with-dependencies` flag allows me to install the latest version of PHP-CS-Fixer.  Hopefully that's the right way.  Thanks for all your wisdom!
