### ISSUE TITLE
no unused imports and global namespace import are collide

### ISSUE THREAD

**Issue by kayw-geek** [PHP-CS-Fixer/PHP-CS-Fixer#6783]
### Description
When config that rules 
` global_namespace_import => ['import_classes' => true]` and 
`no_unused_imports`

```PHP
<?php
namespace Test;

/** @return \Closure */
function x() {}
```
the global_namespace_import rule will import the \Closure namespace  to top of file, and then the `unused_imports` rule will remove these unused imports also.

So I want to modify the `import_classes` rule to do not works on  `DOC_COMMENT`, what do you think?
### Runtime version

v3.14.4

**Comment by kubawerlos** [comment]
When applying `global_namespace_import ` to your code the result is:
```php
<?php
namespace Test;
use Closure;

/** @return Closure */
function x() {}
```
and `no_unused_imports` does not modify that code.
