### ISSUE TITLE
Running CS Fixer with 8.2 EN

### ISSUE THREAD

**Issue by Brandin** [PHP-CS-Fixer/PHP-CS-Fixer#6785]
## Support question

Hi there,

I read the instructions on how to allow PHP CS Fixer to work with PHP 8.2, by setting the ENV `PHP_CS_FIXER_IGNORE_ENV`.
However, when doing so in my terminal (using Cmder on Windows), I get the following error:

```
C:\xampp\htdocs\xxx (master -> origin) 
λ PHP_CS_FIXER_IGNORE_ENV=1 php php-cs-fixer fix .
'PHP_CS_FIXER_IGNORE_ENV' is not recognized as an internal or external command,
operable program or batch file.
```

Any help is appreciated!

**Comment by kubawerlos** [comment]
Hi @Brandin,

it seems it is not that easy on Windows, take a look at this question and its 1st answer: https://superuser.com/questions/223104/setting-and-using-variable-within-same-command-line-in-windows-cmd-exe and let us know if that works.
