### ISSUE TITLE
Empty line is valid after `return`

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#6786]
### Description

`no_extra_blank_lines` is removing empty line before `interface` when after `return` statement. Such code is valid and often used for static analysis when interface/class needs to be understand but not declared on runtime.

### Runtime version

latest / 3.14.4

### Configuration file

https://github.com/atk4/core/blob/4.0.0/.php-cs-fixer.dist.php

### Code snippet that reproduces the problem

  ```php
<?php

return false;

interface Iface
{
}
  ```

**Comment by mvorisek** [comment]
It seems empty line before `interface` is not enforced at all:

```php
<?php

echo 5;
interface Iface
{
}
```

maybe the problem is in `blank_line_before_statement`

**Comment by kubawerlos** [comment]
> Empty line is valid after `return`

Lack of empty line is also valid after `return`

> Such code is valid and often used for static analysis when interface/class needs to be understand but not declared on runtime.

Where? Who does that? PHPStorm will point to this code as nonsense.

> It seems empty line before `interface` is not enforced at all:

Why would it be?

This report represents a very subjective point of view.

Summarizing: you are using `no_extra_blank_lines ` with `return` in the tokens list and complaining that it removes blank line after the `return`.

**Comment by mvorisek** [comment]
@kubawerlos I belive the fix is possible and will hurt noone, the fixers should do fix more than described.

**Comment by kubawerlos** [comment]
> the fixers should do fix more than described

What? No, absolutely not.

> It seems empty line before `interface` is not enforced at all

Yes, this is true, why would be any different?

**Comment by mvorisek** [comment]
> the fixers should do fix more than described

typo, the fixers should *NOT fix more than described

**Comment by kubawerlos** [comment]
Instead of arguing I believe it would be better if you propose a soultion via PR, WDYT?

> It seems empty line before `interface` is not enforced at all

It's not that interfaces are forgotten, this applies to classes, traits and so on, so this was never a feature.

**Comment by mvorisek** [comment]
Look at my profile, I contribute a lot of PRs, but sometimes it takes months until I find out time by myself or until someone else picks it. If an issue is closed, neither me nor someone else will fix it.

**Comment by mvorisek** [comment]
@Wirone can this issue be reopened please?

**Comment by Wirone** [comment]
@mvorisek I won't reopen it because:

- it was processed by @kubawerlos and I don't want to undermine his decision, especially that I agree with him here
- there is a lot of noise in the comments so opening it would provide a lot of cognitive load for anyone wanting to get familiar with it
- most probably core team won't work on it, also I see rather small chances of contributors picking it up too, so there's no point in keeping it open

Sorry 🤷‍♂️.
