### ISSUE TITLE
add fixer for deleting redundant union

### ISSUE THREAD

**Issue by arderyp** [PHP-CS-Fixer/PHP-CS-Fixer#6807]
## Feature request

```
@return A|B|B
: A|B|B
```

should be fixed to 

```
@return A|B
: A|B
```

I am working with [openapi generator](https://github.com/OpenAPITools/openapi-generator) and this is an issue with some of the generated code that I'd like to clean up.

**Comment by keradus** [comment]
PHP CS Fixer requires a valid PHP code as input, before doing any manipulation.
`A|B|B` will not compile, like
```
ker@d ~/github/FriendsOfPHP/PHP-CS-Fixer λ php -l y.php 
PHP Fatal error:  Duplicate type B is redundant in y.php on line 2
```

with that, we won't be able to read file and modify it

**Comment by arderyp** [comment]
Fair enough, thank you for the info
