### ISSUE TITLE
PHP-CS-Fixer 3.15.0 wants to add spaces around | in type declarations for parameters that are passed by reference

### ISSUE THREAD

**Issue by sebastianbergmann** [PHP-CS-Fixer/PHP-CS-Fixer#6828]
### Description

After updating from 3.14.4 to 3.15.0, PHP-CS-Fixer wants to change `object|array` to `object | array`.

### Runtime version

```
./tools/php-cs-fixer -V                       
PHP CS Fixer 3.15.0 (7306744) BoY42 by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.3
```

### Used command

```
./tools/php-cs-fixer fix --dry-run --diff
Loaded config default from "/usr/local/src/recursion-context/.php-cs-fixer.dist.php".
Using cache file ".php-cs-fixer.cache".
   1) src/Context.php
      ---------- begin diff ----------
--- /usr/local/src/recursion-context/src/Context.php
+++ /usr/local/src/recursion-context/src/Context.php
@@ -50,7 +50,7 @@
      *
      * @param-out T $value
      */
-    public function add(object|array &$value): int|string|false
+    public function add(object | array &$value): int|string|false
     {
         if (is_array($value)) {
             return $this->addArray($value);
@@ -66,7 +66,7 @@
      *
      * @param-out T $value
      */
-    public function contains(object|array &$value): int|string|false
+    public function contains(object | array &$value): int|string|false
     {
         if (is_array($value)) {
             return $this->containsArray($value);

      ----------- end diff -----------
```

### Configuration file

https://github.com/sebastianbergmann/recursion-context/blob/main/.php-cs-fixer.dist.php

**Comment by sebastianbergmann** [comment]
Similar issue in PHPUnit:

```
./tools/php-cs-fixer fix --dry-run --diff
Loaded config default from "/usr/local/src/phpunit/.php-cs-fixer.dist.php".
Using cache file ".php-cs-fixer.cache".
   1) tests/_files/mock-object/ClassWithStaticReturnTypes.php
      ---------- begin diff ----------
--- /usr/local/src/phpunit/tests/_files/mock-object/ClassWithStaticReturnTypes.php
+++ /usr/local/src/phpunit/tests/_files/mock-object/ClassWithStaticReturnTypes.php
@@ -21,7 +21,7 @@
     {
     }
 
-    public function returnsUnionWithStatic(): static|stdClass
+    public function returnsUnionWithStatic(): static | stdClass
     {
     }
 }

      ----------- end diff -----------


Found 1 of 1421 files that can be fixed in 0.071 seconds, 20.574 MB memory used
```

https://github.com/sebastianbergmann/phpunit/blob/main/.php-cs-fixer.dist.php

**Comment by sebastianbergmann** [comment]
Looks like a regression of #5495 / #5733 to me.

**Comment by sebastianbergmann** [comment]
Just noticed #6826 which seems to be about the same issue shown in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6828#issue-1620840606 (parameters with union types passed by reference).

#6826 does not seem to be related to the issue shown in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6828#issuecomment-1465587966 (return type declaration without reference operator).

**Comment by Wirone** [comment]
@sebastianbergmann wouldn't it be problem for you to close this issue and create new one, just with the example without [passing by reference](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6828#issuecomment-1465587966)? Or edit this one to keep only scenario not covered by #6826? This would be easier to process, thanks in advance. PS. We'll look at it anyway 🙂

**Comment by sebastianbergmann** [comment]
I moved https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6828#issuecomment-1465587966 to #6830.

**Comment by sebastianbergmann** [comment]
Thank you!
