### ISSUE TITLE
An extra  pipe symbol added which makes property type not resolvable when applied phpdoc_types_order

### ISSUE THREAD

**Issue by Aeliot-Tm** [PHP-CS-Fixer/PHP-CS-Fixer#6841]
### Description

When i run fixing of the code it adds an extra pipe symbol to the property definition in PHPDoc. It makes property type not resolvable.
See screenshot.

![image](https://user-images.githubusercontent.com/8513062/225550242-0b52655d-17da-4df2-8f00-87cc6895bc55.png)

### Runtime version

PHP CS Fixer 2.19.3 Testament by Fabien Potencier and Dariusz Ruminski

### Used command

```shell
php -d memory_limit=-1 vendor/bin/php-cs-fixer fix --diff --allow-risky=yes --dry-run -vvv
```

### Configuration file

```php
<?php

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

$finder = Finder::create()
    ->in(__DIR__ . '/src')
    ->name('*.php');

$rules = [
    '@Symfony' => true,
    'phpdoc_align' => ['align' => 'left'],
    'phpdoc_separation' => false,
    'no_superfluous_phpdoc_tags' => false,
    'concat_space' => ['spacing' => 'one'],
    'yoda_style' => [
        'equal' => false,
        'identical' => false,
        'less_and_greater' => false,
    ],
    'cast_spaces' => [
        'space' => 'none',
    ],
    'global_namespace_import' => [
        'import_classes' => true,
        'import_constants' => false,
        'import_functions' => false,
    ],
    'lowercase_keywords' => true,
    'lowercase_static_reference' => true,
    'ordered_class_elements' => false,
    'single_line_throw' => false,
    'single_quote' => false,
    'phpdoc_annotation_without_dot' => false,
    'phpdoc_tag_type' => false,
    'phpdoc_summary' => false,
    'no_multiline_whitespace_around_double_arrow' => false,
    'increment_style' => false,
];

return (new Config)
    ->setFinder($finder)
    ->setRules($rules)
    ->setCacheFile('.php-cs-fixer.cache');

```

### Code snippet that reproduces the problem

  ```php
  <?php
/**
 * @return array<array{ provider: string, parameters: array<string> }>
 */
function get(): array
{
    return [];
}
```

**Comment by Wirone** [comment]
> You are running PHP CS FIxer v2, which is not maintained anymore. Please update to v3.

Sorry to hear you encountered a problem with Fixer, but we can't help you since you're using v2 which's lifecycle came to an end. We don't provide fixes for that version anymore.

**Comment by keradus** [comment]
Ouch, long time I saw Testament version. Anything that is blocking you to upgrade?

**Comment by Aeliot-Tm** [comment]
We have to support old project and cannot upgrade fixer now due to some conflicts. 

Ok. I did some work around to avoid this problem. And hope we will not bump this problem when will be able to upgrade fixer. Thank you.
