### ISSUE TITLE
`multiline_whitespace_before_semicolons` (`new_line_for_chained_calls`) not working in 3.16

### ISSUE THREAD

**Issue by kbond** [PHP-CS-Fixer/PHP-CS-Fixer#6886]
### Description

The `multiline_whitespace_before_semicolons` rule using the `new_line_for_chained_calls` strategy appears broken as of 3.16.

### Runtime version

3.16.0

### Code snippet that reproduces the problem

Before:

```php
host('stage')
    ->setHostname('dev.hammfg.com')
    ->setRemoteUser('webuser')
;
```

After:

```php
host('stage')
    ->setHostname('dev.hammfg.com')
    ->setRemoteUser('webuser');
```

**Comment by MirakuSan** [comment]
I am having the same issue with a multiline ternary : 
Before : 
```php
$toto = (dummycondition)
    ? 'iftrue'
    : 'iffalse'
;
``` 

After : 
```php
$toto = (dummycondition)
    ? 'iftrue'
    : 'iffalse';
```

**Comment by FrittenKeeZ** [comment]
I guess it has something to do with https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/5126 ?
I have downgraded to Laravel Pint 1.7 because of this bug

**Comment by MarcelGDC** [comment]
The same happens to me. I downgraded to v3.15.1 and the bug disappeared.

**Comment by ampersand** [comment]
This appears to still be an issue with multiline ternary.
