### ISSUE TITLE
`no_break_comment` adds comment before `default` of `match` expression and adds no comment if `match`without `default`is used

### ISSUE THREAD

**Issue by irobin591** [PHP-CS-Fixer/PHP-CS-Fixer#6894]
### Description

When using the `no_break_comment` rule, a `// no break` comment gets added before a default case within a [`match`](https://www.php.net/manual/de/control-structures.match.php) expression even if a break for the `case` is placed (after the match).

Additionally, if a `match` expression is used within a `switch-case` expression without using the default pattern, no `// no break` comment is placed even though a break is missing and the case is falling though to the next case (in this case the default case)

### Runtime version

```
PHP CS Fixer 3.16.0 BoY42 by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.2
```

### Used command

```bash
$ ./vendor/bin/php-cs-fixer fix -vvv --diff
PHP CS Fixer 3.16.0 BoY42 by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.2
Loaded config default from "/var/www/html/.php-cs-fixer.php".
Using cache file ".php-cs-fixer.cache".
F                                                                   1 / 1 (100%)
Legend: .-no changes, F-fixed, S-skipped (cached or empty file), I-invalid file syntax (file ignored), E-error
   1) test.php (no_break_comment)
      ---------- begin diff ----------
--- /var/www/html/test.php
+++ /var/www/html/test.php
@@ -3,6 +3,7 @@
 switch ('wrong placement of no_break_comment') {
     case 'a':
         $x = match (true) {
+        // no break
             default => 'a'
         };
     default:
@@ -12,6 +13,7 @@
 switch ('wrong placement of no_break_comment if case has break statement') {
     case 'a':
         $x = match (true) {
+        // no break
             default => 'a'
         };
         break;

      ----------- end diff -----------


Fixed 1 of 1 files in 0.052 seconds, 12.000 MB memory used
```
### Configuration file

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->name('*.php')
    ->in(__DIR__);

$config = new PhpCsFixer\Config();
return $config->setRules([
        'no_break_comment' => true,
    ])
    ->setFinder($finder);
```

### Code snippet that reproduces the problem

```php
<?php

switch ('wrong placement of no_break_comment') {
    case 'a':
        $x = match (true) {
            default => 'a'
        };
    default:
        $x = 'b';
}

switch ('wrong placement of no_break_comment if case has break statement') {
    case 'a':
        $x = match (true) {
            default => 'a'
        };
        break;
    default:
        $x = 'b';
}

switch ('no placement of no_break_comment') {
    case 'a':
        $x = match (true) {
            false => 'a'
        };
        $y = 'a';
    default:
        $x = 'b';
}
```

**Comment by Wirone** [comment]
Hi @irobin591, thanks for the report. I believe it's really edge case, why would you want to put `match` inside `switch` 🤔? Anyway, fixer probably does not recognise cases' boundaries properly, `NoBreakCommentFixerTest` does not contain scenarios where `switch` and `match` are mixed together while `NoBreakCommentFixer` has some logic related to `default` and `=>` used in `match`.. It requires deeper verification and fix. But most probably will need to wait.

**Comment by kubawerlos** [comment]
We already cover edge cases [such as](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.16.0/tests/Fixer/ControlStructure/NoBreakCommentFixerTest.php#L762-L764):
```php
    case 1: {
        throw new \Exception();
    }
```
so we should this one too.
