### ISSUE TITLE
I want to convert array() to [] - array_syntax short

### ISSUE THREAD

**Issue by maofree** [PHP-CS-Fixer/PHP-CS-Fixer#6897]
## Support question

Hi
I want to use the "Globally (manual)" suggested here
https://cs.symfony.com/doc/installation.html

I've tried and it works, but it did just a thing, remove the spaces and some tabs, instead I want to replace array() with [] and other fixes if necessary

using this code
php-cs-fixer fix ./

it removes only some tabs and dots but nothing else

require_once implode(DIRECTORY_SEPARATOR, array(
    dirname(__FILE__), 'classes', 'ContactFormClass.php',
));

this is not changed to
require_once implode(DIRECTORY_SEPARATOR, array(
    dirname(__FILE__),
    'classes',
    'ContactFormClass.php',
)
);

and
    public $googlemap_styles = array(
        'Default',
        'Subtle Grayscale',
        'RouteXL',
        'Flat Pale',
        'The Propia Effect',
        'vancity',
        'Interactive',
        'Dropoff 3',
        'Sin City',
        'RPN Map Style',
        'Cobalt',
    );

is not changed to

    public $googlemap_styles = [
        'Default',
        'Subtle Grayscale',
        'RouteXL',
        'Flat Pale',
        'The Propia Effect',
        'vancity',
        'Interactive',
        'Dropoff 3',
        'Sin City',
        'RPN Map Style',
        'Cobalt',
    ];

can you help me to understand how to use php-cs-fixer fix command?

https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/array_notation/array_syntax.rst

thanks

**Comment by maofree** [comment]
`php-cs-fixer fix ./ --rules='{"array_syntax": {"syntax": "short"}}'`

I found the solution

**Comment by Wirone** [comment]
Thanks @maofree for providing self-feedback 🙂. Next time, please, create discussion only - issue can be raised after determining problem, if needed.
