### ISSUE TITLE
`statement_indentation` fixer erroneously 'fixes' multiline parameter lists

### ISSUE THREAD

**Issue by curry684** [PHP-CS-Fixer/PHP-CS-Fixer#6935]
Not sure when this behavior was introduced, but since a recent update the following constructor:
```php
    public function __construct(protected readonly ContainerInterface $locator,
                                protected readonly TranslatorInterface $translator,
                                protected readonly RouterInterface $router)
    {
    }
```
Is 'fixed' to:
```php
    public function __construct(protected readonly ContainerInterface $locator,
        protected readonly TranslatorInterface $translator,
        protected readonly RouterInterface $router)
    {
    }
```
Aesthetics aside - to my best knowledge no established PHP coding standard has a real opinion on this, and I prefer the first one's readability when injecting multiple services. Debugging reveals the `statement_indentation` fixer is now doing this, which is simply [documented](https://cs.symfony.com/doc/rules/whitespace/statement_indentation.html) as *"Each statement must be indented."* With which I fully agree, so I do want to have this fixer run.

But multiline parameters *are not statements*. And it's leaving arrays well enough alone, not fixing this:
```php
        return [
    'foo',
     'bar',
      '123',
        ];
```
Which is good, because we have `array_indentation` fixer for that if you want to.

So, why is `statement_indentation` fixer fixing lines that are definitely not statements but parameters? Is this intended, and if so, why not configurable? I believe this behavior should instead be part of a separate `parameter_indentation` fixer.

**Comment by Wirone** [comment]
IMHO there should be new line before first argument:

```
    public function __construct(
        protected readonly ContainerInterface $locator,
        protected readonly TranslatorInterface $translator,
        protected readonly RouterInterface $router)
    {
    }
```

There's no need to push all arguments right, I believe it's more readable when it's aligned to the left (with proper indentation).

But anyway, if it started acting like this recently, we'll investigate it.

**Comment by Wirone** [comment]
Well, it depends on the config, because fixers are atomic and have single responsibility 🙂. And I am not even sure we have fixers for all you mentioned.

**Comment by curry684** [comment]
Symfony coding standard seems to prescribe the notation I mentioned above at https://symfony.com/doc/current/contributing/code/standards.html:
```php
    /**
     * @param $dummy some argument description
     */
    public function __construct(
        string $dummy,
        private Qux $qux,
    ) {
        $this->fooBar = $this->transformText($dummy);
    }
```
But is then inconsistent in its own rules as most parameter lists are single line, ie. https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/HttpClient/AmpHttpClient.php#L54-L72

I suppose this does need its own `parameter_indentation` fixer which allows the user to choose single line or multiline, but **IF** you use multiline => enforce array notation with indented parameters, comma at the end and closing parentheses on its own line with opening accolade. Which would be very similar to `array_indentation` today.

**Comment by julienfalque** [comment]
For the record I intend to merge `statement_indentation` and `array_indentation` into a new `indentation` rule that would handle indentation everywhere (including function parameters) instead of having multiple specific rules.

**Comment by Wirone** [comment]
@julienfalque wouldn't it be something like `braces` that in the end was too big and got deprecated? Maybe it's possible to extract some common logic to an abstract fixer or other service, and keep more atomic fixers?
