### ISSUE TITLE
`phpdoc_var_without_name` is corrupting phpdoc type with `$this`

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#6959]
## Bug report

`array<string, string|array{ string|\Closure(mixed, string, $this): int|float }>|false` is valid phpdoc type and must be kept unchanged.

### Description

```
   1) ui/src/Table.php (phpdoc_var_without_name)
      ---------- begin diff ----------
--- /__w/ui/ui/src/Table.php
+++ /__w/ui/ui/src/Table.php
@@ -43,7 +43,7 @@
      * Determines a strategy on how totals will be calculated. Do not touch those fields
      * directly, instead use addTotals().
      *
-     * @var array<string, string|array{ string|\Closure(mixed, string, $this): int|float }>|false
+     * @var array<string, string|array{ string|\Closure(mixed, string,): int|float }>|false
      */
     public $totalsPlan = false;
```

### Runtime version

```
PHP CS Fixer 3.16.0 BoY42 by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.18
```

### Used command

```
vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --diff --verbose
```

### Configuration file

https://github.com/atk4/ui/blob/01d39d24694e4b4f63a576d090e55e0e97aaa9e4/.php-cs-fixer.dist.php

### Code snippet that reproduces the problem

```
class Table
{
    /**
     * Determines a strategy on how totals will be calculated. Do not touch those fields
     * directly, instead use addTotals().
     *
     * @var array<string, string|array{ string|\Closure(mixed, string, $this): int|float }>|false
     */
    public $totalsPlan = false;
}
```

**Comment by Wirone** [comment]
Is it valid though? These are callable's signature types, `$this` looks improper there because call context is different. [PHPStan does not report anything](https://phpstan.org/r/c2186e1d-de33-4fab-920e-7e09768f233c), but for me it looks wrong 🤔.

**Comment by mvorisek** [comment]
It is valid. `$this` inside any class phpdoc means `$this`, outside the class, it is generalized to `static`.

example usecase: https://github.com/atk4/ui/blob/3c592b8f10fe67c61f179c5c8723b07f8ab754b9/src/Table.php#L575

**Comment by Wirone** [comment]
I understand the intent and the usage, I just find `$this` weird in this particular context - using as an input type. I rarely used it anywhere, but when I did, it was always output context (return type).

**Comment by mvorisek** [comment]
Here is another example from our code base - https://github.com/atk4/data/blob/edddfc9e473ca704fac56cf2624cc9ea924a0c17/src/Model/UserAction.php#L57 - `$this` in the phpdoc is a) asserting (via phpstan) the correct instance is passed, b) explaining the passed object to the programmer. And PHP CS Fixer pass. But for some reasons, the more complex type from this issue is failing PHP CS Fixer and it should be fixed.

Maybe array shapes /wo key are not accepted? https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/c5cbfd68f8/src/DocBlock/TypeExpression.php#L41

https://phpstan.org/writing-php-code/phpdoc-types#array-shapes

> `array{int, int}` (keys are 0 and 1, also known as a tuple)

and it seems object shapes are not accepted either: https://phpstan.org/writing-php-code/phpdoc-types#object-shapes

I will have a look if I can make a PR.

**Comment by mvorisek** [comment]
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6962 fixed array shape parsing, but `phpdoc_var_without_name` rule still needs a fix
