### ISSUE TITLE
[PHP8.3] Support for typed class constants

### ISSUE THREAD

**Issue by Wirone** [PHP-CS-Fixer/PHP-CS-Fixer#6999]
The goal is to add support for [typed class constants](https://wiki.php.net/rfc/typed_class_constants).

Related code changes:
- #7055
- #7009

What needs to be done to achieve full support:
- [x] Test cases added to integrations test suite
- [ ] All built-in fixers tested against typed constants syntax

**Comment by SpacePossum** [comment]
> dynamic class constant fetch syntax

is not related to `typed class constants ` so I think this should be another issue

**Comment by Wirone** [comment]
> > dynamic class constant fetch syntax

> is not related to `typed class constants ` so I think this should be another issue 

It was only copy&paste issue (from 6998), thanks for noticing, fixed now 👍.

**Comment by Wirone** [comment]
After integration test was added for 8.3 and works OK, we can close this as completed - there's no easy way to verify all the rules, so we will observe the feedback from the users 🙂.
