### ISSUE TITLE
PhpdocToCommentFixer false positives with enums

### ISSUE THREAD

**Issue by enumag** [PHP-CS-Fixer/PHP-CS-Fixer#7030]
### Description

I have an enum type and want to deprecate some of the cases.

PhpdocToCommentFixer however wants to change these docblocks to regular comments.

### Runtime version

v3.16.0

### Used command

I'm using php-cs-fixer through symplify/easy-coding-standard so this is irrelevant.

### Configuration file

I'm using php-cs-fixer through symplify/easy-coding-standard so this is irrelevant.

### Code snippet that reproduces the problem

```php
enum MyEnum: string
{
    case A = 'a';

    case B = 'b';

    /**
     * @deprecated use D instead
     */
    case C = 'c';

    case D = 'd';
}
```

**Comment by Wirone** [comment]
Sorry for the noise, I won't use issues' references in commit messages again 😆.
