### ISSUE TITLE
No space before braces on control

### ISSUE THREAD

**Issue by ShockedPlot7560** [PHP-CS-Fixer/PHP-CS-Fixer#7036]
## Rule request

The rule would allow you to specify that you don't want spaces in front of ``{`` for all control instructions like: ``class``, ``function``, ``if``, ``while``, ``switch``, ``try``

### Code snippet that shows how the rule would fix PHP code

```diff
<?php

-if (true) {
+if (true){
}

-function test() : void {
+function test() : void{
}

...
```

**Comment by Wirone** [comment]
Hi @ShockedPlot7560, I don't have good news: this is not going to happen. Fixer promotes standards, current one is [PER-CS](https://www.php-fig.org/per/coding-style/) which has clear stance about curly braces. We already have rules for enforcing space between constructs, braces etc. Maintaining all of those rules is not easy and we won't add another one, especially something that we don't agree with and won't use.

Such fixer can be created and used as [custom rule](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/custom_rules.rst). It won't be included in the core.
