### ISSUE TITLE
`isset($this) ? $this :` should not be transformed to `$this ??` as not equivalent

### ISSUE THREAD

**Issue by kylekatarnls** [PHP-CS-Fixer/PHP-CS-Fixer#7051]
### Description

PHP-CS-Fixer suggests to replace `isset($this) ? $this : new $baseClass()` with `$this ?? new $baseClass()` but when using this code in a `Closure` and this closure is executed without bound context, the first syntax works fine while the second that CS-Fixer suggests will throw:
```
Error : Using $this when not in object context
```

### Runtime version

`3.17.0`

### Used command

```
./vendor/bin/php-cs-fixer fix -v --diff --dry-run
```

### Configuration file

```php
<?php

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

return (new Config())
    ->setRules(['@PHP71Migration' => true])
    ->setFinder(
         Finder::create()
            ->in(__DIR__)
            ->path('file.php')
     )
     ->setUsingCache(true)
     ->setRiskyAllowed(true);
```

### Code snippet that reproduces the problem

**file.php**

```php
<?php

$f = function () {
    return isset($this) ? $this : 42;
};

echo $f();
```

This output `42`

Fix it with CS-Fixer (using `@PHP71Migration`)

```php
<?php

$f = function () {
    return $this ?? 42;
};

echo $f();
```

And now running it you get:
```
Fatal error: Uncaught Error: Using $this when not in object context
```

**Comment by Wirone** [comment]
@kylekatarnls please provide code snippet that reproduces the problem, so it can be verified.

**Comment by kylekatarnls** [comment]
**file.php**

```php
<?php

$f = function () {
    return $this ?? 42;
};

echo $f();
```

**Comment by kylekatarnls** [comment]
#7052 fixes the issue.
