### ISSUE TITLE
Make `native_constant_invocation` platform independent

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7074]
## Feature request

In a lot of projects we use `pcntl` constants, but with the default option - non-user constants prefixed with `\`, the PHP CS Fixer is unstable between linux and Windows, because the pcntl extension is for linux only, thus this issue cannot be fixed by installing all extensions on Windows, it is simply impossible.

Currently the best/working workaround is to include the constants in each project's config manually.

I submit this as a feature request to define all php-src constants, or at least the ones that are platform dependent, in PHP CS Fixer directly.

source: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.18.0/src/Fixer/ConstantNotation/NativeConstantInvocationFixer.php

example diff from Windows:
![image](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/2228672/7c23b396-f53f-4c2f-8ffa-17aa7e50134d)

**Comment by SpacePossum** [comment]
TBH you might be better of using docker/VM on the windows-dev machines if your target environment is not windows,
but I'm sure you know that.
I don't think we can really solve this in a reliable matter other than allowing users to configure all const-names that should be fixed/ignored, but that seems like a hefty price.

**Comment by Wirone** [comment]
I would rather add an configuration option to the fixer that would allow defining set of constants that should be considered as native. This way it would be flexible enough to cover your (and any other) case, without the maintenance overhead related to keeping that constants' list up-to-date.

**Comment by mvorisek** [comment]
not stale
