### ISSUE TITLE
Regression in PHPDoc parsing since 3.19.2

### ISSUE THREAD

**Issue by oprypkhantc** [PHP-CS-Fixer/PHP-CS-Fixer#7093]
### Description

After upgrading to 3.19.2 from 3.18.*, a generic `array` inside a PHPDoc breaks:

```                               
        [Exception]                            
        Unable to parse phpdoc type 'string>' 

PhpCsFixer\DocBlock\TypeExpression->parse()
        in phar:///app/vendor/php-cs-fixer/shim/php-cs-fixer.phar/src/DocBlock/TypeExpression.php at line 200
```

### Runtime version

Broken on:
```
PHP CS Fixer 3.19.2 (210dd89) Triangle by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.9
```

Working on:
```
PHP CS Fixer 3.18.0 (b123395) Triangle by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.9
```

### Used command

`vendor/bin/php-cs-fixer fix -vvv --config=.php-cs-fixer.dist.php`

### Configuration file

```
return (new Config())
	->setFinder($finder)
	->setRiskyAllowed(true)
	->setIndent("\t")
	->setRules([
		'@PhpCsFixer'    => true,
	]);
```

### Code snippet that reproduces the problem

```
/**
 * @method self                          setOrderBy(array<string, string> $by)
 */
class ListDTO
{
}
```

**Comment by Wirone** [comment]
@mvorisek is it related to #7010?

**Comment by mvorisek** [comment]
Yes, I noticed it too for one `@method` tag in our workflow. I am on it already ;-)

The problem is some phpdoc is not parsed by regex by later expected to be parsed by the regex. Valid problem, we cannot assume a phpdoc will parse later.

**Comment by oprypkhantc** [comment]
Thank you :) Although they aren't part of PHPDoc, I believe these should be fixed. They've become quite widespread in the recent years, and are on their way to becoming on par with the basic PHPDoc tags.

**Comment by Wirone** [comment]
@oprypkhantc in the meantime you can downgrade to 3.19.1 since this parsing was introduced in 3.19.2 🙂.

**Comment by mvorisek** [comment]
They are phpdocs, but we do nto support parsing callable grammar fully yet. First, we must never parse anything that was not parsed before - this issue. Then we should be the support to actually be able to fix such docs.

**Comment by mvorisek** [comment]
@Wirone I would like to add a testcase to prevent simillar problem in the future, is there any place/test where I can assert some code is parseable and remain parseable/valid after running all fixers?
