### ISSUE TITLE
`phpdoc_types` Keeps changing Resource class reference to lowercase variant

### ISSUE THREAD

**Issue by ostrolucky** [PHP-CS-Fixer/PHP-CS-Fixer#7097]
## Bug report

php-cs-fixer keeps doing this
```diff
/**
- * @return Resource[]
+ * @return resource[]
 */
public function getRolePolicyResources(): array
{
    return $this->rolePolicyResources->toArray();
}
```

I assume this is because while we mean here reference to Reference **class** that is located in same namespace, php-cs-fixer understands here that we assumed [PHP's resource](https://www.php.net/manual/en/language.types.resource.php)

This happens when phpdoc_types is enabled with groups that contain `meta`

### Runtime version

PHP CS Fixer 3.19.2 Triangle by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.3

**Comment by mvorisek** [comment]
If `Resource` class is from the same level nothing can be done in order to fix `Resource` typos. But I can imagine checking if `Resource` was imported via use, if yes, then do not fix it. Will this approach solve your usecase?

**Comment by Wirone** [comment]
*If* fixer had autoloading context, it could check if there's `Resource` class in current namespace, and skip refactoring if needed. But with such simplified approach (single file) it's hard to distinguish if it's a class name or reserved keyword...

**Comment by ostrolucky** [comment]
`Resource` is in same NS level so no import there :/

**Comment by mvorisek** [comment]
PHP CS Fixer is not a static analyser and looking into other files is not wanted by design. You should use specific config. Maybe `use SameNs\Resource as MyResource;` workaround can work if you use this class heavily.

**Comment by Wirone** [comment]
@ostrolucky for the record: there is #4159 (and there was even PR at some point), so workaround proposed by @mvorisek won't help if you use `no_unused_imports`. As of now the only workaround would be configuring `groups` to not include `meta`, so `Resource` won't be lowercased (but unfortunately it will affect other meta-types).

**Comment by mvorisek** [comment]
> so workaround proposed by @mvorisek won't help if you use `no_unused_imports`. As of now the only workaround would be configuring `groups` to not include `meta`, so `Resource` won't be lowercased (but unfortunately it will affect other meta-types).

@Wirone really? `use SameNs\Resource as MyResource;` (with `as`/alias) should never be removed, as alias might resolve conflict of otherwise existing other class!

**Comment by Wirone** [comment]
@mvorisek what I meant is just using import for the same namespace, without aliasing (hence linked issue). I don't know how it behaves with import, I believe it won't touch such symbols, but personally I wouldn't want to do such aliasing anyway.

Also, @ostrolucky please keep in mind that `resource` is [soft-reserved keyword](https://www.php.net/manual/en/reserved.other-reserved-words.php) in PHP and using it as class name is discouraged (it's even reported by [PHPCompatibility](https://packagist.org/packages/phpcompatibility/php-compatibility)). That's why I personally see this as low-priority issue.

**Comment by ostrolucky** [comment]
fair enough, let's close then
