### ISSUE TITLE
statement_indentation conflicts with PhpStorm block comment

### ISSUE THREAD

**Issue by althaus** [PHP-CS-Fixer/PHP-CS-Fixer#7121]
## Bug report

In the current 3.20.0 release we encounter an issue with the `statement_indentation` rule and using PhpStorm to disable code with block comments as those are not intended.

### Runtime version

~~~
PHP CS Fixer 3.20.0 Triangle by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.20
~~~

### Used command

~~~
/tools/php-cs-fixer fix --dry-run --diff -v
~~~

### Configuration file

~~~
<?php

$finder = PhpCsFixer\Finder::create()
    ->in([__DIR__ . '/src', __DIR__ . '/config', __DIR__ . '/tests'])
;

$config = new PhpCsFixer\Config();

return $config
    ->setRules([
        '@PSR12' => true,
        'array_syntax' => ['syntax' => 'short'],
        'no_unused_imports' => true,
        'trailing_comma_in_multiline' => true,
    ])
    ->setFinder($finder)
;
~~~

### Code snippet that reproduces the problem

Write some code and use PhpStorm to disable a method with a comment:

 ```php
<?php

class Acme
{
//    public function foo(): void
//    {
//        // some code
//    }
}  
  ```

Starting sometime ago PHP-CS-Fixer insists on reformatting this due to the `statement_indention` rule:

  ```php
<?php

class Acme
{
    //    public function foo(): void
    //    {
    //        // some code
    //    }
  ```
  
This is quite a hassle for our quite huge code base. 

Is there a way to disable the check for such code parts?

Kind regards
Matthias

**Comment by Wirone** [comment]
In short: commented out code = unneeded code. This should be just removed, VCS is for keeping history.

Fixer does not know what is inside the comment, from tool's perspective this is just a comment inside a class, so ot should be indented 🙂.

And no, it's not possible to disable code fixing for part of the code.
