### ISSUE TITLE
`fully_qualified_strict_types` removes leading `\` when used in global namespace

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7133]
## Feature request

Current behavior:

```diff
   1) parts/Xxx.php (fully_qualified_strict_types)
      ---------- begin diff ----------
--- /builds/xxx.php
+++ /builds/xxx.php
@@ -1058,7 +1058,7 @@
         $this->rewind();
     }
 
-    public function current(): \Foo
+    public function current(): Foo
     {
         if ($this->currentValue !== null) {
             return $this->currentValue;
      ----------- end diff -----------
```

I believe this fixer should allow to keep leading slash, as `\Closure` is the preferred CN when NS is used. When no NS is used, it should not be different and makes future migration easier.

### Runtime version

3.21.1 / latest

### Used command

`fix`

### Configuration file

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in([__DIR__]);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setRules([
        '@PhpCsFixer' => true,
        '@PhpCsFixer:risky' => true,
        '@PHP74Migration' => true,
        '@PHP74Migration:risky' => true,
    ])
    ->setFinder($finder)
    ->setCacheFile(sys_get_temp_dir() . '/php-cs-fixer.' . md5(__DIR__) . '.cache');
```

### Code snippet that reproduces the problem

```php
<?php

class FooIterator implements \Iterator
{
    public function current(): \Foo
    {
        $this->currentValue = new \Foo();

        return $this->currentValue;
    }
}
```

**Comment by Wirone** [comment]
It's not a bug, bug expected behavior. `fully_qualified_strict_types`'s description clearly states:

> Transforms imported FQCN parameters and return types in function arguments to short version.

Several enhancement requests can be found under [`topic/fqcn`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues?q=is%3Aopen+is%3Aissue+label%3Atopic%2Ffqcn). Feel free to contribute 😉.

**Comment by mvorisek** [comment]
But all other fixers allow `\` even with global NS. I belive this fixer should allow/keep it as well, as `\Closure` is the preffered CN when NS is used. When no NS is used, it should not be different and makes possible future migration easier.

**Comment by Wirone** [comment]
What "all other fixers" you mean? There's only [`global_namespace_import`](https://cs.symfony.com/doc/rules/import/global_namespace_import.html#rule-global-namespace-import) in terms of FQCNs.

We may consider it as a bug if it worked differently before, but if it was always like that, then it should be a feature request (configurable option).

**Comment by mvorisek** [comment]
I know FQCN/short CN is not fully fixed yet, but in the example, `\` before other (FQ)CN is kept. And it is style I prefer, so I think `fully_qualified_strict_types` should support keeping `\` even if the script NS is global (has no NS).

**Comment by Wirone** [comment]
I believe it keeps `\` in `new \Foo()` because fixer does not react to such usages, as description states. If it had support for object initialising or class properties, then it would work the same in those places.

@kubawerlos I don't see [test case for that](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php), do you think it's a bug or expected behavior?

**Comment by kubawerlos** [comment]
Hard to tell, current behavior doesn't seem to be wrong, so I'd say let's document it with a test and maybe then change it as a feature.

**Comment by mvorisek** [comment]
Thank you, can we please get this issue reopened as a feature?
