### ISSUE TITLE
A lot of different code style issues + bugs occurred in 3.21.2

### ISSUE THREAD

**Issue by apfelbox** [PHP-CS-Fixer/PHP-CS-Fixer#7158]
### Description

A weird new CS issue occurred with several different issues:

```diff
 	/**
-	 */
-	public function getAttributes () : array
-	{
-		return $this->attributes;
+	 */ public function getAttributes () : array
+	{ return $this->attributes;
 	}
 ```

or 

```diff
-			// if there are no changed locales -> we are immediately done
-			if (empty($locales))
+			// if there are no changed locales -> we are immediately done if (empty($locales))
 			{
```

or

```diff
 		$lock = $this->lockFactory->createLock(self::LOCK_KEY);

-		if (!$lock->acquire())
-		{
-			return false;
+if (!$lock->acquire())
+		{ return false;
 		}
```

This issue first occured with `3.21.2`, is still present in `3.22.0` and is not present in `3.21.1`.

### Runtime version

PHP CS Fixer 3.21.2 Triangle by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.7

### Used command

```bash
./vendor/bin/php-cs-fixer fix --diff --config vendor-bin/cs-fixer/vendor/21torr/php-cs-fixer/.php-cs-fixer.dist.php -vvv
```

### Configuration file

https://github.com/21TORR/php-cs-fixer/blob/1.x/.php-cs-fixer.dist.php

**Comment by Wirone** [comment]
Thanks @apfelbox for the report, we will investigate it. Weird thing is 3.21.2 was a technical release with many DX improvements, not related to fixers' logic... Your code should remain the same.

Can you run fixer with `--verbose --diff` and tell us which fixer does this change? You should see list of applied fixers above the diff. You can also provide minimal reproduction snippet so we can debug it.

**Comment by Wirone** [comment]
Closing as [feedback](#issuecomment-1637681460) was not provided for 5 months.
