### ISSUE TITLE
self_accessor should correctly replace self in bound closures

### ISSUE THREAD

**Issue by vudaltsov** [PHP-CS-Fixer/PHP-CS-Fixer#7163]
## Bug report

Currently PHP-CS-Fixer always replaces class with self, even in \Clos

### Description

Consider code:

```php
<?php

final class A
{
    public static function a(): void
    {
        (function () {
            var_dump(self::class, A::class);
        })->bindTo(null, B::class)();
    }
}

final class B {}

A::a();
```

Here we should not replace `A::class` with `self::class`, because within bound closure `self` is `B`, not `A`.

https://3v4l.org/38GQA

**Comment by SpacePossum** [comment]
>Since this issue has not had any activity within the last 90 days, I have marked it as stale.

it got a PR opened for it 2 weeks ago, also, valid code-breaking-bugs should never be labelled `stale` IMHO
