### ISSUE TITLE
Keep only description when applying `no_superfluous_phpdoc_tags`

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7174]
## Feature request

Example:

```php
class Foo
{
    /** @var string Desc */
    public string $name;
}
```

should be fixed to:

```php
class Foo
{
    /** Desc */
    public string $name;
}
```

**Comment by Wirone** [comment]
If there's `/** @var string */` then it's removed. So you basically want to remove type declaration from phpDoc when additional description is provided, and as an output you would like to keep only description? I believe it's not phpDoc anymore, so it's not `/**` but `/*` or even regular inline comment `//`.

I believe it should be behind config flag, unless we consider it as a bug and change current behavior 😉.

**Comment by SpacePossum** [comment]
I think it is up for debate if `/** Desc */` is a valid PHPDoc and therefore a desirable result made by the rule,
since it doesn't create this output and it does not by design it is not a bug from my POV.

(than again doc-to-comment rule will like change it to a comment anyways).

**Comment by mvorisek** [comment]
not stale

**Comment by mvorisek** [comment]
not stale

**Comment by Wirone** [comment]
Not reproducible anymore:

<img width="794" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/b5514054-d3ed-4b7e-832c-2f5b57c6a72f">

<img width="794" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/eec79f26-2335-4eda-b52a-c34b7cbe7bc2">

I will leave it closed.
