### ISSUE TITLE
BlankLineBeforeStatementFixer should not touch enum cases

### ISSUE THREAD

**Issue by paulbalandan** [PHP-CS-Fixer/PHP-CS-Fixer#7196]
### Description

When given a series of enum cases, `blank_line_before_statement` fixer adds whitespaces in between enum cases if `case` is added to list of statements.

### Runtime version

PHP 8.2.8
PHP-CS-Fixer v3.22

### Used command

`vendor/bin/php-cs-fixer fix -v`

### Configuration file

```
'blank_line_before_statement' => ['statements' => ['case']]
```

### Code snippet that reproduces the problem

```php
<?php

enum Foo
{
    case Bar;
    case Baz;
}

```

Even when adding `class_attributes_separation => [elements => [case => none]]` does not help as the fixer runs before `blank_line_before_statement`.

**Comment by Wirone** [comment]
Duplicates #6747.
