### ISSUE TITLE
phpStorm: Complains about too high php version

### ISSUE THREAD

**Issue by lilalunex** [PHP-CS-Fixer/PHP-CS-Fixer#7202]
phpStorm shows this error when I open a php File for some seconds:

```
phpcs: PHP needs to be a minimum version of PHP
7.4.0 and maximum version of PHP 8.1.*,
Current PHP version: 8.2.7.
To ignore this requirement please set
'PHP CS_FIXER_ IGNORE_ENV
If you use PHP version higher than supported, you may experience code modified in a wrong way.
Please report such cases at
https://github.com/FriendsOfPHP/PHP-CS-Fixer.
```

[image](https://ibb.co/xXX5YRg)

In the image you can see that php is set to 8.0.
Also in the PHP Settings I have the php language level set to 8.

I am having a shopware 6.4 installation, done with devenv and composer.

### Runtime version

PHP CS Fixer 3.8.0 BerSzcz against war! by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.0.29

### phpStorm version

PhpStorm 2023.1.3
Build #PS-231.9161.47, built on June 22, 2023

**Comment by Wirone** [comment]
This is not a bug, support for PHP 8.2 was enabled in Fixer v3.15, so you need to upgrade to at least that version.
