### ISSUE TITLE
Group imports only in functions

### ISSUE THREAD

**Issue by nunomaduro** [PHP-CS-Fixer/PHP-CS-Fixer#7220]
Given the example below, is it possible to group only the imports of functions?

```diff
<?php

use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;


-use function Laravel\Prompts\confirm;
-use function Laravel\Prompts\multiselect;
-use function Laravel\Prompts\select;
+use function Laravel\Prompts\{confirm, multiselect, select};

class InstallCommand extends Command
{
    // ...
}
```

**Comment by Wirone** [comment]
Currently `group_import` is not configurable in any way, it just groups everything (with classes/functions separation). Feel free to contribute 🙂.

ℹ️ If anybody wants to implement it, then new config option should be introduced and by default fixer behave the same, so disabling classes/functions grouping should be done as an opt-out.

**Comment by Wirone** [comment]
@norberttech would you be also interested in this?

**Comment by norberttech** [comment]
> @norberttech would you be also interested in this?

Yes!!! 🙏I was actually going to ask you how annoying it would be to allow for only functions grouping. Because hinestly, from my POV classes might stay as they are, I care mostly about functions.
