### ISSUE TITLE
`NoSuperfluousPhpdocTagsFixer` removes `@return null` in namespaced files

### ISSUE THREAD

**Issue by paulbalandan** [PHP-CS-Fixer/PHP-CS-Fixer#7233]
### Description

The `no_superfluous_phpdoc_tags` fixer removes `@return null` return types when in a namespaced file. This broke our phpstan build.

### Runtime version

PHP CS Fixer 3.23.1-DEV First Steps by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.8

### Used command

```
php php-cs-fixer fix -v reproducer.php --rules='{"no_superfluous_phpdoc_tags": {"allow_mixed": true, "allow_unused_params": true, "remove_inheritdoc": false}}'
```

### Configuration file

```
'no_superfluous_phpdoc_tags'   => [
    'allow_mixed'         => true,
    'allow_unused_params' => true,
    'remove_inheritdoc'   => false,
],
```

### Code snippet that reproduces the problem

```php
<?php

namespace Bar;

class reproducer
{
    /**
     * @return null
     */
    public static function returnNull()
    {
        return null;
    }

    /**
     * @return null
     */
    public function returnsNull()
    {
        return null;
    }
}

```

With the removal of the returns, phpstan now complains the methods have no return type specified.
From #7189 this bug appears.

**Comment by mvorisek** [comment]
I will fix this.
