### ISSUE TITLE
Prevent spread operator from being passed to a function

### ISSUE THREAD

**Issue by maxm86545** [PHP-CS-Fixer/PHP-CS-Fixer#7256]
## Rule request

Prevent spread operator (`...`) from being passed to a function or method.

### Code snippet that shows how the rule would fix PHP code

```php
<?php

$a = [1, 2, 3];
f(...$a);

function f(int ...$a) {
}

```

```php
<?php

$a = [1, 2, 3];
f($a);

// + phpdoc list<int>?
function f(array $a) {
}

```

The spread operator to pass to a function affects performance and memory consumption.
https://3v4l.org/lfIEG
https://3v4l.org/n643B

P.S. [Use in an array](https://wiki.php.net/rfc/spread_operator_for_array) is allowed.

**Comment by Wirone** [comment]
Hi @maxm86545, thanks for the report, but it won't happen. It's not a spread operator, it's variadic argument and it has advantage over passing an array - you can enforce type for all passed elements with native type. Preventing it is nowhere near good practices that Fixer tries to propagate.

**Comment by maxm86545** [comment]
@Wirone Yes, but, unfortunately, this operation is expensive, it triples the memory. I'm not saying to remove this operator by default, the user should have a choice.

**Comment by Wirone** [comment]
I believe that passing 100000 variadic arguments to a function which causes more memory consumption is an edge case that we, as a core team of Fixer, shouldn't care about. If anyone uses variadic argument and spread operator to invoke such function, then maybe should take memory usage into consideration, but I don't see a point in making such fixer and maintaining it (well, at least not in the core).

**Comment by maxm86545** [comment]
100000 is a clear example. Maybe 100 times 100 elements.
Ok, your point is clear.
