### ISSUE TITLE
Deprecate PER-CS1.0

### ISSUE THREAD

**Issue by keradus** [PHP-CS-Fixer/PHP-CS-Fixer#7281]
after PER-CS2.0 was introduced #7249, we can deprecate PER-CS1.0

**Comment by Wirone** [comment]
IMHO we should add it to the checklist in #4502 because in order to provide full PER-CS v2 we need to finish v1. When all items from the checklist are done, then we can deprecate v1. Of course, we can finish v1 ruleset while it's deprecated, but it would look weird to work on deprecated set 😅.

**Comment by keradus** [comment]
v1 and v2 are having huge overlap - v2 is basically v1 extended by new language sugar syntax possibilities.

with that, i see no harm to add the rules for v1 if it's still around, or to v2 if v1 is gone by that moment.

With that, I would love to mark v1 as deprecated to indicate users that they should start migrating to v2.
