### ISSUE TITLE
 Two passes needed for no_superfluous_phpdoc_tags + phpdoc_add_missing_param_annotation

### ISSUE THREAD

**Issue by mlocati** [PHP-CS-Fixer/PHP-CS-Fixer#7294]
### Description

Two passes may be required if we use both `NoSuperfluousPhpdocTagsFixer` and `PhpdocAddMissingParamAnnotationFixer`.

### Runtime version

```
PHP CS Fixer 3.26.1 Crank Cake by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.33
```

### Configuration file

```php
<?php

$config = new PhpCsFixer\Config();

return $config
    ->setRules([
        'phpdoc_add_missing_param_annotation' => true
        'no_superfluous_phpdoc_tags' => true,
    ])
    ->setFinder(PhpCsFixer\Finder::create()
        ->in(__DIR__)
    )
;
```

### Code snippet that reproduces the problem

Let's assume we have this file:

```php
<?php

/**
 * @param int $bar Bar description
 * @param resource|null $baz=null Wrong baz description
 */
function foo($bar, $baz = null)
{
}
```

At the first pass, `NoSuperfluousPhpdocTagsFixer` changes it to

```php
<?php

/**
 * @param int $bar Bar description
 */
function foo($bar, $baz = null)
{
}
```

At the second pass, `PhpdocAddMissingParamAnnotationFixer` changes it to

```php
<?php

/**
 * @param int $bar Bar description
 * @param null|mixed $baz
 */
function foo($bar, $baz = null)
{
}
```

**Comment by impara** [comment]
Hi, I want to work on this issue....

**Comment by Wirone** [comment]
@impara great to hear! Take a look at contribution guide and other, merge PRs with `topic/priority` to get familiar with what kind of changes are needed (tests, priorities in the rules etc). Run `composer qa` locally to see the result, everything must pass 🙂. Good luck!
