### ISSUE TITLE
`single_line_empty_body` contradicts the PSR-12 code style

### ISSUE THREAD

**Issue by aragon999** [PHP-CS-Fixer/PHP-CS-Fixer#7298]
### Description

While we have not decided if we internally want to use the recently added rule `single_line_empty_body`, this contradicts the [PSR-12 code style](https://www.php-fig.org/psr/psr-12/#44-methods-and-functions): 

> The opening brace MUST go on its own line, and the closing brace MUST go on the next line following the body.

In the past, it was possible to use the two rulesets `@PSR12` and `@PhpCsFixer` and I did not notice any contradiction, but with the `single_line_empty_body` rule added to `@PhpCsFixer` ruleset they are not compatible anymore.

While I could of course adapt the config and add the `'single_line_empty_body' => false,` rule, it might be a general question what should happen in such cases. I am not sure if such a thing is in general considered a bug, or a misconfiguration. If it is not a bug, feel free to close this issue.

### Runtime version

```
PHP CS Fixer 3.26.1 (d023ba6) Crank Cake by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.10
```

### Used command

```
php-cs-fixer fix .
```

### Configuration file

```php
<?php 

return (new PhpCsFixer\Config())
    ->setRules([
        '@PSR12' => true,
        '@PhpCsFixer' => true,
    ])
;
```

### Code snippet that reproduces the problem

The following code which is PSR-12 compatible

```php
    public function updateDestructive(Connection $connection): void
    {
    }
```

will become code which violates the PSR-12 code style:

```php
    public function updateDestructive(Connection $connection): void {}
```

Edit: I just noticed, that by the new ["PER Code Style"](https://www.php-fig.org/per/coding-style/) this is added as a new rule:

> If a function or method contains no statements or comments (such as an empty no-op implementation or when using constructor property promotion), then the body SHOULD be abbreviated as {} and placed on the same line as the previous symbol, separated by a space.

Now I am even more unsure how this should be handled.

**Comment by Wirone** [comment]
You're using opinionated `@PhpCsFixer` which may be changed at any point. It currently extends `@PER-CS2.0`, which recommends `single_line_empty_body`. This behaviour is expected, hence it's not a bug. If you don't like this new behaviour, you can disable it in your config with `"single_line_empty_body" => false`.
