### ISSUE TITLE
Make GetClassToClassKeywordFixer check composer.json require

### ISSUE THREAD

**Issue by samsonasik** [PHP-CS-Fixer/PHP-CS-Fixer#7310]
## Feature request

Hi, I think for `GetClassToClassKeywordFixer`, it is better to check what required in composer.json, eg:

```
"php": "7.4 || ^8.0"
```

that check composer.json's php 7.4 only so not apply `::class`.

Thank you.

**Comment by keradus** [comment]
Hey, thanks for raising this idea!

Right now, PHP CS Fixer runs against source-files context-less (Fixer doesn't know content of other files while fixing given file), and changing it would require well-prepared solution.

Same time, I actually plan to deprecate 7.4 soon, thus I'm not eager to put any effort to build features dedicated for it.

I always encourage to run Fixer on lowest supported PHP version of your project, so you won't experience such fixes toward high-end version if you are not able to commit them in codebase yet.

ref https://packagist.org/packages/friendsofphp/php-cs-fixer/php-stats#3.27

Thanks for your understanding!

**Comment by keradus** [comment]
-=> https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/7312
