### ISSUE TITLE
`no_unneeded_control_parentheses` does not remove parentheses in logical expression

### ISSUE THREAD

**Issue by maurei** [PHP-CS-Fixer/PHP-CS-Fixer#7326]
### Description

I've enabled the following rule
```
'no_unneeded_control_parentheses' => array('statements' => array('break', 'clone', 'continue', 'echo_print', 'return', 'switch_case', 'yield', 'yield_from')),
```

I would expect the snippet:
```php
echo ("foo");
return false || (true) || (false);
```
to be fixed to:

```php
echo "foo";
return false || true || false;
```

but instead I get
```php
echo "foo";
return false || (true) || (false); // <-- not removed
```

### Runtime version

```
PHP CS Fixer 3.15.1 BoY42 by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.10
```

**Comment by SpacePossum** [comment]
This rule only removes not needed parentheses when used in combination of the (configured) (control) constructs.
There is not rule to remove not needed parentheses used in logical comparisons.
Would be great to have such rule, but for now I think this is a FR and not a bug.
