### ISSUE TITLE
Consider renaming `new_with_braces` to `new_with_parentheses`

### ISSUE THREAD

**Issue by localheinz** [PHP-CS-Fixer/PHP-CS-Fixer#7328]
## Feature request

Following the merge of #7284, I wondered whether it would make sense to rename the `new_with_braces` fixer to `new_with_parentheses`:

- brackets: `[`, `]`
- braces: `{`, `}`
- parentheses: `(`, `)`

Also see https://practicaltypography.com/parentheses-brackets-and-braces.html and other sources on the internet about the differences between brackets, braces, and parentheses.

**Comment by Wirone** [comment]
I believe it's covered by #5915 ([see this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/5915#issuecomment-974674378)) and we should continue that PR (CC: @keradus). Probably we don't need this issue to be open, to keep track of it 🙂.

**Comment by localheinz** [comment]
Thank you, @Wirone!

**Comment by keradus** [comment]
@localheinz , would you like to raise some PRs around?

**Comment by localheinz** [comment]
@keradus 

👍
