### ISSUE TITLE
Update the `phpdoc_to_comment` rule to recognize annotations for generic traits

### ISSUE THREAD

**Issue by f-lombardo** [PHP-CS-Fixer/PHP-CS-Fixer#7359]
## Feature request

Update the `phpdoc_to_comment` rule to recognize annotations for generic traits: https://phpstan.org/blog/generics-by-examples#specify-template-type-variable-of-a-generic-trait-when-using-it.

At the moment annotation like `/** @use Part<T> */` are changed to  `/* @use Part<T> */`

**Comment by EldoranDev** [comment]
Hi,

tried to grab this, but failed to replicate.

Added a [test case](https://github.com/EldoranDev/PHP-CS-Fixer/commit/276769a89d63248929fa545467b8d0b96efc8f16) for this issue, [but all tests are still passing](https://github.com/EldoranDev/PHP-CS-Fixer/actions/runs/6460416608/job/17538069859), do you have a sample to reproduce this?

I also tried to reproduce with the following code sample:

```php
<?php

namespace Marcel\PhpcsTest;

/** @template T of object */
class TestClass
{
    /** @use TestTrait<T> */
    use TestTrait;
}
```

And applied php-cs-fixer to it, but it did not replace the comment by default. Are you running a certain set of rules that might cause this?

**Comment by f-lombardo** [comment]
Hi, here is my use case:

```php
/**
 * @template T of object
 */
trait ObjectConversionTrait
{
    /**
     * @param T $object
     *
     * @throws \ReflectionException
     */
    public function someMethod(mixed $object): void
    {
       //.....
    }
}

class CreateOnboardingInput extends UserInput
{
    /**
     * @use ObjectConversionTrait<CreateUserInput>
     **/
    use ObjectConversionTrait;
}
```

And here is my .php-cs-fixer.dist.php file:

```php
<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude('var')
;

return (new PhpCsFixer\Config())
    ->setRules([
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
        'phpdoc_to_comment' => false, // This is needed for enabling '@use ObjectConversionTrait' phpdoc
    ])
    ->setFinder($finder)
;
```

**Comment by Wirone** [comment]
Not reproducible on Fixer v3.37.2-DEV:

<img width="1199" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/dba31bd1-6964-4453-8a58-2689a6b89009">

phpDoc is not changed to comment even if `phpdoc_to_comment` is enabled (IMHO example provided above by @f-lombardo does not make sense because with `phpdoc_to_comment` set to `false` this fixer just can't apply any changes 🤷‍♂️). Please upgrade Fixer to latest version 🙂.
