### ISSUE TITLE
braces_position only supports two options to configure

### ISSUE THREAD

**Issue by CMalvika** [PHP-CS-Fixer/PHP-CS-Fixer#7380]
## Feature request

  Thanks a lot community for a constant support.
  
  We are constantly using braces fixer, previously it was braces, then renamed to curly_braces_position and now renamed again to braces_position.
  
  With previous rule we had a patch and i've even opened a pull request to merge. But by the time this fixer gets toomany updates my PR is already outdated.
  
  Our problem is:
  Currently braces_position has only two options to configure:
  1. next_line_unless_newline_at_signature_end
  2. same_line
  
  We always prefer to put braces in the next line, so i choose to configure next_line_unless_newline_at_signature_end:
  It will work for below:
  ```
public function sync(Arg1 $arg1, Arg2 $arg2)
  {
          // Some logic
  }
```
But it will not work for below:

```
public function sync(
    Arg1 $arg1, 
    Arg2 $arg2,
    Arg3 $arg3,
    Arg4 $arg4
)
  {
          // Some logic
  }
```

With above multiline argument functions braces will always move on the same line, however we prefer to stay it in the next line only.

**Comment by keradus** [comment]
Hi and thanks for your request.

Is this part of a standard or used by a bigger (F)OSS community? For us that is a condition to add a rule to this project. Otherwise, you can create a custom fixer and use that in your projects. Thanks for understanding.

**Comment by Wirone** [comment]
Closing as [no answer was provided](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7380#issuecomment-1788073482) for months.
