### ISSUE TITLE
Allow setting default path mode in config

### ISSUE THREAD

**Issue by ruudk** [PHP-CS-Fixer/PHP-CS-Fixer#7426]
## Feature request

In our project, we want to enforce that everyone always uses `--path-mode=intersection`. 

PHP-CS-Fixer should only touch files that we want it to touch.

If someone configures PHP-CS-Fixer in PHPStorm, they have to make sure they set `--path-mode=intersection` for this to work properly.

It would be great if we could move this to the `.php-cs-fixer.php` file so that it's fixed for everyone.

**Comment by keradus** [comment]
I think it's OKeysh, but I would rather do this:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/7440

then, for v3, you can achieve the new behaviour by using `putenv('PHP_CS_FIXER_FUTURE_MODE=1')` in your config file

**Comment by ruudk** [comment]
Keep open
