### ISSUE TITLE
`FullyQualifiedStrictTypesFixer` removes leading backslash without properly imported symbol

### ISSUE THREAD

**Issue by Wirone** [PHP-CS-Fixer/PHP-CS-Fixer#7458]
## Bug report

`FullyQualifiedStrictTypesFixer` removes leading backslash from FQCN when there's almost identical import in the file.

### Runtime version

PHP CS Fixer 3.39.1-DEV Getting Ready by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.10

### Used command

`./php-cs-fixer check --verbose --diff reproducer.php --rules=fully_qualified_strict_types`

### Code snippet that reproduces the problem

```php
<?php

use XYZ\A;

function Foo(\XYZ\AT $f)
{
}
```

```diff
-function Foo(\XYZ\AT $f)
+function Foo(XYZ\AT $f)
 {
 }
```

**Comment by kubawerlos** [comment]
> `FullyQualifiedStrictTypesFixer` removes leading backslash from FQCN when there's almost identical import in the file.

It removes the leading backslash also without that import, I believe because the code is in global namespace.

**Comment by Wirone** [comment]
Ah, that's a good point! Honestly I did not think about it much, I just checked if it's failing on the main branch too, to verify if I broke something during the "rebase". So I created an issue to go back to it at some point, but maybe it can be just closed 🙂.
