### ISSUE TITLE
Links to source class in all rules documents are broken (lead to 404 on github)

### ISSUE THREAD

**Issue by gguenther24** [PHP-CS-Fixer/PHP-CS-Fixer#7484]
### Description

When I look at rules documentation directly within github like [method_argument_space.rst](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/function_notation/method_argument_space.rst) the link to the source class at the very end of the page is broken and leads to a 404 page.
For [method_argument_space.rst](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/function_notation/method_argument_space.rst) it links to [./../src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php) instead of [./../../../src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php).
I've seen this issue on many rules documentation pages.

### Runtime version
* latest chrome web browser
* looking at rules documentation in the master branch

**Comment by Wirone** [comment]
Hi @gguenther24, thanks for reporting this 🙂. The tricky part is that [docs](https://cs.symfony.com/doc/rules/function_notation/method_argument_space.html) are generated from these source files, so it has to be done in a way that URL is correct in both places.

**Comment by keradus** [comment]
I build 3.40.2 with this single fix only, looks to be working properly now, for both MD files and HTML files.
