### ISSUE TITLE
chore: remove deep dependency declaration of `pdepend/pdepend` when it's compatible with Symfony 7

### ISSUE THREAD

**Issue by keradus** [PHP-CS-Fixer/PHP-CS-Fixer#7517]
- [x] Wait for https://github.com/pdepend/pdepend/issues/695
- [ ] Remove explicit `pdepend/pdepend` constraint from `dev-tools/composer.json` (introduced [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7513))

_Originally posted by @keradus in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7513#discussion_r1419230161_

**Comment by GrahamCampbell** [comment]
FYI, a stable version has now been released.

**Comment by keradus** [comment]
nice!
would you like to send a PR, perhaps ?

**Comment by GrahamCampbell** [comment]
Already pulling the codebase. ;)
