### ISSUE TITLE
CI: Fix MessDetector step

### ISSUE THREAD

**Issue by keradus** [PHP-CS-Fixer/PHP-CS-Fixer#7518]
[Mess Detector step is not triggered](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/actions/runs/8350059967/job/22855643559):

<img width="460" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/f3a5a3fb-7cff-446b-a351-d35e431631f2">

**Comment by Wirone** [comment]
@keradus Mess Detector is already added (there are steps in the job), but actual step is not triggered. So it's rather "fix", not "add" 😉.
