### ISSUE TITLE
PSR12 breaks compatibility with PHP7.0

### ISSUE THREAD

**Issue by mdeweerd** [PHP-CS-Fixer/PHP-CS-Fixer#7526]
## Bug report
(This is neither a feature nor a bug, but somewhere in between, and as it breaks PHP7.0 compatibility, it's closer to a bug).

When applying the PSR12 ruleset, the following override the rule of @PSR2:
```
            'visibility_required' => true,
```

That applies breaking changes for PHP7.0 by introducing "public const" .

I suggest that version upgrades would be limited to the specific rule sets such as "PHP71Migration" where `'visibility_required' => true,` is also set.

I do not know if there are other overrides like that, but IMHO this principle should apply to all rules that "upgrade" the code from one php version to another.

**Comment by mdeweerd** [comment]
> Minimal version supported by Fixer is PHP 7.4

Because Fixer requires a minimum version to run, does not have to imply that it can applies rules for the minimal version.  A static rule checker such as "Phan" runson on PHP8+ but has an option to set the minimal version you want to maintain compatibility with.

I suppose that the latest version has fixes that are not available on the PHP7.0 compatible version of php-cs-fixer.

For any other reader of this issue, the following still applies the visibility directives that are still compatible with PHP7.0:
```
    'visibility_required' => ['elements'=>['property', 'method']],
```

**Comment by mdeweerd** [comment]
>We consider runtime PHP version as the one for triggering (or not) rules and fixes

"One of" - if the PHP version would be one of the triggereing rules then all migrations up to the PHP version that is being run should be applied by default.
That is not the case, and I think that this should apply to the visibility rule as well which is already set in a migration ruleset for users that explicitly decide to upgrade.
Currently it looks like an unannounced incompatible upgrade while on the other hand care was taken to separate risky migrations from others.

> so if we wanted to handle visibility on PHP7.0,  we would need to write Fixer's code compatible with it.

The question is not to have the possiblity to apply rules for PHP8.1 when the tool is run with a PHP7.0 version, but the not apply certain code upgrades when running it with PHP8.
Certain non breaking code upgrades may be(come) available in the php-cs-fixer running on PHP8.3 for instance, but non in the PHP7.0 version (utf8_decode for instance).  So running the latest php-cs-fixer version may also be useful.

Projects generally try ("have to") maintain compatibility with old PHP versions and recent PHP versions at the same time.

**Comment by Wirone** [comment]
Let's emphasise it again:
- Fixer's codebase uses PHP7.4 features so it can't be run on lower versions, because it would fail
- at the same time Fixer rules are conditional based on _runtime_ PHP version, so it's highly coupled with Fixer's PHP requirements

Combine these 2 things and you'll get why it's _now_ impossible to support 7.0. I am not saying it's not possible in general, I just told you that current state of the tool does not allow it. I would love it if Fixer was _target_ PHP version aware and could fine-tune its rules based on that, so it could be run on 8.3 and at the same time could apply fixes to make code compatible with 7.0, but unfortunately it is what it is. Even if we added conditions to `visibility_required` rule, it would not prevent you from applying it, because there's no way to tell Fixer to compare against specific PHP version, Fixer does not have that concept right now.

Summary: I agree with you in general, and I know that many tools support older versions of PHP (in several ways), but I just can't keep this issue open until we rewrite Fixer and change the approach that would be based on _target_ PHP version (I am not even sure if @keradus would be open for going back to older PHP versions).

**Comment by mdeweerd** [comment]
> Fixer's codebase uses PHP7.4 features so it can't be run on lower versions, because it would fail

I understand that, and that's not what this item is about.  The question is not to be able to run the latest php-cs-fixer tool itself on PHP7.0.

> Fixer rules are conditional based on runtime PHP version, so it's highly coupled with Fixer's PHP requirements

Possibly, but that is not the case for the visibility rule.  An surely the fixer needs to run on a recent version to be able to analyse backwards incompatible code it is fixing.


The visibility rule that I refer is one that is ok in the PSR2 ruleset that is set in a PHP7.0 compatible manner, but overridden in the PSR12 ruleset by setting it to true - even when PHP-CS-FIXER is run on a PHP8.1 version.
The rule could simply not be set in the PSR12 rule set and the PSR2 rule would apply.

I do not know if any other incompatibilities could occur by changes made by PHP-CS-FIXER and IMHO this should be at the very least be mentioned in the main README.

Initial suggestion:

:warning: Running PHP-CS-FIXER on your code with a php version that is higher than the minimum php version you want to support for your code will likely create incompatibilities between your code and the targeted PHP versions.
See SPECIFIC_PAGE.

# SPECIFIC_PAGE

BLABLA...

Known incompatibilities are:
- 'visibility': `const CONST=1;' may be converted to `public const CONST=1`;
- ... 
- 
The best guarantee to avoid these transformations is to run an old version of PHP-CS-FIXER by running it on the minimum PHP version that you target.

You can also set the rules listed below.
- `'visibility_required' => ['elements'=>['property', 'method']],`
- ... .

Remaining known implicatly generated incompatibilies are:
- ...
- ...

**Comment by keradus** [comment]
Any rule (or ruleset), when executed, must produce code that is compatible for runtime it is executed with.
IE, PSR12 ruleset executed under 8.1 must create code compatible for 8.1, but doesn't need to create code compatible for 7.4. Yet, PSR12 ruleset executed under 7.4 must create code compatible for 7.4

I'm very up for having a good warning when executing code on high PHP that shall be compatible for low PHP: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/7312
