### ISSUE TITLE
`no_useless_concat_operator` wrongly removes new lines when fixing

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7585]
## Bug report

```
$entity = 'a' . 'b'
    . 'c';
```
is currently fixed to:
```
$entity = 'ab' . 'c';
```
instead of to:
```
$entity = 'ab'
    . 'c';
```

This is clearly a bug in the fixing process and the result is currently not even stable (requires multiple passes to stabilize - to a wrong result though)

**Comment by Wirone** [comment]
IMHO it should be `$entity = 'abc';` done in one pass. What's your actual report, do you want to keep the new line and merge only strings in the same line 🤔?

**Comment by mvorisek** [comment]
To keep new lines, this is already fully supported, working well and needed for long strings.

**Comment by jlecordier** [comment]
> To keep new lines, this is already fully supported, working well and needed for long strings.

Should there be an option then ? To merge into a single line ?
