### ISSUE TITLE
Problem with PHP version 8.3

### ISSUE THREAD

**Issue by Yousha** [PHP-CS-Fixer/PHP-CS-Fixer#7596]
### Description

Im getting this error when trying to use PHPCS via **PHP 8.3**:

> PHP needs to be a minimum version of PHP 7.2.5 and maximum version of PHP 8.1.*.
> Current PHP version: 8.3.0.
> To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
> If you use PHP version higher than supported, you may experience code modified in a wrong way.
> Please report such cases at https://github.com/FriendsOfPHP/PHP-CS-Fixer .

### Runtime version

Can't use `php-cs-fixer -V`, because getting error!
But **composer.lock** file says that Im using **v3.4.0**

Interpreter: PHP 8.3 64bit TS
CLI: CMD and PowerShell
Platform: Windows 10 64bit
Hardware: x64 Intel
Environment: Development/Local

### Used command

`php-cs-fixer fix --no-ansi --verbose --dry-run --diff --format=xml --no-interaction ./web.php`

### Configuration file

Not used.

**Comment by Wirone** [comment]
Support for PHP 8.3 was officially added in [v3.40.0](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.40.0), so you need to upgrade Fixer in your project to this version. Alternatively you can set `PHP_CS_FIXER_IGNORE_ENV=1` when running Fixer to allow higher version of PHP. But using latest version of the tool is highly recommended 🙂.

**Comment by Yousha** [comment]
I think the problem is Packagist version config...

I used `composer require friendsofphp/php-cs-fixer` to install PHPCSFixer. So by your Packagist config, Im using latest Packagist version.

Here is my **composer.json** file:

```
    "require": {
        "friendsofphp/php-cs-fixer": "^3.4"
    },
```

See? version "^3.4" will be installed by default.

**Comment by kubawerlos** [comment]
> So by your Packagist config, Im using latest Packagist version.

What is "your Packagist config"? This one: https://packagist.org/packages/friendsofphp/php-cs-fixer, showing that latest version is v3.41.1?

```
kub@:~/code$ mkdir issue7596
kub@:~/code$ cd issue7596
kub@:~/code/issue7596$ composer require --dev --quiet friendsofphp/php-cs-fixer
kub@:~/code/issue7596$ composer show | grep fixer
friendsofphp/php-cs-fixer          v3.41.1 A tool to automatically fix PHP code style
```
☝🏼 shows it is fine.

My first guess is that PHP version is stopping you from installing newer version, see: [compare/v3.4.0...v3.5.0](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/compare/v3.4.0...v3.5.0#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34) - 3.4.0 supports PHP >= 7.2.5, when next one, 3.5.0 requires minimum PHP 7.4.

A second guess would be that other dependencies are blocking you from upgrading PHP CS Fixer, try:
```
composer why-not friendsofphp/php-cs-fixer ^3.40
```
