### ISSUE TITLE
Nowdoc/heredoc strings do not have whitespace removed from the end of them

### ISSUE THREAD

**Issue by maxbaldanza** [PHP-CS-Fixer/PHP-CS-Fixer#7609]
### Description
I'm using the NoTrailingWhitespaceFixer rule which I'd expect to trim whitespace from the end of heredoc/nowdoc string but it doesn't seem to do so.

I've wrote a failing test for this to help demonstrate the issue: https://github.com/maxbaldanza/PHP-CS-Fixer/pull/1

### Runtime version
3.41.1

### Example code
  ```php
  <?php
  $var = '<<<SQL
                SELECT 
                *
 SQL;';
 ```

**Comment by kubawerlos** [comment]
> I'd expect to trim whitespace from the end of heredoc/nowdoc

That would be a wrong expectation, it is [documented](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.41.1/tests/Fixer/Whitespace/NoTrailingWhitespaceFixerTest.php#L107) that this is not a case.

You might want to take a look at [`NoTrailingWhitespaceInStringFixer`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.41.1/doc/rules/string_notation/no_trailing_whitespace_in_string.rst).

**Comment by maxbaldanza** [comment]
> > I'd expect to trim whitespace from the end of heredoc/nowdoc
> 
> That would be a wrong expectation, it is [documented](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.41.1/tests/Fixer/Whitespace/NoTrailingWhitespaceFixerTest.php#L107) that this is not a case.
> 
> You might want to take a look at [`NoTrailingWhitespaceInStringFixer`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.41.1/doc/rules/string_notation/no_trailing_whitespace_in_string.rst).

Is that the correct link? The link you provided is to a test which I'm not sure is documentation.

Either way I'm also using the `[NoTrailingWhitespaceInStringFixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.41.1/doc/rules/string_notation/no_trailing_whitespace_in_string.rst)` and I still have the same issue. 

I've updated my test to there where I have the same issue: https://github.com/maxbaldanza/PHP-CS-Fixer/pull/1

**Comment by Wirone** [comment]
Our tests are kind of a contract because they show how fixers act _in practice_, so it's a backward-compatibility promise (not counting clear bugs, obviously). Actual docs are mostly for the usage.

**Comment by kubawerlos** [comment]
> I've updated my test to show that this has the same issue: [maxbaldanza#1](https://github.com/maxbaldanza/PHP-CS-Fixer/pull/1)

There are already test showing it works fine, like this one: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.41.1/tests/Fixer/StringNotation/NoTrailingWhitespaceInStringFixerTest.php#L113-L132

If you look at the `testFix` definition in `NoTrailingWhitespaceInStringFixerTest` then you will see that expected goes before input, and you have input before expected - when you swap them, the test is passing.

**Comment by maxbaldanza** [comment]
You are correct that `no_trailing_whitespace_in_string` does work as expected.

Sorry for this and really appreciate your help 🙌
