### ISSUE TITLE
Support for complex PHPDoc types in `fully_qualified_strict_types`

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7619]
## Feature request

With the latest release - v3.42.0 - the `fully_qualified_strict_types` rule does fix some phpdoc to imported types, but not all.

The following code:

```php
<?php

use DataTables;
use DataTables\Database;
use DataTables\Editor;
use DataTables\SearchPaneOptions;

/**
 * @param SearchPaneOptions|callable(Database, \DataTables\Editor): (array|bool) $spInput
 */
function searchPaneOptions($spInput = null) {}
```

is fixed to:
```php
<?php

use DataTables\Database;
use DataTables\SearchPaneOptions;

/**
 * @param SearchPaneOptions|callable(Database, \DataTables\Editor): (array|bool) $spInput
 */
function searchPaneOptions($spInput = null) {}
```
applied rules: braces_position, no_unused_imports, single_line_empty_body

but I would expect the following result instead:
```php
<?php

use DataTables\Database;
use DataTables\Editor;
use DataTables\SearchPaneOptions;

/**
 * @param SearchPaneOptions|callable(Database, Editor): (array|bool) $spInput
 */
function searchPaneOptions($spInput = null) {}
```

**Comment by mvorisek** [comment]
Related with #7619, all fixes on types must be based on parsed TypeExpression.

**Comment by Wirone** [comment]
It's not a bug, because initial support for phpDoc was introduced only for simple tags, like `@tag \F\Q\C\N`. At any point it wasn't aiming for full phpDoc support. I am going to convert this into feature request.

**Comment by alexmandrikdev** [comment]
I also have a problem with this rule in this update. It removes the inline namespaces even when I use the same class with different namespaces.

Before:
``` php
use App\Actions\CreateUrl;

...

CreateUrl::run();
App\Actions\Folder1\CreateUrl::run();
App\Actions\Folder2\CreateUrl::run();

...
```
After:
``` php
use App\Actions\CreateUrl;

...

CreateUrl::run();
CreateUrl::run();
CreateUrl::run();

...
```

**Comment by mvorisek** [comment]
even unioned (`A|B`)/intersected (`A&B`) types are not supported

**Comment by mvorisek** [comment]
I plan to work on this after #7719
