### ISSUE TITLE
Verbose progress should still be `dots`

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7640]
## Feature request

`php-cs-fixer -v` should still diplay progress in dots as before than a progressbar

introduced in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7603

verbose output with dots is helpful to understand the quantity, distribution and speed of the fixes in large projects

this is also how other tools like phpunit works/display progress when verbose output is enabled

**Comment by Wirone** [comment]
You can still use `dots` output by providing `--show-progress=dots`. Verbose mode is not about progress output, but about displaying more information about the result (applied rules). It was previously implicitly connected and `--verbose` was enabling dots output, but these are 2 separate things.

**Comment by mvorisek** [comment]
> ...about displaying more information about the result (applied rules).

and that is what progress with dots does too :) Seeing the overview of fixes in one place is very helpful.

**Comment by Wirone** [comment]
> > ...about displaying more information about the result (applied rules).
> 
> and that is what progress with dots does too :) Seeing the overview of fixes in one place is very helpful.

And you can still see that information if it's helpful for you, but verbose mode is _not_ directly related to progress output type, but to other kind of information that is, or is not displayed in the output. Please see my edited reply - other tools also don't act as you described.

Maybe we could automatically use `dots` for `-vv` or `-vvv`, but I'm against using it for `-v / --verbose` as it was the point of that PR, to simplify the progress output for basic usage. Internally we have `cs:check` script which does `check --verbose --diff` and I really want to have `bar` output there. But I don't see it as something really needed because you can just use `--show-progress` to choose progress output type 🙂.

**Comment by keradus** [comment]
` x/x [████████████████████████████] 100%` format is giving info about progress (both, files count and %) and gives same type of "speed" feeling as before (speed of bumping the number up vs speed of printing next dot - only a feeling for both cases)

----------

Then, with bar, one can still see affected files, while also applied rules (when `-v`)

```
ker@d ~/github/FriendsOfPHP/PHP-CS-Fixer λ git diff ; ## modified file to add not-needed empty lines                  
diff --git a/src/Doctrine/Annotation/Tokens.php b/src/Doctrine/Annotation/Tokens.php
index a388cf4c6..3b1222ea3 100644
--- a/src/Doctrine/Annotation/Tokens.php
+++ b/src/Doctrine/Annotation/Tokens.php
@@ -2,6 +2,9 @@
 
 declare(strict_types=1);
 
+
+
+
 /*
  * This file is part of PHP CS Fixer.
  *


ker@d ~/github/FriendsOfPHP/PHP-CS-Fixer λ ./php-cs-fixer check src/Doctrine ; ## list of affected files is presented
Loaded config default from "/Users/d.ruminski/github/FriendsOfPHP/PHP-CS-Fixer/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
 3/3 [████████████████████████████] 100%

   1) src/Doctrine/Annotation/Tokens.php

Found 1 of 3 files that can be fixed in 0.258 seconds, 18.000 MB memory used


ker@d ~/github/FriendsOfPHP/PHP-CS-Fixer λ ./php-cs-fixer check src/Doctrine -v ; ## list of affected files is presented also with applied rules, due to -v
PHP CS Fixer 3.45.1-DEV Three Keys by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.3.1
Loaded config default from "/Users/d.ruminski/github/FriendsOfPHP/PHP-CS-Fixer/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
 3/3 [████████████████████████████] 100%

   1) src/Doctrine/Annotation/Tokens.php (no_extra_blank_lines)

Found 1 of 3 files that can be fixed in 0.254 seconds, 18.000 MB memory used
```

**Comment by mvorisek** [comment]
Yes, progressbar without `-v` is great. However, with a lot of fixes/long diff, `-v` with dots overview was very helpful localy and in CI too to understand the fixes quickly.

**Comment by Wirone** [comment]
Isn't the summary at the end of the output even more helpful than dots/chars from the progress in that regard? In the `dots` progress output you don't see which files actually were fixed or failed, it's really verbose (space-wise), but not meaningful output. You may be interested in `meaningful` progress output from #6842 which provides a great summary of the command's result (but has a drawback: no % progress).

**Comment by mvorisek** [comment]
That is still too verbose, screen with is like 40 lines, but our projects have 100 - 1k files typically. At least for me, the dots are much more informative than the progress only.

**Comment by Wirone** [comment]
So you want "not too verbose" output in the verbose progress 😅? Does not make sense IMHO. As I said earlier, I believe the best solution here is to utilise `--show-progress=dots` because it's exactly for that, to fine-tune the output in a desired way.

**Comment by mvorisek** [comment]
No. From verbose mode I expect the verbose diff/file fixes (fine now and previously) incl. "more verbose" progress with "dots" instead of "progress" which has less informative value.

**Comment by keradus** [comment]
gladly, we have a configuration possibilities to match your custom need. I believe we won't be able to move forward with alignment when we simply have 2 different preferences. Let's celebrate the differences and possibility to customize the tool.

For now, I'm open for further customization possibilities (PR welcome!) and I want to keep current defaults.
