### ISSUE TITLE
`fully_qualified_strict_types` must fix attributes

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7657]
## Feature request

Expected fixing behaviour:
```diff
-#[\Attr]
+#[Attr]
 class Cl {}
```

**Comment by Wirone** [comment]
FYI: `fully_qualified_strict_types` should not handle global namespace (and it ignores it on purpose in terms of importing symbols), `global_namespace_import` is for that. But to be honest I would like to see them merged under a new fixer with a more appropriate name.
