### ISSUE TITLE
`declare_strict_types` does not work with shebang

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7681]
## Bug report

See unfixed https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.46.0/dev-tools/info-extractor.php file.

I belive it should add `declare_strict_types` to the first `<?php` instead of relying `<?php` will be found on the 1st line. Or handle at least shebang line explicitly.

**Comment by Wirone** [comment]
Duplicate of #7634.
