### ISSUE TITLE
`no_superfluous_phpdoc_tags` removes actual docs when these are after phpDoc tag

### ISSUE THREAD

**Issue by staabm** [PHP-CS-Fixer/PHP-CS-Fixer#7692]
## Bug report

My guess is, php-cs-fixer detects the `@return void` as useless, but then decides to delete the whole comment instead of just the single tag from the phpdoc

### Description

a phpdoc is removed, which should be preserved

### Runtime version

```
$ php php-cs-fixer -V
PHP CS Fixer 3.46.1-DEV Three Keys by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.12
```

using https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/commit/3566e7c926ada331cd07cf6436947d0d89a1d216

### Used command

`php php-cs-fixer fix --dry-run test.php --diff -vvv`

### Configuration file

default config from PHP-CS-Fixer repo

### Code snippet that reproduces the problem

```php
<?php

class X {
    /**
     * @return void
     *
     * Validate price information values
     */
    private function validatePriceinformationConfigset(): void
    {

    }
}
```

expected result

```php
<?php

class X {
    /**
     * Validate price information values
     */
    private function validatePriceinformationConfigset(): void
    {

    }
}
```

actual result

```php
<?php

class X {
    private function validatePriceinformationConfigset(): void
    {

    }
}
```

**Comment by Wirone** [comment]
@staabm can you share the diff from the commands output along with information about applied fixers?

**Comment by Wirone** [comment]
Looking at the output I assume it was `no_superfluous_phpdoc_tags` which removed `@return void` and then `no_empty_phpdoc` remove remaining comment, but what I don't understand is why "Validate price information values" was removed 🤔? Did `no_superfluous_phpdoc_tags` remove it along with `@return`? What happens if you move the coment before the `@return` tag? You can also run Fixer with `--rules= no_superfluous_phpdoc_tags` and check what this single fixer does.

**Comment by staabm** [comment]
```
$ php php-cs-fixer fix --dry-run test.php --diff -vvv --rules=no_superfluous_phpdoc_tags
PHP CS Fixer 3.46.1-DEV Three Keys by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.12
Loaded config default from "C:\dvl\Workspace\PHP-CS-Fixer\.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
 1/1 [████████████████████████████] 100%

   1) test.php (no_superfluous_phpdoc_tags)
      ---------- begin diff ----------
--- C:\dvl\Workspace\PHP-CS-Fixer\test.php
+++ C:\dvl\Workspace\PHP-CS-Fixer\test.php
@@ -2,9 +2,6 @@
 
 class X {
     /**
-     * @return void
-     *
-     * Validate price information values
      */
     private function validatePriceinformationConfigset(): void
     {

      ----------- end diff -----------


Found 1 of 1 files that can be fixed in 0.019 seconds, 14.000 MB memory used

```

**Comment by staabm** [comment]
maybe the text in the following lines are interpreted as the description of the `@return void` tag?

**Comment by julienfalque** [comment]
I'm having a look at it.

**Comment by julienfalque** [comment]
It seems to be done [on purpose](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.46.0/src/DocBlock/DocBlock.php#L224), although not covered by test cases in the fixer's tests.

I could not find a specification on how parameters and return types descriptions can be written in PHPDocs. However, PhpStorm does parse those the same way PHP CS Fixer currently does:

![image](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/1736542/81a1890b-0aae-4eb1-b259-e68e557de151)

so I'm thinking this is the expected behavior.

**Comment by staabm** [comment]
thanks for looking into it. thats interessting. seems its a won't fix then.

**Comment by dktapps** [comment]
Having the same issue in my CI builds: https://github.com/pmmp/BedrockProtocol/actions/runs/7446277958/job/20256185137?pr=215

**Comment by Wirone** [comment]
I believe the problem is somewhere in `PhpCsFixer\DocBlock\DocBlock::getAnnotations()`, which in provided snippet finds annotation like this:

```
object(PhpCsFixer\DocBlock\Annotation)#1738 (8) {
  ["lines":"PhpCsFixer\DocBlock\Annotation":private]=>
  array(3) {
    [0]=>
    object(PhpCsFixer\DocBlock\Line)#1739 (1) {
      ["content":"PhpCsFixer\DocBlock\Line":private]=>
      string(20) "     * @return void
"
    }
    [1]=>
    object(PhpCsFixer\DocBlock\Line)#1741 (1) {
      ["content":"PhpCsFixer\DocBlock\Line":private]=>
      string(7) "     *
"
    }
    [2]=>
    object(PhpCsFixer\DocBlock\Line)#1736 (1) {
      ["content":"PhpCsFixer\DocBlock\Line":private]=>
      string(41) "     * Validate price information values
"
    }
  }
  ["start":"PhpCsFixer\DocBlock\Annotation":private]=>
  int(1)
  ["end":"PhpCsFixer\DocBlock\Annotation":private]=>
  int(3)
(...)
```

I believe it should stop at first empty line and do not treat non-indented text as previous tag's description. But I did not look at phpDoc specification, it's just my perspective.

**Comment by staabm** [comment]
Fwiw, this problem occured with recent updates. It worked a few months ago

**Comment by Wirone** [comment]
I suspect #7649 🤔. @mvorisek what do you think?

**Comment by staabm** [comment]
hmm the same problem on different source, but with even less useful outcome:

```
<?php

/**
 * ViewHelper Method for rendering images which are lazy loaded by lazyload.min.js
 * Use this method to prevent uncontrolled code in views or possible wrong implementations.
 *
 * @param array  $options    e.g. alt, title, width, height, class, ...
 * @param string $attrSrcSet
 *                           - provides different image sources for browser to load according to viewport
 *                           - inject without attribute name like 'scrset="....."' !
 * @param string $attrSizes
 *                           - provides comma separated media conditions for image sizes
 *                           - inject without attribute name like 'sizes="....."' !
 */
function renderLazyLoadingImage(string $imgUrl, array $options = [], string $attrSrcSet = '', string $attrSizes = ''): string
{}

```

```
$ php php-cs-fixer fix --dry-run test2.php --diff -vvv --rules=no_superfluous_phpdoc_tags
PHP CS Fixer 3.46.1-DEV Three Keys by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.12
Loaded config default from "C:\dvl\Workspace\PHP-CS-Fixer\.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
 1/1 [████████████████████████████] 100%

   1) test2.php (no_superfluous_phpdoc_tags)
      ---------- begin diff ----------
--- C:\dvl\Workspace\PHP-CS-Fixer\test2.php
+++ C:\dvl\Workspace\PHP-CS-Fixer\test2.php
@@ -5,12 +5,6 @@
  * Use this method to prevent uncontrolled code in views or possible wrong implementations.
  *
  * @param array  $options    e.g. alt, title, width, height, class, ...
- * @param string $attrSrcSet
- *                           - provides different image sources for browser to load according to viewport
- *                           - inject without attribute name like 'scrset="....."' !
- * @param string $attrSizes
- *                           - provides comma separated media conditions for image sizes
- *                           - inject without attribute name like 'sizes="....."' !
  */
 function renderLazyLoadingImage(string $imgUrl, array $options = [], string $attrSrcSet = '', string $attrSizes = ''): string
 {}

      ----------- end diff -----------


Found 1 of 1 files that can be fixed in 0.613 seconds, 14.000 MB memory used

```

phpdocs and their description get stripped away

**Comment by staabm** [comment]
> I suspect #7649

@Wirone I just confirmed locally that it starts failling with https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/commit/8d6b23e26ef8ff3ea0f737008851422d444b48dc

**Comment by mvorisek** [comment]
in #7649 I narrowed some whitespace matching from `\s` to `\h` to unify them more across more files, @staabm can you please revert what is needed and submit a PR with a test case?

**Comment by staabm** [comment]
@mvorisek I have no clue about the regex involved and PHP-CS-Fixer internals
