### ISSUE TITLE
`method_chaining_indentation` should be executed after `no_space_around_double_colon`

### ISSUE THREAD

**Issue by mho22** [PHP-CS-Fixer/PHP-CS-Fixer#7699]
## Bug report

Linked with [Pint Issue 234](https://github.com/laravel/pint/issues/234) posted by @shengslogar

### Description

Because of its alphabetical placement, the rule `method_chaining_indentation` takes precedence over `no_space_around_double_colon`, even though it should be executed after `no_space_around_double_colon`.

A problematic fix will occur if `method_chaining_indentation` is set before `no_space_around_double_colon` following alphabetical order.

### Runtime version

```
PHP CS Fixer 3.46.0 Three Keys by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.14
```

### Used command

```
vendor/bin/php-cs-fixer fix -vvv test.php
```

### Configuration file

```php
use PhpCsFixer\Finder;
use PhpCsFixer\Config;


$finder = ( new Finder() )->in( __DIR__ );


return ( new Config() )
    ->setUsingCache( false )
    ->setRules( [
        'method_chaining_indentation' => true,
        'no_space_around_double_colon' => true
    ] )
    ->setFinder( $finder );
```

### Code snippet that reproduces the problem in `test.php`

`Before`

  ```php
$formattedIncorrectly = Foo::bar
    ::baz()
                    ->where('id', 1)
    ->firstOrFail();

$formattedCorrectly = Foo::bar
::baz()
    ->where('id', 1)
    ->firstOrFail();
  ```

`After`

```php 
$formattedIncorrectly = Foo::bar::baz()
        ->where('id', 1)
        ->firstOrFail();

$formattedCorrectly = Foo::bar::baz()
    ->where('id', 1)
    ->firstOrFail();
```

`Expected`

```php
$formattedIncorrectly = Foo::bar::baz()
    ->where('id', 1)
    ->firstOrFail();

$formattedCorrectly = Foo::bar::baz()
    ->where('id', 1)
    ->firstOrFail();
```

**Comment by Wirone** [comment]
Fixers are run in order determined by their priority, not by name. If there is direct relation between two fixers, then they must have proper priorities and integration tests ensuring proper order. We will investigate your case as soon as we can.

**Comment by mho22** [comment]
@Wirone I wanted to explore the priorities of the mentioned fixers: `MethodChainingIndentationFixer` and `NoSpaceAroundDoubleColonFixer`. It appears that they don't have a `getPriority()` method, so they rely on their extension from `AbstractFixer` returning priority `0`. Since both fixers share the same zero priority, their position in the associative array 'simulates' their priority, right ?

While I'm not entirely certain, it seems that when reading the rulesets, the rules are sorted in alphabetical order. If these two rules are added to a ruleset, `method_chaining_indentation` will take precedence over `no_space_around_double_colon` due to alphabetical sorting. These are the results of testing this locally, when I switch position of rules in my example above.

**Comment by Wirone** [comment]
@mho22 Yeah, if fixers don't have explicit priority and share the default one, the running order depends on the definition order. When rules come from predefined rulesets most probably they're sorted alphabetically. So in the end there _may_ be scenario when fixers' names determine the order 😉. Most fixers don't depend on each other, for other scenarios we have priorities and dependency graph, which unfortunately may be incomplete.

**Comment by mho22** [comment]
@Wirone I would be delighted to contribute, if I may. What additional guidelines should I follow, aside from those mentioned in the 'contribution' section? Should I perhaps analyze other pull requests tagged 'topic/priority'? I might be putting the cart before the horse.

**Comment by Wirone** [comment]
@mho22 you can take a look at #7296 to see what kind of changes are required (priority graph, integration test, modifying fixers' priority and phpDoc about before/after). There are several tests that cover this process, so if you change priority some tests should fail and should somehow guide you what to do next. Please run `composer qa` locally to check if everything is OK 🙂.
