### ISSUE TITLE
Add/enforce PHPUnit data provider return type

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7717]
## Feature request

Provider type can never express the full target method features as for example generics is not supported.

In general, the developer should not even try to narrow the type to the best possible type as each test/data provider case is usually run in CI anyway.

I propose to introduce a fixer that add a return type `iterable<array<mixed>>` like:
```
class Test extend TestCase
    /**
     * @return iterable<array<mixed>>
     */
    public static function provideFixCases(): iterable
    {
    }
}
```

I propose `iterable<array<mixed>>` to handle both named and unnamed params.

Also, I would expect a configuration option `enforce` of type `bool`. When true and return type is already present, it will be replaced. I propose `enforce: true` to be default, as there are not many cases when a return type is good to be narrower, in a real world, it is mostly only inconsistent and `@phpstan-return` could be used if a narrower type is really wanted.

**Comment by Wirone** [comment]
> I propose `enforce: true` to be default, as there are not many cases when a return type is good to be narrower, in a real world, it is mostly only inconsistent and `@phpstan-return` could be used if a narrower type is really wanted.

I believe it's a no-go for @keradus because we aim for good return type in data providers - just search `@return iterable<` in `tests`. There's no point in overriding already existing return type. It could work only if enforced return type was configurable, but also it could be problematic because e.g. in our tests we have data providers that only returns expected code, some expected+input, some have fixer's config and it's impossible to make it generic.

Also, I believe that `iterable<array<mixed>>` does not bring any value and it could be omitted and ignored in PHPStan. Return type either should represent actual data structure or be undefined.

**Comment by mvorisek** [comment]
I understand your view.

`iterable<array<mixed>>` would solve any IDE/static analyser "missing return type" warnings.

> because we aim for good return type in data providers - just search `@return iterable<` in `tests`. We even have `ProjectCodeTest::testDataProvidersDeclaredReturnType` test that ensures the return type matches requirement. IMHO there's no point in overriding already existing return type.

`iterable<array{string, 1?: ?string, array<string, mixed>}>` is currently a little better for phpstan, but after https://github.com/phpstan/phpstan-phpunit/pull/152 it will not help anything, as the provider's data will be checked much more better againt the full accepting params.

**Comment by Wirone** [comment]
> `iterable<array<mixed>>` would solve any IDE/static analyser "missing return type" warnings.

We don't want to add `@return` only to satisfy SA tool with bare minimum info, we want to add it to be helpful. `iterable<array<mixed>>` is _not_ helpful IMHO, it's a "shut the f**k up" kind of dummy plug 🤷‍♂️.

As for the https://github.com/phpstan/phpstan-phpunit/pull/152 (thanks for pointing it out, I'll subscribe), I believe we have good return types where they're defined, and other are ignored with the config - we try to decrease the amount of ignored warnings while working with the code. Anyway, that PR is in draft state for long, and I agree with @stof's [comment](https://github.com/phpstan/phpstan-phpunit/pull/152#issuecomment-1831619754) that this should not be that much invasive (and report mismatch of the defined type with inferred data structure).

**Comment by keradus** [comment]
@Wirone said everything.

I decided to not aim nor promote suggested `mixed` as dataProvider output.

You can still create a custom fixer and use that in your projects. Thanks for understanding.
