### ISSUE TITLE
`leading_backslash_in_global_namespace` breaks generics

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7720]
## Bug report

Currently `fully_qualified_strict_types` with `leading_backslash_in_global_namespace` option fixes local generics symbols, example:

```diff
 <?php
 
 class MethodGenerics
 {
     /**
      * @template T of \Exception
      * @param \Closure(): T $fx
-     * @return T
+     * @return \T
      */
     public function makeException(\Closure $fx)
     {
         return $fx();
     }
 }
 
 /**
  * @template T of \Exception
  */
 class ClassGenerics
 {
     /**
      * @param \Closure(): T $fx
-     * @return T
+     * @return \T
      */
     public function makeException(\Closure $fx)
     {
         return $fx();
     }
 }
```

This is wrong, there is nothing to be fixed.

I expect the same also for local in-class type aliases [2].

[1] https://phpstan.org/blog/generics-in-php-using-phpdocs#type-variables
[2] https://phpstan.org/writing-php-code/phpdoc-types#local-type-aliases

**Comment by mvorisek** [comment]
https://phpstan.org/r/cd9889fd-3d95-4817-8a09-b5b124a92b1e - the generics `T` must not be added to `$uses`, it must be put into local reserved symbols like `self`

**Comment by Wirone** [comment]
It can't be added to a list, because `T` is just a convention, you can use any name for a template. Fixer must read `@template` tags and ignore names used there.

**Comment by mvorisek** [comment]
That is what I have written: "local reserved symbols" :)

**Comment by julienfalque** [comment]
This related to #4723.

**Comment by mvorisek** [comment]
I will work on this one.
