### ISSUE TITLE
Cannot declare class [...] because the name is already in use

### ISSUE THREAD

**Issue by thyseus** [PHP-CS-Fixer/PHP-CS-Fixer#7738]
## Bug report

Given the following Code:

```php
class PostResource extends \LaraZeus\Sky\Filament\Resources\PostResource
{
```

php-cs-fixer generates:

```php
use LaraZeus\Sky\Filament\Resources\PostResource;

class PostResource extends PostResource
{
```

which, correctly, gives this error message:

```
Cannot declare class App\Filament\Resources\PostResource because the name is already in use
```

It was working in a prior php-cs-fixer version of December 2023, it has to be a recent update that broke the behavior.

Thanks a lot !

**Comment by Wirone** [comment]
Fixed in #7679, will be part of upcoming release.
