### ISSUE TITLE
Incorrect formatting of a template file using statement_indentation

### ISSUE THREAD

**Issue by marden** [PHP-CS-Fixer/PHP-CS-Fixer#7754]
### Description

I'm getting weird formatting in a template file which contains both html and php. The php opening tag is indented with spaces to visualize a code block between html tags. 

### Runtime version

PHP CS Fixer 3.47.0 Big Changes by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.1.25

### Used command

vendor/bin/php-cs-fixer fix --diff --verbose modules/user/views/delete.php

### Configuration file
```php
[
        '@Symfony' => true,
        '@PER-CS2.0' => true,
        '@PHP81Migration' => true,
    ]
```
### Code snippet that reproduces the problem
Original template:
```php
<div>
    <div class="form-group ">
        <?= 'Hello'; ?>
        <div>
            <?php
            $deleteBtnOptions = [
                'class' => 'btn btn-default',
            ];

                echo $deleteBtnOptions['class'];
            ?>
        </div>
    </div>
</div>
  ```
After fix:
```php
<div>
    <div class="form-group ">
        <?= 'Hello'; ?>
        <div>
            <?php
            $deleteBtnOptions = [
                'class' => 'btn btn-default',
            ];

        echo $deleteBtnOptions['class'];
        ?>
        </div>
    </div>
</div>
```

The diff:
```
1) modules/user/views/delete.php (statement_indentation)
@@ -7,8 +7,8 @@
                 'class' => 'btn btn-default',
             ];
 
-            echo $deleteBtnOptions['class'];
-            ?>
+        echo $deleteBtnOptions['class'];
+        ?>
```

Expected result:
```php
<div>
    <div class="form-group ">
        <?= 'Hello'; ?>
        <div>
            <?php
            $deleteBtnOptions = [
                'class' => 'btn btn-default',
            ];

            echo $deleteBtnOptions['class'];
            ?>
        </div>
    </div>
</div>
```
It's interesting that after removing `<?= 'Hello'; ?>` the behavior changes and gives the expected result. It looks like Fixer is confused with `<?= .. ?>` and `<?php ?>` in one place.

**Comment by Wirone** [comment]
Please have in mind that Fixer is focused on modern PHP, that does not mix code with HTML markup (see [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6788#issuecomment-1438688702)), that's why I'm going to close this report. Feel free to provide PR, but we can't assure it will be merged anyway.
