### ISSUE TITLE
Syntax error, unexpected token ">"

### ISSUE THREAD

**Issue by Ferikl** [PHP-CS-Fixer/PHP-CS-Fixer#7758]
### Description

Hi, thanks for great product!
After latest release I have some strange errors while running fixer:

```
> composer cs:fix -vvv

database/factories/User/UserSettingsFactory.php                              syntax error, unexpected token ">"  
     11▕     public function definition(): array
     12▕     {
     13▕         return [
     14▕             'sounds_type'             => 'music',
  ➜  15▕             'payment_email'           => $this->faker->email,
     16▕             'email'                   => $this->faker->email,
     17▕             'locale'                  => 'en',
     18▕             'email_confirmed_at'      => now(),
     19▕             'email_confirmation_hash' => Str::random(10),

```
composer section:

```
"scripts": {
        "cs:check": "php-cs-fixer fix --verbose --ansi --show-progress=dots --config=.php-cs-fixer.php --diff --dry-run",
        "cs:fix": "php-cs-fixer fix --verbose --ansi --show-progress=dots --config=.php-cs-fixer.php",
        "psalm": "vendor/bin/psalm"
    },
```

### Runtime version
HP CS Fixer version: v3.47.1
PHP: PHP 8.2.14 (cli)

previous version works fine, and I am 100% sure files are ok.

**Comment by kubawerlos** [comment]
Hi @Ferikl, can you add missing stuff from the [bug report template](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.47.1/.github/ISSUE_TEMPLATE/bug_report.md)?

I mean, precisely, "Configuration file" and "Code snippet that reproduces the problem". Thanks.

**Comment by Ferikl** [comment]
@kubawerlos 
shame on me! thanks a lot to point me. My config file was broken. Going to close the issue
