### ISSUE TITLE
Cache is not supported using the official docker image

### ISSUE THREAD

**Issue by soullivaneuh** [PHP-CS-Fixer/PHP-CS-Fixer#7768]
### Description

The cache file is not generated using the docker official image.

According to the documentation:

> The cache is supported only when the tool was downloaded as a phar file or installed via Composer.

But I don't really see why the docker image should not support it as we can fetch it back thanks to volume binding.

Possible related: #6996.

### Runtime version

```
PHP CS Fixer 3.47.0 Big Changes by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.14
```

### Used command

```
❯ docker run --rm -t -v ${PWD}:${PWD} -w ${PWD} ghcr.io/php-cs-fixer/php-cs-fixer:3.47.0-php8.2 check --using-cache=yes                       
PHP CS Fixer 3.47.0 Big Changes by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.14
Loaded config default from "/home/sullivan/p/gitlab.com/ss-open/ci/recipes/.php-cs-fixer.dist.php".
 6/6 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

   1) rector.php
   2) .fixtures/fixture.php

Found 2 of 6 files that can be fixed in 0.038 seconds, 14.000 MB memory used

❯ ls .php-cs-fixer.cache                 
ls: cannot access '.php-cs-fixer.cache': No such file or directory
```

### Configuration file

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->ignoreDotFiles(false)
    ->ignoreVCS(true)
    ->ignoreVCSIgnored(true)
;

$config = new PhpCsFixer\Config();

return $config->setRules([
        '@PSR1' => true,
        '@PSR12' => true,
        'strict_param' => true,
        'array_syntax' => ['syntax' => 'short'],
    ])
    ->setRiskyAllowed(true)
    ->setFinder($finder)
;
```

### Code snippet that reproduces the problem

N/A

**Comment by Wirone** [comment]
Thank you for reporting this. It could be easily solved if we included PHAR file in Docker image instead of raw code, but [I opted for the latter](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7555#discussion_r1430472092) because of debugging/experimenting purposes.

I've provided fix in #7769, hopefully it'll be released soon 🙂.
