### ISSUE TITLE
Rule nullable_type_declaration_for_default_null_value should remove default value on non-optional arguments

### ISSUE THREAD

**Issue by nicolas-grekas** [PHP-CS-Fixer/PHP-CS-Fixer#7787]
## Bug report

When I applied this rule to the Symfony codebase, everything worked really well *except* for non-optional arguments with a null default.

For those, I had to patch them manually, see
https://github.com/symfony/symfony/pull/53612/commits/fb9fa26102512090550f9137751f81677c06d5f9

This means that in the context of https://wiki.php.net/rfc/deprecate-implicitly-nullable-types, php-cs-fixer is currently not totally safe to prepare a codebase to PHP 9. (The reason being that non-optional arguments with default values are also deprecated).

nullable_type_declaration_for_default_null_value should remove those non-optional arguments with a null default, so that upgrading is made super easy.

### Runtime version

latest

### Used command

php-cs-fixer fix --rules nullable_type_declaration_for_default_null_value

**Comment by kubawerlos** [comment]
@nicolas-grekas do you mean that `nullable_type_declaration_for_default_null_value` should do, what currently [`no_unreachable_default_argument_value`](https://cs.symfony.com/doc/rules/function_notation/no_unreachable_default_argument_value.html) does?

**Comment by nicolas-grekas** [comment]
I also posted https://github.com/php/php-src/issues/13353

**Comment by nicolas-grekas** [comment]
From the end user pov, the current behavior is the risky one, because it turns
a non-deprecated syntax: (int $a = null, $b)
into a deprecated one: (?int $a = null, $b).

**Comment by SVGAnimate** [comment]
@nicolas-grekas I believe in the example below there is an update to present.

<table>
  <tr><th>PHP 5</th><th>PHP 7</th><th>PHP 8</th></tr>

<tr><td>

```PHP
<?php
function ($a = null, $b) {
}
```

</td><td>


</td><td>

```PHP
function (?$a, $b) {
}
```

</td></tr>



<tr><td>

</td><td>

```PHP
<?php
function (int $a = null, $b) {
}
```

</td><td>

```PHP
function (?int $a, $b) {
}
```

</td></tr>

</table>

In PHP5 nullable parameter is supported thus``function foo($a = null, $b){}``
In PHP7 the nullable parameter is a mixed type ( union of int|float|string|array|object|null )
In PHP8 nullable parameter is supported thus ``function foo(?$a, $b){}``
