### ISSUE TITLE
Test class links in web are broken

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7806]
## Bug report

steps to reproduce:

1. open https://cs.symfony.com/doc/rules/class_notation/final_internal_class.html
2. click "Test class: PhpCsFixer\Tests\Fixer\ClassNotation\FinalInternalClassFixerTest" link at the page bottom
3. the link is:

current/wrong: `https://cs.symfony.com/tests/Fixer/ClassNotation/FinalInternalClassFixerTest.php`

expected: `https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.47.0/tests/Fixer/ClassNotation/FinalInternalClassFixerTest.php`

I have no idea by which component/deploy the links are solved.

a little related with https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7790 as the links are pointing to non-latest version.

**Comment by Wirone** [comment]
[Fixed](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer.github.io/commit/a110222fe6085b8e837fdf1d09d4477793eb6c1a).
