### ISSUE TITLE
`/doc/rules/index.rst` fails to render on GitHub

### ISSUE THREAD

**Issue by donatj** [PHP-CS-Fixer/PHP-CS-Fixer#7807]
## Bug report

The link in the README to the rules page's `rst` file no longer renders as HTML on GitHub. 

This might just be a GitHub problem and not a problem with the document itself, but I thought you might want to be aware

https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/index.rst

<img width="915" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/133747/05303182-60e8-442e-8a6a-d13a7bc6771d">

### Runtime version

N/A

### Used command

N/A

### Configuration file

N/A

### Code snippet that reproduces the problem

N/A

**Comment by Wirone** [comment]
Yeah, I was aware because @kubawerlos pointed it out. I did not look at it yet, looks rather like Github issue (size limit?), but maybe we can fix it somehow, so thanks for reporting 👌.

**Comment by beistehen** [comment]
Having the same issue and stumbling over your post while seraching for answers, I found the following discussion (but no solution yet):
https://github.com/orgs/community/discussions/86715

So it seems to be a Github Issue.

**Comment by mvorisek** [comment]
v3.32.1 (and lower) renders fine: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.32.1/doc/rules/index.rst

v3.33.0 (and higher) is broken: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.33.0/doc/rules/index.rst

diff: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/compare/v3.32.1...v3.33.0 any idea? length limit?

**Comment by Wirone** [comment]
It is [external problem](https://github.com/orgs/community/discussions/86715#discussioncomment-8265126) so I'm going to close this as there's nothing we can do on our side. We could only change the format to achieve smaller file, but I don't want to do this. Let's just hope Github fixes this soon.

**Comment by mvorisek** [comment]
Did you tried to split the file in two to confirm it is a length limit?

**Comment by Wirone** [comment]
Did you read linked discussion? Because you would know many other people verified it already and it seems like a length limit 😉.
