### ISSUE TITLE
How disable no_break_comment check?

### ISSUE THREAD

**Issue by dimkinthepro** [PHP-CS-Fixer/PHP-CS-Fixer#7887]
### Description
How disable no_break_comment check?

**Comment by Wirone** [comment]
Put `'no_break_comment' => false` in your config file, [it's documented here](https://cs.symfony.com/doc/config.html#configuring-rules). Also, please ask questions like this in [discussions](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions) as this is not a bug.
