### ISSUE TITLE
no_trailing_whitespace_in_string new parameter to allow single white space if it exists

### ISSUE THREAD

**Issue by njake** [PHP-CS-Fixer/PHP-CS-Fixer#7893]
To make this rule not so risky maybe 'keep_single_space' or somekind of new parameter is good for keeping one space if it exists and remove all trailing after that.

Example
```
--- Original
+++ New
-<?php $a = ' 
-    foo 
-    foo2   
+<?php $a = ' 
+    foo 
+    foo2 
 ';
```

**Comment by keradus** [comment]
why a single whitespace is good, but 2 whitespaces are not good?

**Comment by njake** [comment]
For later readability single space is better and it wont break if text is used as SQL command or exec commands ect.

Example using SQL in string
``
--- Original
+++ New
-<?php $a = 'SELECT    
-id  
-name                        
-address
-<?php $a = 'SELECT 
-id 
-name 
-address
``

**Comment by julienfalque** [comment]
Why do you need to keep one space instead of removing all? What difference does it make for e.g. SQL?

**Comment by njake** [comment]
I'm just trying to make examples of how this could be improved if the coder has accidentally inserted unnecessary spaces.
I have lot of diffirent kind of legacy ugly code with those unnecessary spaces and it would be great if fixer could remove them without breaking world.

SQL parsing from parts. Not real life example.
```
$select = 'SELECT          '; // Can be trimmed down to one space.
$columns = '   
     id     
     name    
'; // Can be trimmed down to one space.
$where = 'WHERE '; // Broke SQL if space trimmed. So it needed to keep here.
$whereColumns = ' id=1';
```

**Comment by julienfalque** [comment]
I think I get your point, but then it looks like a small edge-case to me. I don't think we'll invest time on this so I'd suggest not using `no_trailing_whitespace_in_string` and maybe creating a custom rule.

**Comment by keradus** [comment]
Agree.

Please continue with @julienfalque suggestion.

Thanks!
