### ISSUE TITLE
"no-return" phpdoc not removed because superflous

### ISSUE THREAD

**Issue by staabm** [PHP-CS-Fixer/PHP-CS-Fixer#7914]
### Description

cs-fixer is removing a `@return never` phpdoc above a method, as soon as a `:never` native type is added.
it is not removing a `@return no-return` phpdoc though, which is a alias of `@return never` in at least [PHPStan](https://phpstan.org/writing-php-code/phpdoc-types#bottom-type) and [psalm](https://github.com/vimeo/psalm/issues/1155#issuecomment-451002822).
(there are even more "aliases", see above links)

put `test.php` into the php-cs-fixer repo root:

```php
// test.php
<?php
class X {
    /** @return never */
    private function doFoo(): never
    {
    }
    /** @return no-return */
    private function doFoo1(): never
    {
    }
}
```

expected result

```php
class test
{
    private function doFoo(): never {}

    private function doFoo1(): never {}
}
```

actual result
```php
class test
{
    private function doFoo(): never {}

    /** @return no-return */
    private function doFoo1(): never {}
}
```

### Runtime version

```
$ php -v
PHP 8.2.12 (cli) (built: Oct 24 2023 21:15:35) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies

$ php php-cs-fixer --version
PHP CS Fixer 3.52.2-DEV 15 Keys by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.12

```

### Used command

`php php-cs-fixer fix test.php` within PHP-CS-Fixer repo root

### Configuration file

PHP-CS-Fixer repo default config

### Code snippet that reproduces the problem

see above

**Comment by keradus** [comment]
-1 for removing the phpstan/psalm's alias types.

+0 for renaming them to proper php-like `@return never` (and run superfluous annotation removal afterward)

**Comment by Wirone** [comment]
> -1 for removing the phpstan/psalm's alias types.

Why? These are equivalents of `never`, probably for historical reasons (introduced before native return type), so IMHO these should be removed if superfluous.

**Comment by keradus** [comment]
in my proposal they ultimately would. just with 2 atomic rules, and one can decide what they want. if they want "all", they enable both rules.

I do not want to clutter rule operating on proper types with "historical types", and i want explicit rule to clean up "historical types"

**Comment by Wirone** [comment]
OK, now it's more clear how you see it, it totally wasn't clear from the first comment. I am not sure if I agree with this approach, though. Personally I would do this in the same fixer, maybe behind opt-in flag.

**Comment by julienfalque** [comment]
I think I prefer a dedicated rule for replacing e.g. `no-return` with `never` because there might be other aliases (now or in the future) we want to replace that are not related to removing superfluous `@return` tags.

**Comment by Wirone** [comment]
If it was general purpose fixer for unifying phpDoc, then OK. Making a rule just for `@return` and aliases of `never` seems like an overkill.

**Comment by Wirone** [comment]
If there are not any more examples of annotations that could be standardised (alias → basic name), then I don't see a point in investing time in this, as it can be easily achieved with regex-based replace using `@return (never\-returns?|no\-return)+` as a match pattern and `@return never` as an expected outcome.

![image](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/81a1cfe5-8615-4ec1-85b2-5160b278cf90)

Then it can be removed by `no_superfluous_phpdoc_tags`. I know that it would be better to have it automated, but I believe this is very edge case that not necessarily is worth being included in the core of Fixer.
