### ISSUE TITLE
ClassAttributesSeparationFixer - ['property' => 'none'] Add unwanted blank line when comment present

### ISSUE THREAD

**Issue by Mushr0000m** [PHP-CS-Fixer/PHP-CS-Fixer#7920]
### Configuration

```
PHP 8.1.13
```

```
PHP CS Fixer 3.52.1 (5b7534c)
```

```
'class_attributes_separation' => [
    'elements' => [
        'const' => 'none',
        'method' => 'one',
        'property' => 'none',
        'trait_import' => 'none',
    ],
],
```

### Description

I removed all fixers except this one, maybe I'm missing something but with the rule `['property' => 'none']` I expect to have zero blank line between all my properties. But it seems to fails if the property have a comment.

Actual result :

```diff
 class Foo
 {
    public $aa;
-
    public $bb;

    /**
     * Some comment
     */
    public $cc;

    // Some comment
    public $dd;
-
    public $ee;
 }
```

Expected result :

```diff
 class Foo
 {
    public $aa;
-
    public $bb;
-
    /**
     * Some comment
     */
    public $cc;
-
    // Some comment
    public $dd;
-
    public $ee;
 }
```

**Comment by paulbalandan** [comment]
This is expected behavior. The `none` option behaves like this:

- Same elements - no spaces in between
- Different elements - 1 space in between
- Same elements but at least one has a PHPDoc - 1 space surrounding that element with doc comment

**Comment by Mushr0000m** [comment]
Ok thanks
