### ISSUE TITLE
Install now: 404

### ISSUE THREAD

**Issue by afilina** [PHP-CS-Fixer/PHP-CS-Fixer#7951]
### Problem description

1. Visit this page: https://cs.symfony.com/doc/rules/language_construct/explicit_indirect_variable.html
2. Click Install Now
3. See a 404

### Minimal reproducer

1. Visit this page: https://cs.symfony.com/doc/rules/language_construct/explicit_indirect_variable.html
2. Click Install Now
3. See a 404

### Fixer version

n/a

### PHP version

n/a

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment]
Thanks @afilina for the report. Recently we bumped Sphinx version that generates the site and probably something has changed when it comes to paths. I've prepared the fix, I'll give others time to make familiar with it and approve, but I'll merge and deploy it anyway today's evening at most 🙂.

FYI: you can also use shim package or [Docker image](https://ghcr.io/php-cs-fixer/php-cs-fixer) to run Fixer.

**Comment by Wirone** [comment]
@afilina Download links are now correct 🙂.
