### ISSUE TITLE
`PhpUnitAttributesFixer` - ability to keep annotations

### ISSUE THREAD

**Issue by Wirone** [PHP-CS-Fixer/PHP-CS-Fixer#7956]
It would be great to have an option to add the attributes without removing the annotation (which also requires checking if the attribute is already there to avoid "fixing" it multiple times). When you need to support both PHPUnit 11 (to support the latest PHPUnit version) and PHPUnit 9.6 (to support older PHP versions), the way to go is to define both the attributes (for PHPUnit 10+) and the annotation (used by PHPUnit 9 and ignored in 10+ when the attributes are present).

_Originally posted by @stof in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7831#issuecomment-2060981640_

**Comment by Wirone** [comment]
This is actually great idea and I am surprised we did not think about it during the code review 🤔. In our case it's also required to keep annotations as we still support PHP 7.4 and PHPUnit 9.6. So basically we need to do this for ourselves too ☺️.

**Comment by keradus** [comment]
note: we may want to have sync between them if dev update one but not the other.

**Comment by mvorisek** [comment]
This feature is needed in order to keep PHPUnit 9 support.

**Comment by kubawerlos** [comment]
> This feature is needed in order to keep PHPUnit 9 support.

Then stop reporting [bugs](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8072) for the fixer :trollface: 

I will raise the PR with the config option after the bugfix is merged.
