### ISSUE TITLE
Please improve the documentation

### ISSUE THREAD

**Issue by speller** [PHP-CS-Fixer/PHP-CS-Fixer#7958]
### Feature request

The current documentation is unclear, I always spend a lot of time guessing how to configure PHP CS Fixer. Example:

https://cs.symfony.com/doc/rules/control_structure/control_structure_braces.html - how should I know that the value should be `true` or `false`? Can it be mentioned explicitly?
https://cs.symfony.com/doc/rules/control_structure/control_structure_continuation_position.html - how should I know what value should be set to this configuration? When I try `'control_structure_continuation_position' => 'next_line'` it fails. What does it mean that it has some options, how to set it? There's no example on the page.
https://cs.symfony.com/doc/rules/language_construct/single_space_around_construct.html - a complete mess for me. What should I do with these sub-options? Should I list all of the structures when I want "all enabled"? What all of these sub-configurations mean? Should they be in the root config or in this option sub-config? How should I know that `'single_space_around_construct' => true` is a valid configuration?
https://cs.symfony.com/doc/rules/basic/braces.html - it says that the rule is deprecated but one of the suggested options is `curly_braces_position` which is also deprecated.

PHP CS Fixer is a great tool but the configuration becomes more and more messy over time. When I upgrade a 2-year-old project I get deprecations and errors that can not be replaced with something directly and I spend hours guessing what should I use to get the same result. I would suggest providing upgrade instructions in the documentation for deprecated options on how to get the same result with new options.

### Contribution Checks

- [X] I have verified if this feature request was already discussed
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment]
[Documentation about configuring rules](https://cs.symfony.com/doc/config.html#configuring-rules) is clear.

- You use `"some_rule" => true` to include the rule with default config (if it's configurable, otherwise it just enables the rule)
- You use `"some_rule" => false` to disable the rule (which can be inherited from used ruleset)
- You use `"some_rule" => ['some_option' => ...]` to configure available options.

There is a clear convention, it does not make sense to repeat it in every rule. Each rule's documentation only lists available options which you can use in the configuration, with allowed values you can use for configuring it. There are also examples with default config and [custom config](https://cs.symfony.com/doc/rules/language_construct/single_space_around_construct.html#example-2):

> With configuration: `['constructs_contain_a_single_space' => ['yield_from'], 'constructs_followed_by_a_single_space' => ['yield_from']]`.

You basically can copy and paste config array from the docs to your config file.

I really don't get what should be improved here. With all the respect, looks like a typical PEBKAC to me 🙂.

**Comment by keradus** [comment]
> PHP CS Fixer is a great tool but the configuration becomes more and more messy over time. 

I strongly encourage to use presets, eg `@PHP74Migration + @PER-CS`. manual rulesets are non trivial to establish and you take config maintenance on you.

> I would suggest providing upgrade instructions in the documentation

While I'm close with Wirone on it, I also acknowledge that I could be just used to current docs and I'm open for any improvements, if they get supported by community.
Please, raise the PR so we can have them improved ;)

**Comment by speller** [comment]
> There is a clear convention, it does not make sense to repeat it in every rule

Let me explain why I was frustrated. I don't read PHP CS Fixer documentation from the beginning to the end. I only refer to it once a year when something fails in an existing project or I'm going to setup a new one. When I need some docs, I type the failing or deprecated setting into google and click on the first link that leads me to a page like this: https://cs.symfony.com/doc/rules/control_structure/control_structure_braces.html . When I'm on the page, I expect an intuitive UI to get the full help related to the config option. If there are some implicit rules or config variations then I expect to see such information and learn it right away without leaving the page. But now I should magically invent that to learn everything about the config on the page https://cs.symfony.com/doc/rules/control_structure/control_structure_braces.html I should go to https://cs.symfony.com/doc/config.html#configuring-rules to some specific block. How? No way for me as a user. And this is not everything. There's NO link to the list of all rules from the specific rule page. To see the list I should magically invent where to go to see it. Either back to Google or edit the URL manually. This is a lack of UX in the documentation. I never did and never plan to be an expert in the PHP CS Fixer documentation because I'm focused on applications development and this tool is just a tool that helps me to develop. I'm not questioning the tool quality itself or the contributors' efforts. I'm much appreciated for everyone who works on it. I'm just explaining my real use case. Based on my rich web apps development, I'm concluding not ideal UX.



> I strongly encourage to use presets, eg `@PHP74Migration + @PER-CS`. manual rulesets are non trivial to establish and you take config maintenance on you.

Yes, but in big old projects, it can be too difficult and I first should make it work as it was without errors and warnings. I'll try to use this way more actively in the future, thank you.
