### ISSUE TITLE
Enforing variable to be CamelCase Or snake_cae but not both at the same time

### ISSUE THREAD

**Issue by robingta** [PHP-CS-Fixer/PHP-CS-Fixer#7991]
### Feature request

I have looked for all the configurations but did not find one that will force variables to be either Camel case or Snake Case
but not both at the same time

### Contribution Checks

- [ ] I have verified if this feature request was already discussed
- [ ] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment]
I am going to close this, as we can consider it as a duplicate of #6643, and is initially implemented in #5097 but stale for long because of complexity, unclear requirements and Fixer's limitations (e.g. lack of inheritance context).
