### ISSUE TITLE
`simplified_null_return` errors out with `TypeError: Illegal offset type`

### ISSUE THREAD

**Issue by FeBe95** [PHP-CS-Fixer/PHP-CS-Fixer#8037]
### Problem description

Running the rule `simplified_null_return` errors out while checking a PHP translation file in our PHP project. The error is triggered by a combination of these "properties":
1. Top-level `return` statement
2. Omitting last-line semicolon `;`
3. Closing PHP tag `?>`

The PHP code in question does not raise any syntax errors as it is perfectly valid:
> The closing tag of a block of PHP code automatically implies a semicolon; you do not need to have a semicolon terminating the last line of a PHP block.

—  [PHP: Instruction separation - Manual](https://www.php.net/manual/en/language.basic-syntax.instruction-separation.php)

For the curious:
The file is a standard Laravel translation file, as described here: [Localization - Laravel 11.x - The PHP Framework For Web Artisans](https://laravel.com/docs/11.x/localization#using-short-keys)

### Minimal reproducer

test.php
```PHP
<?php

return []

?>
```

CLI:
```sh
> .\vendor\bin\php-cs-fixer check test.php -vvv --sequential --using-cache=no --rules=simplified_null_return
```

Output:
```
PHP CS Fixer 3.57.1 7th Gear by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.12
Running analysis on 1 core sequentially.
You can enable parallel runner and speed up the analysis! Please see usage docs for more information.
Loaded config default.
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


Found 0 of 1 files that can be fixed in 0.003 seconds, 22.000 MB memory used

Files that were not fixed due to errors reported during fixing:
   1) C:\<redacted>\test.php

                             
        [TypeError]          
        Illegal offset type  
                             

      PhpCsFixer\Fixer\ReturnNotation\SimplifiedNullReturnFixer->needFixing()
        in C:\<redacted>\vendor\friendsofphp\php-cs-fixer\src\Fixer\ReturnNotation\SimplifiedNullReturnFixer.php at line 71
      PhpCsFixer\Fixer\ReturnNotation\SimplifiedNullReturnFixer->applyFix()
        in C:\<redacted>\vendor\friendsofphp\php-cs-fixer\src\AbstractFixer.php at line 75
      PhpCsFixer\AbstractFixer->fix()
        in C:\<redacted>\vendor\friendsofphp\php-cs-fixer\src\Runner\Runner.php at line 422
      PhpCsFixer\Runner\Runner->fixFile()
        in C:\<redacted>\vendor\friendsofphp\php-cs-fixer\src\Runner\Runner.php at line 363
      PhpCsFixer\Runner\Runner->fixSequential()
        in C:\<redacted>\vendor\friendsofphp\php-cs-fixer\src\Runner\Runner.php at line 158
      PhpCsFixer\Runner\Runner->fix()
        in C:\<redacted>\vendor\friendsofphp\php-cs-fixer\src\Console\Command\FixCommand.php at line 338
      PhpCsFixer\Console\Command\FixCommand->execute()
        in C:\<redacted>\vendor\symfony\console\Command\Command.php at line 326
      [ ... ]
```

### Fixer version

3.57.1

### PHP version

8.2.12

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment]
Please have in mind that Fixer is focused on modern PHP, that does not mix code with other markup (see [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6788#issuecomment-1438688702)), hence no support for implicit semicolon.

Are you open to providing a PR? Because it won't be a priority task for the core team.

**Comment by FeBe95** [comment]
@Wirone Thanks for your response. As you can see in the `test.php` file, we are only using plain PHP. No additional markup is used. (Reference to Laravel was only made to clarify our use case, but the issue is not directly related to any Laravel specific code).

I will have a look into how to avoid this error. Maybe there is a simple fix for it, but I am not too familiar with the internal PHP CS Fixer code.

**Comment by Wirone** [comment]
The easiest fix is to not use closing PHP tag, which enforces trailing semicolon ☺️.

**Comment by FeBe95** [comment]
True 😅
Still, I am working on a fix which looks promising so far.

**Comment by SpacePossum** [comment]
thanks @FeBe95 , I think this issue can be closed after merge of https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8049

**Comment by FeBe95** [comment]
Yes, true. Totally forgot about it.
