### ISSUE TITLE
constant_case rule changes consts name

### ISSUE THREAD

**Issue by bugajakmateusz** [PHP-CS-Fixer/PHP-CS-Fixer#8058]
### Problem description

`constant_case` rule changes usages case if the constant is named 'NULL'.

Despite fixing [this issue](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7992) so CS-Fixer is not changing definition of consts, it's still changes their usage.

### Minimal reproducer

```
class X
{
    final public const string NULL = 'null';
    final public const string A = 'a';
    final public const string B = 'b';
}

class Y
{
    private function test(): string
    {
        return match ($valueType) {
            ScalarTypeName::A,
            ScalarTypeName::B,
            ScalarTypeName::NULL,
    }
}
```
after cs-fix:

class X
{
    final public const string NULL = 'null';
    final public const string A = 'a';
    final public const string B = 'b';
}

```
class Y
{
    private function test(): string
    {
        return match ($valueType) {
            ScalarTypeName::A,
            ScalarTypeName::B,
            ScalarTypeName::null,
    }
}
```

### Fixer version

3.58.0

### PHP version

8.3.7

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by kubawerlos** [comment]
> * [x]  I have verified if this problem was already reported

@Wirone maybe we have to add quiz or sth for ☝🏼, because it's 2nd time today this is a lie...

**Comment by bugajakmateusz** [comment]
@kubawerlos I used default GitHub filters, so I checked only opened issues - I haven't though that fix has been already made but it's not released yet - forgive me :)

**Comment by Wirone** [comment]
It was pointed out in the closed PR, fixed in another one, without intermediate issue, so yeah, I can see this overlooked 👍.
