### ISSUE TITLE
`simple_to_complex_string_variable` does not fix complex variable

### ISSUE THREAD

**Issue by jlecordier** [PHP-CS-Fixer/PHP-CS-Fixer#8063]
### Problem description

This fixer should turn this :

```php
"Hello ${name['key']}!"
```

into this :

```php
"Hello {$name['key']}!"
```

but instead still returns this :

```php
"Hello ${name['key']}!"
```

This fixer should turn this :

```php
"Hello ${name[0]}!"
```

into this :

```php
"Hello {$name[0]}!"
```

but instead still returns this :

```php
"Hello ${name[0]}!"
```

### Minimal reproducer

Add this :

```php
        yield 'array key access' => [
            <<<'EXPECTED'
                <?php
                $name = ['key' => "World"];
                echo "Hello {$name['key']}!";
                EXPECTED,
            <<<'INPUT'
                <?php
                $name = "World";
                echo "Hello ${name['key']}!";
                INPUT,
        ];

        yield 'array index access' => [
            <<<'EXPECTED'
                <?php
                $name = ["World"];
                echo "Hello {$name[0]}!";
                EXPECTED,
            <<<'INPUT'
                <?php
                $name = "World";
                echo "Hello ${name[0]}!";
                INPUT,
        ];
```

after this :

```php
        yield 'basic fix' => [
            <<<'EXPECTED'
                <?php
                $name = "World";
                echo "Hello {$name}!";
                EXPECTED,
            <<<'INPUT'
                <?php
                $name = "World";
                echo "Hello ${name}!";
                INPUT,
        ];
```

into `tests/Fixer/StringNotation/SimpleToComplexStringVariableFixerTest.php`,

then run `./vendor/bin/phpunit tests/Fixer/StringNotation/SimpleToComplexStringVariableFixerTest.php`

### Fixer version

3.57.2

### PHP version

8.3.2

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by kubawerlos** [comment]
This is not a bug as technically nothing is broken, maybe more of an enhancement than a feature, @keradus, @Wirone if you have a strong opinion about what exactly kind this is, do not hesitate to update it.
