### ISSUE TITLE
When “?string” gets “string|null” than error: “Default null value for not-nullable property is invalid”

### ISSUE THREAD

**Issue by CreativeNative** [PHP-CS-Fixer/PHP-CS-Fixer#8104]
### Problem description

I changed the type declaration from “?string” to Union Type “string|null” and now I get a lot of  “Default null value for not-nullable property is invalid” errors. 

### Minimal reproducer

`private int|null $id = null;`
This produces “Default null value for not-nullable property is invalid” error.

`private ?int $id = null;`
This instead produces no errors.

### Fixer version

v3.59.3

### PHP version

8.2

### How do you run Fixer?

Composer package

### Contribution Checks

- [ ] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by keradus** [comment]
Hey :wave:

[ref](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/.github/ISSUE_TEMPLATE/1-bug_report.yml)
> Provide a minimal code snippet and the CLI command that should be run to reproduce the problem.
> Please see how to utilise --rules option on the [usage page](https://cs.symfony.com/doc/usage.html).
> 
> If it's not possible to prepare short CLI reproducer command, please provide complete config used in your project.
> 
> If relevant, provide the expected output, the actual output and/or the error that occurred, if any.


I miss configuration you are using, command you are running, and where you get the error (eg snapshot of CLI result of Fixer command)

**Comment by CreativeNative** [comment]
I'm not really a PRO in using PHP-CS-Fixer, but I try my best to explain. My configuration uses the LaminasCodingStandard and the error comes from the CLI when I start the command : 

`vendor/bin/phpcs module`

The issue I'm experiencing is due to the change in type declaration from ?string to string|null. In PHP 8.2, ?string is a shorthand for string|null, but they are not exactly the same. When you use ?string, it implies that the property can be either a string or null. However, when you use string|null, it implies that the property can be either a string or null, but it's not nullable by default.
The "Default null value for not-nullable property is invalid" error is likely because the PHP-CS-Fixer is expecting a nullable property, but the string|null union type doesn't imply nullability by default.

So the fixer changes this

`private int|null $id = null;`

to this

`private int|null $id;`

which breaks my code because I can't set a default value.

**Comment by Wirone** [comment]
@CreativeNative `vendor/bin/phpcs` is a binary of PHPCodeSniffer, you opened an issue in wrong project 🙂.
