### ISSUE TITLE
phpdoc_align - support indentation in multiline comments

### ISSUE THREAD

**Issue by JParkinson1991** [PHP-CS-Fixer/PHP-CS-Fixer#8127]
### Feature request

Hello,

This feature request is linked to the bug report https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8052.

It would be great if we could extend the current fixes to support the Drupal `@param` standard. 

```php
 * @param string $mail
 *   The email address. The description can be longer if necessary, and if so,
 *   you can wrap it to another line.
 * @param string $from
 *   (optional) The email address to send the mail from, if different from
 *   the site-wide address.
```

Reference: https://www.drupal.org/docs/develop/standards/php/api-documentation-and-comment-standards#param

I don't think we're too far away with the current implementation. 

It seems like if we add a `multiline_indent` configuration value which defines the number of spaces to indent subsequent lines of a multiline comment (defaulting to `0`) we could support this standard.

Assuming the target alignment fix will yield the below

```php
$config = [
    'phpdoc_align' => ['align' => 'left'],
];
```

```php
# orig
/**
 * @param string $foo
 *     Not bar
 */

# current state
/**
 * @param string $foo
 *                    Not bar
 */

# left align fixed as per issue #8052
/**
 * @param string $foo
 * Not bar
 */
```

If we allow indent config, we can support Drupal standards as well

```php
$config = [
    'phpdoc_align' => [
        'align' => 'left',
        'multiline_indent' => 4
    ],
];
```

```
# orig
/**
 * @param string $foo
 *     Not bar
 */

# fixed with configured indent (no change)
# Assuming bug from #8052 is resolved
/**
 * @param string $foo
 *     Not bar
 */
```

### Contribution Checks

- [X] I have verified if this feature request was already discussed
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by kick-the-bucket** [comment]
Would this by any chance work with PhpStan array shapes?
```php
    /**
     * @return array{
     *     client: string,
     *     template: string,
     *     subject: string,
     *     message: string,
     *     is_read: bool,
     *     group: string,
     *     is_send: bool,
     * }[]
     */
    private function getData(): array
```
