### ISSUE TITLE
binary_operator_spaces does not format properly

### ISSUE THREAD

**Issue by regnerisch** [PHP-CS-Fixer/PHP-CS-Fixer#8130]
### Problem description

When running phpcsfixer with `binary_operator_spaces` the following code is wrong formatted:

```php
    private function toAddress(string|AddressInterface $ip): ?AddressInterface
    {
        return match (true) {
            $ip instanceof AddressInterface => $ip,
            is_string($ip) => Factory::parseAddressString($ip),
            default => null,
        };
    }
```

formatted as:

<img width="1232" alt="grafik" src="https://github.com/user-attachments/assets/3a6b5f2d-ae03-4fbd-9353-7c7afd7bd531">

### Minimal reproducer

```json
    "binary_operator_spaces": {
      "default": "single_space",
      "operators": {
        "=>": "align_single_space_minimal"
      }
    },
```

### Fixer version

3.59.3

### PHP version

8.2

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment]
The fixer works properly:

<img width="1172" alt="image" src="https://github.com/user-attachments/assets/73d5b0a4-ec8c-41c8-90d6-dccfca355450">

The issue here is inlay hint `value` which shifts the rest of the line to the right and then `=>` look like misaligned.

**Comment by regnerisch** [comment]
Oh, how did I miss that :face_palm: ... Sorry for the issue. 

You are right, it takes a lot of space, but IMHO it looks cleaner. Pretty sure without an IDE I would not align it like that.
