### ISSUE TITLE
`method_argument_space`: ability to enforce multiline signature

### ISSUE THREAD

**Issue by Asisyas** [PHP-CS-Fixer/PHP-CS-Fixer#8136]
### Problem description

The rule for “method_argument_space” does not always work correctly. In some cases, the rule is completely ignored.

After debugging, I found the problem that if at least one of the conditions is fully met ( `{method_argument_space: {on_multiline: 'ensure_fully_multiline/ensure_single_line'}` ), no corrections are applied. However, if both rules are violated simultaneously, the correction occurs based on the configuration specified.

### Minimal reproducer

**Config example**

```php
$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__ . '/src');

return (new \PhpCsFixer\Config())
    ->setUsingCache(false)
    ->setRules([
        'method_argument_space' => [
            'on_multiline' => 'ensure_fully_multiline',
            'attribute_placement' => 'standalone',
        ]
    ])
    ->setFinder($finder)
    ;
```

### Case 1    
**Class Examples**

```php
class TestClass
{
    public function __construct(#[Autowire] int $a, string $b, array $c)
    {
    }
}

// OR

class TestClass
{
    public function __construct(#[Autowire]
                                int $a, string $b, array $c)
    {
    }
}

// OR (with property promotion)

class TestClass
{
    public function __construct(#[Autowire] public int $a, protected string $b,  private array $c)
    {
    }
}

```

**Excepted result**

```php
class TestClass
{
    public function __construct(
        #[Autowire]
        int $a,
        string $b,
        array $c
    )
    {
    }
}

// OR (with property promotion)

class TestClass
{
    public function __construct(
        #[Autowire]
        public int $a,
        protected string $b,
        private array $c
    )
    {
    }
}
```

**Actual result:**
`Fixed 0 of 1 files in 0.011 seconds, 14.00 MB memory used`

---

### Case 2 (Test passed)

```php
class TestClass
{
    public function __construct(#[Autowire]
                                int $a,
                                string $b, array $c)
    {
    }
}

// OR (with property promotion)

class TestClass
{
    public function __construct(#[Autowire] public int $a, protected string $b,
                                private array $c)
    {
    }
}

```
**Actual result:**

```php
class TestClass
{
    public function __construct(
        #[Autowire]
        int $a,
        string $b,
        array $c
    )
    {
    }
}

// OR (with property promotion)

class TestClass
{
    public function __construct(
        #[Autowire]
        public int $a,
        protected string $b,
        private array $c
    )
    {
    }
}

```

### Fixer version

3.59.3 7th Gear

### PHP version

8.2.11

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment]
Please get familiar with [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/2325#issuecomment-1690183634). Examples 1 and 3 won't be touched even with `ensure_fully_multiline`, but snippet 2 should be "ensured" 🤔. Please note this mode is only _ensuring_ (not _enforcing_) _fully multiline_ (at least one new line must be present already). I believe finding existing new lines currently has to be done from first declaration hint to closing `)`, that's why the new line between the attribute and the first type declaration is not taken into consideration... So we have a feature request (ability to truly enforce multiline signature) and a bug (newline not recognised) in one issue 🙂. Are you open for contribution @Asisyas?

**Comment by Asisyas** [comment]
@Wirone 

Yes, I can take this on, but I am currently a bit overloaded with my main project. If it’s not urgent, I would be happy to assist with the functional improvements.
