### ISSUE TITLE
`\Exception` is changed to `Exception`

### ISSUE THREAD

**Issue by sebastianbergmann** [PHP-CS-Fixer/PHP-CS-Fixer#8182]
### Problem description

I have a namespaced class that extends a class named `Exception` in the same namespace. This class has a method with a parameter type declaration that uses `\Exception` as a type. This intentionally references the built-in `\Exception` class and not the class named `Exception` in the same namespace.

PHP-CS-Fixer 3.63.1 changes `\Exception` to `Exception`. PHP-CS-Fixer 3.62.0 did not do this.

### Minimal reproducer

On the `8.5` branch of PHPUnit, I have this source code file ([`InvalidArgumentException.php`](https://github.com/sebastianbergmann/phpunit/blob/90f86fc098b4ab614464e63f939105cce13cb975/src/Framework/Exception/InvalidArgumentException.php)):

```php
<?php declare(strict_types=1);
/*
 * This file is part of PHPUnit.
 *
 * (c) Sebastian Bergmann <sebastian@phpunit.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace PHPUnit\Framework;

use function debug_backtrace;
use function in_array;
use function lcfirst;
use function sprintf;

/**
 * @internal This class is not covered by the backward compatibility promise for PHPUnit
 */
final class InvalidArgumentException extends Exception
{
    public static function create(int $argument, string $type): self
    {
        $stack    = debug_backtrace();
        $function = $stack[1]['function'];

        if (isset($stack[1]['class'])) {
            $function = sprintf('%s::%s', $stack[1]['class'], $stack[1]['function']);
        }

        return new self(
            sprintf(
                'Argument #%d of %s() must be %s %s',
                $argument,
                $function,
                in_array(lcfirst($type)[0], ['a', 'e', 'i', 'o', 'u'], true) ? 'an' : 'a',
                $type
            )
        );
    }

    private function __construct(string $message = '', int $code = 0, ?\Exception $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }
}
```

Running PHP-CS-Fixer 3.62.0 on this file using `.php-cs-fixer.dist.php`](https://github.com/sebastianbergmann/phpunit/blob/90f86fc098b4ab614464e63f939105cce13cb975/.php-cs-fixer.dist.php) does not perform any changes.

Running PHP-CS-Fixer 3.63.1 on this file using `.php-cs-fixer.dist.php`](https://github.com/sebastianbergmann/phpunit/blob/90f86fc098b4ab614464e63f939105cce13cb975/.php-cs-fixer.dist.php) performs the following change:

```patch
diff --git a/src/Framework/Exception/InvalidArgumentException.php b/src/Framework/Exception/InvalidArgumentException.php
index ba37b58a92..34d8eb8515 100644
--- a/src/Framework/Exception/InvalidArgumentException.php
+++ b/src/Framework/Exception/InvalidArgumentException.php
@@ -39,7 +39,7 @@ public static function create(int $argument, string $type): self
         );
     }
 
-    private function __construct(string $message = '', int $code = 0, ?\Exception $previous = null)
+    private function __construct(string $message = '', int $code = 0, ?Exception $previous = null)
     {
         parent::__construct($message, $code, $previous);
     }
```

`PHPUnit\Framework\Exception` exists and is the class we want to extend (`final class InvalidArgumentException extends Exception`). However, for the `$previous` parameter of the `__construct` method we really need `\Exception`.

According to `--dry-run --verbose`, the `fully_qualified_strict_types`, `native_function_invocation`, `global_namespace_import` fixers are involved.

I can work around this issue by importing `\Exception`:

```patch
diff --git a/src/Framework/Exception/InvalidArgumentException.php b/src/Framework/Exception/InvalidArgumentException.php
index ba37b58a92..711a85f7b6 100644
--- a/src/Framework/Exception/InvalidArgumentException.php
+++ b/src/Framework/Exception/InvalidArgumentException.php
@@ -13,6 +13,7 @@
 use function in_array;
 use function lcfirst;
 use function sprintf;
+use Exception as BaseException;
 
 /**
  * @internal This class is not covered by the backward compatibility promise for PHPUnit
@@ -39,7 +40,7 @@ public static function create(int $argument, string $type): self
         );
     }
 
-    private function __construct(string $message = '', int $code = 0, ?\Exception $previous = null)
+    private function __construct(string $message = '', int $code = 0, ?BaseException $previous = null)
     {
         parent::__construct($message, $code, $previous);
     }
```

### Fixer version

3.63.1

### PHP version

8.3.10

### How do you run Fixer?

PHAR

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by keradus** [comment]
> I also wonder

I was too hurray to release fix for parallel issue that i overlooked version I release. you can ignore the -DEV and rely on 3.63.1.

**Comment by phil-davis** [comment]
I have a similar problem with some occurrences of `\DateTimeZone` being changed to `DateTimeZone`
https://github.com/sabre-io/vobject/actions/runs/10590564911/job/29346559096

Pinning to php-cs-fixer 3.62.0 "fixes" it for now.

**Comment by phil-davis** [comment]
3.63.2 works for me - thanks

**Comment by sebastianbergmann** [comment]
> 3.63.2 works for me - thanks

Same!
