### ISSUE TITLE
Errors during liniting Enums with a case matching `MSG_OOB`

### ISSUE THREAD

**Issue by kalkin** [PHP-CS-Fixer/PHP-CS-Fixer#8189]
### Problem description

When 'native_constant_invocation' is set to `true` and one of the cases matches the regex `MSG_OOB` I get the following error with the latest release:

> Files that were not fixed due to errors reported during linting after fixing:
>   1) XXXX/events/src/EventType.php

### Minimal reproducer

```php
<?php
declare(strict_types=1);

namespace Events;

enum EventType: string
{
    case MSG_TXT = 'msg.txt';
    case MSG_OOB = 'msg.oob';
    case PROMPT = 'prompt';
    case SUBJECT = 'subj';
    case SUMMARY = 'sum';
}
```

### Fixer version

3.64.0

### PHP version

8.3.10

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by SpacePossum** [comment]
verified, please see the PR for details, thanks for reporting @kalkin

**Comment by kalkin** [comment]
Thank you very much for the fast response. ♥
