### ISSUE TITLE
Data provider attribute must be recognized

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#8227]
### Feature request

Currently `DataProviderAnalyzer` does not recognize data provider usages using native attribute.

Once implemented, `php_unit_data_provider_name` should be improved to rename data provider methods in attributes as well.

/cc @kubawerlos as you are the author of these

**Comment by kubawerlos** [comment]
Duplicate of https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7244
