### ISSUE TITLE
Unable to add a line after PHP tag

### ISSUE THREAD

**Issue by mdk999** [PHP-CS-Fixer/PHP-CS-Fixer#8249]
### Problem description

I am trying to add a space after the opening PHP tag for PSR12 compliance. Setting the rule to `@PSR12` does not seem to accomplish this. I've also tried to enable the options below by setting these to`true` in the `.php-cs-fixer.php` file as well
`blank_line_after_opening_tag`
`linebreak_after_opening_tag`

### Minimal reproducer

command line
`vendor/bin/php-cs-fixer fix test.php --rules=@PSR12`

Sample file
```
<?php
/**
 * Testing..
 *
 * @copyright 2024
 * @license Proprietary
 */
 ```
 Expected
 ```
 <?php
 
/**
 * Testing..
 *
 * @copyright 2024
 * @license Proprietary
 */
 ````
 Actual
 ````
 <?php
/*
 * Testing..
 *
 * @copyright 2024
 * @license Proprietary
 */
 ````

### Fixer version

3.64.0

### PHP version

8.3.12

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment]
I reproduced it and it seems like we really don't have [test case](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/60618e4681ca38edc18ee792225379c570779f7e/tests/Fixer/PhpTag/BlankLineAfterOpeningTagFixerTest.php) for code like your example, with a comment directly after opening tag. `blank_line_after_opening_tag` does not picks this, but it should. Thanks for reporting this, are you interested in providing fix?
