### ISSUE TITLE
no_unused_imports removes used const import

### ISSUE THREAD

**Issue by Kenny1291** [PHP-CS-Fixer/PHP-CS-Fixer#8260]
### Problem description

I am using a constant from another namespace in foreach loop and the rule is removing the necessary import.

### Minimal reproducer

```php
//constants.php
<?php

namespace Test;

const MY_CONST = [
    "myKey" => "myValue"
];
```
```php
//test.php
<?php

namespace Test1;

require 'constants.php';

use const Test\MY_CONST;

foreach (MY_CONST as $key => $value) {
    echo "test";
}
```
```PowerShell
vendor/bin/php-cs-fixer fix . --rules=no_unused_imports
```

### Fixer version

3.64.0 Space Sets

### PHP version

8.3.11

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by kubawerlos** [comment]
Hi @Kenny1291, I cannot reproduce it, I've added your code sample and the import is not removed: [2ac9cbed6a75c9cb4a26c55a11631f93d717da54](https://github.com/6b7562617765726c6f73/PHP-CS-Fixer/commit/2ac9cbed6a75c9cb4a26c55a11631f93d717da54).

**Comment by Kenny1291** [comment]
Hi @kubawerlos, thank you for getting back. Here's a repo that reproduces the issue:
https://github.com/Kenny1291/no_unused_imports-reproduce-issue

**Comment by kubawerlos** [comment]
@Kenny1291 thanks, it is indeed failing on the repo.

But when I update the fixer to lastest `master` branch it is not removing the import, so it must been fixed sometime after latest release.

**Comment by kubawerlos** [comment]
In deed, silly GitHub search did not showed it when I've [searched for "const"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pulls?q=is%3Apr+const+is%3Aclosed).
