### ISSUE TITLE
ExplicitIndirectVariableFixer fixes the wrong way

### ISSUE THREAD

**Issue by corentin-larose** [PHP-CS-Fixer/PHP-CS-Fixer#8261]
### Problem description

@see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8262

First, I want to express my gratitude for this awesome work, second, I want to contribute.

Purpose of the `ExplicitIndirectVariableFixer` fixer is to modify `PHP 5.6` code in order to make it work with the `PHP
7.0+` interpreter, **NOT** changing the behavior of the code.

For instance, in `PHP 7.0+`, you can no longer write `$$foo->bar`, you **MUST** write `${$foo->bar}` instead.

Quoting PHP manual [Changes to the handling of indirect variables, properties, and methods ](https://www.php.net/manual/en/migration70.incompatible.php):

> Indirect access to variables, properties, and methods will now be evaluated strictly in left-to-right order, as
> opposed to the previous mix of special cases. The table below shows how the order of evaluation has changed.
>
> |      Expression       |  PHP 5 interpretation   |  PHP 7 interpretation   |
> |:---------------------:|:-----------------------:|:-----------------------:|
> | `$$foo['bar']['baz']` | `${$foo['bar']['baz']}` | `($$foo)['bar']['baz']` |
> |  `$foo->$bar['baz']`  |  `$foo->{$bar['baz']}`  |  `($foo->$bar)['baz']`  |
> | `$foo->$bar['baz']()` | `$foo->{$bar['baz']}()` | `($foo->$bar)['baz']()` |
> | `Foo::$bar['baz']()`  | `Foo::{$bar['baz']}()`  | `(Foo::$bar)['baz']()`  |
>
> Code that used the old right-to-left evaluation order must be rewritten to explicitly use that evaluation order with
> curly braces **(see the above middle column)**. This will make the code both forwards compatible with PHP 7.x and
> backwards
> compatible with PHP 5.x.

These are precisely the examples used in the code documentation and unit tests of the `ExplicitIndirectVariableFixer`
method.
Despite of the warning: **"(see the above middle column)"**, the developer took the "PHP7 interpretation" column instead of the "PHP 5 interpretation" column in order to build the fixer.

In my pull request (in which I will tag this issue), I changed the `ExplicitIndirectVariableFixerTest::provideFixCases()` and `ExplicitIndirectVariableFixerTest::provideFix80Cases()` data provider methods in order to reflect the right logic, I
also added a missing case.

> |  Expression   | PHP 5 interpretation  | PHP 7 interpretation  |
> |:-------------:|:---------------------:|:---------------------:|
> | `$$foo->bar`  |    `${$foo->bar}`     |    `($$foo)->bar`     |

[My pull request](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8262) doesn't contain an actual fix for `ExplicitIndirectVariableFixer` since I am not used to the way fixers work yet. When I am used, if this bug is still open, I will fix it. In the meantime, people will be aware of the wrong behavior.

For information, I did exactly the same bug report on RectorPHP: https://github.com/rectorphp/rector/issues/8861

### Minimal reproducer

I know... at first, you will think I made a mistake or misunderstood, since this rule has been performing this way for
years... So, here is the **BUG** proof:

Run this on PHP 5.6 ([https://3v4l.org/XB19f#v5.6.40](https://3v4l.org/XB19f#v5.6.40))

```php
<?php
$baz = 'bat';
$foo = array('bar' => 'baz');

echo $$foo['bar'];
echo PHP_EOL;
echo ${$foo['bar']};
echo PHP_EOL;

// PHP 5.6 output:
bat
bat
```

Run this on PHP 7.0 ([https://3v4l.org/jBLbv#v7.0.0](https://3v4l.org/jBLbv#v7.0.0))

```php
<?php
$baz = 'bat';
$foo = array('bar' => 'baz');

echo ${$foo}['bar']; // This is the way `ExplicitIndirectVariableFixer` currently fixes the code.
echo PHP_EOL;
echo ${$foo['bar']}; // This is the way `ExplicitIndirectVariableFixer` SHOULD fix the code.
echo PHP_EOL;

// PHP7.0 output
Notice: Array to string conversion in /in/jBLbv on line 5

Notice: Undefined variable: Array in /in/jBLbv on line 5

bat
```

### Fixer version

3.64.1-DEV

### PHP version

8.3.13

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by kubawerlos** [comment]
> Purpose of the `ExplicitIndirectVariableFixer` fixer is to modify `PHP 5.6` code in order to make it work with the `PHP 7.0+` interpreter

How come? The intention of the fixer was never to touch code in PHP below 7 (it was introduced when PHP CS Fixer was supporting PHP 5, but the fixer [did not](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/3164/files#diff-0a95b07e6a7660a4cbff42f46a43a0d613b861c8e4f299613f333eeab42fd3bfR57)).

> **NOT** changing the behavior of the code.

Exactly, from the description it is only to make the code easier to read:

> `Add curly braces to indirect variables to make them clear to understand.`

Currently, it does NOT change behaviour:

1. There is an application in PHP 7+ (PHP CS Fixer supports only PHP 7.4+).
2. There is an expression in code `$foo->$bar['baz'];`.
3. Fixer `ExplicitIndirectVariableFixer` is applied.
4. The expression is now `$foo->{$bar}['baz'];` (which behaves exactly the same).

Your proposition is for everyone having `$foo->$bar['baz'];` in the application (in PHP 7+) to change it to `$foo->{$bar['baz']}`, which will not behave the same: https://3v4l.org/4BJaF.

**Comment by samsonasik** [comment]
I agree with @kubawerlos , the existing functionality is **already** the way it should be, as it always depends of what variable is, eg:

```php
        $foo = 'a';
        $a = [
            'bar' => new stdClass()
        ];

        echo $$foo['bar'];
```

see it https://3v4l.org/eip64 vs https://3v4l.org/tYFTb , that's why I reverted patch on rector side of what you proposed it https://github.com/rectorphp/rector-src/pull/6536

**Comment by samsonasik** [comment]
@Wirone this can be closed as well
