### ISSUE TITLE
Support php 8.4

### ISSUE THREAD

**Issue by chenrui333** [PHP-CS-Fixer/PHP-CS-Fixer#8298]
### Feature request

Support php 8.4

relates to https://github.com/Homebrew/homebrew-core/pull/198473

### Contribution Checks

- [X] I have verified if this feature request was already discussed
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by chenrui333** [comment]
previously, https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7465 (I checked that there is no 8.4 support milestone yet, so raise this feature req)

**Comment by Wirone** [comment]
Just like year ago I am going to close this, as we're totally aware about lack of 8.4 support and we will provide it at some point, no need for generic issue like this. I've created [milestone](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/milestone/173) that will be filled with more atomic issues found during investigation.

**Comment by chenrui333** [comment]
Thanks @Wirone for creating the milestone. 👍
