### ISSUE TITLE
[PHP8.4] `normalize_index_brace` treats property hook's `{}` as index access

### ISSUE THREAD

**Issue by Wirone** [PHP-CS-Fixer/PHP-CS-Fixer#8301]
### Problem description

As you can see in #8300, there is a problem with property hooks syntax, which is treated as array index fetch.

[This fixer should work only for PHP <8.0](https://3v4l.org/o8Rdd), but there is no condition within fixer itself. It seems like the root cause of this is `PhpCsFixer\Tokenizer\Transformer\BraceTransformer::transformIntoCurlyIndexBraces()`, which replaces `{` with `CT::T_ARRAY_INDEX_CURLY_BRACE_OPEN`.

### Minimal reproducer

The code like this:

```php
<?php

class PropertyHooks
{
    public string $bar {
        set(string $value) {
            $this -> foo = strtolower($value);
        }
    }
}
```

is malformed into this:

```php
<?php

class PropertyHooks
{
    public string $bar[
        set(string $value) {
        $this->foo = strtolower($value);
    }
    ]
}
```

### Fixer version

3.64.1-DEV

### PHP version

8.4.1

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment]
@keradus @SpacePossum I've updated description and provided some context. How should we handle this?

- Add condition to `NormalizeIndexBraceFixer` so it does not do anything on PHP 8.0+?
- Add condition to `BraceTransformer::transformIntoCurlyIndexBraces()` so it does not convert regular `{` tokens to custom token on PHP 8.0+? In theory it's a BC break, but most probably we can consider it as a bug, since these braces shouldn't be customised on PHP8 anyway because support for the syntax was removed.
- Add new transformer for property hooks? Would be great, but it could be done in separate PR, as a feature required for adding PHP 8.4 support.

Anyway, the fix seems to be easy, but let's decide how we want to handle this. I can prepare PR with a fix and create issue for the new transformer after we settle the path.

**Comment by keradus** [comment]
whenever meaning of token gets overloaded with multiple-meanings, we shall introduce a custom token.

having a custom token for new meaning of `{` will also automatically prevent the case when it's converted into curly_index_open

draft here: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8312
