### ISSUE TITLE
PHAR is not included in the latest release

### ISSUE THREAD

**Issue by szepeviktor** [PHP-CS-Fixer/PHP-CS-Fixer#8305]
### Problem description

The PHAR is missing from this release
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.65.0

### Minimal reproducer

The quiet popular `shivammathur/setup-php` GHA action downloads the PHAR file but currently fails.

### Fixer version

3.65.0

### PHP version

n/a

### How do you run Fixer?

PHAR

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by keradus** [comment]
thanks
