### ISSUE TITLE
add php 8.4 to the supported interpreter list?

### ISSUE THREAD

**Issue by christopherowen** [PHP-CS-Fixer/PHP-CS-Fixer#8306]
### Feature request

Could we please allow php 8.4 in the supported version list in composer?

currently, when running a composer.json file, with `composer config platform.php 8.3` set and while running with php 8.4 an error is produced:

```
PHP needs to be a minimum version of PHP 7.4.0 and maximum version of PHP 8.3.*.
Current PHP version: 8.4.1.
```

### Contribution Checks

- [ ] I have verified if this feature request was already discussed
- [ ] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by christopherowen** [comment]
I had been using php-cs-fixer with 8.3 before, so maybe I am running into a different issue than in that ticket?

**Comment by kubawerlos** [comment]
> I had been using php-cs-fixer with 8.3

Because it supports PHP 8.3.

**Comment by christopherowen** [comment]
thank you all for your kind replies and helpful insight.  I will wait on the develops in #8300.
