### ISSUE TITLE
Version 3.66.0 incorrectly changes `->createStub` to `::createStub` in tests

### ISSUE THREAD

**Issue by oliverklee** [PHP-CS-Fixer/PHP-CS-Fixer#8337]
### Problem description

With version 3.66.0, PHP-CS-Fixer complains about (and changes) dynamic method calls `->createStub` in tests, and suggests changing them to the static method call `::createStub`. As the method is not static, this is incorrect.

Please note that calls to `-->createMock` are not touched.

This is with PHPUnit 9.6.20. In later versions of PHPUnit (more precisely, in 10.5.), this method was made static.

This is a regression - in version 3.65.0, this problem did not occur.

### Minimal reproducer

https://github.com/TYPO3BestPractices/tea/pull/1533

### Fixer version

3.66.0

### PHP version

8.3.15

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by oliverklee** [comment]
My educated guess is that this was introduced with #8319.

**Comment by kubawerlos** [comment]
Method `createStub` (and other 2) [became](https://github.com/sebastianbergmann/phpunit/commit/6d98a507127c215d70a0e108bd72b05fcde58733) static over a year ago, so the change made in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8319 is correct.

The fixer itself is risky, and it is [described](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.66.0/doc/rules/php_unit/php_unit_test_case_static_method_calls.rst#using-this-rule-is-risky) why:
> Risky when PHPUnit methods are overridden or not accessible, or when project has PHPUnit incompatibilities.

You have the "PHPUnit incompatibilities". Luckily, there is an option `methods`, sadly with wrong type and without example, but this will be [handled](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8338) soon (until it is merged you can see it [here](https://github.com/6b7562617765726c6f73/PHP-CS-Fixer/blob/doc_PhpUnitTestCaseStaticMethodCallsFixer/doc/rules/php_unit/php_unit_test_case_static_method_calls.rst)).
